### ISSUE TITLE
Logins online UUID broken

### ISSUE THREAD

**Issue by popcorn9499** [games647/FastLogin#10]
When i login with my bungeecord in offline mode. If its a premium user fastlogin doesn't detect. 

using bungeeAuth as cracked login.

**Comment by games647** [comment]
Activated the user premium logins?

**Comment by popcorn9499** [comment]
i did activate that it didn't work after that.



`# FastLogin config
# Project site: https://www.spigotmc.org/resources/fastlogin.14153
# Source code: https://github.com/games647/FastLogin
#
# You can access the newest config here:
# https://github.com/games647/FastLogin/blob/master/bukkit/src/main/resources/config.yml

# Request a premium login without forcing the player to type a command
#
# If you activate autoRegister, this plugin will check/do these points on login:
# 1. An existing cracked account shouldn't exist
# -> paid accounts cannot steal the existing account of cracked players
# - (Already registered players could still use the /premium command to activate premium checks)
# 2. Automatically registers an account with a strong random generated password
# -> cracked player cannot register an account for the premium player and so cannot the steal the account
#
# Furthermore the premium player check have to be made based on the player name
# This means if a cracked player connects to the server and we request a paid account login from this player
# the player just disconnect and sees the message: 'bad login' or 'invalid session'
# There is no way to change this message
# For more information: https://github.com/games647/FastLogin#why-do-players-have-to-invoke-a-command
autoRegister: false

# If this plugin detected that a player has a premium, it can also set the associated
# uuid from that account. So if the players changes their usernames, they will still have
# the same playerdata (inventory, permissions, ...)
#
# Warning: This also means that the UUID will be different if the player is connecting
# through a offline mode connection. This **could** cause plugin compatibility issues.
#
# This is a example and doesn't apply for every plugin.
# Example: If you want to ban players who aren't online at the moment, the ban plugin will look
# after a offline uuid associated to the player, because the server is in offline mode. Then the premium
# players could still join the server, because they have different UUID.
#
# Moreover you may want to convert the offline UUID to a premium UUID. This will ensure that the player
# will have the same inventory, permissions, ... if they switched to premium authentification from offline/cracked
# authentification.
#
# This feature requires Cauldron, Spigot or a fork of Spigot (PaperSpigot, TacoSpigot)
premiumUuid: true

# If your players have a premium account and a skin associated to their account, this plugin
# can download the data and set it to the online player.
#
# Keep in mind that this will only works if the player:
# * is the owner of the premium account
# * the serverconnection is established through a premium connection (paid account authentification)
# * has a skin
#
# This means this plugin doesn't need to create a new connection to the Mojang servers, because
# the skin data is included in the Auth-Verification-Response sent by Mojang. If you want to use for other
# players like cracked player, you have to use other plugins.
#
# If you want to use skins for your cracked player, you need an additional plugin like
# ChangeSkin, SkinRestoer, ...
forwardSkin: true

# Database configuration
# Recommened is the use of MariaDB (a better version of MySQL)

# Single file SQLite database
#driver: org.sqlite.JDBC
# File location
#database: '{pluginDir}/FastLogin.db'

# MySQL and SQLite
driver: com.mysql.jdbc.Driver
host: 192.168.100.134
port: 3306
database: minecraft
username: minecraft
password: minecraft`

**Comment by games647** [comment]
But did the user activated it?

**Comment by games647** [comment]
># Warning: This also means that the UUID will be different if the player is connecting
# through a offline mode connection. This **could** cause plugin compatibility issues.

It's only sent if it's actually a online mode connection.

**Comment by popcorn9499** [comment]
how does the user activate it. The bungee was in offline mode if thats what ur meaning? or if u mean the client being in offline mode. it was not because the client was in online mode

**Comment by games647** [comment]
If the user invoke the command /premium for auto logins, fastlogin will establish future connection in online mode (only for that player) in order to check if the actually the right owner of this account.

**Comment by popcorn9499** [comment]
none of those commands worked for some reason

**Comment by games647** [comment]
Maybe because you forgot to install FastLogin on the backend server too?

**Comment by popcorn9499** [comment]
i need it on the backend?

**Comment by games647** [comment]
Yes

**Comment by popcorn9499** [comment]
i didnt know that so ill try that and tell u if it does or doesnt work. ty for telling me this

**Comment by games647** [comment]
It's mentioned in the FAQ

>BungeeCord support
>Yes it has. Just activate ipForward in your BungeeCord config and place the plugin in the plugins folder of Bukkit/Spigot and BungeeCord

**Comment by popcorn9499** [comment]
i did try it before hand on spigot and it didnt work with just spigor and the dependencys.

**Comment by games647** [comment]
As mentioned before, premium UUIDs are only sent if the user activated it

**Comment by popcorn9499** [comment]
can you explain why everytime i log in i have to do /premium to keep premium uuid?

**Comment by games647** [comment]
As explained in the FAQ, if user joins the server we only know the IP-Address and the username. By enabling the config option autoRegister FastLogin will detect premium players automatically based on this username (does a account with this username exists).

But this has the limitation that cracked players who wants to play with a premium username cannot join the server. Although I implemented a check if that player has already a registered account on the server in order to allow existing cracked players to join the server, it's in my opinion a bad user experience. 

Also because the client will only see the message "bad login" or "invalid session" and there is no way to change this message, because it's a connection between the client and mojang at that moment,

I hope you understand my decision now. All this is also explained in the FAQ.
