### ISSUE TITLE
Authme 5.2 causes already logged in message on session reconnect

### ISSUE THREAD

**Issue by gaberilde** [games647/FastLogin#101]
it's a small bug but a slight annoying for my players.

if authme session reconnect is on and it happens it will login before this does causing a already logged in message, i dont think it always happens it might be lag causing it but what u could do is check if it is logged in and dont do the /login process if it is logged in or try to make it run earlier so authme dosent notice it?

**Comment by games647** [comment]
That's fixed in the dev-build.

**Comment by gaberilde** [comment]
The problem with that version is it dosent auto login or register on bungee when i do the sqlite thing at least it does everything else.... dont think there are many or any in the console.

**Comment by games647** [comment]
>The problem with that version is it dosent auto login or register on bungee

You followed the setup guide? Moreover it only assume the player is premium if a player invokes /premium or you activated autoRegister in the config and the player is new.

**Comment by gaberilde** [comment]
well the config is set to auto register and auto login and it works with the spigot build when when i replace the plugin on my test spigot and bungee i type /premium and it says type it again when i get added even if i am added it still never signs me in automatilly even through the config is correct, i only replaced the plugin not the config and if i replace it back then it starts working again and idk if its to do with the sqllite setup on bungee or not but if the config is the same and it works for 1 plugin version and not the other, must be a issue with plugin as i replaced on all my test bungees and spigots didnt change a single setting plus they havent changed themselves, they stayed on true but no effect!

**Comment by games647** [comment]
Could you active debug logging in spigot.yml and try to login with activated premium

**Comment by games647** [comment]
Try to invoke /premium. BungeeCord doesn't seem to think you're premium. Othwise there would be logging message with logging level fine.

**Comment by gaberilde** [comment]
i cleared the fastlogin and authme db files everywhere and i register then i do /premium i type it again says added i rejoin it dosent sign me in and it is true in the config for both bungee and spigot

idk if this makes a difference but i am using spigot 1.8.8 and just about the latest bungee version

restarting the server does not lose it neither rejoin because i type /premium and it says i am that.

if you want you can connect to my test server with dev plugin and full console access and you can also connect to my main server with the spigot version of the plugin that works for me but you wont have full console access there, of course.

**Comment by games647** [comment]
So you use a FastLogin dev-build and made use of https://github.com/games647/FastLogin#how-to-install ?

**Comment by gaberilde** [comment]
i have the exact config from bungee/spigot builds, so it would all be already configured and set up correctly like i said switching to old version immadly fixes this problem, without changing anything but that

**Comment by games647** [comment]
Sorry for the log conversation. I eventually found it. That was really stupid. Sorry

**Comment by gaberilde** [comment]
you fixed that now but still getting already logged in its not a too big deal but autoin my last one didnt do that so should hopefully fix it soon!

**Comment by games647** [comment]
>but autoin my last one didnt do that so should hopefully fix it soon!

But AutoIn had race conditions.

It looks like it just sends the message, but won't take any actions if it notices that the player is already logged in.

**Comment by gaberilde** [comment]
yes you should try make it so it dosent try logging in twice maybe if u can that is bur dont worry ok
