### ISSUE TITLE
[Login in Minecraft.net]

### ISSUE THREAD

**Issue by Arthuuurr** [games647/FastLogin#1010]
### What happened?

It won't let me log in to my server. I get the error "Sign in to minecraft.net" when my account is official minecraft

### What did you expect?

enter the server

### Steps to reproduce

In fact, there are no steps, until yesterday it let me enter without problems and today I try to enter and it gives me that error.

### Configuration file

https://paste.iruvatar.com/oxoquwipiw.yaml

### Plugin version

Latest version 

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Do you have `prevent_proxy_connections` enabled in BungeeCord config?

**Comment by Arthuuurr** [comment]
fixed, thanks

**Comment by games647** [comment]
It should be noted that, this error would also happen with normal online mode. It verifies that no proxy is in between the authentication to the server and Mojang.
