### ISSUE TITLE
 Client does not support authentication protocol requested by server. plugin type was = 'sha256_password'

### ISSUE THREAD

**Issue by kixxu** [games647/FastLogin#1015]
### What happened?

As mentioned in title, it doesn't work.

### What did you expect?

No errors in Proxy console and Sending request working.

### Plugin list

AuthMe, FastAsyncWorldEdit, FastLogin, *HexChat, LuckPerms, PlaceholderAPI, PowerBoard, ProtocolLib, ServerSelectorX, ServersNPC [22:02:41 INFO]:  SkinsRestorer, Skript, *SpawnpointPlugin, ViaBackwards, ViaVersion, WorldGuard, YamipaPlugin

### Configuration file

https://hastebin.com/share/dofibinumo.yaml

### Server log

https://mclo.gs/4svWKvx

### Plugin version

1.12-SNAPSHOT-42911e9

### Platform

Velocity

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by kixxu** [comment]
> Do you followed the setup guide for BungeeCord?

Yes

**Comment by games647** [comment]
There is the error message: Client does not support authentication protocol requested by server. plugin type was = 'sha256_password'

Your MySQL/MariaDB server requires a password type that isn't supported. You need to adjust its configuration.

**Comment by kixxu** [comment]
I'll probably switch from MySQL to MongoDB if it's supported.

**Comment by games647** [comment]
> I'll probably switch from MySQL to MongoDB if it's supported.

Sorry that's not supported, because we are using a relational database system. 

> I'm using mysql_native_password and it still happens.

With the same error?

**Comment by JumperOnJava** [comment]
I have same issue, tried 
- mysql_native_password
- caching_sha2_password
- sha256_password
- mysql_clear_password

**Comment by filipswiszcz** [comment]
I had the same error. The solution was to downgrade the MySQL version from 8.0 to 5.7, which resolved this problem.
