### ISSUE TITLE
Players hacked my server!

### ISSUE THREAD

**Issue by Wearwolfy** [games647/FastLogin#102]
I swore this was my last issue, i didn't think i would need to write another one but i think ur plugin made it possible for people to grief my server, they gave themselves op and griefed the server?
I am waiting for a fix until i reopen again. The player joins, he types /gmc, leaves and joins a few times, then he comes back and can type /speed (they are not allowed to have that command), later on they give themselves op and griefed the server. I didn't setup iptables back then, might that have been the problem or your plugin?
http://pastebin.com/XWmS3FH9

**Comment by games647** [comment]
Are you sure you had a Aith plug in installed?

**Comment by games647** [comment]
Moreover please post your fastlogin config. FastLogin would set the premium UUID if it auto logins players, but the pastebin shows the cracked UUID.

**Comment by games647** [comment]
What about the Bungeecord log? If you want, you could message me privately on Spigot.

**Comment by games647** [comment]
Do you used a strong password for your auth plug in?

**Comment by games647** [comment]
And I see no logging output from Fast Login.  Even no from the debug levels.

**Comment by Wearwolfy** [comment]
Yep i had auth plugin installed

**Comment by Wearwolfy** [comment]
http://pastebin.com/JgTgc1v0
Fastlogin config

**Comment by Wearwolfy** [comment]
See, everything worked fine for a week, premium players and cracked players could join. Until this hacker group showed up, maybe they ip spoofed. I didn't configure the ip tables back then or the plugin isn't fully secure =(

**Comment by Wearwolfy** [comment]
And yes i had a strong password

**Comment by games647** [comment]
You should always firewall your local spigot server if you have Bungee cord.

**Comment by Wearwolfy** [comment]
all spigot servers or only the hub?

**Comment by Wearwolfy** [comment]
some1 said this to me on spigot is that true? "I'd recommend not using plugins like FastLogin.
The BungeeCord firewall guide explains everything you need to know.
You want to block access to offline-mode servers."

**Comment by games647** [comment]
What about the Bungee cord log?

**Comment by Wearwolfy** [comment]
doesn't it only generate/save one of there are crashes/problems

**Comment by Wearwolfy** [comment]
And yes i will send thel

**Comment by Wearwolfy** [comment]
them

**Comment by games647** [comment]
BungeeCord will always make a log file called bungee.log

**Comment by Wearwolfy** [comment]
nope only proxy.log 
files, there are 4 of these logs

**Comment by games647** [comment]
That's the bungeecord log.

**Comment by Maxetto** [comment]
You just got UUIDStealed by an Hacked Client because you had not firewalled your server.

FastLogin doesn't have anything to do with this. It's all your fault and you should read the Spigot's Firewall Guide.

You can determine it because player "_MarcoPro_" is connecting from localhost, and the second time he joins, he switches UUID: `[Essentials] Found new UUID for MarcoPro. Replacing 153a13e8-2027-33aa-aff8-223d72b499b0 with 47f97fe7-263b-3c0c-baeb-21e581258712`

**Comment by games647** [comment]
Then I'm closing this, but I think of adding an additional security layer to prevent such cases as those cases could easily happen.
