### ISSUE TITLE
Duplicate message due to auto-login

### ISSUE THREAD

**Issue by Eufranio** [games647/FastLogin#103]
When a player joins the server and he is logged in by active session (AuthMe), FastLogin still log the player, and then duplicates the message:

![black-vote2](http://image.prntscr.com/image/f913abe2464c496684af2c0338e0371c.png)

Console:
```
[15:04:53 INFO]: UUID of player PotterCraft_ is 03c81579-9839-4c0e-bf5e-2d2ece544972
[15:04:53 INFO]: PotterCraft_[/IP] logged in with entity id 181 at ([ZeSpawn]-1522.5, 112.0, 683.5)
[15:04:53 INFO]: PotterCraft_ entrou no Lobby
[15:04:53 INFO]: [AuthMe] The user PotterCraft_ has 2 accounts:
[15:04:53 INFO]: [AuthMe] §7§aPotterCraft_§7, chafingamer.
[15:04:53 INFO]: [AuthMe] PotterCraft_ logged in!
[15:04:53 INFO]: [AuthMe] The user PotterCraft_ has 2 accounts:
[15:04:53 INFO]: [AuthMe] §7§aPotterCraft_§7, chafingamer.
[15:04:53 INFO]: [AuthMe] PotterCraft_ logged in!
```

**Comment by games647** [comment]
Isn't this the same as #101

**Comment by Eufranio** [comment]
Yep, but your fix caused this. Yesterday I was running an old version of FastLogin and everything was fine, today I updated to latest dev build and it started happening.

**Comment by ljacqu** [comment]
Pardon the unrelated question, but @Eufranio, is "Vecê tem 2 contas" correct? Or does AuthMe have a misspelling of _você_?

**Comment by Eufranio** [comment]
RIP, it isnt, should be "Você" lol

**Comment by Eufranio** [comment]
Lmao it's even worst when I'm logged by having an premium account & session & auto-logged by AuthMeBridge

![bondia](http://image.prntscr.com/image/4861675bc2ce41e58f4577f2e713c1ac.png)

**Comment by games647** [comment]
Are these three message all coming from FastLogin? It's a bit weird that it sends three messages or do you have multiple server redirects?

**Comment by Eufranio** [comment]
I don't have, the three messages are 
Message from FastLogin by having a premium account
Message by AuthMe by session reconnect
Message by AuthMeBridge by session resumed by Bridge (when I switch servers)

**Comment by games647** [comment]
So you configured FastLogin to have the same message as the other plugins?

**Comment by Eufranio** [comment]
Nope, I'm just saying that the FastLogin message will pop up saying i'm logged, but after, AuthMe message will also pop up, and so on...

**Comment by Eufranio** [comment]
So, the first race condition is fixed, but now AuthMeBridge is having race conditions with FastLogin. Can you fix? Both AuthMeBridge and FastLogin are logging us, then we're having duplicate messages.
