### ISSUE TITLE
can't using a FastLogin, no response at /premium

### ISSUE THREAD

**Issue by ImanSkuy** [games647/FastLogin#1053]
### What happened?

i get this, i think i already set up my config correctly, i cant use /premium command too, no response with  "sending Request"

![Screenshot_20230703_202547_Chrome](https://github.com/games647/FastLogin/assets/125931056/6e5cf7bf-20c1-46b8-bf20-8108ddf38dad)

I'm using a waterfall server for my proxy, but my Authme and fastlogin plugins are on the Subserver, im using a MySQL for my database

### Plugin list

Server Plugins (28) Bukkit Plugins: *AntiVoid, AuthMe, BungeeGuard  *CustomPlaceholders, DeluxeCommands, DeluxeHub, Deluxe Join, DeluxeMenus, DriveBackupV2, Essentials, FastAsyncWorldEdit, FastLogin, HolographicDisplays, JukeBox, LuckPerms, Multiverse -Core, NoteBlockAPI, Placeholder API, ProtocolLib, *Scoreboard-revision, ServersNPC, SkinsRestorer, TAB, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldGuard

### Configuration file

https://hastebin.com/share/qogerizota.yaml

### Server log

https://mclo.gs/h1T098C

### Plugin version

1.12-SNAPSHOT-c106089

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Do you followed the setup guide for BungeeCord with FastLogin referenced on the project page? Sending request means your proxy rejected to answer so take a look at the server log there too.

**Comment by ImanSkuy** [comment]
> Do you followed the setup guide for BungeeCord with FastLogin referenced on the project page? Sending request means your proxy rejected to answer so take a look at the server log there too.
> 
> See this server log message too:
> 
> [05:46:29] [Server thread/INFO]: [FastLogin] Remember to follow the proxy guide to complete your setup

Already, but i din't know What's more, I think that adding Stats ID to allowed proxied is already done

**Comment by ImanSkuy** [comment]
is fastlogin support for 1.20 Waterfall and PaperMC version?

**Comment by games647** [comment]
Please post the bungee log.
