### ISSUE TITLE
Invalid Session

### ISSUE THREAD

**Issue by TonnoConsorzio** [games647/FastLogin#1056]
### What happened?

When I try to log in it tells me invalid session in red, and this happens with only the cracked accounts, but not always only on two or three out of 10 people who have the cracked account. I already saw an existing ticket, but I did not understand how to solve this

### What did you expect?

entering the server normally

### Steps to reproduce

log in to the server

### Plugin list

AureliumSkills, AuthMe, BlockLocker, Chunky, CoreProtect, Corpses, DiscordSRV, Essentials, EssentialsSpawn, FastAsyncWorldEdit, FastLogin, GSit, LPC, LuckPerms, NoChatReports, PL-Hide, PlaceholderAPI, PlayerNPC, ProtocolLib, SkinsRestorer, sleep-most, spark, SternalBoard, SuperVanish, TAB, Vault, Vulcan

### Configuration file

https://gist.github.com/TonnoConsorzio/4837b70fa8fc23205d43c5c68806979c

### Server log

https://gist.github.com/TonnoConsorzio/5ae9187029ea71ed975313ce43ce05ce

### Plugin version

1.12-SNAPSHOT-c106089

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
For cracked accounts, this is normal. Cracked players shouldn't be able to uses onlinemode connection. This is only enabled for premium players. You enabled `autoRegister`, so the plugin requests an onlinemode connection if the username is associated to Mojang account. This solely based on this one property.

Otherwise it **have** to fail as mentioned in the comments above the configuration setting.

**Comment by TonnoConsorzio** [comment]
> For cracked accounts, this is normal. Cracked players shouldn't be able to uses onlinemode connection. This is only enabled for premium players. You enabled `autoRegister`, so the plugin requests an onlinemode connection if the username is associated to Mojang account. This solely based on this one property.
> 
> Otherwise it **have** to fail as mentioned in the comments above the configuration setting.

OK, so I should disable which setting, because many cracked players come in and only these 3 fail and give this error

**Comment by games647** [comment]
This setting only applies to new players, so likely never noticed it before. The username from that player is likely very common.
