### ISSUE TITLE
Asking Premium players to log-in after they rejoin

### ISSUE THREAD

**Issue by Destructomite** [games647/FastLogin#1059]
### What happened?

Premium users have to enter a password if they disconnect and reconnect to a server that’s not the lobby.

### What did you expect?

The Premium user should automatically be logged back in.

### Steps to reproduce

If a premium player joins a server that’s not the lobby, then leaves the server it causes them to have to put their password back in when they rejoin. The only temporary fix to this is to intentionally get the password wrong enough times to the point where it disconnects you back to the lobby.

### Plugin list

AuthMe, FastLogin, ProtocolLib, Essentials, EssentialsChat

### Plugin version

1.10

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Very outdated plugin version. Please update to dev build.
