### ISSUE TITLE
Nothing seems to work?

### ISSUE THREAD

**Issue by Arektor** [games647/FastLogin#106]
So I know, this may seems totally dumb as I see lots of people having this plugin working, but it just won't work with me. I tried on local, on my server, with clean setup: it doesn't work. Latest spigot update, latest jenkins dev build: nothing.

I have a premium account, the server is in offline mode, there is AuthMe on the server and FastLogin says that it successfully hooked into it. I've enabled autoRegister, premiumUuid and forwardSkin: none of them works.

I still need to register and login, I don't have my premium uuid, and I'm in alex skin.

Logs:
http://pastebin.com/awMrsHaY

Offline UUID: 86f0c161-224f-305e-8bdf-9086ff1bfec8
Online UUID: 0946ef02-50fd-43fb-a723-bf0823ce07bf

If you need the AuthMe and FastLogin config folders: https://www.dropbox.com/s/cn2b18jylwmzute/FasTLogin%20and%20AuthMe%20config.zip?dl=1

Am I doing something wrong?

**Comment by games647** [comment]
Do you use Bungee cord?

**Comment by Arektor** [comment]
No, I don't. That's just a spigot 1.11.2 server (just recompiled it with latest build, still the same)

**Comment by games647** [comment]
Autoregister will only be used if the account is knew to AuthMe and FastLogin. You could also try to invoke /premium and relogin.

**Comment by Arektor** [comment]
Tried to /premium then relogin but still the same issue.
However I just updated ProtocolLib, from the version uploaded on Spigot to the latest jenkins dev build, and its now working fine.

All my apologies for that useless ticket, that wasn't coming from FastLogin.
