### ISSUE TITLE
Integration with DiscordSRV role sync.

### ISSUE THREAD

**Issue by Exanthiax** [games647/FastLogin#1068]
DiscordSRV has a role sync system on it where you can prevent players from joining if they are not synced.
Would it be possible to integrate FL into DSRV, where if someone is a Premium account, they do not need to have a role synced, but if they are a cracked account, they will need to sync their Discord to the game and then FL will let them join?

DiscordSRV would handle the links, it's just telling DSRV who is cracked/premium and if it should send a link message or not.
https://github.com/DiscordSRV/DiscordSRV

**Comment by ShadowOfHeaven-Me** [comment]
Rather than posting this as enchancement, you could write a plugin using DiscordSRV's and FastLogin's API
