### ISSUE TITLE
I don't know how but some1 is overriding premium players?

### ISSUE THREAD

**Issue by Wearwolfy** [games647/FastLogin#107]
We need help... 
I enabled autoregister etc, 
But somehow some1 override a donor rank and i saw BajanCanadian and JeromeASF on the server how is this possible??
this is what he said
Dear Reader,
Today I regret to inform you that I have logged in today to find that, due to the server being cracked and using autheticator someone has logged in with my username and is using my account. I hope a member of staff can fix this for me soon. Thanks
Best regards,
ExxGod

**Comment by Wearwolfy** [comment]
config http://pastebin.com/bYAA5gGa

**Comment by Wearwolfy** [comment]
Oh wait, did i need to give my players a specific permission? Cause only now i see that me and my staff members have a skin? The rest is asking where is my skin???

**Comment by Wearwolfy** [comment]
Is there a way to automatically add Premium players to the premium list? so that they don't have a cracked account?

**Comment by games647** [comment]
AutoRegister only auto registers accounts if they use a premium username **and are unknown to AuthMe and FastLogin.**

>The rest is asking where is my skin???

As pointed out in the config. The skin is only visible through a premium connection and if you activated premium skins. Looks like the other player are not connected through the premium one.

>Is there a way to automatically add Premium players to the premium list?

Yes invoke the premium command

**Comment by Wearwolfy** [comment]
What happens if cracked players invoke premium

**Comment by games647** [comment]
Just a warning pops up.

**Comment by Wearwolfy** [comment]
Hmm, if you say that if a premium players auto registers, gets automatically added to the list. Then there must be like a bug or something cause its not giving skins to the players and alot of them were complaining. It looks like our first members do have a skin? My staff and some of the early players? What am i doing wrong?

**Comment by Wearwolfy** [comment]
Maybe its because i have 2 protocol plugins? I have protocollib and protocolsupport

**Comment by games647** [comment]
FastLogin will use ProtocolSupport over ProtocolLib and then ProtocolSupport automatically sets the skin.

**Comment by Wearwolfy** [comment]
Hmm another wierd thing, i just check on other servers(if they have issues).
And the thing is when i press tab on factions, you can see the head in front of the names (most of them are the steve skin) but me and a few other players. And in skyblock, i noticed that there is no head in front of the names?? With is hapening hear?? They both have protocolsupport and protocllib

**Comment by Wearwolfy** [comment]
Is there a known conflict with a plugin?

**Comment by Wearwolfy** [comment]
idk if this helping you but this is a part of a log file when new players login/register on the hub server that is.
http://pastebin.com/PMJ2GXik

**Comment by Wearwolfy** [comment]
I really need this fixed, but i do appreciate your help.
And I am certainly gonna donate to you? (do donors better support?)

**Comment by Eufranio** [comment]
Do you use bungeecord?

**Comment by Wearwolfy** [comment]
@Eufranio yes

**Comment by Eufranio** [comment]
do you have FastLogin installed in both spigot AND bungee?

**Comment by Wearwolfy** [comment]
Yep

**Comment by Eufranio** [comment]
and, where are you editing the configs? bungee or spigot?

**Comment by Wearwolfy** [comment]
All the configs are the same

**Comment by Wearwolfy** [comment]
Wait i just noticed something? There is an authme folder in Bungeecord but not an Authme plugin just AuthmeBridge?

**Comment by Wearwolfy** [comment]
Is that normal?

**Comment by Eufranio** [comment]
is FastLogin loaded in the /plugins list? is the database accessible? (just be MySQL since you are using bungee)

**Comment by Wearwolfy** [comment]
Yeah, everything worked before, lemme check real quick

**Comment by Wearwolfy** [comment]
Yep its enabled

**Comment by games647** [comment]
Could you explain in short words what's actual the issue here.

**Comment by Wearwolfy** [comment]
Since i also saw BajanCanadian and JeromeASF on the server(players were freaking out). Earlier you said players couldn't register with premium names??

**Comment by games647** [comment]
First because the player should be already registered and second because it would try to request a premium authentication from that player. Maybe the playernames had a different case?

**Comment by games647** [comment]
Is my guess correct?

**Comment by Wearwolfy** [comment]
i was trying to figur that out, some1 screenshotted their name but he recently removed his screenshots folder so idk if the uppercases were the same and the players are still complaining about no skins

**Comment by games647** [comment]
As I said the premium are only set if it's a premium connection.

**Comment by Wearwolfy** [comment]
Ye ik, but it are all premium connections xD

**Comment by Wearwolfy** [comment]
They didn't have to /login or /register

**Comment by games647** [comment]
Could you try it without ProtocolSupport

**Comment by Wearwolfy** [comment]
The whole server is like, OMG wtf where is my skin??  YE WTF I am steve

**Comment by Wearwolfy** [comment]
Ye maybe idk, cause some players do have it

**Comment by Wearwolfy** [comment]
The thing is though without protocolsupport the servernpc's don't seem to work

**Comment by Wearwolfy** [comment]
Is there a known issue with Protoclsupport?

**Comment by games647** [comment]
Not known, but please just try it.

**Comment by Wearwolfy** [comment]
Ok ill remove ProtocolSupport tommorow and hope that this is fixed

**Comment by Wearwolfy** [comment]
Oh wait, i am using fastlogin v1.9 maybe thats the issue?

**Comment by Wearwolfy** [comment]
hello?

**Comment by Wearwolfy** [comment]
if i use v1.10 would it then be fixed?

**Comment by games647** [comment]
What if you just try it....

**Comment by Wearwolfy** [comment]
well then i would need to remake like my whole hub server cause if one server doesn't have protocolsupport, the servernpc plugin can't detect if there are players on that server

**Comment by games647** [comment]
It's just temporarily

**Comment by Wearwolfy** [comment]
but in the last issue you said "use protocolsupport or protocollib, you can find it on spigot"

**Comment by Wearwolfy** [comment]
I have a test server

**Comment by Wearwolfy** [comment]
i removed everything from authme and fastlogin db, logged in and had my skin

**Comment by Wearwolfy** [comment]
Oh wait maybe if i do this and install protocolsupport again

**Comment by games647** [comment]
Stop spamming. Edit your existing post if you post it within seconds.

**Comment by Wearwolfy** [comment]
I am not spamming ....

**Comment by Wearwolfy** [comment]
You may close this, I think its related to the current issue I have

**Comment by Wearwolfy** [comment]
Nvm ill do it myself
