### ISSUE TITLE
Premium players can't login

### ISSUE THREAD

**Issue by Lazer4o** [games647/FastLogin#1080]
### What happened?

![image](https://github.com/games647/FastLogin/assets/84748484/89e706cb-d2cb-43ed-b740-3cca86cd25f2)

### Plugin version

latest

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Please try again with an vanilla client. I need the exact error message and the corresponding server log.
