### ISSUE TITLE
FastLogin Not Working, No Response on Exicuting /premium 

### ISSUE THREAD

**Issue by WAFFUGOD** [games647/FastLogin#1082]
### What happened?

I had already Added all Configs
Everything is Done
Does it works for 1.20?
I had Used protocol Lib too bTw

### What did you expect?

Please Fix it Asap

### Plugin version

Latest

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Please post the exact version as mentioned in the template and the server log.
