### ISSUE TITLE
ViaVersion BIG BUG 🪲!

### ISSUE THREAD

**Issue by tomasalias** [games647/FastLogin#1083]
### What happened?

I have a 1.20.1 Purpur Minecraft server with ViaVersion and ViaBackwards. When I try to join with version 1.19.4, this error message appears.

![Snímek obrazovky 2023-08-30 112535](https://github.com/games647/FastLogin/assets/80042910/db58a864-5a01-4479-a6a9-b496fafc3660)

### Plugin list

BKCommonLib, AuthMe, CoreProtect, DeluxeTags, DriveBackupV2, *DynamicIcon, Essentials, FastLogin, floodgate, Geyser-Spigot, KitPvP, LagAssist, LuckPerms, My_Worlds, *OnePlayerSleep, PlaceholderAPI, ProtocolLib, SilkSpawners_v2, SkinsRestorer, SmoothTimber, spark, Train_Carts, Vault, ViaBackwards, ViaVersion, WorldEdit, zDiscord

### Plugin version

1.12-SNAPSHOT-ae2e6b3

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Does this error reproduce without FastLogin?

**Comment by tomasalias** [comment]
I use ViaVersion and ViaBackwards 4.7.1

**Comment by games647** [comment]
It's about the network protocol so it is likely related to ViaVersion or ViaBackwards. My advice would be you redirect this report to them as it happens without FastLogin too.
