### ISSUE TITLE
FastLogin error bungeecord

### ISSUE THREAD

**Issue by moneth16** [games647/FastLogin#1088]
How to fix it?
https://pastebin.com/5NvTxTM3

**Comment by games647** [comment]
Please use the bug template on opening and fill it with the relevant details. For example the plugin version is relevant here to help you.

**Comment by moneth16** [comment]
**What happened?**
https://pastebin.com/5NvTxTM3

**What did you expect?**

I was expecting the plugin to load correctly on waterfall

**Steps to reproduce**

I just setted the plugin for the first time so there notthing to reproduce

**Plugin list**

AuthMeBungee-2.2.0-beta1, BungeeGuard.jar,  FastLoginBungee.jar

**Configuration file**

https://pastebin.com/6HdPDwPq

**Server log**

https://pastebin.com/7CaUMY3g

**Plugin version**

1.12-SNAPSHOT-d76690d

**Platform**

WaterFall 1.18

**Comment by games647** [comment]
You are using an outdated BungeeCord version. Please update it.
