### ISSUE TITLE
1.8 FastLogin compatability

### ISSUE THREAD

**Issue by Brickery** [games647/FastLogin#109]
On the plugin page on Spigot it says that this plugin is compatible with 1.7 through 1.11. However the readme.md file on github says it is only compatible with 1.9 and up. I cannot find the correct version for 1.8, could you help me?

The error I get when I use fastlogin: http://pastebin.com/5hFkXfFB

**Comment by Eufranio** [comment]
You need [ProtocolLib](https://www.spigotmc.org/resources/protocollib.1997/).

**Comment by games647** [comment]
@Brickery The newer versions were only tested against the newest minecraft versions, but the plugin is backwards compatible so it should also for that versions.

As @Eufranio said ProtocolLib or ProtocolSupport is required. This is also mentioned on Spigot and Github.
