### ISSUE TITLE
Fastlogin dosn't seem to work with mysql ( MC paper  1.20.1 and 1.12-SNAPSHOT ) 

### ISSUE THREAD

**Issue by VladFilen** [games647/FastLogin#1092]
### What happened?

I'm using both FastLoginBukkit.jar and FastLoginBungee.jar
Every time I do the /fastlogin command it returns an eternal error 
I'm using MariaDB 
My server in the offline mode

### Plugin list

ActionbarCoords, AuthMe, BetterItemFrames, BetterKeepInventory, Brewery, ColoredSigns, CoreProtect, DeathCoords, DiscordSRV, EmeraldBank ,Essentials, EssentialsSpawn, FarmAssistReboot, FastLogin, floodgate, Geyser-Spigot, GrimAC, HotbarRefill, ImageFrame, *isSlimeChunk ,LuckPerms, LWC, MoreMobHeads, NoCropTrample, PlaceholderAPI, ProtocolLib, Shopkeepers, SkinsRestorer, Towny, TownyChat ,UberEnchant, Vault, ViaBackwards, ViaVersion, WorldEdit, WorldGuard

### Configuration file

https://hastebin.com/share/atiliwokas.yaml

### Server log

https://hastebin.com/share/wayicetano.php

### Plugin version

1.12-SNAPSHOT-d76690d

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Please use mysql driver in Spigot. The mariadb driver is currently not shipped with the Bukkit version of the plugin.

**Comment by VladFilen** [comment]
Thank you, it's fixed
