### ISSUE TITLE
KCauldron

### ISSUE THREAD

**Issue by ArcasCZ** [games647/FastLogin#11]
Can you please try to rewrite it agaist newest KCauldron? There are several things that are missing at KCauldron, so it doesn't work.

**Comment by games647** [comment]
>several things that are missing at KCauldron, so it doesn't work.

What do you mean by that?

**Comment by ArcasCZ** [comment]
I mean there is lot of things that are incompatibile - its still at 1.7.10 with some specific (such as Guava and problem with that ClassSearch function (hoverer it names)).

**Comment by games647** [comment]
>I think for you, as developer who know his plugin, it's easier.

Of course I understand that.

>1.7.10 with some specific (such as Guava and problem with that ClassSearch function (hoverer it names)).

Oh right, the libraries...

**Comment by ArcasCZ** [comment]
Is there somethink that you can do with it? :-) May I help you someway?

**Comment by sgdc3** [comment]
Just create a separate "legacy" jar with the missing dependencies, like authme does ;)

**Comment by ArcasCZ** [comment]
There goes the problem. Example: KCauldron use Guava 10, you need Guava 17 - which will be used?

**Comment by sgdc3** [comment]
@games647

**Comment by games647** [comment]
>And another problem - the function which gets Spigot config is somehow broken - I can't find it.

You mean you cannot find it in Cauldron?

BTW: How do you enable BungeeCord support on Cauldron servers?

**Comment by ArcasCZ** [comment]
Bungee support on KCauldron is really bad... You can enable it in spigot.yml but I don't know, if it works. Also, when I tried compile it by myslef I can't find function, that will return spigot config...

**Comment by games647** [comment]
Travis compiles it completely fine. You can it here for example: https://github.com/bergerkiller/CraftSource/blob/master/org.bukkit.craftbukkit/CraftServer.java#L1718

**Comment by ArcasCZ** [comment]
You have to look here - https://gitlab.prok.pw/KCauldron/KCauldron

**Comment by ArcasCZ** [comment]
Especially here
https://gitlab.prok.pw/KCauldron/KCauldron/blob/master/src/main/java/org/bukkit/craftbukkit/CraftServer.java

**Comment by games647** [comment]
I didn't know that Cauldron have Spigot embed. 

Then it has to be accessed directly. org.spigotmc.SpigotConfig.bungeecord

**Comment by ArcasCZ** [comment]
Or add in config value: BungeeCord: true/false :-)

Will you port it on KCauldron then? :-)

**Comment by games647** [comment]
>Will you port it on KCauldron then? :-)

yes

>Or add in config value: BungeeCord: true/false :-)

It's better to use the server software features of ip and uuid forwarding then implementing a new one.

**Comment by ArcasCZ** [comment]
That's true. If you'll need any help, just tell me :-) Anyway - when you think it will be done? :-)

**Comment by games647** [comment]
>when you think it will be done? :-)
This weekend or next week

**Comment by ArcasCZ** [comment]
OK, That's nice :-)

**Comment by ArcasCZ** [comment]
How does it looks like? :-)

**Comment by games647** [comment]
I had not much free time. So I'll do it this weekend.

**Comment by games647** [comment]
@ArcasCZ 

You said:
>There goes the problem. Example: KCauldron use Guava 10, you need Guava 17 - which will be used? 

But I can only find guava within the package guava10.com...
Do you meant that?

**Comment by games647** [comment]
Nevermind I found out that it redirects it.

**Comment by ArcasCZ** [comment]
So, does it works at KCauldron server? :-)

**Comment by games647** [comment]
I **guess**

**Comment by ArcasCZ** [comment]
Any public build or should I build it by myself?

**Comment by games647** [comment]
I had no time to test it. So there is no public build at the moment.

**Comment by ArcasCZ** [comment]
Could you send me compiled file? I'll test it today.

**Comment by games647** [comment]
https://github.com/games647/FastLogin/releases/tag/1.3

**Comment by ArcasCZ** [comment]
Thanks. I'll test it and let you know.

**Comment by ArcasCZ** [comment]
http://pastebin.com/SUPCuGvq

**Comment by games647** [comment]
What? But this class is included in FastLogin.

**Comment by games647** [comment]
Is this the complete exception?

**Comment by ArcasCZ** [comment]
Yep. Absolutely complete. Anyway - I saw it is in jar file. So...

**Comment by games647** [comment]
Lets try to move it somewhere else. https://github.com/games647/FastLogin/releases/tag/CLASS_LOADING

**Comment by ArcasCZ** [comment]
http://pastebin.com/35sGkNJb

Nope...

Do you have TeamSpeak?

**Comment by games647** [comment]
Do you have the correct version, because it should be now pointing to a different package.

**Comment by ArcasCZ** [comment]
Yep.

**Comment by games647** [comment]
But it works for me.

**Comment by ArcasCZ** [comment]
Do you run it on KCauldron?

**Comment by games647** [comment]
yes

**Comment by ArcasCZ** [comment]
Do you have TeamSpeak / Skype?

**Comment by games647** [comment]
I have both. I would prefer Skype at the moment if that's okay for you?

**Comment by ArcasCZ** [comment]
Yep, add me - Vojtas-pocitac

**Comment by ArcasCZ** [comment]
Seems working!

**Comment by ArcasCZ** [comment]
Solved - problem on my side.

**Comment by games647** [comment]
Can I move org.slf4j back?

**Comment by games647** [comment]
Is it normal that I cannot join the server with a vanilla client (no mods), but it works with forge?

**Comment by ArcasCZ** [comment]
Yep, you can :-)

Also, KCauldron server won't let you connect, 'cause it has some changes in server. But with Forge you can connect vanilla servers.
