### ISSUE TITLE
Driver doesn't accept JDBC URL

### ISSUE THREAD

**Issue by games647** [games647/FastLogin#1100]
Using the latest velocity version and the latest fastlogin version
I've made sure my database is configured correctly

The first picture appears when I use mysql
The second picture appears when I use mariadb
![QQ图片20231007030352](https://github.com/games647/FastLogin/assets/76251800/3d4b5bd5-4309-4d4d-ac84-ddba1c50fd29)
![QQ图片20231007030358](https://github.com/games647/FastLogin/assets/76251800/8d91cbac-c91e-44ca-bc74-f31ffe70af6f)

_Originally posted by @LovelyGuYiMeng in https://github.com/games647/FastLogin/discussions/1099_

**Comment by games647** [comment]
@LovelyGuYiMeng Could you post the exact config for mariadb version and which exact version number of FastLogin you use. I checked the code and it should already do the correct behavior.

**Comment by LovelyGuYiMeng** [comment]
> @LovelyGuYiMeng您能否发布 mariadb 版本的确切配置以及您使用的 FastLogin 的确切版本号。我检查了代码，它应该已经执行了正确的行为。

fastlogin is the last development version #1282
mariadb version is 10.11.5 and default config

**Comment by games647** [comment]
Could you please post/upload the complete config for the MariaDB case. Just tested it again and it works for me.

**Comment by Krakenied** [comment]
Its now broken for custom drivers due to the lowercase
https://github.com/games647/FastLogin/blob/70960661b43aa9a4688d6c46adbff5da809854ed/core/src/main/java/com/github/games647/fastlogin/core/storage/MySQLStorage.java#L51
