### ISSUE TITLE
INVOKESPECIAL/STATIC on interfaces require ASM 5

### ISSUE THREAD

**Issue by ArcasCZ** [games647/FastLogin#111]
I've got problem using FastLogin on Thermos (latest build) for MC 1.7.10, Java 8 and latest FastLogin

Log: http://pastebin.com/VSH56FQb

**Comment by Wearwolfy** [comment]
Do you have Protocollib or protcolsupport installed?
Do you have an auth plugin installed?

**Comment by ArcasCZ** [comment]
Yes, I have ProtocolLib v. 3.7.0 and AuthMe 5.2-SNAPSHOT-1529

**Comment by Wearwolfy** [comment]
Maybe try an older fastlogin build, i use it for 1.8 and it works

**Comment by ArcasCZ** [comment]
Used version I was using before (first Cauldron supporting version) and still same error.

**Comment by Eufranio** [comment]
The SpecialSource library included with Thermos uses ASM4.
Updating it to the latest version will fix the issue.

Instructions for updating to ASM5:
1. Navigate to the libraries\net\md-5\SpecialSource\1.7-SNAPSHOT folder of the server
2. Delete the SpecialSource-1.7-SNAPSHOT.jar jar file
3. Download SpecialSource v1.7.4 from http://central.maven.org/maven2/net/md-5/SpecialSource/1.7.4/SpecialSource-1.7.4.jar
4. Copy the jar file to the libraries\net\md-5\SpecialSource\1.7-SNAPSHOT folder
5. Rename the jar file you just copied to SpecialSource-1.7-SNAPSHOT.jar

**Comment by games647** [comment]
Thanks a lot for @Eufranio 

I'm closing this, because it's duplicate with #84

**Comment by Kamilkime** [comment]
For anyone who is looking for download of that SpecialSource v1.7.4 (used in that great tutorial of @Eufranio) - you can find it here =)
https://repo1.maven.org/maven2/net/md-5/SpecialSource/1.7.4/SpecialSource-1.7.4.jar
