### ISSUE TITLE
Race condition: AuthMe session and FastLogin premium auto-login

### ISSUE THREAD

**Issue by Eufranio** [games647/FastLogin#112]
When I am logged by AuthMe session & FastLogin logs me by having a premium account, messages are duplicate:

![a](http://image.prntscr.com/image/2c460d26c48e42f18de5c8bd8fc69f2a.png)

1st message: I am logged in by having a premium account
2nd message: I am logged in by session
3th and 4th messages: AuthMe "logged successfully" response for the 2 successfull logins.

**Comment by Eufranio** [comment]
whoops, it's fixed.

**Comment by Eufranio** [comment]
My god...

![a](http://image.prntscr.com/image/66eba9e0a12d4ec4b106f69dbfd27cb4.png)

There's no "you were logged by having a premium account" message now, but looks like the login event is fired twice...

**Comment by games647** [comment]
Use #103 for that.
