### ISSUE TITLE
Thermos vs. IllegalAccessError

### ISSUE THREAD

**Issue by ArcasCZ** [games647/FastLogin#113]
http://pastebin.com/8n5y1R9a

FastLogin: v1.9
Thermos: Latest
Forge: 1614
MineCraft: 1.7.10

**Comment by Eufranio** [comment]
What's your ProtocolLib version?

**Comment by games647** [comment]
Update it to a dev-build

**Comment by ArcasCZ** [comment]
Where I can found it?
