### ISSUE TITLE
Unknown console error

### ISSUE THREAD

**Issue by mwmo2911** [games647/FastLogin#1130]
### What happened?

Whenever a player logs into the server, errors appear in the console.

### Plugin list

Paper Plugins: (1): EconomyShopGUI-Premium Bukkit Plugins: (64): AdvancedChests, AuthMe, *Banknotes, BattlePass, BetonQuest, BloodNight, Chunky, ChunkyBorder, Citizens, CMI, CMILib, Codex, CommandNotifier, CommandPanels, ConsoleSpamFix, Core, CoreProtect, CoreProtectTNT, CustomBansPlus, CustomEnchantments3, DeluxeMenus, DiceFurniture, DiscordSRV, Drop2Inventory, EzChestShop, FastAsyncWorldEdit, *FastLogin, FearFeeling, *FloodFill, FurnitureLib, InventoryRollbackPlus, ItemRarityGlow, Jobs, LuckPerms, MiniMOTD, MMOCore, Multiverse-Core, Multiverse-Portals, MythicLib, MythicMobs, NPC_Destinations, OreAnnouncer, Pl-Hide-Pro, PlaceholderAPI, Plan, PowerNBT, ProtectionLib, ProtocolLib, RegionRaid, Shopkeepers, SkinsRestorer, SkQuery, Skript, spark, SpawnerMeta, SuperiorSkyblock2, TAB, UltraCosmetics, Vault, Vegas, VentureChat, Vouchers, WildTools, WorldGuard

### Configuration file

https://hastebin.com/share/zocoquvini.yaml

### Server log

https://hastebin.com/share/oramebixum.ruby

### Plugin version

1.10-git484855724b794de1fe057cf7360245362658b432

### Platform

Spigot

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by games647** [comment]
That's an outdated plugin version. Please try to to use a development as mentioned in the checklist.
