### ISSUE TITLE
Incorrect access control settings for wiki pages

### ISSUE THREAD

**Issue by nartsisss** [games647/FastLogin#1138]
Current settings for wiki pages in the repository allows any user without collaborator status to edit, create, or delete pages:
<img width="1346" alt="image" src="https://github.com/games647/FastLogin/assets/54633007/544c071f-1cea-4dfd-9403-cc0569f08a1f">

This poses a security risk as random user may modify general information contained in the wiki pages.
You should fix it in _**Settings** > **General** > **Features**_
![image](https://github.com/games647/FastLogin/assets/54633007/4d42cd23-ee43-4804-bbcd-68eec96887c6)

**Comment by games647** [comment]
It is open on purpose to edit the language files.

**Comment by nartsisss** [comment]
Thanks for the quick reply.

Unfortunately, you can't restrict editing of certain wiki pages, at some point there will be someone who will abuse it.

Maybe you should move this from the wiki pages to a separate (for example "locales") directory with a locale file for each language?
