### ISSUE TITLE
Auto register not working for some players

### ISSUE THREAD

**Issue by Wearwolfy** [games647/FastLogin#114]
Do the players need a permissions? Cause atm it isn't working
http://i.imgur.com/T031ZgC.png

**Comment by Wearwolfy** [comment]
![2017-01-14_22 46 19](https://cloud.githubusercontent.com/assets/21149078/21958290/525689b4-daab-11e6-82f2-93f0a51228fe.png)

**Comment by Wearwolfy** [comment]
As you see only me and another player are premium and the rest are cracked players

**Comment by lizardfreak321** [comment]
Can you attach your config with MySQL credentials edited out?

**Comment by Wearwolfy** [comment]
Ok

**Comment by Wearwolfy** [comment]
http://pastebin.com/Phx2AEXc

**Comment by Wearwolfy** [comment]
Its the same on all the servers

**Comment by lizardfreak321** [comment]
Is your server behind a bungeecord proxy?

**Comment by Wearwolfy** [comment]
Ye, fastlogin is also installed on bungeecord

**Comment by lizardfreak321** [comment]
Is that the config from bungeecord? The only config that matters is that one if I am not mistaken.

**Comment by Wearwolfy** [comment]
Ok

**Comment by Wearwolfy** [comment]
Lemme get that config

**Comment by Wearwolfy** [comment]
http://pastebin.com/jrbfU6ia

**Comment by lizardfreak321** [comment]
Does it work after the players do /premium?

Your config appears to be old, try regenerating it by deleting it, then reconfigure it. There will be a few new options.

**Comment by Wearwolfy** [comment]
I am still using v1.9

**Comment by Wearwolfy** [comment]
Should i upgrade and yes /premium works then players get their skin

**Comment by lizardfreak321** [comment]
Your config appears to be what is out of date, not the jar. Regenerate it, and configure the settings.

**Comment by Wearwolfy** [comment]
lets say, it do this will it be fixed then?

**Comment by lizardfreak321** [comment]
I don't think so, but it is something that I highly recommend. If it doesn't work after the config refresh, you will need help with games647

**Comment by Wearwolfy** [comment]
damn @games647 Where is my hero when I need him, thats why i need his skype :/

**Comment by lizardfreak321** [comment]
You created this issue two hours ago, and for now your players can just do /premium. I think he is asleep, he will help you here when he can.

**Comment by Wearwolfy** [comment]
No they can't they need permission for that xD
I am giving it manually to them but its fine. Only if it worked Thanks for the help anyway @lizardfreak321

**Comment by games647** [comment]
>damn @games647 Where is my hero when I need him, thats why i need his skype :/

That's why I don't accept it. In the previous ticket I already asked you why you want that, but I received no answer. My reasons are:
1. There is a reason for a ticket management. It's easier to manage issues, feature requests and so on
2. Other users could search for existing tickets and then maybe could solve it on their own
3. This is not a one-man-project. There are others that help too. (This is **not** limited to coders)
4. Last but not least, I'm not always available for help. There are others too (like in this case asked for the config - thanks to @lizardfreak321 ) So that you can get your solution **faster**. 

In fact I'm more often on Github than on Skype. I hope you understand me. 

BTW: As I said in the other ticket. If you make new posts between a couple of minutes and there is no new answer in the meanwhile. Please be kind and use edits or think about just doing one bigger post.

Back to the topic of this ticket. 
What about the database records of those players? Are those player saved as premium there?

**Comment by Wearwolfy** [comment]
1. Sorry from now on I will be editing my post
2. I don't really know what u mean by that? How do I check? U want a screenshot of the a database?

**Comment by games647** [comment]
>What the user above me said, could that be the issue?

FastLogin always uses default values if they are not in the config, but the config seems to be up-to-date.

You could try out a dev-build from here: http://ci.xephi.fr/job/FastLogin/

>I don't really know what u mean by that? How do I check? U want a screenshot of the a database?

Just tell me if the premium column is set to 1 for the reported players.

**Comment by Wearwolfy** [comment]
I just checked the database and the things that is wierd is that there are 11k premium fields and 6k authme fields

**Comment by games647** [comment]
AuthMe purges old data automatically.

**Comment by Wearwolfy** [comment]
See this is why I write new messages, so it notifies you, otherwise it takes too long for you to reply

**Comment by games647** [comment]
https://github.com/games647/FastLogin/issues/114#issuecomment-272681184
>between a **couple of minutes** and there is **no new answer in the meanwhile**

>FINAL EDIT: Yep, this is difenetly the cause , in the beginning everything works perfect after the bot attacks, no premium players are registered again

I think it's because the server reached the maximum amount of 600 name -> uuid requests per 10 minutes. Sadly the API from mcapi.ca is removed, so there is no backup solution.

**Comment by Wearwolfy** [comment]
So whats the fix?

**Comment by games647** [comment]
Use a antibot plugin.

**Comment by games647** [comment]
I'm closing this, because it's only related to #110
