### ISSUE TITLE
The plugin gets stuck at: Sending request...

### ISSUE THREAD

**Issue by roberto7745** [games647/FastLogin#1145]
### What happened?

The plugin gets stuck at: Sending request... and doesn't work. I am putting the command on the lobby server.
I use it on a network with 1 bungeecord, 1 auth (paper) and 1 lobby (Paper)

### What did you expect?

Not working

### Steps to reproduce

I putted /premium

### Plugin list

Authme, Authmebungee, Fastlogin, ProtocolLib and more.

### Configuration file

https://gist.github.com/roberto7745/8a664e514111e813c325af504c957888#file-gistfile1-txt

### Server log

https://gist.github.com/roberto7745/fac721b9b42c44334bb071dea2b7e84c#file-gistfile1-txt

### Plugin version

1.10-git484855724b794de1fe057cf7360245362658b432

### Platform

BungeeCord

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by games647** [comment]
You are not using the latest build. Version 1.10 is totally out of date.

**Comment by roberto7745** [comment]
> You are not using the latest build. Version 1.10 is totally out of date.

![image](https://github.com/games647/FastLogin/assets/139126016/1f3b3fb4-f90a-4be6-8bd7-b097686bb5a6)
![image](https://github.com/games647/FastLogin/assets/139126016/86d4b545-5a90-4148-8218-2c8eee797e3a)

I'm now using this version and this is the message.

**Comment by games647** [comment]
And do you followed the BungeeCord setup guide of this plugin?

**Comment by roberto7745** [comment]
Yes.

**Comment by roberto7745** [comment]
> And do you followed the BungeeCord setup guide of this plugin?
> 
> https://github.com/games647/FastLogin?tab=readme-ov-file#bungeecordwaterfall-or-velocity

![image](https://github.com/games647/FastLogin/assets/139126016/4181e4a0-e808-44cd-93a0-0a8b82c0f9dc)
Where can I found this?

**Comment by roberto7745** [comment]
![image](https://github.com/games647/FastLogin/assets/139126016/148ba796-8217-413e-bc32-e58e664f6962)
fastlogin send this to auth server

**Comment by roberto7745** [comment]
[15:43:34 INFO]: [FastLogin] Enabling FastLogin v1.12-SNAPSHOT-108f5ad
[15:43:34 INFO]: [FastLogin] Found enabled proxy configuration
[15:43:34 INFO]: [FastLogin] Remember to follow the proxy guide to complete your setup

And when  I start the lobby Fastlogin send this

**Comment by games647** [comment]
Please post the bungee proxy log.

**Comment by roberto7745** [comment]
> Please post the bungee proxy log.

No message is sent to the proxy.

**Comment by games647** [comment]
If you install the plugin on the plugin on the proxy too like the guide says, you will log message inside the `proxy.log` file. Please post the complete file.
