### ISSUE TITLE
Other plugins PreLoginEvent deny reason does not show, player gets disconnected with timeout. (Velocity)

### ISSUE THREAD

**Issue by GregorSomething** [games647/FastLogin#1146]
### What happened?

When player connects to server and some plugin handles PreLoginEvent (Velocity) before FastLogin, then player gets disconnected with time out exception. This is due to miss handled Continuation in FastLogins PreLoginEvent.
https://github.com/games647/FastLogin/blob/108f5ad32404c0be029e3801fd03b93a096a59d7/velocity/src/main/java/com/github/games647/fastlogin/velocity/listener/ConnectListener.java#L74-L76
Does not let event to resume and same is here
https://github.com/games647/FastLogin/blob/108f5ad32404c0be029e3801fd03b93a096a59d7/velocity/src/main/java/com/github/games647/fastlogin/velocity/listener/ConnectListener.java#L84-L94
Line is missing before `return` or `break`
```java
continuation.resume();
``` 

### What did you expect?

Player would get instantly disconnected with correct reason.

### Steps to reproduce

1. Write a plugin that would subscribe to event `PreLoginEvent` with PostOrder.EARLY or FIRST.
2. Set result to deny with or without a reason.
3. FastLogin causes time out for this connection.
4. Player does not see correct disconnect reason.

### Plugin list

my-plugin, fastlogin

### Plugin version

1.12-SNAPSHOT-108f5ad

### Platform

Velocity

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by games647** [comment]
Oh, yes that's an oversight. Thank you very much.
