### ISSUE TITLE
SSLHandshakeException handshake_failure

### ISSUE THREAD

**Issue by Llamatic** [games647/FastLogin#115]
[Server] SEVERE [FastLogin] Tried converting name->uuid from third-party api

javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

`15.01 09:05:59 [Server] INFO at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
15.01 09:05:59 [Server] INFO at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
15.01 09:05:59 [Server] INFO at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
15.01 09:05:59 [Server] INFO at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
15.01 09:05:59 [Server] INFO at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
15.01 09:05:59 [Server] INFO at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
15.01 09:05:59 [Server] INFO at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
15.01 09:05:59 [Server] INFO at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
15.01 09:05:59 [Server] INFO at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
15.01 09:05:59 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
15.01 09:05:59 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
15.01 09:05:59 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1433)
15.01 09:05:59 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1431)
15.01 09:05:59 [Server] INFO at java.security.AccessController.doPrivileged(Native Method)
15.01 09:05:59 [Server] INFO at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
15.01 09:05:59 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1430)
15.01 09:05:59 [Server] INFO at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
15.01 09:05:59 [Server] INFO at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
15.01 09:05:59 [Server] INFO at com.github.games647.fastlogin.core.shared.MojangApiConnector.getUUIDFromAPI(MojangApiConnector.java:125)`

**Comment by games647** [comment]
Update your Java version
