### ISSUE TITLE
Login Problem with /premium

### ISSUE THREAD

**Issue by zNitrx** [games647/FastLogin#1157]
### What happened?

When I register myself in the Test Server and I do /premium, it works, but if I logout and then I log in again, I can't log in and console gives an error

### What did you expect?

That I can join normally

### Steps to reproduce

1st: /register [Password] [Password]
2nd: When you are registered, you do /premium
3rd: You logout
4th: You log in
5th: You can't join and console gives a huge error

### Plugin list

AuthMeReloaded, ProtocolLib, FastLogin, ViaBackwards & ViaVersion

### Configuration file

https://gist.github.com/zNitrx/b3afb7f50c8cde047269079343c70fee

### Server log

https://gist.github.com/zNitrx/0ce521d651287b56422fbb6a749e6471

### Plugin version

5.6.0-SNAPSHOT-b2614

### Platform

Spigot

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version; i.e. v1.10 is out of date)

- [x] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by games647** [comment]
Please verify the checklist again. You are using an out of date plugin version.
