### ISSUE TITLE
Can"t login as premium player

### ISSUE THREAD

**Issue by nicogb2007** [games647/FastLogin#1163]
### What happened?

I could not join the server and it sent an error message instead
![Capture d’écran 2024-03-02 171710](https://github.com/games647/FastLogin/assets/107760410/2cd6637f-8cb7-4574-b34b-85904ef9545a)

### What did you expect?

Joining the server and getting auto loged in as it always did before

### Steps to reproduce

I tried to join the server and the error popped up

### Plugin list

MarriageMaster, AngelChest, BlockProt, DiscordSRV, Essentials, EssentialsSpawn, FastLogin, floodgate, Geyser-Spigot, LoginSecurity, LuckPerms [16:18:10 INFO]:  Maintenance, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, OpenAudioMc, PlaceholderAPI, ProtocolLib, SilkSpawners, SkinsRestorer, ViaVersion  voicechat, WorldEdit

### Configuration file

https://pastebin.com/uZ7U1Ddc

### Server log

https://pastebin.com/tAniKc3b

### Plugin version

1.12-SNAPSHOT-a65a5f3

### Platform

Spigot

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version; i.e. v1.10 is out of date)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by ShadowOfHeaven-Me** [comment]
This seems to be the server's fault, rather than FastLogin's
