### ISSUE TITLE
Server is not fully started yet. Please retry

### ISSUE THREAD

**Issue by itznotwilly** [games647/FastLogin#1167]
### What happened?

when i want to join i get this 'Server is not fully started yet. Please retry'

### Server log

[18:37:56 INFO]: Disconnecting *** (/****): Server is not fully started yet. Please retry
[18:37:56 INFO]: *** (/****) lost connection: Server is not fully started yet. Please retry

### Plugin version

1.12-SNAPSHOT-a65a5f3

### Platform

Spigot

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version; i.e. v1.10 is out of date)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by itznotwilly** [comment]
i forgot to say i juse 1.20.4

**Comment by games647** [comment]
Please post the startup log
