### ISSUE TITLE
Auto login does not work

### ISSUE THREAD

**Issue by juanchiLopez** [games647/FastLogin#117]
Hello, the auto login does not work, in bungee cord I have the fastlogin plugin and on the login server spigot I have the fastlogin version 1.9 plugin with authme reloaded version 5.2. In the log output this message "[17:58:40] [Server thread / INFO]: [FastLogin] BungeeCord setting detected. No auth plugin is required"

The plugin is excellent. Sorry for my bad English

**Comment by games647** [comment]
Do you followed the setup guide on this project page?

**Comment by PabloGamer380YT** [comment]
It happens the same as the one, just that I do not know what to put in the proxy-whitelist could you give me an example ?? Because the file goes blank, I already copy and paste the bungeecord stats ID and I'm still throwing the same error

**Comment by PabloGamer380YT** [comment]
Forget it, I already knew how, but I advise you specify a little better say with images, for those who do not know much about Plugins or things like that

**Comment by games647** [comment]
So what was the problem?

**Comment by PabloGamer380YT** [comment]
None, I just did not know exactly what to put on the proxy-whitelist
