### ISSUE TITLE
Errors in console on player join

### ISSUE THREAD

**Issue by SwierczKacper** [games647/FastLogin#1186]
### What happened?

Every time any player connecting to server console got spammed by errors from plugin.

### What did you expect?

Working.

### Steps to reproduce

Install plugin :)

### Plugin list

ajParkour, AuthMe, AutoPickup, Citizens, CoreProtect, CustomOreGen, Elevator, Essentials, EssentialsSpawn, GSit, HackedCore*, HackedServer, HolographicDisplays, Infiniteannouncements, InventoryRollbackPlus, InvSeePlusPlus, IridiumSkyblock, KSBChatManager, KSBCommandsManager, KSBFakePlayers, KSBLoginManager, KSBSkyBlock, LiteBans, Lottery, LuckPerms, Multiverse-Core, NametagEdit, OfflineGrowthPro, PistonMOTD, PlaceholderAPI, Plan, PlayerParticles, PluginManager, ProtocolLib, PublicCrafters, RealScoreboard, RePlant, SilkSpawners, SkinsRestorer, SM-Votifier*, StackMob, SuperVanish, TabList, TheCore, TimeIsMoney, TreeFeller, UltimateAntiBot, UltimateAutoRestart, UltimateShops, Vault, ViaBackwards, ViaRewind, ViaVersion, VoidGen, Vulcan, WorldEdit, WorldGuard

### Configuration file

https://hastebin.com/share/agavewobur.yaml

### Server log

https://mclo.gs/EQ2PnkT

### Plugin version

1.10

### Platform

Spigot

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version; i.e. v1.10 is out of date)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by games647** [comment]
Please download the latest build referenced on the checklist.
