### ISSUE TITLE
Failed to check premium state (BungeeAuth)

### ISSUE THREAD

**Issue by VankkaGithub** [games647/FastLogin#119]
BungeeCord log: http://pastebin.com/d6fityab
FastLogin config: http://pastebin.com/cQWgMmDH
BungeeAuth config: http://pastebin.com/DNnkypFk

The mysql user has all permissions and both plugins are connected to the same database
I also have FastLogin installed on both Bungee and Spigot
I have enabled `ip-forward` and `bungeecord`
```
18:06:38 [SEVERE] [BungeeAuth] Could not connect to MySQL database! Because: Cannot load connection class because of underlying exception: 'java.lang.NumberFormatException: For input string: "null"'.
18:06:38 [SEVERE] [FastLogin] Failed to check premium state
java.lang.NullPointerException
	at me.vik1395.BungeeAuth.Tables.checkPlayerEntry(Tables.java:93)
	at com.github.games647.fastlogin.bungee.hooks.BungeeAuthHook.isRegistered(BungeeAuthHook.java:63)
	at com.github.games647.fastlogin.core.shared.JoinManagement.checkPremiumName(JoinManagement.java:68)
	at com.github.games647.fastlogin.core.shared.JoinManagement.onLogin(JoinManagement.java:47)
	at com.github.games647.fastlogin.bungee.tasks.AsyncPremiumCheck.run(AsyncPremiumCheck.java:34)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by games647** [comment]
>18:06:38 [SEVERE] [BungeeAuth] Could not connect to MySQL database! Because: Cannot load connection class because of underlying exception: 'java.lang.NumberFormatException: For input string: "null"'.

I think you missed that message

**Comment by VankkaGithub** [comment]
nope i didn't

**Comment by VankkaGithub** [comment]
It worked before i added FastLogin

**Comment by games647** [comment]
FastLogin doesn't change anything of the configuration of a plugin. Looks like the BungeeAuth config is invalid. So it's not the fault of FastLogin.

It could happen, because FastLogin explicit requested the player data from that plugin on login and without FastLogin this data could never been requested before.

**Comment by VankkaGithub** [comment]
http://pastebin.com/x9LNsgWK here is it after i disabled FastLogin didn't change the configration **at all**

**Comment by games647** [comment]
Do you logged in during test phase?

**Comment by VankkaGithub** [comment]
yes

**Comment by games647** [comment]
Which version of BungeeAuth do you use?

**Comment by VankkaGithub** [comment]
1.4 a.k.a. latest from spigot

**Comment by games647** [comment]
Is it possible that you on your username or password have special characters in it or only contains of digits?

**Comment by games647** [comment]
Could you try this build of BungeeAuth. It includes the newest changes from the source code of BungeeAuth and I changed the exception logging to find the original error. 

https://github.com/games647/BungeeAuth-Minecraft/releases/tag/exception

My change:
https://github.com/games647/BungeeAuth-Minecraft/commit/b35ca0d33ae6e9bc01465711f44c113aa8c59bf6

**Comment by VankkaGithub** [comment]
I did not login or register the error came up on login, ill try your build

**Comment by VankkaGithub** [comment]
http://pastebin.com/f1s8x3D9 error again

**Comment by games647** [comment]
Do you use a FastLogin dev-build or the one from spigot?

**Comment by VankkaGithub** [comment]
spigot

**Comment by games647** [comment]
Please download a dev-build from here: http://ci.xephi.fr/job/FastLogin/

**Comment by VankkaGithub** [comment]
Issues still exsist

**Comment by games647** [comment]
Found it. BungeeCord ignored the softdepend tag.

**Comment by VankkaGithub** [comment]
oh right i'm using latest of HexaCord btw https://github.com/HexagonMC/BungeeCord

**Comment by games647** [comment]
It was BungeeCord special behavior. 

In Bukkit:
softdepend

In BungeeCord:
softDepend**s**
