### ISSUE TITLE
Clients get disconnected with `multiplayer.disconnect.invalid_public_key_signature.new`

### ISSUE THREAD

**Issue by GregorSomething** [games647/FastLogin#1193]
### What happened?

Server 1.20.4 paper, with ViaVersion (latest)
Users get disconnected with `multiplayer.disconnect.invalid_public_key_signature.new` when FastLogin in enabled (enforce secure profile is off).

### What did you expect?

Client would get connected to server and would not get disconnected again. (and the rest of the normal behavior)

### Steps to reproduce

1. Server 1.20.4 + ViaVersion + FastLogin + AuthMe + FreedomChat
2. Connect to server with 1.20.5
3. Gets disconnected with reason invalid_public_key_signature

### Plugin list

AuthMe, FastLogin, FreedomChat, ProtocolLib, ViaBackwards, ViaVersion

### Configuration file

https://hastebin.com/share/ixewehogag.yaml

### Server log

Paper
```
[14:46:17 INFO]: UUID of player SipelgMees is cedfa665-be8a-3cfc-99e4-57123a67ebde
[14:46:18 INFO]: SipelgMees joined the game
[14:46:18 INFO]: SipelgMees[/127.0.0.1:46817] logged in with entity id 355 at ([world]-245.5, 68.0, -97.5)
[14:46:18 INFO]: [FastLogin] Player info LOGIN command for SipelgMees from proxy
[14:46:18 INFO]: [FastLogin] Delaying force login until join event fired?: false
[14:46:18 INFO]: SipelgMees lost connection: Invalid signature for profile public key.
Try restarting your game.
[14:46:18 INFO]: SipelgMees left the game
[14:46:19 INFO]: [FastLogin] Player CraftPlayer{name=SipelgMees} disconnected
```
Bungee
```
14:46:15 [INFO] [/127.0.0.1:48822] <-> InitialHandler has pinged
14:46:17 [INFO] [/127.0.0.1:48826] <-> InitialHandler has connected
14:46:17 [INFO] [FastLogin] Incoming login request for SipelgMees from /127.0.0.1:48826
14:46:17 [INFO] [FastLogin] Handling player SipelgMees
14:46:17 [INFO] [FastLogin] Requesting premium login for registered player: SipelgMees
14:46:17 [INFO] [FastLogin] Overridden UUID from 9f391579-c250-4fca-9a18-c459f0498603 to cedfa665-be8a-3cfc-99e4-57123a67ebde (based of SipelgMees) on [SipelgMees,/127.0.0.1:48826] <-> InitialHandler
14:46:17 [INFO] [SipelgMees] <-> ServerConnector [lobby] has connected
14:46:18 [INFO] [SipelgMees] disconnected with: multiplayer.disconnect.invalid_public_key_signature.new
14:46:18 [INFO] [SipelgMees] -> UpstreamBridge has disconnected
14:46:18 [INFO] [SipelgMees] <-> DownstreamBridge <-> [lobby] has disconnected
```

### Plugin version

1.12-SNAPSHOT-a65a5f3

### Platform

BungeeCord

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version; i.e. v1.10 is out of date)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by games647** [comment]
Could be related to #1189 

Could you post the Bungee cord version?

**Comment by Krakenied** [comment]
^ it's newer than https://github.com/SpigotMC/BungeeCord/commit/1be25b6c74ec2be4b15adf8ca53a0497f01e2afe

**Comment by homerek111** [comment]
@games647 it seems that someone found a way to fix it here: https://github.com/SpigotMC/BungeeCord/issues/3675
![obraz](https://github.com/games647/FastLogin/assets/93496464/4fb10ac4-1b2e-4f96-a83e-c814342ecb69)
