### ISSUE TITLE
multiplayer.disconnect.invalid_public_key_signature.new

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [games647/FastLogin#1198]
### Is your feature request related to a problem? Please describe.

As already written here, the new version of BungeeCord is throwing some players off. 
I saw that updating FastLogin would solve the problem

### Describe the solution you'd like

 I have reported the problem to them as well, however I don't believe that the problem will somehow be solved from their side(dynamicbungeeauth plugin), so I am writing here to see if there is any possibility.
Thank you

### Describe alternatives you've considered

However, my problem is that I have the "dynamicbungeeauth-premium" plugin.
Without this plugin it is possible to connect to the server, but this plugin is not so easy to replace. As I would lose quite a few passwords with players when they have the autologin of this plugin turned on.

### Platform

BungeeCord

### Relevance

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by games647** [comment]
It's clearly a bug from the auth plugin changing the onlinemode. The author of that plugin needs to fix it or you need to use an older BungeeCord version. I could write you an importer for FastLogin and AuthMe, but there nothing else I could help you here.
