### ISSUE TITLE
Premium join as nopremium if tries to login while server is Starting

### ISSUE THREAD

**Issue by Blackyvk** [games647/FastLogin#12]
I Think fastlogin is one of the latest plugins to load, when a players joins the server while this is loading, he gets to the "queue" while server finish loading but during this time fastlogin doesnt acts and the server assigns a offline uuid to the player, when server finishes loading you login as a offline player and arent autologged  in.

Best solution for this is locking the server while it is loading and  when fastlogin finishes loading remove the lock. People can wait while the server is loading, no need to hurry.

**Comment by games647** [comment]
It looks like this is a ProtocolLib issue. I'll write a workaround for it.

**Comment by Blackyvk** [comment]
Just tried it but it didnt work for me

**Comment by games647** [comment]
I **guess** another plugin is preventing the kick. It works for me on my test server, but I only have a small amount of plugins installed.

Do you at least see the message sometimes?

**Comment by Blackyvk** [comment]
nope, not even once, tried restarting and relogging many times

**Comment by games647** [comment]
Could you retry it with this: https://github.com/games647/FastLogin/releases/tag/DEBUG_JOIN

**Comment by Blackyvk** [comment]
well .... this time worked, but it took the whole server load for the kick to be excecuted, cant be done earlier?  well it works like this I think anyway, i just notice that i get the offline uuid in console while logging in and then i get kicked  http://pastebin.com/KJMyYGb4

**Comment by games647** [comment]
>well .... this time worked

Okay, that's weird. I just added some debug messages.

>but it took the whole server load for the kick to be excecuted, cant be done earlier?

Unfortunately it's not possible. The server is busy with loading the plugins.

>i just notice that i get the offline uuid in console while logging in and then i get kicked

Yes because FastLogin or ProtocolLib isn't hooked into the server at this time.
