### ISSUE TITLE
Auto-Login won't work

### ISSUE THREAD

**Issue by Eufranio** [games647/FastLogin#120]
The Auto-Login feature from FastLogin isn't working on my server. I'm running AuthMeReloaded v5.3-SNAPSHOT b1551, ProtocolLib 3.5.7, FastLogin from [jenkins](http://ci.xephi.fr/job/FastLogin/736), and there are no errors in the console, and all users needs to use the /login command.
I'm sure I'm premium, I even used /premium two times and it says I'm already in the premium list.

Server log: https://paste.ee/p/5RPz7

**Comment by games647** [comment]
Missing BungeeCord log.

**Comment by Eufranio** [comment]
BungeeCord log: https://paste.ee/p/d8dQr

**Comment by games647** [comment]
I though that build doesn't work on Bungee?

**Comment by Eufranio** [comment]
?

**Comment by games647** [comment]
#118

**Comment by Eufranio** [comment]
That didn't fix the issue, the players still having to log every time they log into the server. There are no errors in the bukkit console, Updated bungee log: https://paste.ee/p/5Jj1w

**Comment by games647** [comment]
Check if your proxy-id in the whitelist file is corrected. I tested it using 
BungeeCord 1119
newest FastLogin build
AuthMe 1422-legacy
Thermos-1.7.10-1614-58-server
ProtocolLib 3.6.5-222

**Comment by Eufranio** [comment]
Fixed updating AuthMe.
