### ISSUE TITLE
java.sql.SQLException: Error parsing time stamp when using SQLite database

### ISSUE THREAD

**Issue by mikroskeem** [games647/FastLogin#121]
Log: https://paste.nightsnack.cf/raw/norujokani

Running on Paper build 1056 and using FastLogin 1.9 (latest version from SpigotMC)

**Comment by games647** [comment]
Update FastLogin to a dev-build. It's a bug in the driver of SQLite (included in Spigot)

As described in #95 #97 #98 #100 #108 too.

**Comment by mikroskeem** [comment]
Whoops, I didn't look up other issues. Sorry for wasting your time.
