### ISSUE TITLE
Trying to set up the plugin and getting *Sending request...*

### ISSUE THREAD

**Issue by HatzulMagic** [games647/FastLogin#1213]
### What happened?

As the title says, when i use /premium it doesnt work as expected, i get a message telling Sending request...(Don't forget to follow the Bungeecord setup guide). i checked another tickets but i see i dont have the solution yet

### Plugin list

AuthMe, protocol lib , fastlogin

### Server log

Velocity log - https://hastebin.com/share/okimihagif.ruby 
Hub log - https://hastebin.com/share/upigofuriv.makefile

### Plugin version

1.12 snapshot / latest

### Platform

Velocity

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version; i.e. v1.10 is out of date)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by games647** [comment]
I can see that the Velocity module failed to startup. You have to disable SQLite, because it's not compatible there. Here is the mentioned guide: https://github.com/games647/FastLogin?tab=readme-ov-file#bungeecordwaterfall-or-velocity

**Comment by games647** [comment]
Yes and replacing it with a valid MySQL/MariaDB configuration.

**Comment by HatzulMagic** [comment]
ok, it works thanks!
but soon or later i wont have acces to the database anymore, can you please some alternative way?

**Comment by games647** [comment]
Why would you loose access to it? You manage it yourself. You can always export.
