### ISSUE TITLE
Plugin does not function correctly at all using Velocity

### ISSUE THREAD

**Issue by Clyde6790pGIT** [games647/FastLogin#1222]
### What happened?

Floodgate and Premium users get auto registered but sometimes it does not at all, and sometimes when it does auto register it doesn't auto log you in, trapping users in an "invalid password" loop. 
@Smart123s 

### Steps to reproduce

1. Just log into the server as a Floodgate or Premium user
2. Get through the insanely buggy autoregister
3. Rejoin, and wow your locked out.
![image](https://github.com/games647/FastLogin/assets/78290310/4f35650f-7446-450a-bf89-dc58d7aca7ca)

### Plugin list

LoginSecurity, Fastlogin, GeyserMC, Floodgate, GeyserUpdater, LimboAPI, LimboReconnect, SkinsRestorer, ViaVersion/Backwards, VelociTab, OpenAudioMC

### Configuration file

https://hastebin.com/share/naxoduheti.yaml

### Server log

https://hastebin.com/share/atayigadem.csharp
(IP's are just localhost so they aren't redacted)

### Plugin version

1.12-SNAPSHOT-29100b5

### Platform

Velocity

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version; i.e. v1.10 is out of date)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by Clyde6790pGIT** [comment]
Hi, I tested it again and It doesn't even WORK PROPERLY, it doesn't even make it to auto registration anymore nor even auto login, premium or floodgate players now get treated as cracked players and I almost want to give up on this plugin, it worked fine for a bit before it just stopped working.

**Comment by games647** [comment]
Please post the corresponding spigot log, because that's then responsible to execute the force login command.

**Comment by Clyde6790pGIT** [comment]
Hi, here are logs from PaperMC.
https://hastebin.com/share/ijasahaloc.csharp

**Comment by Clyde6790pGIT** [comment]
I've also noticed a weird pattern, it never works on the first server setup in the Velocity server list, but works on the 2nd and 3rd one, but if you swap the 2nd or 3rd one into the first one, it doesn't work.

**Comment by Smart123s** [comment]
Is your config form Velocity? If so, how do you use SQLite? If not, could you share your FastLoginVelocity config? Most of the stuff in FastLoginBukit config is ignored when using a proxy.

**Comment by Clyde6790pGIT** [comment]
> Is your config form Velocity? If so, how do you use SQLite? If not, could you share your FastLoginVelocity config? Most of the stuff in FastLoginBukit config is ignored when using a proxy.

The config shared is from fastloginvelocity, it has the same settings in fastloginbukkit.

**Comment by Smart123s** [comment]
Could you test this for me? (build of PR https://github.com/games647/FastLogin/pull/1223). As always with test builds: please don't use it non-test servers until the code gets merged.

[FastLogin-9a40cf0afb1d59d77892b098ca8fdbc13d33b4b9.zip](https://github.com/user-attachments/files/16116759/FastLogin-9a40cf0afb1d59d77892b098ca8fdbc13d33b4b9.zip)

**Comment by Clyde6790pGIT** [comment]
Ok, I'll test this on a test velocity server, hopefully it fixes all this broken stuff.
