### ISSUE TITLE
Gayser-Standalone not allowing me to connect without a java account

### ISSUE THREAD

**Issue by USBCharger** [games647/FastLogin#1227]
### What happened?

I play on a server with fastlogin. When I try to join using Geyser-Standalone WITHOUT logging into my java account, I am given the following error 'The Java Edition server you're connecting to requires a paid Java Edition account!'

When I log in to the server logging in to my java account first, everything works as intended, and I log in under my java credentials. (I used the geyserconnect service to log in with my java account, but I am 99% sure Geyser-Standalone can also do this)

### Steps to reproduce

Message above should explain the issue

### Plugin list

AntiPopup, Authme, BasicQuests, Chunky, Chunkyborder, Coreprotect, CraftingStore, CustimCrafting, DirectionalBlock, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, ExcellentCrates, ExoticGarden, FastChunkPregenerator, Fastlogin, FluffyMachines, Gastronomicaon, ImageFrame, ItemEdit, ItemsAdder, LibsDisguises, LoneLibs, LuckPerms, MapTowny, MorkazSk, MovableTileEntities, MythicMobs, NexEngine, PlaceholderAPI, ProtocolLib, PurperExtras, Quarters, SFCalc, SiegeWar, SkBee, SkCoAPI, SkCord, Skellett, SkGoat,SkinsRestorer, SkJson, skRayFall, Skript, skript-placeholders, skript-reflect, Slimefun, spark, squaremap, squaremap-worldguard, squaremarker, TAB, TeaksTweaks, Towny, TownyChat, TownyCombat, TownyFlight, TownyMenu, TownyResources, TreeFeller, vane-core, vane-portals, vane-trifles, Vault, ViaVersion, VoidGen, Votifier, VotingPlugin, Vulcan, WolfyUtilities, Worldedit, Worldguard, WorldGuard-Towny.

### Configuration file

Don't have it, not the owner/staff

### Server log

same thing, I might be able to ask for this as well as the config if needed though

### Plugin version

1.12-SNAPSHOT-cd67797

### Platform

Spigot

### Relevance

- [ ] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version; i.e. v1.10 is out of date)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by games647** [comment]
Normally, server owners/developers contact us here. This seems to indicate that the server isn't even offline mode for FastLogin to work. The corresponding server log would indicate this.

**Comment by USBCharger** [comment]
Yes. I'm aware usually server owners/staff are the crowd normally contacting you here. I logged on with tlauncher (not with a premium account) and it did let me in, and unlike on my premium account it asked me to register with a password.

**Comment by games647** [comment]
Sorry, but I'm currently misunderstanding the situation here. Could you please clarify what works and what doesn't. I guess with your last message you meant you joined the server using a non-registered username, isn't it? However, if you join the server logged into Microsoft account, you will be automatically force logged in?

Maybe it would be helpful if you clearly define what the login process is and when it doesn't work. Furthermore, is your bedrock account linked with your Java edition account?

**Comment by USBCharger** [comment]
Logging on using Java with a premium or cracked account: Works
Logging on using Bedrock, logged in to a premium Java account on Bedrock (I used GeyserConnect to do this): Works
Logging on using Bedrock, NOT LOGGED IN TO A JAVA ACCOUNT, just regular bedrock using Geyser-Standalone (or GeyserConnect): Does not work, gives following error: 'The Java Edition server you're connecting to requires a paid Java Edition account!'

**Comment by USBCharger** [comment]
Here's the error that comes up for it btw. Seeing the error, I'm kinda wondering if it's because I joined before on my Rockethub account o

```
10.07 12:58:45 [Server] [INFO] [FastLogin] New packet START[class=PacketLoginInStart, id=0] from com.comphenix.protocol.injector.temporary.TemporaryPlayerInvocationHandler@604f7b1
10.07 12:58:45 [Server] [INFO] [FastLogin] Handling player Rockethub
10.07 12:58:45 [Server] [INFO] [FastLogin] Requesting premium login for registered player: Rockethub
10.07 12:58:45 [Disconnect] User /174.93.64.171:32871 has disconnected, reason: Disconnected
```
