### ISSUE TITLE
failed to resolve 'sessionserver.mojang.com'

### ISSUE THREAD

**Issue by pitruk** [games647/FastLogin#123]
Hi,

Sometimes it displays an error and can't get to the server as a premium

I Use a Waterfall and spigot. (In Bungeecord i don't see any error)

> 14:34:22 [SEVERE] Error authenticating pitruk with minecraft.net
> java.net.UnknownHostException: failed to resolve 'sessionserver.mojang.com'. Exceeded max queries per resolve 16 
> 	at io.netty.resolver.dns.DnsNameResolverContext.finishResolve(DnsNameResolverContext.java:481)
> 	at io.netty.resolver.dns.DnsNameResolverContext.tryToFinishResolve(DnsNameResolverContext.java:403)
> 	at io.netty.resolver.dns.DnsNameResolverContext.query(DnsNameResolverContext.java:167)
> 	at io.netty.resolver.dns.DnsNameResolverContext.tryToFinishResolve(DnsNameResolverContext.java:397)
> 	at io.netty.resolver.dns.DnsNameResolverContext.query(DnsNameResolverContext.java:167)
> 	at io.netty.resolver.dns.DnsNameResolverContext.access$900(DnsNameResolverContext.java:54)
> 	at io.netty.resolver.dns.DnsNameResolverContext$3.operationComplete(DnsNameResolverContext.java:195)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
> 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
> 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
> 	at io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:216)
> 	at io.netty.resolver.dns.DnsQueryContext.access$300(DnsQueryContext.java:41)
> 	at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:159)
> 	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
> 	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
> 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by games647** [comment]
failed to resolve 'sessionserver.mojang.com' check your DNS-Server settings.

**Comment by pitruk** [comment]
The DNS server is working well, but I update my waterfall and everything works as should.

Thanks.

**Comment by games647** [comment]
Maybe they updated the netty library in the meanwhile and that fixed the bug.

**Comment by ItsPris** [comment]
same issue  for me though can't fix it
