### ISSUE TITLE
Error when play joins: [20:35:04] [Protocol Worker #1 - FastLogin - [recv: START[class=PacketLoginInStart, id=0], ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1], send: ]/ERROR]: [FastLogin] Unhandled exception occurred in onAsyncPacket() for FastLogin

### ISSUE THREAD

**Issue by ImGGAAVVIINN** [games647/FastLogin#1233]
### What happened?

Fats login does not work, and give error every time a player joins the server

### Steps to reproduce

Install spigot 1.21 
Install protical lib
Install login security
Install fast login
Join with a premium account
Error

### Plugin list

RemoveJoinLeaveMessage, Lobbys, SAML, PlaceholderAPI, ClearLag, PerWorldPlugins, CompatNoCheatPlus, Multiverse-Core, Multiverse-SignPortals, Multiverse-Inventories, DeluxeMenus, NoChatReports, ViaVersion, Multiverse-Portals, floodgate, UltimateHomes, ViaBackwards, GriefPrevention, ViaRewind, LuckPerms, Skript, Essentials, ViaRewind-Legacy-Support, ProtocolLib, SkinsRestorer, Geyser-Spigot, Multiverse-NetherPortals, ItemJoin, EssentialsSpawn, LPC, FastLogin, LoginSecurity

### Configuration file

https://hastebin.com/share/oruyoravuc.yaml

### Server log

https://hastebin.com/share/pulohejoda.markdown

### Plugin version

[20:39:15] [Server thread/INFO]: FastLogin version 1.10-git484855724b794de1fe057cf7360245362658b432

### Platform

Spigot

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version; i.e. v1.10 is out of date)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by games647** [comment]
Please use the latest if you actually enabled that checkbox. Your version is very out of date as the template already says.

**Comment by ImGGAAVVIINN** [comment]
I tried the development version, the plugin still didn't work. 
Fast login does way <user> logged on, but don't allow premium users to skip the login command

**Comment by games647** [comment]
Do you tried the `premium` command?
