### ISSUE TITLE
You cannot execute commands if you are not logged in yet.

### ISSUE THREAD

**Issue by FierraCodes** [games647/FastLogin#1237]
### What happened?

I have a premium account but it registered me as a cracked account, and when i try to do /premium after logging in, it says:
You cannot execute commands if you are not logged in yet

### Plugin list

AuthMeReloaded

### Configuration file

https://gist.github.com/FierraCodes/b270d7dd6cc9aa92ae34195cbceaf0fd

### Server log

https://gist.github.com/FierraCodes/046ed056ea396af0a00140e42790a639

### Plugin version

v1.12-SNAPSHOT-4dd6b9a

### Platform

Velocity

### Relevance

- [X] I tried the [latest build](https://ci.codemc.io/job/Games647/job/FastLogin/) 
(build refers to development builds not necessary a release version; i.e. v1.10 is out of date)

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by games647** [comment]
>[05:21:58] [Server thread/INFO]: [FastLogin] Remember to follow the proxy guide to complete your setup

Did you followed the proxy guide mentioned on the plugin page?

**Comment by FierraCodes** [comment]
It's my bad, I forgot I had AuthMeProxy on velocity.
