### ISSUE TITLE
Premium users cannot change skin (SkinsRestorer)

### ISSUE THREAD

**Issue by VankkaGithub** [games647/FastLogin#124]
FastLogin config: http://pastebin.com/t5T0egQS
SkinsRestorer config: http://pastebin.com/iea44bv2

FastLogin version : 1.9 (from Spigot)
SkinsRestorer version: 12.9.7 (from Spigot)

**Comment by Eufranio** [comment]
Are you sure it's a FastLogin problem?
Also, which server software are you using?

**Comment by VankkaGithub** [comment]
BungeeCord well it works whitout FastLogin

**Comment by Eufranio** [comment]
What is the backend server software that skins aren't working?

**Comment by VankkaGithub** [comment]
https://github.com/HexagonMC/BungeeCord/releases/tag/v129 I am using this version of HexaCord with v12.9.7 of SkinsRestorer

**Comment by Eufranio** [comment]
And the backend servers?

**Comment by VankkaGithub** [comment]
ohw PaperSpigot 1.10.2 (currently latest), 1.8.3 (latest)

**Comment by Eufranio** [comment]
Do you have ProtocolLib in both servers?

**Comment by VankkaGithub** [comment]
yes

**Comment by games647** [comment]
FastLogin just enables the online mode in BungeeCord. It doesn't override any skins. Your skin plugin just have to set the skin after the online mode verification.

**Comment by VankkaGithub** [comment]
forwardSkin gives the user their premium skin if you turn it off it still doesn't work

**Comment by games647** [comment]
I know, but there is no way to change it without modifications of the Bungee code. BungeeCord does all the online mode handling including setting the premium skin. So SkinsRestorer also doesn't work if the Bungee server is in online mode at all time.

forwardSkin in BungeeCord just overrides the skin to an empty one.

**Comment by VankkaGithub** [comment]
How come i can be in offline or online mode whitout FastLogin and it works

**Comment by games647** [comment]
Then their implementation doesn't seem work quite well.

I just can repeat. If you enable forwardSkin, FastLogin changes nothing of a user skin. But you could try to turn on premium UUIDs or download a FastLogin dev-build. Maybe SkinsRestorer have a bug with it. 

Next time please describe your issue with more details. Just "cannot change" doesn't help me to solve it.

**Comment by VankkaGithub** [comment]
Doing /skin says Skin Changed but it doesn't actually change*
