### ISSUE TITLE
ProtocolLib version

### ISSUE THREAD

**Issue by gxlydlyf** [games647/FastLogin#1244]
### Is your feature request related to a problem? Please describe.

This plugin requires the use of ProtocolLib version 5.3+, but ProtocolLib version 5.3+ does not support Minecraft version <1.20.5. I hope the latest version of this plugin can have good compatibility and support Minecraft version <1.20.5.

### Describe the solution you'd like

It would be nice if this plugin could support ProtocolLib version <= 5.2.

### Describe alternatives you've considered

I tried using an older build of this plugin.

### Platform

Spigot

### Relevance

- [X] I checked for existing tickets -
If there are, please vote them with a thumbs reaction and not create new ones

**Comment by gxlydlyf** [comment]
![image](https://github.com/user-attachments/assets/53f374c5-6aea-4a38-991a-5bd7b7e76f2e)
They don't seem to have notified that the latest version of ProtocolLib can support game versions less than or equal to 1.20.4. Although the page only says "recommended", in fact, using the latest version of ProtocolLib with game version 1.20.4 sometimes causes many errors.

**Comment by gxlydlyf** [comment]
So, will this plugin support protocolLib5.2? @games647

**Comment by games647** [comment]
Yes, but it requires more effort. Currently builds before: ticket #1210 with 5fb6308130bc93c2487d85df84a3be14cc0b5e94

**Comment by gxlydlyf** [comment]
> Yes, but it requires more effort. Currently builds before: ticket #1210 with [5fb6308](https://github.com/games647/FastLogin/commit/5fb6308130bc93c2487d85df84a3be14cc0b5e94) work

我将会使用旧版,期待您支持ProtocolLib 5.2的那一天!感谢!

**Comment by gxlydlyf** [comment]
> Yes, but it requires more effort. Currently builds before: ticket #1210 with [5fb6308](https://github.com/games647/FastLogin/commit/5fb6308130bc93c2487d85df84a3be14cc0b5e94) work

I will use the old version and look forward to the day when you support ProtocolLib 5.2! Thanks!
