### ISSUE TITLE
trying do /fastlogin and /premium

### ISSUE THREAD

**Issue by comonier** [games647/FastLogin#130]
i have this error:
**An internal error occurred while attempting to perform this command**

`27.02 02:55:31 [Server] ERROR Failed to query profile
27.02 02:55:31 [Server] INFO java.sql.SQLException: Error parsing time stamp
27.02 02:55:31 [Server] INFO at org.sqlite.jdbc3.JDBC3ResultSet.getTimestamp(JDBC3ResultSet.java:565) ~[spigot111-java8.jar:git-Spigot-261f181-7359112]
27.02 02:55:31 [Server] INFO at com.zaxxer.hikari.pool.HikariProxyResultSet.getTimestamp(HikariProxyResultSet.java) ~[FastLogin.jar:?]
27.02 02:55:31 [Server] INFO at com.github.games647.fastlogin.core.AuthStorage.loadProfile(AuthStorage.java:129) [FastLogin.jar:?]
27.02 02:55:31 [Server] INFO at com.github.games647.fastlogin.bukkit.commands.PremiumCommand.onCommand(PremiumCommand.java:53) [FastLogin.jar:?]
27.02 02:55:31 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot111-java8.jar:git-Spigot-261f181-7359112]
27.02 02:55:31 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot111-java8.jar:git-Spigot-261f181-7359112]
27.02 02:55:31 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) [spigot111-java8.jar:git-Spigot-261f181-7359112]
`

**Comment by games647** [comment]
And again check for duplicates -.- #125

**Comment by comonier** [comment]
duplicates ? you do not explain !

**Comment by comonier** [comment]
FastLogin.jar	308.69 KB	 exibir
original-FastLogin.jar	2.65 KB	 exibir

what of both ones ?

**Comment by games647** [comment]
>duplicates ? you do not explain ! 

This is had other users before that created a ticket too.

>what of both ones ?

Only the bigger one
