### ISSUE TITLE
Hello everyone, I got some problem with FastLogin plugin, Can someone help me ?

### ISSUE THREAD

**Issue by Kuroyabumozu** [games647/FastLogin#132]
I'm new in this plugin, and when I typed the command "/premium"
the bungeecord terminal spouted this to me 
https://ooo.0o0.ooo/2017/03/05/58bb21152c551.png

**Comment by ljacqu** [comment]
@games647 Looks like this is going to haunt you forever :laughing:

**Comment by games647** [comment]
#129
