### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by WilliamEstrela** [games647/FastLogin#133]
![image](https://cloud.githubusercontent.com/assets/5386302/23668981/86f5cb4e-0341-11e7-90f8-19e0a2cf9886.png)

**Comment by games647** [comment]
Update ProtocolLib

**Comment by WilliamEstrela** [comment]
Already updated, Continue with error

**Comment by games647** [comment]
I need the full log

**Comment by WilliamEstrela** [comment]
http://pastebin.com/WmA4wYza

**Comment by games647** [comment]
FastLogin isn't installed on this instance.

**Comment by WilliamEstrela** [comment]
Error zip file: https://www.dropbox.com/s/2d5sffm3q3113co/2017-03-07-1.zip?dl=0

**Comment by games647** [comment]
Read your log carefully:

**Comment by WilliamEstrela** [comment]
Hey, bungeecord: false, put true the solved problem, tks
