### ISSUE TITLE
UUID Spoof fix

### ISSUE THREAD

**Issue by Sebak17** [games647/FastLogin#136]
Does this plugin have a UUID Spoof fix?

**Comment by games647** [comment]
What do you mean exactly? It could set the premium uuid if you want to do so.

**Comment by Sebak17** [comment]
I mean special versions that change the UUID of the player to other.

**Comment by games647** [comment]
No the purpose of this plugin is only to let premium player skip cracked authentication and therefore those player could have a premium UUID.

**Comment by lukacat10** [comment]
I'm pretty sure from a quick look at the source code that the plugin is looking into mojang's servers if the player has decided to log in to this specific server. If it is so than UUID spoof is impossible, as mojang's servers take into account that the real UUID owner has logged in using login tokens and the fact that when the player decides to join a server mojang's servers know about it.
