### ISSUE TITLE
changed any display words is not works from messages.yml 

### ISSUE THREAD

**Issue by Kuroyabumozu** [games647/FastLogin#137]
I've changed some display words from messages.yml
but when I/player invoked the command "/premium" the warnning still show in Original words..
but the display words in "auto-login", it is works.
https://paste.ubuntu.com/24258261/
how can I sovlve this problem?

**Comment by games647** [comment]
You have to change some message inside the spigot server since there is no message communication between the servers.

**Comment by Kuroyabumozu** [comment]
sorry, I don't understand what's related with you plugin's message and the change message on Spigot?

**Comment by games647** [comment]
Just copy the message file.
