### ISSUE TITLE
Wrong password for premium?

### ISSUE THREAD

**Issue by Blackyvk** [games647/FastLogin#14]
I just noticed this checking my log, thats a premium user. the authme database shows that he never  logged in.

http://pastebin.com/VSvgEFC3

**Comment by games647** [comment]
>[17:10:30] [Protocol Worker #2 - FastLogin - [recv: PacketLoginInStart[0, legacy: 0], send: ]/INFO]: [AuthMe] ConnectionPool was unavailable... Reconnected!

Maybe it's because of this.

**Comment by Blackyvk** [comment]
Yes I noticed it but it shows everytime authme tries to do something, login logout, shows all the time but only failed to log in that player today... it could fail more if more premiums try to log at the same moment ?

**Comment by games647** [comment]
Are you using AuthMe 3.X at the moment?

**Comment by Blackyvk** [comment]
Yeah,authme 5 is too buggy.

**Comment by games647** [comment]
Do you modified AuthMe 3.X, because it doesn't event startup of for because the modified getOnlinePlayers method.

**Comment by Blackyvk** [comment]
yes with BuildTools.

java -jar BuildData/bin/SpecialSource-2.jar map -m CraftBukkit/deprecation-mappings.csrg -i MyPlugin.jar -o MyPlugin-fixed.jar

**Comment by games647** [comment]
The forceLogin doesn't seem to work.

**Comment by games647** [comment]
Found the source. I'm really stupid. It doesn't work on autoRegister.

**Comment by games647** [comment]
Sorry for that

**Comment by Blackyvk** [comment]
no problem, I only noticed it with that player, other premiums were able to register and login before and after this issue, I can see about 4 players never logged in in my authme database... will try this on my test server, thanks!

**Comment by Blackyvk** [comment]
hmmm i think this didnt work, I did a clean install (databases), tried to log in got autoregistered > "auto logged in", but i was spammed with the /register message and I wasnt able to move chat or even open the ESC menu, i had to alt+f4, I relogged and got in.

**Comment by games647** [comment]
Weird, because it works me. What you descripted happened to you before the commit.

**Comment by Blackyvk** [comment]
after, i just build it.... unless i'm not doing it right... might import it again and try.

**Comment by games647** [comment]
You cloned it with git right?

**Comment by Blackyvk** [comment]
cloned it with eclipse

I just tried again and worked... maybe i didnt deleted the premium database in my first attempt. 

When you use /authme unregister player for example.. fastlogin doesnt register that player again if its in the fastlogin database i think, so maybe... i didnt deleted the premium database, I hope that was the problem.

i'm using authme and fastlogin both with mysql just in case.

I'll try more later with some people.
