### ISSUE TITLE
BungeeCord not Auto Login when join

### ISSUE THREAD

**Issue by MethaponKunG** [games647/FastLogin#149]
when join BungeeCord the plugin not working but command work
PremiumUUID not working
Auto Login not working

**Comment by games647** [comment]
Do you followed the setup guide on the main Github page?

**Comment by MethaponKunG** [comment]
yes

**Comment by MethaponKunG** [comment]
all step

**Comment by MethaponKunG** [comment]
no error at all 
I've enable debug in spigot

**Comment by MethaponKunG** [comment]
Do I need to set mySQL

**Comment by games647** [comment]
Yes or include the sqlite driver into the bungee jar

**Comment by MethaponKunG** [comment]
um

**Comment by MethaponKunG** [comment]
I install already - -

**Comment by MethaponKunG** [comment]
I mean do I have to config this 
# MySQL/MariaDB
#driver: com.mysql.jdbc.Driver
#host: localhost
#port: 3306
#database: fastlogin
#username: myUser
#password: myPassword

**Comment by games647** [comment]
You have to configure the connection to your MySQL server if you use BungeeCord.

**Comment by MethaponKunG** [comment]
ok thank you
