### ISSUE TITLE
Kicked with "Server is not fully started yet" on join.

### ISSUE THREAD

**Issue by k-jiang** [games647/FastLogin#15]
Could not join an already-fully-started server with following kick message:
Connection lost
Kicked whilst connecting to survivalserver: Server is not fully started yet. Please retry.

with:
Spigot 1.9.4 build 833
bungeecord build 1156 http://ci.md-5.net/job/BungeeCord/
ProtocolLib 4.0.1 https://www.spigotmc.org/resources/protocollib.1997/
AuthMe both 3.4(nms fixed with buildtools) and 5.2 beta 2
ProtocolSupport 4.23 build 518 http://build.true-games.org/job/ProtocolSupport/

note: Everything is fine when FastLogin is removed from Spigot side.

**Comment by games647** [comment]
Related to #12

I'll fix it now. It's because the connection is established with through BungeeCord where authme isn't hooked it.
