### ISSUE TITLE
Premium players UUIDS have changed

### ISSUE THREAD

**Issue by ver151set** [games647/FastLogin#157]
Using 1.12, newest Fastlogin, and Authme 5.3.1-spigot. Even though in config premium users are NOT set to use online-uuids, after this update they are given new uuids on join. The new uuid is not an online mojang uuid, so not only am I lost, but a have a horde of impatient kids blowing me up. Any help is appreciated

**Comment by games647** [comment]
Copied from Spigot

>Please use: https://ci.xephi.fr/job/FastLogin/changes
Those builds are outdated. Your issue is properly fixed by this: https://ci.xephi.fr/job/FastLogin/754/changes
