### ISSUE TITLE
Bukkit detected as bungee, no premium detection, no databases.

### ISSUE THREAD

**Issue by Blackyvk** [games647/FastLogin#16]
[18:10:36] [Server thread/INFO]: [FastLogin] Hooking into auth plugin: AuthMe
[18:10:36] [Server thread/INFO]: [FastLogin] BungeeCord setting detected. No auth plugin is required

I just tried your last build on a clean server:

Spigot 1.9.4 + AuthMe 3.4

No premium detection
No databases created mysql or sqlite (tried both)
Required to register as Premium

**Comment by games647** [comment]
I fixed that with the last commit.

**Comment by games647** [comment]
I fixed that with the last commit.

**Comment by k-jiang** [comment]
Thank you for your great work!
Are there any way to download development builds of the plugin? I tried clicking on the Travis-CI button on main page but there is no "download" or "artifacts".

**Comment by games647** [comment]
Travis is only used for automatic tests. Normally Jenkins servers can be used to download builds

**Comment by games647** [comment]
You can use this: https://github.com/games647/FastLogin/releases/tag/1.3

**Comment by Blackyvk** [comment]
seems to be working :)
