### ISSUE TITLE
FastLogin doesnt' work

### ISSUE THREAD

**Issue by Auswahluhr6004** [games647/FastLogin#169]
Hello, my problem is that FastLogin doesn't work.

When i write /premium it says: /premium [player]

Best regards Auswahluhr6004

**Comment by games647** [comment]
Please use pastebin for the config and please update to dev-build.

**Comment by Auswahluhr6004** [comment]
Ok. The Config: https://pastebin.com/FX0jfVi0

**Comment by games647** [comment]
Did you do that?

>and please update to dev-build.

**Comment by Auswahluhr6004** [comment]
No. Because i don't know what this is? I'm new in this panel

**Comment by games647** [comment]
Download a new version from [here](https://ci.xephi.fr/job/FastLogin/). Next time add your server log. It will help developers a lot.
