### ISSUE TITLE
Failed to verify Session 

### ISSUE THREAD

**Issue by Blackyvk** [games647/FastLogin#17]
I dont know if i'm becoming annoying posting issues every day (hour)...

I know this is because the user must restart his launcher and get a new session, but  should this error appear ?

http://pastebin.com/bQB5qXSV

**Comment by games647** [comment]
>Read timed out

Looks like the Mojang API is down.

**Comment by games647** [comment]
It occurred while checking against the Mojang servers if the owner of that account really requested to join that server. In order to check if it's the owner.

**Comment by Blackyvk** [comment]
Yes he is the owner,  he just restarted everything and worked... the error will always be there when mojang is down i guess.

**Comment by games647** [comment]
At the moment yes.
