### ISSUE TITLE
Let ‘whitelist add’ Command connection to Mojang server for premium UUID

### ISSUE THREAD

**Issue by liwanglin12** [games647/FastLogin#170]
The server will only use Offline UUID when Online-mode is disabled. So I can't use command to add a whitelist for premium user.

**Comment by games647** [comment]
You can configure it yourself. Just disable premium UUID.

**Comment by liwanglin12** [comment]
If I disabled that, any player will not able to join with premium account... So Fastlogin will not use to me.

**Comment by games647** [comment]
If you disable it, players will get their offline UUID independent of their premium, so you could use the whitelidt command. Why do say they cannot login at all?

**Comment by liwanglin12** [comment]
First, I am using Fastlogin( Auto-register & login ), so Player's best choice is to use online login. 
IF player uses online mode login, they will get a UUID from Mojang server.

On the other hand, I want to allow crack player login，so I turn off the Online-mode in server.properties. So it caused: when I use ` whitelist add` command, the server will generate an Offline UUID by username which I input.

So let's summarize:
Player who have paid account, use their Mojang account login and get an Online UUID for better login experience (provide by Fastlogin)
And the server added an Offline UUID **Not for** an Online UUID to `whitelist.json` because I turned off the `Online-Mode`.

When a player wants to log in, their Online UUID will not equal Offline UUID which in the whitelist. So they can't join the server. If let player uses offline mode, Fastlogin will not work because a player has no valid session in Mojang server.

I am not related English user, so if you can't understand I mean, I am very sorry. Thanks for the reply!

**Comment by liwanglin12** [comment]
So what I want: If you can add a whitelist function to replace Spigot Native version，or just deceive server `Online-mode: true` when whitelist adding process, the issue will fix.

**Comment by games647** [comment]
>If let player uses offline mode, Fastlogin will not work because the player has no valid session in Mojang server.

If you disable premiumUUID in the settings of FastLogin, they could still login through online mode. FastLogin just overrides the player UUID, so they get the offline UUID.

**Comment by games647** [comment]
>When a player wants to log in, their Online UUID will not equal Offline UUID which in the whitelist. So they can't join the server. If let player uses offline mode, Fastlogin will not work because the player has no valid session in Mojang server.

This means you use your whitelist using offline UUIDs and still use FastLogin. FastLogin will still work, because it's an feature of it.

**Comment by liwanglin12** [comment]
> so they get the offline UUID

OK, I understand. Although I think it would be better to use premium UUID if the user has paid account, I have to admit that this is indeed an effective solution. thank!
