### ISSUE TITLE
Fastlogin bungeecord

### ISSUE THREAD

**Issue by anonimo345423** [games647/FastLogin#171]
I tried everything fastlogin page said to do, but i still get "sending request" when i use /premium, help me :(

**Comment by anonimo345423** [comment]
One thing i noticed is that putting fastlogin on bungee only generates a config.yml, nothung else, have i to put the auth plugin also on bungee? Thx

**Comment by games647** [comment]
Please follow the setup on spigot or here on Github

**Comment by anonimo345423** [comment]
I checked them more than 1 time
