### ISSUE TITLE
Bungee

### ISSUE THREAD

**Issue by anonimo345423** [games647/FastLogin#172]
My thread was closed, i didn't solve the problem. I followed the guide but when i do /premium i get "sending request" and nothing else. I'm using latest versions of loginsecurity (tried authme too) and bungee

**Comment by anonimo345423** [comment]
And fastlogin too

**Comment by games647** [comment]
You can still respond to the other ticket. You should just follow the setup guide on the main page of this project.

**Comment by anonimo345423** [comment]
I did, checked more than 1 time...

**Comment by games647** [comment]
It means that the bungee module of fastlogin didn't respond. Did you checked the log on BungeeCord.
