### ISSUE TITLE
Premium players still need to login!

### ISSUE THREAD

**Issue by Kapakulia** [games647/FastLogin#173]
Hey, So I did /premium and every thing work, but when I relog to a server I need to login. I am using AuthME

**Comment by games647** [comment]
What is your server environment? Do you use BungeeCord? If so, do you followed the setup guide? Do you have any errors in the server log? Do you invoked the premium command after you logged in?

**Comment by Kapakulia** [comment]
Here is a error in console http://prntscr.com/ghfbx6 . I Have bungeecord and I followed the setup guide.

**Comment by games647** [comment]
You have an outdated version. Please download a dev-build.

**Comment by Kapakulia** [comment]
Server version or Authme?

**Comment by games647** [comment]
Of FastLogin
