### ISSUE TITLE
LuckPerms Incompatibility 

### ISSUE THREAD

**Issue by Flayovec** [games647/FastLogin#174]
Version 1.10 is incompatible with LuckPerms, if player have premium login activated he get kicked with message "[LP] Permission data could not be loaded. Please try again later."

**Comment by games647** [comment]
Please give out more information. Do you use BungeeCord? What did you tried? What configuration are you using?

**Comment by Flayovec** [comment]
I use Spigot 1.8.8, FastLogin 1.10 with default configuration.

**Comment by games647** [comment]
Do you have any errors in the log? What did you tried (using the command or just joined without changing anything)? Do you tried another version of LuckPerms (maybe a dev-build)? Does work without FastLogin?

**Comment by Flayovec** [comment]
Without errors, I use /premium command and after this I can't join. No, I try only one. Yes without FastLogin it works.

**Comment by games647** [comment]
Please post your server log.

**Comment by Flayovec** [comment]
Now it works fine, maybe some problems with ping, if it will occur again I will reply to you
