### ISSUE TITLE
Premium users still need to register

### ISSUE THREAD

**Issue by dado243** [games647/FastLogin#175]
Hello, I tried to use this but premium users still need to register!!

**Comment by games647** [comment]
I cannot help you if you only provide a minimal description about your setup. What server software do you use? What did you tried? If you use Bungee, do you followed the setup guide? 

Did you read the FAQ? It says autoRegister only works for new players (in case that's the source of your issue). 

Furtheremore you can use the search feature for existing tickets with admins asking the same question.

**Comment by dado243** [comment]
so should i install it on allready full database is that what you say?
