### ISSUE TITLE
Database Issue BungeeCord

### ISSUE THREAD

**Issue by xXSchrandXx** [games647/FastLogin#176]
### What behaviour is observed:
What happened?
On loading the plugin this Error/Waring comes:
`Exception encountered when loading plugin: FastLogin
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:160)
	at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:44)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:273)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)`

### Plugin list:
This can be found by running `/pl`
Anti Bot Attack, BungeeTabListPlus, CommandSync, Fastlogin, ServerListPlus, Skinsrestorer, Viaversion

### Environment description
Bungeecord network, MySql

### Plugin version:
This can be found by running `/version plugin-name`
last spigot build

### Configuration:
```
# FastLogin config
# Project site: https://www.spigotmc.org/resources/fastlogin.14153
# Source code: https://github.com/games647/FastLogin
#
# You can access the newest config here:
# https://github.com/games647/FastLogin/blob/master/core/src/main/resources/config.yml
autoRegister: true

secondAttemptCracked: true

switchMode: false

premiumUuid: true

nameChangeCheck: true

forwardSkin: true

premium-warning: true

ip-addresses: []

mojang-request-limit: 600

auto-register-unknown: true

autoLogin: true
driver: com.mysql.jdbc.Driver
host: HOST
port: 3306
database: DB
username: NAME
password: PASSWD

proxies:
  # 'IP:Port' or 'Domain:Port'
  # - 'xyz.com:1337'
  # - 'test.com:5131'

```

**Comment by games647** [comment]
Do you have only numbers in your storage password? If so, wrap them into `'pass'`.

**Comment by xXSchrandXx** [comment]
Ups, forgot that ...
Thanks

**Comment by games647** [comment]
No problem, but please close the ticket if it's resolved.
