### ISSUE TITLE
Switch from secondAttemptCracked: true to secondAttemptCracked: false

### ISSUE THREAD

**Issue by M4T14SG4M3R** [games647/FastLogin#180]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!)

### What behaviour is observed:
[//]: Isn't an error, i want to know if it's possible to add that option

### What behaviour is expected:
[//]: # It should work like this:
If you have secondAttemptCracked: true and you want to set it to false, it will work only for new players, meaning that players that are already registered and uses a premium username will not be kicked because of invalid session, so, if i registered with a premium username but with cracked launcher with secondAttemptCracked: true, now with secondAttemptCracked: false it will not kick me for invalid session because the plugin will remember that i'm already registered

**Comment by games647** [comment]
Yes, isn't that the correct behavior? If a premium player already registered an account on your there should be no cracked that can claim that account.

**Comment by M4T14SG4M3R** [comment]
Yes but if i change from secondAttemptCracked: true to secondAttemptCracked: false, cracked users who have a premium username will not be able to join because it will request them a premium check, it should store them so when they join the plugin will remember that they are already registered and will not request a premium check, but for new cracked players who aren't registered and uses a premium username it will always request them a premium check because they are not registered, the purpose of this is to avoid a loss of users because cracked users who have a premium username will not be able to join with secondAttemptCracked: false and all of the other features like autoRegister, nickNameChangeCheck etc are in true

**Comment by games647** [comment]
>cracked users who have a premium username will not be able to join because it will request them a premium check,

Do you use BungeeCord? FastLogin tries to check if the player exists  using your auth plugin and if not it performs a premium name check. For BungeeCord it's not possible to connect to the backend Spigot server while connecting, so FastLogin can only check the player existence against the FastLogin database. 

>it should store them so when they join the plugin will remember that they are already registered and will not request a premium check

It already does it, but if the plugin doesn't know anything about this player or a previous attempts to auto login the player failed, the plugin will fallback.

Nevertheless you could migrate the data of your cracked players into the FastLogin table. You just have to extract all data from your auth plugin and insert it into the FastLogin table (with ignore if the player name is already in the table).

**Comment by M4T14SG4M3R** [comment]
I'm using BungeeCord, how i can migrate the tables as you says? i'm noob with mysql and java, i only configure the files

**Comment by games647** [comment]
Do you use MySQL or SQLite for your auth plugin?

**Comment by M4T14SG4M3R** [comment]
MySQL

**Comment by games647** [comment]
1. Check if you have a UNIQUE(NAME) index in your current FastLogin table. 
2. Make a backup of the fastlogin table - just to make sure
3. Run this SQL script with *_table replaced with the relevant table names

```SQL
INSERT IGNORE INTO FASTLOGIN_TABLE (Name, Premium, LastIp)
  SELECT
    realname AS Name,
    0        AS Premium,
    ip       AS LastIp
  FROM AUTHME_TABLE;
```

This should do the trick. All rows with the same (case insensitive) name should be ignored, because of the UNIQUE name index.

**Comment by M4T14SG4M3R** [comment]
It worked, thank you :D
