### ISSUE TITLE
Failed to check if player has a paid account

### ISSUE THREAD

**Issue by M4T14SG4M3R** [games647/FastLogin#181]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting an issue make sure you are running the latest build of the plugin and checked for duplicate issues!)

### What behaviour is observed:
[//]: There is an error in the console where it checks if the player is premium or not by using multiple ip addresses

### What behaviour is expected:
[//]: It doesn't work with multiple ip addresses

### Steps/models to reproduce:
[//]: Add this to the config the first ip is the second ip of the server and the second ip listed is the main ip of the server
ip-addresses:
    - 123-123-123-1
    - 123-123-132-123

### Environment description
[//]: BungeeCord (HexaCord) with mysql enabled

### Plugin version or build number (don't write latest):
[//]: FastLogin latest dev build

### Error Log:
https://hastebin.com/acotidulac.sql

### Configuration:
[//]:
ip-addresses:
    - 123-123-123-1
    - 123-123-132-123
mojang-request-limit: 300

**Comment by games647** [comment]
Please send your startup it seems that the list of ip addresses is empty

**Comment by M4T14SG4M3R** [comment]
02:23:33 [ADVERTENCIA] [FastLogin] Submitted IP-Address is not local /123.12.123.1
02:23:33 [ADVERTENCIA] [FastLogin] Submitted IP-Address is not local /123.123.12.123

**Comment by games647** [comment]
Are those addresses local in your subnet?

**Comment by games647** [comment]
I thought the address have to be local. I removed the local check now.

**Comment by M4T14SG4M3R** [comment]
It worked, thank you :D
