### ISSUE TITLE
AutoLogin not work

### ISSUE THREAD

**Issue by KamThail** [games647/FastLogin#183]
/premium is normally used, but when you exit the server and enter the server again, it does not AutoLogin as set in the Config.
Please help me.

**Comment by games647** [comment]
Please follow the issue template. I need those information to actually help you. Here is it for reference:
https://raw.githubusercontent.com/games647/FastLogin/master/.github/ISSUE_TEMPLATE.md

**Comment by KamThail** [comment]
Thank you

**Comment by KamThail** [comment]
### What behaviour is observed:
[//]: # (Autologin does not work.)

### What behaviour is expected:
[//]: # (AutoLogin works normally.)

### Steps/models to reproduce:
[//]: # (I don't know)

### Plugin list:
[//]: # (SuperLobby, WorldEdit, SpawnTravel, DisableJoinMessage, ChatControl, ViaVersion, SuperCensor, ProtocolLib, AAC, CommandBlockerUltimate, FastLogin, BungeeNPC, Authme, AACAdditionPro, AuthMeBridge, Litebans)

### Environment description
[//]: # (My version Spigot is 1.8.8-R0.1-SNAPSHOT
My version BungeeCord is BungeeCord-Boorstrap:1.12-SNAPSHOT
And Authme with mysql)

### Plugin version or build number):
[//]: # (FastLogin Version 1.10)

### Error Log:
[Hastebin] (https://hastebin.com/duretasegi.md)

### Configuration:
[//]: # (remember to delete any sensitive data)
[Hastebin] (https://hastebin.com/bopuxapope.bash)

**Comment by games647** [comment]
Please see the first line of the document. Lines in the format of will not be displayed.
>-[//]: # (Lines in this format are considered as comments and will not be displayed.)

I noticed you are using BungeeCord. Do you followed the BungeeCord setup guide on the project site (spigot and here)? - https://github.com/games647/FastLogin#bungeecordwaterfall-1

**Comment by KamThail** [comment]
I do follow
BungeeCord 3, but it does not have a file. proxy-whitelist Is in the FastLogin folder.
But it is in Spigot's FastLogin folder.

**Comment by games647** [comment]
The proxy-whitelist file will be automatically created if you enable BungeeCord in your spigot.yml file.

**Comment by KamThail** [comment]
ok

**Comment by KamThail** [comment]
i have proxy-whitelist.txt in Spigot Server

**Comment by KamThail** [comment]
In FastLogin folder

**Comment by games647** [comment]
Just continue the guide.

**Comment by KamThail** [comment]
ok

**Comment by KamThail** [comment]
What is firewall spigot server

**Comment by games647** [comment]
You should always protect the spigot server, so that the spigot server is only reachable through BungeeCord and not directly using the ip port combination.

**Comment by KamThail** [comment]
Yes i protect it Players can only access via BungeeCord can't access via Port. by entering IP: 127.0.0.1 into server.propoties.

**Comment by games647** [comment]
Then it's fine.

**Comment by KamThail** [comment]
Yes

**Comment by KamThail** [comment]
Where is stats id from the BungeeCord

**Comment by games647** [comment]
Config.yml of the bungee server

**Comment by KamThail** [comment]
Copy stats id in to the proxy-whitelist.txt?

**Comment by KamThail** [comment]
Thank you it working!!!!
