### ISSUE TITLE
Don't work autologin

### ISSUE THREAD

**Issue by LYZTeam** [games647/FastLogin#185]
Hi, i have a problem with Authme and fastlogin

i do the command /premium, the command work but on rejoin don't work autologin

Log Console:

https://pastebin.com/rHBVjWaA

Config Fastlogin:

https://pastebin.com/TRyiqydi

FastLogin on mysql:

http://prntscr.com/hf1oat

**Comment by games647** [comment]
Please fill the issue template. I need to know more about your server setup like if you use BungeeCord.

**Comment by SimoAle** [comment]
### What behaviour is observed:
[//]: # Don't work plugin

### What behaviour is expected:
[//]: # autologin

### Steps/models to reproduce:
[//]: # none

### Plugin list:
[//]: #WorldEdit, PlaceholderAPi, ServerSelectorX, stablist, joinmotd, protocolib, multiversecore, accountguard, worldguard, aac, skinrestorer, voxelsniper, permissionsex, conditionalcommands, cji, vault, chattoggler, fastlogin, essentials, essentialschat, essentialsspawn, holographicdisplay, holographicdisplaypatch, authme, litebans

### Environment description
[//]: # Spigot, Mysql no bungeecord

### Plugin version or build number (don't write latest):
[//]: # 1.1.0

### Error Log:
[Hastebin] https://pastebin.com/rHBVjWaA

### Configuration:
[//]: # https://pastebin.com/TRyiqydi
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file

**Comment by games647** [comment]
>java.lang.NoClassDefFoundError: fr/xephi/authme/api/NewAPI

Outdated AuthMe version

**Comment by SimoAle** [comment]
Ok, i download the latest?

**Comment by games647** [comment]
Just update AuthMe and that's it.
