### ISSUE TITLE
Failure to find com.lenis0012.bukkit:loginsecurity

### ISSUE THREAD

**Issue by madtomic** [games647/FastLogin#186]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building FastLoginBukkit 1.11
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.lenis0012.bukkit:loginsecurity:jar:2.1.6 is missing, no dependency information available
[WARNING] The POM for com.github.games647:LogIt:jar:9e3581db27 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] FastLogin .......................................... SUCCESS [  3.933 s]
[INFO] FastLoginCore ...................................... SUCCESS [  9.850 s]
[INFO] FastLoginBukkit .................................... FAILURE [  0.325 s]
[INFO] FastLoginBungee .................................... SKIPPED
[INFO] FastLoginUniversal ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.925 s
[INFO] Finished at: 2017-11-29T23:37:34-05:00
[INFO] Final Memory: 20M/246M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project fastlogin.bukkit: Could not resolve dependencies for project com.github.games647:fastlogin.bukkit:jar:1.11: Failure to find com.lenis0012.bukkit:loginsecurity:jar:2.1.6 in https://hub.spigotmc.org/nexus/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of spigot-repo has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :fastlogin.bukkit
PS C:\Users\madtomic\Desktop\maven\FastLogin-master>

**Comment by games647** [comment]
https://github.com/lenis0012/LoginSecurity-2/issues/114

**Comment by games647** [comment]
For now you have to import LoginSecurity manually with the following command on the jar file of LoginSecurity:

```
mvn install:install-file -Dfile=LOGINSECURITY.jar -DgroupId=com.lenis0012.bukkit -DartifactId=loginsecurity -Dversion=2.1.6  -Dpackaging=jar
```
