### ISSUE TITLE
No-Premium User can enter with premium name

### ISSUE THREAD

**Issue by SeDark** [games647/FastLogin#188]
A few days ago a user came with the name "tonacho" which is a famous youtuber, obviously it is not him and his UUID is not the one of his premium account either.

https://es.namemc.com/profile/tonacho.1

01:47:22 [INFORMACIÓN] Loaded player §9tonacho§7 (4c9cde18-09c5-3e89-9475-4c735eb7afce)

Config: 
https://pastebin.com/k6Wqhq22

I do not know exactly how he does it, since I've tried to enter with a premium name with a non-premium launcher and I can't.

### Plugin list:

In Bungee: LuckPerms, BungeeTabListPlus, BuycraftX, DeluxeChat, FastLogin, LiteBans, SkinsRestorer, Yamler-Bungee

### Environment description

Bungeecord Network (BungeeCord 1​28​6) MYSQL

### Plugin version or build number (don't write latest):

#780 (1.11-25c725f)

**Comment by games647** [comment]
Already existing users before the FastLogin installation are assumed to be cracked and therefore can still login and play.

**Comment by SeDark** [comment]
Can not do anything about it?
There are users who did their accounts years ago and I would not like them to enter with their name in a non-premium launcher

**Comment by games647** [comment]
Just unregister them. FastLogin asks your login plugin at the moment they want to join your server.

**Comment by SeDark** [comment]
"cracked player cannot register an account for the premium player and so cannot the steal the account"

I always believed that this meant that a user with a non-premium launcher could not use an existing account in the minecraft database.

Then nothing can be done and I must assume that there are users who can impersonate others who have a premium account by entering their name?

It's not that it's a big problem, but if there was some way to fix it that is not manual (and that does not allow this to happen), I would ask you to implement it if possible...

**Comment by games647** [comment]
>"cracked player cannot register an account for the premium player and so cannot the steal the account"
I always believed that this meant that a user with a non-premium launcher could not use an existing account in the minecraft database.

See line 11 in the config.

>It's not that it's a big problem, but if there was some way to fix it that is not manual (and that does not allow this to happen), I would ask you to implement it if possible...

Just use auto purge by your auth plugin-

**Comment by SeDark** [comment]
I think I did not express myself well, this user did not exist in AuthMe, I had no previous players when I install this plugin (FastLogin) since my server was premium, that is, I installed fastlogin together with authme.

**Comment by games647** [comment]
Please post the BungeeCord log at the moment the user tried to login.

**Comment by SeDark** [comment]
https://hastebin.com/ononegenut.xml

**Comment by games647** [comment]
Could post the startup log too, because I see no debug messages of FastLogin at all.

**Comment by SeDark** [comment]
https://hastebin.com/ficehequbi.sql

**Comment by games647** [comment]
Are you sure that's the first time a player with that name logged into the server and do you see any messages about rate-limiting?

**Comment by SeDark** [comment]
https://hastebin.com/tunenujasi.hs 
This log is the first time this user entered

And now that you mention it, from time to time two errors come out, although they do not have to do with this user

18:39:26 [INFORMACIÓN] [FastLogin] RATE_LIMIT REACHED

https://hastebin.com/yopugurate.swift

**Comment by games647** [comment]
That's the reason. FastLogin cannot at that time if that player is premium or not. So it will assume all are cracked. I should make the rate limit message more informative.

**Comment by SeDark** [comment]
I understand that the limit is 600 requests every 10 minutes, my server is small, I have an average of 30-40 people, it is impossible to reach that limit.

Am I wrong with the limit?

**Comment by games647** [comment]
You can easily reach this limit if other plugins do the same requests like skins plugins or head blocks.

**Comment by SeDark** [comment]
I imagine then that there is no solution to this?

Anyway, thanks for the help

**Comment by games647** [comment]
This could maybe help you:

https://www.spigotmc.org/threads/changeskin.138380/page-33#post-2574599

I guess your hosting your bungee and spigot servers on the same host. Then the Spigot servers maybe do multiple requests too, because they aren't connected.
