### ISSUE TITLE
Support for multiple / remote BungeeCord instances.

### ISSUE THREAD

**Issue by k-jiang** [games647/FastLogin#19]
Hi, can you make this plugin supports for multiple remote BungeeCord?

I have tried to add multiple lines of stats-id on the spigot side proxy-whitelist.txt, yet it seems that only the one on the first line can auto-logged premium players.

The first bungee I have is located on the same machine as spigot (so call localhost). The second and third are located on the different machines. All BungeeCords sharing the same MySQL database of FastLogin. Between spigots and remote bungee there is a firewall allows only spigot traffic to go through. Unfortunately this firewall is not what I can control.

I haven't tested it harder so it might be the problem with multiple BungeeCord supports, OR it could be the problem with the firewall (assuming FastLogin uses some extra protocol like AutoIn did). I will try it on my PC later.

**Comment by games647** [comment]
>I have tried to add multiple lines of stats-id on the spigot side proxy-whitelist.txt, yet it seems that only the one on the first line can auto-logged premium players.

Yeah it only the first line. Sorry for that. I never thought about multiple BungeeCords.

>All BungeeCords sharing the same MySQL database of FastLogin.

The problem currently is that FastLogin caches the data locally, which we should disable/remove if the data is accessed by multiple instances. 

>OR it could be the problem with the firewall (assuming FastLogin uses some extra protocol like AutoIn did). I will try it on my PC later.

No fastlogin just uses the normal plugin message channel in Minecraft which was previously implemented as communication between mods and plugins, for example worldedit gui and worldedit. BungeeCord intercept those packets and fastlogin on the bungeecord server will read them.

**Comment by sgdc3** [comment]
@games647 Multiple Bungeecord instances usually use RedisBungee to sync the data, this means that there is a redis database somewhere, just use it! ;)

**Comment by games647** [comment]
I thinking of just removing the local cache, because MySQL has also cache system. Then we only have to allow multiple entries in the whitelist file and that's it.
