### ISSUE TITLE
sponge/forge 1.12.2 login issue

### ISSUE THREAD

**Issue by popcorn9499** [games647/FastLogin#193]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for duplicate issues!)

So basically I was using a bungeecord network to try and login to my forge server from my spigot vanilla server. This resulted in no connection attempt being made

### What behaviour is observed:
The player stayed on the hub world when trying to login to my forge 1.12.2 server running spongeforge

### What behaviour is expected:
[//]: # (What did you expect?)
To login my forge 1.12.2 server running spongeforge

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
Try to login to the spongeforge 1.12.2 server results in the player not connecting to the spongeforge server at all. not even a connection attempt appears. 

Only happens with fastlogin installed along with what i need on the bungeecord.

21:58:12 [INFO] [popcorn9499] <-> ServerConnector [GG] has connected
21:58:12 [INFO] [popcorn9499] <-> ServerConnector [GG] has disconnected
 thats all that comes in the console

### Plugin list:
[//]: # (This can be found by running `/pl`)
Please tell me what plugins on what server you want
The bungee plugin list is
Authmebungeebridge
Fastlogin
spongepls
Luckperms-bungee

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL, ...)
Minecraft 1.12.2 hub server (Vanila)
minecraft 1.12.2 forge server (spongeforge)
Fastlogin is using mysql

### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
fastlogin 1.10

### Error Log:
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error or stacktrace (if any)
21:58:12 [INFO] [popcorn9499] <-> ServerConnector [GG] has connected
21:58:12 [INFO] [popcorn9499] <-> ServerConnector [GG] has disconnected

### Configuration:
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file 
Which config.yml do you want.

**Comment by games647** [comment]
Do you enabled BungeeCord support in the sponge configuration?

**Comment by popcorn9499** [comment]
Thanks. Missed the config. Forgot about the need for bungeecord support and ip forwarding. Sorry to bother you. Have a happy Valentines day

**Comment by popcorn9499** [comment]
Sorry forgot to close it until now.
