### ISSUE TITLE
Doesn't work on Paper Spigot 1.12.2.

### ISSUE THREAD

**Issue by TheIntelloBox** [games647/FastLogin#196]
Hey,

I have put the plugin but my Premium players and me must do /login and /register...
I'm on Paper Spigot 1.12.2 and there's no error.

**Comment by games647** [comment]
Please follow the issue template

**Comment by TheIntelloBox** [comment]
### What behaviour is observed:
I have put the plugin but my Premium players and me must do /login and /register... # (What happened?)

### Plugin list:
Authme Reloaded (dev build) and FastLogin (latest dev build) : # (This can be found by running `/pl`)

### Environment description
Paper Spigot 1.12.2, MySQL, Java 8: # (Server software with exact version number, Minecraft version, SQLite/MySQL, ...)

### Plugin version or build number (don't write latest):
FastLogin : 1.11-8cbdb66 and AuthmeReloaded : b1904 : # (This can be found by running `/version plugin-name`.)

### Error Log:
No error.

### Configuration:
https://hastebin.com/dajinaquca.bash: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file

**Comment by games647** [comment]
Could you post the server log please.
