### ISSUE TITLE
No autologin and no errors showing up

### ISSUE THREAD

**Issue by QUIQUELHAPPY** [games647/FastLogin#197]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for duplicate issues!)

### What behaviour is observed:
[//]: # No autologin
No errors. https://github.com/games647/FastLogin/issues/196 may be related?
Row added to database, UUID null? [Image imgur](https://i.imgur.com/7Q74IL2.png)

### What behaviour is expected:
[//]: # Autologin with AuthMeReloaded (last v)

### Steps/models to reproduce:
[//]: # 1.Use the last version of fast login and authmereloaded

### Plugin list:
[//]: # AsyncWorldEditInjector, AnimationLib, SkinsRestorer, WorldEdit, EmptyWorldGenerator, AsyncWorldEdit, PlaceholderAPI, NoteBlockAPI, UltimateBossBar, noDamage, Vault, BanManager, ProtocolLib, WorldGuard, JukeBox, WorldGuardExtraFlags, TitleManager, AnimatedMenu, VentureChat, FastLogin, AuthMe

### Environment description
[//]: # 1.12.2
BungeeCord (enabled in spigot.yml)
AuthMeReloaded installed on the lobby server
AuthMeReloaded encryption: salted sha512
FastLogin installed on the lobby server
Fast login installed on the bungeecord proxy
Using mysql and both fastlogin and mysql
Running the server in localhost (testing)

### Plugin version or build number (don't write latest):
[//]: # AuthMe version 5.4.0-b1877
FastLogin version 1.11-8cbdb66

### Error Log:
No errors, just not doing what I was expecting
[23:44:30 INFO]: [FastLogin] Loading FastLogin v1.11-8cbdb66
[23:44:38 INFO]: [FastLogin] Hooking into auth plugin: AuthMeHook
[23:44:38 INFO]: [FastLogin] BungeeCord setting detected. No auth plugin is required

### Configuration:
[//]: # (remember to delete any sensitive data)
https://hastebin.com/visamiliqi.bash

**Comment by games647** [comment]
Could you post the full server log including when someone premium joins the server and could you maybe try build # 785?

**Comment by QUIQUELHAPPY** [comment]
for sure.
Startup with the version I had:
[Bungeecord start log](https://hastebin.com/ikurefogoj.sql), [Spigot start log](https://hastebin.com/ewarejesiz.md)

Join log with the version I had: [bungeecord](https://hastebin.com/ojiturusur.css), join log: [spigot](https://hastebin.com/logagawofa.pas)

____

Startup with [# 785](https://ci.codemc.org/job/FastLogin/785/):
[Bungeecord start log](https://hastebin.com/ekibiyivok.sql), [Spigot start log](https://hastebin.com/egelusokip.md)

Join log with [# 785](https://ci.codemc.org/job/FastLogin/785/):
Bungeecord [join log](https://hastebin.com/juvonofemu.css), Spigot [join log](https://hastebin.com/udijogepag.md)
*still not working

**Comment by games647** [comment]
Do you put the proxy id into the proxy whitelist file inside the FastLogin folder?

**Comment by QUIQUELHAPPY** [comment]
Nope, now it's working! Thanks :) Probably #196 has the same problem 😉
