### ISSUE TITLE
Skins doesnt work in premiums accounts

### ISSUE THREAD

**Issue by Breadshot** [games647/FastLogin#198]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for duplicate issues!)

### What behaviour is observed:
[//]: # (What happened?)
The skins in my premium account doesnt work
### What behaviour is expected:
[//]: # (What did you expect?)
See my skin that I can see in any server
### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
I just write /premium and I get out of my sv and then I get in again and it doesnt work (Yes I /stop my server)
### Plugin list:
[//]: # (This can be found by running `/pl`)
Essentials, EssentialsChat, PermissionsEx, ServerNPC, NametagEdit, Vault, EssentialsSpawn, ProtocolLib, SuperLobby, FastLogin, SpigotBoard, AuthMe, Announcer, HolographicDisplays, LiteBans
### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL, ...)
Minecraft 1.8/Spigot1.8.8
### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
FastLogin version 1.10-git484855724b794de1fe057cf7360245362658b432
### Error Log:
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error or stacktrace (if any)
No error log
### Configuration:
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file 
https://hastebin.com/atukawiwej.bash

Please help :c

**Comment by games647** [comment]
Could you try the latest dev-build please and update your config. There are some configuration options missing. https://github.com/games647/FastLogin/blob/master/core/src/main/resources/config.yml
