### ISSUE TITLE
Autologin without command + config option for it

### ISSUE THREAD

**Issue by ActimelPL** [games647/FastLogin#2]
Hello,

I am having issues with the auto login for AuthMe-5.2 build #699. I am using the latest (protocolsupport compatible) version of your plugin.

Your plugin correctly detects the AuthMe plugin and puts verbose of a succesful hook. The player however, is not correctly logged in and has to type in the password. I am using latest ProtocolSupport and ProtocolLib.

Please let me know if you will need logs for debug. Thanks.

**Comment by games647** [comment]
Did the player invoked the premium command?

**Comment by ActimelPL** [comment]
Is it required for every user that joins the server?

**Comment by SkymaxPlay** [comment]
ActimelPL jak dasz do do bugee to na bungee bedzie lista osób co wpisało komendę do logowannia premium.

**Comment by SkymaxPlay** [comment]
Każdy gracz jest weryfikowany tylko gdy wpisze komendę /premium . Inaczej nie zweryfikuje. Mogę Ci go przerobić

**Comment by games647** [comment]
@ActimelPL 

I already posted that into the faq [here](https://github.com/games647/FastLogin#why-do-players-have-to-invoke-a-command). In short words:

* A cracked player who uses a premium username would be kicked with the message bad login
    * There's no way to change the message
    * We can only premium players based on their usernames and a successful connection afterwards
        * But it would be possible to request a premium login on the first login and if that failed, the player could login as a cracked player
        * I thought that would be bad user experience and so I didn't introduced that feature
* A paid account could steal the account of cracked player
    * (Different from FAQ) Solution: Check if the account already exists
* A cracked player could still create a new account for premium players
    * (Different from FAQ) Solution: Register the account automatically with a random generated password

Although there is the still the problem of the first point, I could add a configuration option to enable auto logins without commands.

**Comment by ActimelPL** [comment]
Thanks to you, I now understand how your plugin works. I probably ommited that explanation in faq before the download.

There is another plugin available on SpigotMC, called Auto-In, which works the way desired by me. It is probably checking the existence of an AuthMe account to find if the register is needed for it.

The optional configuration option would be great.
