### ISSUE TITLE
Authme sends its invalid_session Message on AutoLogin

### ISSUE THREAD

**Issue by Phreag** [games647/FastLogin#201]
### What behaviour is observed:
The Plugin works great. But Authme sends its invalid_session Message to the player.

### What behaviour is expected:
I should not see a Message there

### Plugin list:
Authme 5.4.0 b1877
FastLogin 1.10 (from Spigot)

### Environment description
PaperSpigot 1.12.2, latest build, BungeeCord

### Error Log:
no Error log

What is wrong? I fixed it by changing the Message in Authme, but that should not be the solution.

**Comment by games647** [comment]
Could you please post the message?

**Comment by ljacqu** [comment]
NB: AuthMe no longer does this in newer builds, cf. https://github.com/AuthMe/AuthMeReloaded/pull/1518

**Comment by Phreag** [comment]
Thanks!
Updating AuthMe to latest dev Build fixed it!
