### ISSUE TITLE
(request) update account status from cracked automatically

### ISSUE THREAD

**Issue by quiquelhappy** [games647/FastLogin#204]
**Feature request:**
If user was a cracked user (Premium=0) update automatically the value on the database if the owner of that account joins with a premium launcher (set Premium=1 without running the command /premium).

**Example:**
QUIQUELHAPPY has been playing the server for some time now and was a cracked user, he decided to buy minecraft. Now he joins the server with the paid launcher, his account status on the database changes from Premium=0 to Premium=1 (just after joining)

Thanks 😄

**Comment by games647** [comment]
That's not possible, because we can only make sure whether a player is premium by requesting a premium authentication from that player (and maybe make a premium name check before). If the player is still cracked, the **client** will disconnect and show the message "Invalid session".

**Comment by QUIQUELHAPPY** [comment]
I really want that my players that have Minecraft paid can join with a cracked launcher, I've seen that if I remove the row just when they connect I can compare if they are premium or not with the previous value stored in another table, but I would like to see this just natively supported :(

**Comment by games647** [comment]
>I really want that my players that have Minecraft paid can join with a cracked launcher,

It's already possible for new players if you enable autoRegister, but the issue here is that cracked players will disconnect once we request an premium authentication from them. In my opinion this is very bad for the user experience, because we cannot change this disconnect message.

**Comment by QUIQUELHAPPY** [comment]
I don't understand the limitation...
I mean, if you can check if the user is cracked or not without kicking it at any momment why you can't check it everytime the user joins without depending on the stored value on the database? (and then compare if the old value has changed from "0" to "1"?

**Comment by games647** [comment]
>I mean, if you can check if the user is cracked or not without kicking it

You can't, you can only check the username, but that doesn't guarantee you that this connecting client is actual the owner of that account. To do that, you have to request an onlinemode authentication. Then premium join the server thinking it's a all onlinemode server, but cracked clients will disconnect (from the client-side) with the message "Invalid session".

**Comment by QUIQUELHAPPY** [comment]
Well, I don't know what I'm doing then, because it seems that is working, lmao

**Comment by games647** [comment]
Yes it works, but only for owners of premium accounts. This has nothing to do with the type of launcher you are using only. It's just about if you are authenticated against Mojang or not.

**Comment by QUIQUELHAPPY** [comment]
https://i.imgur.com/qgeFzAU.png

**Comment by games647** [comment]
Yes with this change autoRegister is always enabled, but it doesn't work if a cracked player joins the game that isn't authenticated against Mojang. Try to join the game with a name like Notch and see what happens.

**Comment by QUIQUELHAPPY** [comment]
Okay, let me see

**Comment by QUIQUELHAPPY** [comment]
for some reason it always returns cracked now, yesteday is was kinda working

**Comment by QUIQUELHAPPY** [comment]
fast login is not working now, Idk why

**Comment by games647** [comment]
If you made too many requests to the Mojang API server, you are rate-limited. You cannot make more than 600 requests within 10 minutes. Furthermore FastLogin caches results from the Mojang API. 

>I've tried to remove the used data from the database and join as a new player and fastlogin is not detecting it as a paid user

This would only work if you enabled autoRegister and the account is not registered.
