### ISSUE TITLE
Support for AuthMeBungee (not AuthMe Bridge)

### ISSUE THREAD

**Issue by ssamjh** [games647/FastLogin#206]
Hello there

This plugin here is the one I am talking about: https://www.spigotmc.org/resources/authmebungee.50219/

It's the newer version of AuthMe support for BungeeCord.

I have seen you support the older AuthMeBridge solution, however that plugin above is made especially to work with AuthMeReloaded.

**Comment by games647** [comment]
I think it tested it with AuthMeBridge, but it should work with both nevertheless.
