### ISSUE TITLE
Problem with new Releases.

### ISSUE THREAD

**Issue by EncryptSL** [games647/FastLogin#209]
Hello games647, i have a big problem with new Releases.

When i add your new releases my plugins catch the error. 
I have my plugins connected to the database and can not find the hikari class. 
But when I get the old version of the plug-in, so everything is fine.
So I have to use the old version. Version is :  FastLogin version 1.10-git484855724b794de1fe057cf7360245362658b432

I use a hikari connection using the integration of maven.

Some ideas ?

**Comment by EncryptSL** [comment]
When will it be ?.¨
Ok thanks for answer. ;).

**Comment by games647** [comment]
If you want to use HikariCP in your own plugin, you have to shade it too. This will copy the library into your library and prevent conflicts with dependency version updates of FastLogin. You can take the FastLogin Source-Code for example:

https://github.com/games647/FastLogin/blob/084afef899b56c470ed32f584254c9607710a13e/bukkit/pom.xml#L19-L54

This will copy all library into your plugin jar that have a compile scope (default if not specified - i.e. provided and test is excluded). Relocating is the concept of moving the dependency classes in the java class to a different package so multiple versions of this dependency can coexist without conflicting each other. In your case you should rename the target destinations to your own project name.

**Comment by EncryptSL** [comment]
Problem solved thx for answer and your time 👍 . 🥇
