### ISSUE TITLE
Plugin FastLogin generated an exception while executing task (text cannot be NULL)

### ISSUE THREAD

**Issue by Blackyvk** [games647/FastLogin#212]
Server is in whitelist mode on: player tried to connect several times, he wasnt on the whitelist.

### Plugin list:
Fastlogin, AuthMe, ProtocolLib

### Environment description
Spigot  1.12.2

### Plugin version or build number (don't write latest):
FastLogin version 1.11-SNAPSHOT-9b0b8f5

### Error Log:
https://hastebin.com/obepiguwen.vbs

### Config : 
https://gist.github.com/Blackyvk/59e80fd7bf25d1dd3fcf6c376dd2dfa6

**Comment by Blackyvk** [comment]
I tried to regenerate the file and I only notice small changes on the comments and 1 line message is a little different, but it's basically the same file.

https://hastebin.com/aveqojuzag.pl

**Comment by games647** [comment]
Do you use BungeeCord?

**Comment by Blackyvk** [comment]
no

**Comment by games647** [comment]
Please post the startup log. The plugin failed to load the messages in this case.

**Comment by Blackyvk** [comment]
I dont see any errors here
https://hastebin.com/obikebiqak.md
