### ISSUE TITLE
Fastlogin does not auto log in premium players

### ISSUE THREAD

**Issue by MineyShadow** [games647/FastLogin#218]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for duplicate issues!)

### What behaviour is observed:
[//]: # (What happened?)
1.8-1.12.2 premium users are automatically registered/logged in while 1.13 players aren't, authme outputs login/register messages. Premium players are not kicked for invalid session if they are running offline in 1.13 while they get kicked in 1.8-1.12.2

### Plugin list:
[//]: # (This can be found by running `/pl`)
Spigot - 
![image](https://user-images.githubusercontent.com/37338176/43119363-8a50d646-8f2f-11e8-9af2-fc95a87da7a3.png)
Waterfall -
![image](https://user-images.githubusercontent.com/37338176/43119408-ad8f6bea-8f2f-11e8-93b7-134e58310959.png)

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL, ...)
Waterfall-Bootstrap:1.13-SNAPSHOT:9b49f93:210 on Linux
Mysql Database
Spigot 1.12.2 on Linux - git-Spigot-642f6d2-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
FastLogin version 1.11-SNAPSHOT-c172b1e - Bungee
FastLogin v1.11-SNAPSHOT-c172b1e - Spigot
### Error Log:
[//]: # (No images please - only the textual representation)
No Errors in any console.
### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
https://gist.github.com/MineyShadow/ba4add6d0283454211de8fbe79c9a6a3

**Comment by games647** [comment]
Could you try the newer version please?

**Comment by MineyShadow** [comment]
Fixed in latest version, thank you!

**Comment by games647** [comment]
The plugin wasn't correctly lowercased. Should be fixed now.

**Comment by MineyShadow** [comment]
Same issue still with the recent new version.

**Comment by MineyShadow** [comment]
Somehow the issue got fixed, no idea how but maybe this happens from time to time, I'll re-open if the issue is back
