### ISSUE TITLE
Auto login premium accounts after reload

### ISSUE THREAD

**Issue by wvffle** [games647/FastLogin#226]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for duplicate issues!)

### What behaviour is observed: 
All users got logged out after reload

### What behaviour is expected: 
Auto login premium accounts after reload

### Steps/models to reproduce: 
- Log into the server with premium account
- Reload the server

### Plugin list: 
- FastLogin
- AuthMe

### Environment description:
Minecraft 1.12.2

### Plugin version or build number (don't write latest):
FastLogin version 1.10-git484855724b794de1fe057cf7360245362658b432

### Error Log:
No errors.

### Configuration:
[Hastebin](https://hastebin.com/nokojoqoya.makefile)

**Comment by games647** [comment]
FastLogin doesn't handle authentication sessions. Your auth plugin does that.
