### ISSUE TITLE
When you login with a cracked account it does not requires to register/login.

### ISSUE THREAD

**Issue by Gobli989** [games647/FastLogin#228]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for duplicate issues!)

### What behaviour is observed:
[//]: # (What happened?)
When you login with a cracked account it does not requires to register/login.

### What behaviour is expected:
[//]: # (What did you expect?)
For premium accounts: login instantly, for cracked ones: register/login

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
I don't know, thats what I want to know.

### Plugin list:
[//]: # (This can be found by running `/pl`)
#### Server Plugins:
* ProtocolLib
* LuckPerms
* TitleManager
* AdvancedPortals
* WorldEdit
* FastLogin
#### Bungee Plugins:
* FastLoginBungee
* ViaVersion
* ViaRewind

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL, ...)
Spigot 1.8.8-R0.1-SNAPSHOT
10.1.33-MariaDB

### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
FastLogin-1.10

### Error Log:
[//]: # (No images please - only the textual representation)
I don't get any error. 😄 

### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Bungee Config](https://pastebin.com/ueAX8Lq6)
[Spigot Config](https://pastebin.com/NqLUZrwX)

**Comment by games647** [comment]
Sorry for the **very** late response. I was too busy. However I want to still answer this, it may help others. You didn't even had auth plugin installed. FastLogin is no auth plugin. It only cooperates with them
