### ISSUE TITLE
Issue with Luckperms

### ISSUE THREAD

**Issue by xion87** [games647/FastLogin#229]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for duplicate issues!)

### What behaviour is observed:
Luckperms will receive wrong UUID, these issue started when i start to use fastlogin

### What behaviour is expected:
It should receive the correct UUID

### Steps/models to reproduce:
Have Fastlogin and luckperms on bungee

### Plugin list:
Latest LuckpermsBungee, fastloginbungee, authmebungee, fastlogin luckperms and authme on login server

### Environment description
Paperspigot 1.8.9

### Error Log:
https://gist.github.com/xion87/09ae0f7321585d0eabb60d2515ed33f7

### Configuration:
Paperspigot LP config: https://gist.github.com/xion87/d4b174faa271494224fd0fd153168d7e
Fastlogin config:  https://gist.github.com/xion87/2347fdd0d6873df7014e4863e9c6fa66

### Notes
I noticed that you fixed a similiar issue time ago with bukkit version, maybe you did not fixed it with LP bungee? From these issues
https://github.com/lucko/LuckPerms/issues/988
https://github.com/games647/FastLogin/issues/167

**Comment by MrPowerGamerBR** [comment]
Can confirm this issue, the error shows up in the BungeeCord's console and in the Minecraft Server's console.

![image](https://user-images.githubusercontent.com/9496359/44356171-f0f49800-a484-11e8-80fb-b432cda10f49.png)

**Comment by MrPowerGamerBR** [comment]
By the way, I noticed this issue started happening after I enabled `premiumUuid` and `nameChangeCheck`, both Bungee and Bukkit have the same configuration files.

**Comment by xion87** [comment]
i just noticed Luckperms if you just login on bungeecord with different capitalizazion it trow that error and uuid will be changed on db.... is not a fastlogin issue, so i close...
