### ISSUE TITLE
FastLogin + AuthMe + ProtocolSupport counts all players as cracked

### ISSUE THREAD

**Issue by Govindass** [games647/FastLogin#237]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for duplicate issues!)

### What behaviour is observed:
[//]: # (What happened?)
when I join the server with my premium account it counts me as cracked player, I get cracked UUID instead of premium with ProtocolSupport installed, does not happen without ProtocolSupport
### What behaviour is expected:
[//]: # (What did you expect?)
I expected it to count me as premium player.
### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
simply install ProtocolSupport on 1.12.2 server.
### Environment description
1.12.2 paperspigot, 1.12.2 minecraft
### Plugin version or build number (don't write latest):
#848
### Error Log:
nothing that I have noticed
### Configuration:
https://pastebin.com/raw/cHCgU2hx

**Comment by Govindass** [comment]
any news on fixing this..?

**Comment by AlikSondor** [comment]
Turn on BungeeCord in AuthMe config.

**Comment by Govindass** [comment]
> Turn on BungeeCord in AuthMe config.

I don't understand, I'm not using BungeeCord and I have never used it, do you really think I'm using BungeeCord or it's the magical way to fixing everything?

**Comment by AlikSondor** [comment]
It's the magical way to fixing everything))

**Comment by games647** [comment]
Do you see the premium message? Which version of ProtocolSupport do you run?

**Comment by Govindass** [comment]
> Do you see the premium message? Which version of ProtocolSupport do you run?

yes I see premium message, I do not know what version of protocolsupport, I tried multiple, now I have deleted it, know one which works?

**Comment by AlikSondor** [comment]
> > Do you see the premium message? Which version of ProtocolSupport do you run?
> 
> yes I see premium message, I do not know what version of protocolsupport, I tried multiple, now I have deleted it, know one which works?

I have ProtocolLib 4.4.0
ViaRewind and ViaBackwards (ProtocolSupport Analogs, with extra features and better implementation)
AutoRegister did not work for me until I switched BangeeCord to true mode. (I use a single spigot server without BangeeCord)
The problem has disappeared, everything works.

**Comment by Govindass** [comment]
> > > Do you see the premium message? Which version of ProtocolSupport do you run?
> > 
> > 
> > yes I see premium message, I do not know what version of protocolsupport, I tried multiple, now I have deleted it, know one which works?
> 
> I have ProtocolLib 4.4.0
> ViaRewind and ViaBackwards (ProtocolSupport Analogs, with extra features and better implementation)
> AutoRegister did not work for me until I switched BangeeCord to true mode. (I use a single spigot server without BangeeCord)
> The problem has disappeared, everything works.

viarewind and viabackwards do not work for me, I get kicked as soon as I join, not a problem with autoregister. ProtocolSupport works, but counts me as cracked player, but I'm going to try bungeecord on in authme.

**Comment by Govindass** [comment]
ProtocolSupport + bungeemode in authme still doesn't work.

**Comment by 7wOv6ySCjo** [comment]
Hey @Govindass how do you get the info about the count of cracked and premium players? Which commands is it?

**Comment by Govindass** [comment]
> Hey @Govindass how do you get the info about the count of cracked and premium players? Which commands is it?

I don't get that info, but it is in the mysql database (if you use mysql)
