### ISSUE TITLE
FastLogin not working (login error)

### ISSUE THREAD

**Issue by kodaLee** [games647/FastLogin#239]
### What behaviour is observed:
[//]: # An error on login

### What behaviour is expected:
[//]: # For it to auto login (setup properly)

### Steps/models to reproduce:
[//]: # Any player on the Premium list logging in

### Plugin list:
[//]: # LuckPerms, StartCommands, Hub, ViaVersion, CustomJoin, ViaBackwards, ProtocolLib, ViaRewind, AuthMe, FastLogin

### Environment description
[//]: # 1.8.x(based on 1.8.8) to 1.13.0, MySQLi 10.1.37)

### Plugin version or build number (don't write latest):
[//]: # FastLogin version 1.10-git484855724b794de1fe057cf7360245362658b432

### Error Log:
[//]: # https://privatebin.net/?b8056068d9839ce3#6ucanTFctmglmcoS/ZVHMgIcf1K5i4q+8dbaKlFW8wc=
[//]: # https://privatebin.net/?689f969bf85b0076#9ccNdKkD3EurP/LllzXeBaRx3CBzwnmZ9X8FzUACmiI=

### Configuration:
[//]: # https://privatebin.net/?540331454fd4c81f#rfiYo7c8deM+cAQjSTwu6JEYKW9e/9RKa3i5c22mtoA=

**Comment by games647** [comment]
Please verify your bungee plugin list. It tries hook into the BungeeAuth plugin, but you posted AuthMe.

**Comment by Nativ-e** [comment]
Verify? Do you mean removing BungeeAuth? I will try this. Thanks!

**Comment by Nativ-e** [comment]
> Please verify your bungee plugin list. It tries hook into the BungeeAuth plugin, but you posted AuthMe.

I have deleted BungeeAuth. Now nothing is happening

**Comment by Nativ-e** [comment]
No errors

**Comment by games647** [comment]
Then please close it next time.

**Comment by Nativ-e** [comment]
Uhm. I never said it was solved. I said Nothing is happening. No errors or anything in console. It's just not doing anything 
Bungeecord: http://prntscr.com/m73m3b
Spigot: Plugins are on first thread

**Comment by games647** [comment]
Sorry you said:

>No errors

Please post the bungee and bukkit server startup.

**Comment by Nativ-e** [comment]
I just noticed a few errors when it was loading in bungeecord!
# https://hastebin.com/ejikifuyig.makefile

**Comment by Nativ-e** [comment]
uhm... hello

**Comment by games647** [comment]
Then please read the setup guide including the last point.

>uhm... hello

This is just a hobby project. Please remember that.

**Comment by games647** [comment]
MariaDB, but they are both compatible.
