### ISSUE TITLE
Premium UUID only if launcher is Premium else Cracked uuid?

### ISSUE THREAD

**Issue by StpNex** [games647/FastLogin#241]
Hello I wanted to know if this is possible

If a player with a premium account and launcher logs in, they will be auto registered and logged in

else if a player with a premium account and offline laucher logs in, they will treated as cracked and request to register and use pass every time

If it's possible, how can I do it? thanks

**Comment by StpNex** [comment]
Found how, nvm.

**Comment by 7wOv6ySCjo** [comment]
Can you tell how do you made this? @StpNex
