### ISSUE TITLE
MySQL Access denied

### ISSUE THREAD

**Issue by JadssDev** [games647/FastLogin#247]
I get this error every time i start my server and it doesnt work... i did get my details of my mysql database but it doesnt work:

error:
![image](https://user-images.githubusercontent.com/47069768/55889859-a35ea400-5ba9-11e9-8f3d-c6285623a702.png)

config of mysql:
![image](https://user-images.githubusercontent.com/47069768/55889777-83c77b80-5ba9-11e9-93bf-fbef44db2ace.png)

**Comment by games647** [comment]
"Access denied" , you have used a wrong username password combination to connect to the MySQL server.

**Comment by jadsspt** [comment]
yes it is.
i did every thing correct

**Comment by jadsspt** [comment]
every detail is correct.
i don t have a password and my username is root

**Comment by games647** [comment]
Is it an empty password? Then please try `password: ''` and a login with using `mysql -u root -p`

**Comment by jadsspt** [comment]
i did get password to ''
but doesnt work,.

**Comment by games647** [comment]
Please try out a newer build. It now allows username only authentication.
