### ISSUE TITLE
Failed to load driver class org.sqlite.JDBC

### ISSUE THREAD

**Issue by Amonly25** [games647/FastLogin#248]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for duplicate issues!)

### What behaviour is observed:
I'm installing bungeecord and I can not make fastlogin work, everything works fine as far as Bungeecord is concerned, non-premium users can log in and login correctly, but the premiums do not detect them as such, I leave everything configured.

### What behaviour is expected:
Fix it xd

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)

### Plugin list:
On bungee: AutheMebungee, FastloginBungee, ProtocolLib, Skinrestorer

On paper: Authme, FastLoginBukkit, ProtoclLib, SkinRestorer

### Environment description
Bungee And Paper 1.13.2

### Plugin version or build number (don't write latest):
Authme 5.6.0 - when I put / fastlogin version, it says sending request and nothing happens (same as when I put / premium), but it's the last

### Error Log:
Paper https://pastebin.com/AY8UT044 Bunge:https://pastebin.com/9qVPvJqs

### Configuration:
Autoregister: true
Authme is hooked
All the onlinemode is in false
Proxy-whitelist is set
Ip forward: true
prevent_proxy_connections: false
bungeecord: true

Everything is fine, fastlogin not. I am testing on my computer because i cant do it on my dedicated.

I am using this ip rigthnow Bungee: 0.0.0.0:25577 paper: 0.0.0.0:25565

**Comment by games647** [comment]
You missed something in the Bungee log file:

>
23:01:47 [WARNING] Exception encountered when loading plugin: FastLogin
java.lang.RuntimeException: Failed to load driver class org.sqlite.JDBC in either of HikariConfig class loader or Thread context classloader
    at fastlogin.hikari.HikariConfig.setDriverClassName(HikariConfig.java:511)
    at com.github.games647.fastlogin.core.shared.FastLoginCore.setupDatabase(FastLoginCore.java:155)
    at com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:48)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:247)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:279)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by Amonly25** [comment]
I do not understand what that would be, could you help me?

**Comment by games647** [comment]
As shown in the Bungee setup guide of FastLogin, BungeCord doesn't include the driver for SQLite (the single .db file database). It only includes the ddiver for MariaDB or MySQL. So you have to configure that.
