### ISSUE TITLE
premium users unable to login on latest build

### ISSUE THREAD

**Issue by DailyStruggle** [games647/FastLogin#251]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for duplicate issues!)

### What behaviour is observed:
[//]: # plugin errors and premium login is blocked with a "Server is in Online Mode" message

### What behaviour is expected:
[//]: # automatic login for premium uuid

### Steps/models to reproduce:
[//]: # add jar, restart, update config, restart, attempt to join

### Plugin list:
[//]: # [14:58:27] Plugins (37): AdvancedPortals, AuthMe, AutoRestart, BannerMaker, BungeeTabListPlus*, ChatControl, ClearLag*, ColoredAnvils*, ConsoleSpamFix, CoreProtect, DecoHeads*, EditableSign, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, FastAsyncWorldEdit, FastLogin, KeepChunks, LuckPerms, NoPlugins, PlaceholderAPI*, PlugMan, ProtocolLib*, ProtocolSupport, Slap-Pro*, SuperVanish, Vault, VoidGenerator, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Environment description
[//]: # paper 1.13.2

### Plugin version or build number (don't write latest):
[//]: # 5.6.0-beta1

### Error Log:
[//]: # (No images please - only the textual representation)
[Hastebin](https://hastebin.com/ebohigonoz.sql)

### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/umoyasupox.makefile)

**Comment by DailyStruggle** [comment]
the bug persists.

cracked accounts can access the server but not premium accounts.

**Comment by games647** [comment]
Do you still have the error?

**Comment by DailyStruggle** [comment]
yes, the error is still popping up every time I try to log in

**Comment by DailyStruggle** [comment]
directly logging into the server works. 

logging in via bungee does not work.

I think there's an issue with the proxy-whitelist file not existing

**Comment by games647** [comment]
The file is created automatically once you activate BungeeCord in the configuration.

**Comment by DailyStruggle** [comment]
thanks. For anyone reading this in the future, I should probably clarify that "bungeecord" was in spigot.yml and there was also a "bungee-online-mode" in paper.yml

**Comment by games647** [comment]
Well I didn't know that neither.

**Comment by games647** [comment]
But this should only affect caching. Does it created the file only after you changed both values?

**Comment by DailyStruggle** [comment]
yes, the file is there after updating these two values. It's mostly working properly now.
