### ISSUE TITLE
NoClassDefFoundError: org/apache/commons/lang3/Validate

### ISSUE THREAD

**Issue by pegelf** [games647/FastLogin#254]
### What behaviour is observed:
I can't get logged in automatically and my skin is not shown. The Server log also shows, that the plugin seems to crash. The Server runs on 1.14.2.

### Plugin list:
LuckPerms, dynmap, SpawnerPlugin, WorldBorder, Essentials, ProtocolLib, AuthMe, FastLogin

### Environment description
Spigot 1.14.2

### Plugin version or build number (don't write latest):
premiumUUID

### Error Log:
> 14:19:32[FastLogin]: Hooking into auth plugin: AuthMeHook
> Craft Scheduler Thread - 4/WARN 06.06.2019 14:19:59
> 14:19:59[FastLogin]: Plugin FastLogin v1.11-SNAPSHOT-3c3d926 generated an exception while executing task 20
> Console 06.06.2019 14:19:59
> 14:19:59java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate
> at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) ~[?:?]
> at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
> at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
> at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
> at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
> at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibLoginSource.setOnlineMode(ProtocolLibLoginSource.java:58) ~[?:?]
> at com.github.games647.fastlogin.bukkit.listener.protocollib.NameCheckTask.requestPremiumLogin(NameCheckTask.java:55) ~[?:?]
> 14:20:00 at com.github.games647.fastlogin.bukkit.listener.protocollib.NameCheckTask.requestPremiumLogin(NameCheckTask.java:16) ~[?:?]
> at com.github.games647.fastlogin.core.shared.JoinManagement.onLogin(JoinManagement.java:35) ~[?:?]
> at com.github.games647.fastlogin.bukkit.listener.protocollib.NameCheckTask.run(NameCheckTask.java:43) ~[?:?]
> at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
> at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
> at java.lang.Thread.run(Thread.java:844) [?:?]
> Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.Validate
> at java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[?:?]
> at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
> at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
> at java.lang.ClassLoader.loadClass(ClassLoader.java:566) ~[?:?]
> at java.lang.ClassLoader.loadClass(ClassLoader.java:499) ~[?:?]
> ... 15 more
> User Authenticator #1/INFO 06.06.2019 14:20:00
> 14:20:00UUID of player pegelf is 6f14a194-c773-318f-b3f6-1c9ca3e48a9b
> Server thread/INFO 06.06.2019 14:20:00
> 14:20:00pegelf[/213.138.44.119:49501]: logged in with entity id 639 at ([lanjugend]-293.2815154962046, 139.0, -1967.7989843938597)
> Craft Scheduler Thread - 6/WARN 06.06.2019 14:20:01
> 14:20:01[FastLogin]: Plugin FastLogin v1.11-SNAPSHOT-3c3d926 generated an exception while executing task 21
> Console 06.06.2019 14:20:01
> 14:20:01java.lang.NullPointerException: null
> at com.github.games647.fastlogin.bukkit.task.ForceLoginTask.isOnlineMode(ForceLoginTask.java:70) ~[?:?]
> at com.github.games647.fastlogin.bukkit.task.ForceLoginTask.run(ForceLoginTask.java:38) ~[?:?]
> at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
> at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
> at java.lang.Thread.run(Thread.java:844) [?:?]

**Comment by gjvnq** [comment]
Same problem on 1.14.3 using PaperMC

**Comment by games647** [comment]
Update ProtocolLib to a development version. That plugin wasn't updated for 1.14 at that time.
