### ISSUE TITLE
Bug BungeeCord

### ISSUE THREAD

**Issue by Tylwen** [games647/FastLogin#255]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for duplicate issues!)

### What behaviour is observed:
[//]: # (What happened?)
When I do / premium, it's me again '/ premium [player]' and in the console 'Spigot'il nothing happens
### What behaviour is expected:
[//]: # (What did you expect?)

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
When I do / premium, it's me again '/ premium [player]' and in the console 'Spigot'il nothing happens. I disabled the discord on Spigot and it worked but once I activate it again, I still have this problem. So I suspect the problem comes from BungeeCord. I even removed all unnecessary plugins from FastLogin on Bungee and Spigot, and still have the same problem.
### Plugin list:
[//]: # (This can be found by running `/pl`)
Spigot:
PlaceholderAPi, CommandsXL, GuiCreationTool, MultiWorld, SkinsRestorer, DeluxeTags, AutoRestat, Mentions, Realistic_World, ViaVersion, EpicBanRequests, EnderCoin, LagAssist, LuckPerms, WorldEdit, ViaVersionStatus, LTItemMail, SimplePluginManager, Votifier, ProtocolLib, MVdWPlaceholderAPI, VotingPlugin, AsyncWorldEdit, Maintenance, PocketGames, TicketManager, DeluxeMenus, FeatherBoard, CalenderEvents, TitleAdvanced, WorldGuard, HolographicDisplay, lastLoginAPI, VoteParty, ChatItem, AnimatedNames, PluginLibrary, ObsidianDestroyer, AuthMe, RankSync, WildStacker, Factions, BossShop, Essentials, LeaderHeads, BetterRTP, BungeeTabListPlusBridgeBukkit, EZRankPro, Statz, JobsReborn, ServerListMOTD, Vault, MineCrypto, BustaMine, DoubleorNothing, Investment, AutoSell, SavageFTOP, Citizens, TradeMe, FastLogin.

Bungeecord:
AdvancedBan, AuthmeBungee, BReport, BungeeAliases, BungeeChatFilter, BungeeCommandSpy, BungeePAF, BungeeMail, BungeeMSG, BungeeOnlineTime, BungeeTabList, EasyBungeeServerWait, FastLogin, LuckPermsBungee, Maintenance, fakeprotocal, all addon PAF, ServerListPlus.
### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL, ...)
Spigot 1.13.2, BungeeCord 1414, MySQL
### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)

### Error Log:
[//]: # (No images please - only the textual representation)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error or stacktrace (if any)
No error in log, just repeat my command with more [player]
### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file 
Bungee : https://hastebin.com/fuyadayuga.makefile
FastLogin : https://hastebin.com/hawagofoco.http
Spigot : https://hastebin.com/ayezeqifem.sql

**Comment by games647** [comment]
Please post the startup log of BungeeCord
