### ISSUE TITLE
Get premium status API

### ISSUE THREAD

**Issue by Nubebuster** [games647/FastLogin#260]
((FastLoginBukkit) Bukkit.getPluginManager().getPlugin("FastLogin")).getStatus() is not accessible.

Could you make an API where I can get the Instance? I need this to ip-ban non premium players who are getting banned with my custom plugin.

Thanks in advance!

[edit] alternative it would be nice to have a LoginEvent.isPremium

**Comment by games647** [comment]
>((FastLoginBukkit) Bukkit.getPluginManager().getPlugin("FastLogin")).getStatus() is not accessible.

Yes it isn't you need to specify the UUID too. It's getStatus(UUID).

**Comment by Nubebuster** [comment]
> > ((FastLoginBukkit) Bukkit.getPluginManager().getPlugin("FastLogin")).getStatus() is not accessible.
> 
> Yes it isn't you need to specify the UUID too. It's getStatus(UUID).

That's not what I meant. The functions getStatus(UUID) is not accessible

**Comment by games647** [comment]
Please clarify what do you mean with not accessible. It's a public method that everyone can access.

**Comment by Nubebuster** [comment]
https://gyazo.com/c5330ae9898e3f0f35f55ed5d6fc111e

Image

**Comment by games647** [comment]
Yes, because it was only introduced in newer versions. See the Jenkins server for development builds that builds the Source Code after each commit.
