### ISSUE TITLE
How to setup SSL transport for the database connection

### ISSUE THREAD

**Issue by ham1255** [games647/FastLogin#262]
How to make it work becuase i done setting up the ssl in mysql but problem is when i enable ssl it does not connect it keep failing till i disable ssl on user on php my admin and the config

**Comment by ham1255** [comment]
i am using MariaDB

**Comment by games647** [comment]
As far as I know MariaDB doesn't require SSL transport, but it's definitely recommended if the database runs on a different server than the Minecraft host.

**Comment by ham1255** [comment]
Lol i asked how to do it since i enable the option in phpmyadmin + fl config its says wrong password in sql connection

**Comment by games647** [comment]
Well if it's authentication problem, then I couldn't help you there. Please check if the password is put into this format: 'PASS' and check if the username password combination is correct.

**Comment by ham1255** [comment]
but i still Access denied for user 'fastlogin'@'<>' (using password: YES)

**Comment by ham1255** [comment]
<> is = domain i removed
