### ISSUE TITLE
FastLogin doesn't work because of ClassNotFoundException!

### ISSUE THREAD

**Issue by IceMeltt** [games647/FastLogin#263]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for duplicate issues!)

### What behaviour is observed:
[//]: # (What happened?)
When somebody is logging in, the plugin is throwing an exception because of the Apache Commons library is not found. 

### What behaviour is expected:
[//]: # (What did you expect?)
The plugin should not throw stacktrace with the cause:

> Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.Validate

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
The player is just joining in, and the plugin is throwing an exception. Autologging doesn't work aswell.

### Plugin list:
[//]: # (This can be found by running `/pl`)
![image](https://user-images.githubusercontent.com/23281839/61408586-a7a10880-a8e0-11e9-8dfc-d45d8a0868d8.png)

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL, ...)
Minecraft version: 1.14.3
Preffered database system: SQLite
Java version: 8
Spigot version: git-Spigot-9a643a6-eb2e657 (MC: 1.14.3)

### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
![image](https://user-images.githubusercontent.com/23281839/61408892-61987480-a8e1-11e9-92f0-d9ddc422b13b.png)

### Error Log:
[//]: # (No images please - only the textual representation)
https://pastebin.com/9Aar21bD

### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
https://pastebin.com/gafLPgEN

**Comment by kristupas098** [comment]
Same error for me

**Comment by games647** [comment]
Outdated ProtocolLib version
