### ISSUE TITLE
Doesn't detect the protocollib plugin

### ISSUE THREAD

**Issue by yooniks** [games647/FastLogin#269]
FastLogin just doesn't find the protocollib plugin. (I do not use bungeecord, just spigot)
This message occurs in the console: https://github.com/games647/FastLogin/blob/master/bukkit/src/main/java/com/github/games647/fastlogin/bukkit/FastLoginBukkit.java#L95

Like you can see in the logs:

> [03:37:14] [Server thread/INFO]: [FastLogin] Enabling FastLogin v1.10-git484855724b794de1fe057cf7360245362658b432
> [03:37:14] [Server thread/INFO]: HikariPool-1 - Starting...
> [03:37:15] [Server thread/INFO]: HikariPool-1 - Driver does not support get/set network timeout for connections. (org.sqlite.Conn.getNetworkTimeout()I)
> [03:37:15] [Server thread/INFO]: HikariPool-1 - Start completed.
> [03:37:15] [Server thread/WARN]: [FastLogin] Either ProtocolLib or ProtocolSupport have to be installed if you don't use BungeeCord
> [03:37:15] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.4.0
> [03:37:15] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.

I fixed it with adding loadbefore: [ProtocolLib] and removing load: STARTUP from plugin.yml. Think about that.

**Comment by games647** [comment]
This looks like a bug, because both ProtocolLib and FastLogin have the `load: STARTUP` property and the softdepend is defined that FastLogin will load after the plugin in depends on.

What version of Spigot do you use? I tried to reproduce it using the `Spigot-798ea6a-2012f1e (MC: 1.14.4)`, ProtocolLib `4.5.0 commit 446a1c8326462df5805b25ba2818b78bc3dd1e9d` and FastLogin `1.11-SNAPSHOT-fbbe7a7`, but I had no luck. For me it worked flawlessly.

**Comment by yooniks** [comment]
That's actually not mine. Two users of my plugin send me private message that fastlogin doesn't work with my premium plugin (https://www.spigotmc.org/resources/casualprotector-best-server-protector-antibot-anticrash.59866/)
FastLogin v1.10-git484855724b794de1fe057cf7360245362658b432
git-Spigot-72c2605-251a5b6 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
Protocollib - just v4.4.0

When the first user told me about that i didn't take it seriously but when more users told me about this issue i decided to make a issue here. Maybe it should be 4.5.0 version (but it's only recommended on 1.14 mc I think)

**Comment by games647** [comment]
What plugin.yml do you have now in your plugin? Do you do any kind of heavy reflections that could alter the behavior here? Does it also happen without your plugin?

I tried it now with 

* ProtocolLib 4.4.0 
* `git-Spigot-de459a2-51263e9 (MC: 1.10.2)`
* FastLogin 1.10

**Comment by yooniks** [comment]
> What plugin.yml do you have now in your plugin? 
If you mean fastlogin, it's this:
`# project data for Bukkit in order to register our plugin with all it components
# ${-} are variables from Maven (pom.xml) which will be replaced after the build
name: FastLogin
version: 1.11-SNAPSHOT
main: com.github.games647.fastlogin.bukkit.FastLoginBukkit

# meta data for plugin managers
authors: [games647, 'https://github.com/games647/FastLogin/graphs/contributors']
description: "Automatically login premium (paid accounts) player on a offline mode server"

# Load the plugin as early as possible to inject it for all players
#load: STARTUP

# This plugin don't have to be transformed for compatibility with Minecraft >= 1.13
api-version: 1.13

loadbefore: [ProtocolLib]

softdepend:
    # We depend either ProtocolLib or ProtocolSupport
    - ProtocolSupport
    - ProtocolLib
    - PlaceholderAPI

commands:
    fastlogin:
        description: 'Label the invoker as premium'
        aliases: [prem, premium, loginfast]
        usage: /<command> [player]
        permission: fastlogin.command.premium
    cracked:
        description: 'Label the invoker or the player specified as cracked if he was marked premium before'
        aliases: [unpremium]
        usage: /<command> [player]
        permission: fastlogin.command.cracked
permissions:
    fastlogin.command.premium:
        description: 'Label themselves as premium'
        default: true

    fastlogin.command.premium.other:
        description: 'Label others as premium'
        children:
            fastlogin.command.premium: true
    fastlogin.command.cracked:
        description: 'Label themselves as cracked'
        default: true
    fastlogin.command.cracked.other:
        description: 'Label others as cracked'
        children:
            fastlogin.command.cracked: true`
If you mean casualprotector:
`depend: ['ProtocolLib']
loadbefore: ['ProtocolLib', 'AdvancedEnchantments', 'MyItems', 'FastLogin']`
It doesn't happen without my plugin. I just register the packet listeners like window click, block place etc. (i also do http request (not async) that takes about 1-2 seconds to send and read just to check the license and version).

**Comment by games647** [comment]
Yes I meant your plugin. 

If you register a packet listener why do you load want your plugin to be loaded before it. Then your plugin should register them after ProtocolLib has started. And you cannot have depend and loadbefore at the same time, because according to [this](https://github.com/bergerkiller/CraftSource/blob/e77a0c6f9d5fe3c752d5740ec4facd63b4a29b0f/org.bukkit/plugin/SimplePluginManager.java#L260). Dependencies should be loaded before.

**Comment by yooniks** [comment]
loadbefore list has plugins that should be loaded before my plugin. i need it because im checking if the plugins has been loaded before and i print info or do some things

**Comment by games647** [comment]
No I think you misunderstood that part. It means that your plugin loads before these plugins (Source: https://bukkit.gamepedia.com/Plugin_YAML). What you describe is what depend and softdepend already does.

**Comment by yooniks** [comment]
Thats funny😆
https://bukkit.gamepedia.com/Plugin_YAML/pl
i have read it (it's in my language, polish) and it has mistake. In my language it means that it's list of plugins that should be loaded BEFORE my plugin. 
Anyway, i don't think its my plugin problem at all

**Comment by games647** [comment]
Using Google Translate, this sounds like a wrong description. However the comments seems to be correct. 

> Treated like this, plugins weakly dependent on yours.

Meaning that your plugin will load before the listed ones.

**Comment by yooniks** [comment]
I have already removed the "loadbefore" list from my plugin.yml and it works fine with fastlogin, thanks! I don't know why it's wrong described at bukkit.gamepedia =/ I used to think about 'loadbefore' working like the description says.
