### ISSUE TITLE
New player is getting timed out, and kicked when joining

### ISSUE THREAD

**Issue by yashendra2797** [games647/FastLogin#274]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for duplicate issues!)

### What behaviour is observed:
[//]: # (What happened?)
Player who owns the game joins for the first time. His ping stays at 0, and then he gets kicked.

### What behaviour is expected:
[//]: # (What did you expect?)
Player is automatically logged in, like many others before, and after him.

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
Nothing. The player just joins, and after a few seconds gets kicked without ever being logged in.

### Plugin list:
[//]: # (This can be found by running `/pl`)
https://i.imgur.com/0hZO89t.png

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL, ...)
Paper version git-Paper-187 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
AuthMe-5.6.0-SNAPSHOT.jar (#2307)
FastLoginBukkit.jar (#860)
### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)

### Error Log:
[//]: # (No images please - only the textual representation)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error or stacktrace (if any)
https://gist.github.com/yashendra2797/05868b9fe8d3713592ec3e6921e22053

### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file 
[AuthMe config.yml](https://gist.github.com/yashendra2797/4b70f90202fd8420d81eedcd60683b5c)
[FastLogin config.yml](https://gist.github.com/yashendra2797/5d18ba1be1995fb0f25226dc295bffab)

**Comment by 7wOv6ySCjo** [comment]
Hey @yashendra2797 you solved this?

**Comment by yashendra2797** [comment]
I don't know, cause the player never joined again.

**Comment by games647** [comment]
Time out doesn't mean that a player was kicked. It only means the server doesn't heard anything from that connection anymore and therefore closed it. This can happen if the launcher crashed or game was closed abruptly (computer shutdown, process killed, ...). This doesn't really seem related to FastLogin at all.

**Comment by yashendra2797** [comment]
I'm not trying to revive a 6 month old issue, but the player wasnt facing the issue when FL was disabled. However we've had several version changes since then, and that player stopped coming online, so this issue is probably a fluke.
