### ISSUE TITLE
FastLogin looks like not working. Autologin, premium uuid and skin forward not working.

### ISSUE THREAD

**Issue by SviFeX** [games647/FastLogin#284]
### What behaviour is observed:
Premium player do not login automaticly and skin is not forwarded. Auto login is not working with any login plugins. Tested plugins with "successful hook": AdvancedLogin, LoginSecurity, UltraAuth, CrazyLogin.

### What behaviour is expected:
Find solution, fix problem or help with configuration.

### Steps/models to reproduce:
Run server and login as premium player.

### Plugin list:
Plugins (30): LuckPerms, CommandAliasPlus, WorldEdit, OpenInv, Essentials, PlaceholderAPI, PlugMan, PlayTime, Multiverse-Core, WorldGuard, **ProtocolLib**, Holograms, PowerlessLamps, DeathMessagesPrime, CustomJoinMessage, AutoSaveWorld, SkinsRestorer, OldCombatMechanics, TabList, ConsoleSay, Multiverse-Inventories, EssentialsChat, EssentialsGeoIP, HungerGames, Multiverse-Portals, EssentialsSpawn, TheTime, **FastLogin**, **AdvancedLogin**

Tested also on clean spigot 1.14.4 with only login plugins, fast
login and protocollib.

### Environment description
git-Spigot-56f8471-eafd742 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

### Plugin version or build number (don't write latest):
Fastlogin: 1.10-git484855724b794de1fe057cf7360245362658b432
AdvancedLogin: 3.9
ProtocolLib: 4.4.0

### Error Log:
No errors log but: [latest.log](https://gist.github.com/SviFeX/f3a3c4aa9eaf1f1d527a975d9221868a)

### Configuration:
[FastLogin](https://gist.github.com/SviFeX/4d96030f797e8cd0422dba70308ce1b7)

**Comment by LoneDev6** [comment]
Did you try using latest [protocollib ](http://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/)and latest [Paper](https://papermc.io/)?

**Comment by SviFeX** [comment]
Fixed by newest dev version of Protocolib.
