### ISSUE TITLE
[Bug/Limitation] Premium UUID when user is offline

### ISSUE THREAD

**Issue by LoneDev6** [games647/FastLogin#285]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for duplicate issues!)

### What behaviour is observed:
[//]: # (What happened?)
UUID is not replaced to premium when plugins call getUniqueId on offline player.
So plugins will get a different UUID if they get UUID when user is offline.

### What behaviour is expected:
[//]: # (What did you expect?)
A way to allow plugins that need to get UUID to get the same UUID when user is online and offline

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)

Call this code when user is online and after user is logged out: System.out.println(Bukkit.getOfflinePlayer("LoneDev").getUniqueId().toString());

User must be premium and "premiumUuid" option of FastLogin must be set to true

### Plugin list:
[//]: # (This can be found by running `/pl`)
Authme and FastLogin

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL, ...)
1.14.4, Paper

### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
git-Paper-209

### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)

https://hasteb.in/ogahaqan.yaml

**Comment by LoneDev6** [comment]
Bump

**Comment by LoneDev6** [comment]
For example this plugin is not working when a premium user is offline because it takes offline UUID which is wrong.
https://dev.bukkit.org/projects/openinv

**Comment by games647** [comment]
If the player is logged in using an premium connection and `premiumUUID` is enabled, then the premium UUID will be returned on `getUniqueId()`. However if the server is in offline mode (`onlinemode` setting), the server will use the UUID based on the player name in offline mode except BungeeCord is also enabled, then it will first try search the cache.

**Comment by LoneDev6** [comment]
So it's a spigot bug? I mean, spigot MUST check on its cache (or implement UUID caching system).
But Bungeecord has UUID caching system?

If it's like that you should add this to FAQ, it's really important to avoid confusion

**Comment by games647** [comment]
Sorry if that was misleading. No it's not bug of Spigot. I think everything works as it should. For Spigot either onlinemode or offlinemode exists. Mixed onlinemode isn't really supported.

> I mean, spigot MUST check on its cache (or implement UUID caching system).

It does if the server is either in onlinemode or uses BungeeCord. Otherwise file access is redundant, because offlinemode UUIDs are only dependent on the case sensitive username. 

>But Bungeecord has UUID caching system?

No, Spigot has. Sorry if that was misleading.

>If it's like that you should add this to FAQ, it's really important to avoid confusion

I just found that out, but yes you are right.

**Comment by LoneDev6** [comment]
Thanks a lot!
I think we could try to hook/patch the original Spigot method **getUniqueId** to return premium UUID when premium user is not ingame (and FastLogin is loaded, obv).
I don't really know if it's possible to edit bytecode at runtime or to detour a function while Spigot is running.

**Comment by games647** [comment]
There are multiple reasons against it. Sorry to say that.

- Compatibility: 
    Some plugins could expect offline mode -> always offline UUID. 
    **Every new Spigot version could break this plugin or vice versa.**
- Performance: Proxies, ByteCode manipulation, Reflection, ... always has a performance penalty. Especially in the login process, you don't want any bottlenecks.
- Complexity: Hooking so deeply in the Minecraft server is very complex and requires a lot of steps. One of the easiest solutions would be ByteCode maniupulation, but this doesn't work Java 9+. Although most servers run Java 8, it's not really a future proof solution.

**Comment by LoneDev6** [comment]
Thanks for the clarification!
I edited my plugins to cache UUIDs in files, I hope also other plugins will do the same.
