### ISSUE TITLE
MySQL weird O.o

### ISSUE THREAD

**Issue by checkplys** [games647/FastLogin#29]
Well, the console says this:
![image](https://cloud.githubusercontent.com/assets/9268058/16540722/510eaa26-4066-11e6-826f-8d82103186a9.png)

but...
```
driver: com.mysql.jdbc.Driver
host: 5.196.78.91
port: 3306
database: ----------
username: -------
password: -----------
```

**Comment by games647** [comment]
Didn't it worked for you yesterday?

**Comment by checkplys** [comment]
Yes

**Comment by games647** [comment]
It looks like your username-password combination is wrong.

**Comment by checkplys** [comment]
I found the error, my host was with some bugs, and I think the config was "rollbacked" and the mysql IP was the ftp one again, like yesterday.

**Comment by checkplys** [comment]
Fixed
