### ISSUE TITLE
Disable bungeecord "slave mode" manually

### ISSUE THREAD

**Issue by LoneDev6** [games647/FastLogin#291]
Please add a setting to disable bungeecord auto detection and disable auto switch to "slave mode"

**Comment by games647** [comment]
Could I ask for the motivation behind this? Because if BungeeCord support is disabled while using BungeeCord, the plugin will request an online mode connection between BungeeCord and Spigot which isn't possible.

**Comment by LoneDev6** [comment]
No problem, I found out this wouldn't work as server would result to be in online mode after this modification, so bungeecord would kick the user.
Thanks!

Also please if you find the time, check my other ticket, it's a really bad bug that keeps hunting my players https://github.com/games647/FastLogin/issues/288
Sometimes (it's completely random) my players are turned into cracked and they can't join as they are asked to enter a password (AuthMe). Only way to fix is to use /premium from console
