### ISSUE TITLE
Very rare chance of a premium player always being counted as cracked

### ISSUE THREAD

**Issue by Govindass** [games647/FastLogin#294]
I don't remember if I have posted this issue in the past, but I have been having this issue for probably years now with FastLogin
### What behaviour is observed:
There is a very rare chance of a premium player to be counted as cracked and even if they relog many times, to still be counted that way, while it works for other players, this has happened to my account personally a few times and to a few of my players.

I have developed my own fix for this, by using Skript to insert data into MySQL database, it gets fixed when I insert data of player as premium into the fastlogin table. In my server cracked players are forced to use names starting with "-" character, so I can easily tell which player is cracked and which is not, so my automatic fix can work well in this environment, but for others, this could be critical.

I have failed to find an exact way to reproduce this problem over the years, it just happens, very rarely, but happens.

### Environment description
happened both when I didn't use bungeecord and when I started using it.
FastLogin: 1.11-SNAPSHOT-2c7e569
mysql:  Ver 15.1 Distrib 10.1.41-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
(I have had the same problem with a mysql v5, not only mariadb issue)
server software: Paper version git-Paper-1618 (MC: 1.12.2)

### Plugin version or build number (don't write latest):
happened through many FastLogin versions, including the current one I'm using, 1.11-SNAPSHOT-2c7e569

### Error Log:
I don't know if there's any, but I never noticed anything on this kind of situation erroring and I'd say I check for errors often enough.

### Configuration:
 https://pastebin.com/raw/tdn9Zcrj

**Comment by games647** [comment]
So it happens even if your account was saved as premium before?

**Comment by Govindass** [comment]
> So it happens even if your account was saved as premium before?

yes and after manually fixing it, it happened again after multiple months, has happened for a few players also, one of them being a staff of mine

**Comment by games647** [comment]
In case of BungeeCord it could be fixed by https://github.com/games647/FastLogin/commit/5a5cf016d9c01c0d4e8a1757429ef0e283ee6988

**Comment by Govindass** [comment]
you could remove BungeeCord tag since this happened before I started using it too, but I will try to update, but I don't think I'll be able to tell if it is fixed soon, I will try to make some logging system which will let me know if a problem like this happened again

**Comment by gabriel262m** [comment]
I have the same issue, the plugin dont read me like a premium player and im in the list.
In my test server all works fine, i delete the plugin 5 times and nothing...

**Comment by TheCompieter** [comment]
i also have this issue with this plugin that's the reason why i stopped using it im really greatfull if this were to get fixed

**Comment by Govindass** [comment]
closing this as there hasn't been a problem for over a month after using latest dev build, not 100% sure if fixed, but I'll re-open if it appears again.

**Comment by jusobreira** [comment]
> I have the same issue, the plugin dont read me like a premium player and im in the list.
> In my test server all works fine, i delete the plugin 5 times and nothing...

I'm heaving this issue to..

**Comment by TheCompieter** [comment]
i am no longer having this issue with the latest build as far as i know.
so try the latest build and if you use normal mysql maybe try mariadb.
