### ISSUE TITLE
Strange error :D

### ISSUE THREAD

**Issue by 7h3ev1l** [games647/FastLogin#3]
I translated this to my language but i cant compile/package it.
`[ERROR] Failed to execute goal on project fastlogin.bukkit: Could not resolve dependencies for project com.github.games647:fastlogin.bukkit:jar:0.5: Failed to collect dependencies for [org.spigotmc:spigot-api:jar:1.8.8-R0.1-SNAPSHOT (provided), com.comphenix.protocol:ProtocolLib:jar:3.6.5-SNAPSHOT (compile?), protcolsupport:ProtocolSupport:jar:Build-337 (system), fr.xephi:authme:jar:5.2-SNAPSHOT (compile?), com.github.lenis0012:LoginSecurity-2:jar:-9c09e73b7f-1 (compile), com.github.RoyalDev:RoyalAuth:jar:-e21354a9b7-1 (compile), de.luricos.bukkit:xAuth:jar:2.6 (compile?), de.st_ddt.crazy:CrazyCore:jar:10.7.7 (system?), de.st_ddt.crazy:CrazyLogin:jar:7.23 (system?)]: Failed to read artifact descriptor for ru.tehkode:PermissionsEx:jar:1.22.7: Could not transfer artifact ru.tehkode:PermissionsEx:pom:1.22.7 from/to pex-repo (http://pex-repo.aoeu.xyz/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1] `

I tried to add protocollib but nothing happen.

**Comment by games647** [comment]
> unable to find valid certification path 

Looks like the repository from permissions ex makes issues.

**Comment by games647** [comment]
I hope this fixes it.

**Comment by scarabcoder** [comment]
Getting this error.
@dyanakiev It's been a year, did you ever find a way around it?
