### ISSUE TITLE
Server Is Online Mode

### ISSUE THREAD

**Issue by checkplys** [games647/FastLogin#30]
// I know I'm creating a lot of issues, but, IDK wtf is happening

in the server.proprieties online mode is false, but....
![image](https://cloud.githubusercontent.com/assets/9268058/16540777/ea8908bc-4067-11e6-8cfb-2a049d897a0f.png)

**Comment by games647** [comment]
You have to activate BungeeCord support

**Comment by Eufranio** [comment]
nossa q burro

**Comment by games647** [comment]
Please speak english.
