### ISSUE TITLE
ProtocolLib not detected

### ISSUE THREAD

**Issue by BrayaanPS** [games647/FastLogin#306]
# What behaviour is observed:
a premium user when entering the server does not log in automatically

### What behaviour is expected:
you must log in automatically as they have premium login activated

### Problem message:
https://hastebin.com/zatoveriqu.css

### Screenshots (if applicable)
https://youtu.be/jiY8GgXtJ-Q

### Plugin list:
Authme, [BPS](https://www.spigotmc.org/resources/%E2%AD%90bps-premium-%E2%9A%A1-supports-1-8-8-1-15-bungee-cord-mysql-%E2%AD%90.67158/), LuckPerms, ProtocolLib, Vault, Fastlogin

### Environment description
Using: Paper 1.15.2 (126)

### Plugin version or build number (don't write latest):
1.11-SNAPSHOT

### Server Log:
https://hastebin.com/asagayalor.md

### Configuration:
https://hastebin.com/uvuguheguz.makefile

**Comment by games647** [comment]
Although my last commit fixed it. It's still a better solution to keep the original behavior. Unfortunately I'm completely unable to reproduce it locally. Even using all the same versions except the paid plugin. Could you maybe test this build: https://github.com/games647/FastLogin/releases/tag/dependency
and post the server log output.

**Comment by BrayaanPS** [comment]
If it works now, thank you very much!
it already enters you as it should be.

**Comment by games647** [comment]
Yes, but could check the build on the link nevertheless, so I could check what went wrong in the first place.
