### ISSUE TITLE
UnknownHostException: sessionserver.mojang.com

### ISSUE THREAD

**Issue by heraqu** [games647/FastLogin#308]
Hello, once in a while there is a problem logging in to the server from a premium account. Failed session error pops up. What could be the problem? I have AuthMe. Config server.properties set correctly.

**Comment by games647** [comment]
Then it's a bug not a question. So I especially need the error log. You can follow the template form here: https://raw.githubusercontent.com/games647/FastLogin/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by heraqu** [comment]
---
name: Bug report
about: When entering the server: https://i.imgur.com/Q7uuF8B.png
title: ''
labels: 'bug'
assignees: ''

---

The error is that when I enter the server it is "Invalid session" error. I have a premium account. I have used authme, loginsecurity and it is still the same error. What could be the problem?

### Plugin list:
https://i.imgur.com/e3vSdnu.png

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)

### Plugin version or build number (don't write latest):
I have the latest plugins, I downloaded them from the official spigot website:
I can't give screenshots with / version because I can't get to the server "Invalid Session" error
                            
FastLogin: FastLogin 1.10   	
LoginSecurity: LoginSecurity 3.0.1

### Server Log:
https://i.imgur.com/0puR7hs.png
https://gist.github.com/heraqu/fa994eea8f098856a1c1e28daf167889

### Configuration:
https://gist.github.com/heraqu/649f56c3d179e61f98ca7bb7ee9ca5f9

**Comment by games647** [comment]
>.UnknownHostException: sessionserver.mojang.com

This means the IP address of the Mojang cannot be found. Please check your DNS settings. This error would also occur on onlinemode servers.

**Comment by heraqu** [comment]
We have online = false and this happens to everyone, not just me.

**Comment by games647** [comment]
>We have online = false

No I meant it would also happen for **if** your server were in onlinemode. The error you are getting means the server cannot resolve the domain address `sessionserver.mojang.com` to an IP address that computers use to communicate with each other. DNS servers are responsible to resolve the addresses. Your server tries to ask the DNS server for the IP addresses. So either your Spigot server host is misconfigured (uses no or incorrect DNS server settings) or your DNS server you configured is faulty.

**Comment by Ariel0110** [comment]
WARN Failed to verify session
23.05 16:40:35 [Server] INFO org.json.simple.parser.ParseException
23.05 16:40:35 [Server] INFO at org.json.simple.parser.JSONParser.parse(JSONParser.java:257) ~[Spigot-1.8.8.jar:git-Spigot-76236cb-9cd1111]
23.05 16:40:35 [Server] INFO at org.json.simple.parser.JSONParser.parse(JSONParser.java:81) ~[Spigot-1.8.8.jar:git-Spigot-76236cb-9cd1111]
23.05 16:40:35 [Server] INFO at org.json.simple.parser.JSONParser.parse(JSONParser.java:75) ~[Spigot-1.8.8.jar:git-Spigot-76236cb-9cd1111]
23.05 16:40:35 [Server] INFO at org.json.simple.JSONValue.parseWithException(JSONValue.java:78) ~[Spigot-1.8.8.jar:git-Spigot-76236cb-9cd1111]
23.05 16:40:35 [Server] INFO at com.github.games647.fastlogin.bukkit.MojangApiBukkit.hasJoinedServer(MojangApiBukkit.java:47) [FastLogin%20(2).jar:?]
23.05 16:40:35 [Server] INFO at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.verifyResponse(VerifyResponseTask.java:84) [FastLogin%20(2).jar:?]
23.05 16:40:35 [Server] INFO at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.run(VerifyResponseTask.java:54) [FastLogin%20(2).jar:?]
23.05 16:40:35 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [Spigot-1.8.8.jar:git-Spigot-76236cb-9cd1111]
23.05 16:40:35 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [Spigot-1.8.8.jar:git-Spigot-76236cb-9cd1111]
23.05 16:40:35 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
23.05 16:40:35 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
23.05 16:40:35 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
I have the same problem and this is the error in console , Please , how Do I fix it?
Idk what's dns settings so can you please tell me how to fix it step by step? Thanks.
@games647

**Comment by games647** [comment]
@Ariel0110 #325

**Comment by Ariel0110** [comment]
I did that , But now when I log in with a new premium account , I got no skin and I have to register Unless I do /premium 
also even after I do /premium I still got no skin , It auto logs me in , But dosen't give me my skin.

**Comment by games647** [comment]
@Ariel0110 

>Unless I do /premium
also even after I do /premium I still got no skin , It auto logs me in , But dosen't give me my skin.

If the check failed, you are saved as a cracked player, so you could still join the server if something went wrong. Therefore you have to activate it manually using the command. Skin settings depends on your server platform, so please open a new issue with the data requested from the template.
