### ISSUE TITLE
sending request never ends (all steps from the guide are done)

### ISSUE THREAD

**Issue by Fabri4K** [games647/FastLogin#309]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: # (first of all, my english is not very good so sorry if some phrases doesnt make any sense) When i try to execute /premium it says Sending request... and it never ends

### What behaviour is expected:
[//]: # i wanted it to say done and be able to connect without having to enter the password

### Steps/models to reproduce:
[//]: # I did every step in the bungeecord guide and when i use /premium it says that

### Screenshots (if applicable)
[//]: # https://imgur.com/a/NYoe1xV

### Plugin list:
[//]: # LuckPerms, PlaceholderAPI, DisableJoinMessage, jBossBar, NameTagEdit, BuycraftX, Multiverse-Core, VoidSpawn, SkinsRestorer, FastAsyncWorldEdit, VoidGenerator, SOJ, ViaVersion, Tablist, Vault, WorldEdit, Essentials, VaultChatFormatter, Protocolib, WorldGuard, BungeePortals, EssentialsProtect, EssentialsChat, EssentialsAntiBuild, EssentialsSpawn, FastLogin, AuthMe, HolographicDisplays

### Environment description
[//]: # Im running the plugin in bungeecord but i also put the plugin in the login spigot 1.8.8 server

### Plugin version or build number (don't write latest):
[//]: # Version 1.10

### Server Log:
[//]: # There's no actual error, in the console, when i try to use /premium, the console doesnt says anything

### Configuration:
[//]: # https://pastebin.com/tabpAvGq

**Comment by games647** [comment]
># There's no actual error, in the console, when i try to use /premium, the console doesnt says anything

Then just post the log anyway. Please post the BungeeCord server log too.

**Comment by Fabri4K** [comment]
Oh wait, now that i see, there is an error in the bungeecord when i start it.
 Bungeecord logs:
https://pastebin.com/KSvzeiUQ
Login spigot server logs:
https://pastebin.com/b4a3JdvW

**Comment by Fabri4K** [comment]
> > There's no actual error, in the console, when i try to use /premium, the console doesnt says anything
> 
> Then just post the log anyway. Please post the BungeeCord server log too.

Oh wait, now that i see, there is an error in the bungeecord when i start it.
 Bungeecord logs:
https://pastebin.com/KSvzeiUQ
Login spigot server logs:
https://pastebin.com/b4a3JdvW

**Comment by games647** [comment]
Well then you didn't followed the last step. It means there that there is no SQLite driver in BungeeCord and you didn't configured the plugin to MySQL/MariaDB.

**Comment by Fabri4K** [comment]
ohh i thought it was optional

**Comment by Fabri4K** [comment]
Hi again, there is a tutorial for this plugin? because idk what to do right now, i copied the org folder into the bungeecord but now i dont know what to do. where is the changeskin config?

**Comment by games647** [comment]
>where is the changeskin config?

You meant for activating the premium skin? It's a configuration option which is enabled by default

>because idk what to do right now, i copied the org folder into the bungeecord but now i dont know what to do

This plugin only enables premium logins if the command is activated or you enable the autoRegister option for new players.

**Comment by Fabri4K** [comment]
I mean, i did all this steps for the sqlite support:
1-Download the SQLite driver .jar from here: https://bitbucket.org/xerial/sqlite-jdbc/downloads
2-Open your BungeeCord/Waterfall jar with any archiver program
3-Open the SQLite driver with any archiver program
4-Copy the contents (the "org"-folder) from the SQLite driver to BungeeCord

But i dont know what the fifth step means or how to do it:
5-Now just use the SQLite settings in the ChangeSkin config.

**Comment by Fabri4K** [comment]
OHH I DID IT! I never made a mysql and add sqlite support to the bungeecord so im really happy that its working now! yay!! thank you for the great support (i know im stupid so sorry for that)
