### ISSUE TITLE
AutoLogin not working after Auto Registering Premium user

### ISSUE THREAD

**Issue by Maxetto** [games647/FastLogin#310]
# What behaviour is observed:
[//]: # (What happened?)
Sometimes, when a new Premium player  joins, it gets auto-registered but not auto-logged in, even though in AuthMe's config there's no requirement to login after registration.

### What behaviour is expected:
[//]: # (What did you expect?)
New Premium players always have to be registered and logged in automatically.

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
Join server as a Premium user without being neither in AuthMe and FastLogin database.

### Plugin list:
[//]: # (This can be found by running `/pl`)
LuckPerms, WorldEdit, PlugMan, CrackShot, SuperCensor, BimmCore, ConsoleSpamFix, WorldGuard, Multiverse-Core, ViaVersion, Vault, Essentials, ProtocolLib, Citizens, iDisguise, ChestCommands, EssentialsChat, McInfected, EssentialsSpawn, McInfectedDedicated, AuthMe, Matrix, McInfectedLobbyItems, HolographicDisplays, McInfectedRanks, FastLogin

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
Paper version 1.8.8 (git-PaperSpigot-"4c7641d")
MariaDB 10.3.22
AuthMe 5.6.0-SNAPSHOT-b2385
ProtocolLib 4.5.0

### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
FastLogin 1.11-SNAPSHOT-8ecb565

### Server Log:
[//]: # (No images please - only the textual representation)
https://hastebin.com/mapixurudi.md

### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
AuthMe: https://hastebin.com/ohisotiwam.bash
FastLogin: https://hastebin.com/edinejuhar.makefile

**Comment by Maxetto** [comment]
Might be happening if the player was joined before, but when the server was in Online Mode.

**Comment by games647** [comment]
This could be because of session event we are canceling. Could you try this build: https://github.com/games647/FastLogin/releases/tag/authme-session

Then AuthMe could create duplicate login messages, but I wont cancel that event.

**Comment by Maxetto** [comment]
Unfortunately the issue is still happening.
Seems to happen easily if 2 or more people join together.

**Comment by Maxetto** [comment]
I think I may have found the issue. AuthMe's SALTEDSHA512 algorithm does not work.

**Comment by Maxetto** [comment]
Definitely an AuthMe issue. Sorry for bothering. Happened with an SP player.
