### ISSUE TITLE
Support for Velocity Proxy

### ISSUE THREAD

**Issue by Patbox** [games647/FastLogin#311]
[//]: # (Lines in this format are considered as comments and will not be displayed.)

### Is your feature request related to a problem? Please describe.
[//]: # (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])
Support for Velocity Proxy software. It isn't compatible with Bungee plugins, so I can't use FastLogin with it.
### Describe the solution you'd like
[//]: # (A clear and concise description of what you want to happen.)
Port FastLogin(Bungee) to Velocity
### Describe alternatives you've considered
[//]: # (A clear and concise description of any alternative solutions or features you've considered.)
There's no alternatives, if you want to use Velocity

**Comment by 7wOv6ySCjo** [comment]
Yes. We need this. Velocity it's better than Waterfall and BungeeCord.

**Comment by iamceph** [comment]
I starter working on this, will post update later :)

**Comment by 7wOv6ySCjo** [comment]
Any news about veloticy support?

**Comment by MoonSoD** [comment]
Curious aswell, looking forward to it.

**Comment by Govindass** [comment]
I am also interested in this

**Comment by iamceph** [comment]
Sadly, I did not had time. I will be working on this next month

**Comment by iamceph** [comment]
This feature requires refactoring the whole plugin as the core itself is depend on bukkit/bungee libraries. I am thinking about doing that, but I don't know if the owner would like that.
I foked this repo and I am starting working on this. I will actually try to make a PR to make that official :)

**Comment by 7wOv6ySCjo** [comment]
Why the author @games647 doesn't give us an official and concrete answer about adding support to Velocity? Is there some kind of internal problem with the creator of Velocity?
How unprofessional, I'm disappointed.

**Comment by Govindass** [comment]
> 
> 
> Why the author @games647 doesn't give us an official and concrete answer about adding support to Velocity? Is there some kind of internal problem with the creator of Velocity?
> How unprofessional, I'm disappointed.

I mean no one pays the creator for this, it's just a public free plugin, that is also open-source, so you can add Velocity support yourself

**Comment by iamceph** [comment]
Yeah, this has nothing to do with author. Velocity was not a thing when FastLogin was created. It needs complete rewrite to support Velocity.

**Comment by kubo6472** [comment]
> 
> 
> Yeah, this has nothing to do with author. Velocity was not a thing when FastLogin was created. It needs complete rewrite to support Velocity.

https://forums.velocitypowered.com/t/snap-run-bungeecord-plugins-on-velocity/608
have not tested yet

**Comment by games647** [comment]
>doesn't give us an official and concrete answer about adding support to Velocity? I

I followed the development of Velocity closely till today. At the beginning there were too many breaking changes. A few months ago, I took another look. I got the idea to start working on it for Velocity 2.0. However after this [announcement](https://forums.velocitypowered.com/t/an-unfortunate-update-on-2-0-0-and-an-exciting-announcement/772), plans have shifted. 

So I'm now working towards implementing support for 1.1.X. However there are a few things I want to make to ensure future versions are easier to test, so changes can be made with less manual testing. The current plan is the following:

1. Add integration tests: automatic testing environment of authentication process
2. Separate major optional features into modules: ProtocolLib vs ProtocolSupport, etc
3. Add velocity support

Velocity support won't be that complicated, because the proxy logic is rather minimal in comparison to Spigot. Nevertheless adding a new platform always adds more maintenance work.

Side note: I now understand that I should post more status updates. I was a little overwhelmed recently, so I took only the small steps like assign labels, give short answers, close, etc. I think this is something I need to change here.

**Comment by kubo6472** [comment]
> https://forums.velocitypowered.com/t/snap-run-bungeecord-plugins-on-velocity/608
~~have not tested yet~~

It works and I am using it since. Just thought I should let you know.

**Comment by games647** [comment]
@kubo6472 Thanks that's good to know. However I guess `premiumUUID=false` doesn't work?

**Comment by 7wOv6ySCjo** [comment]
> > https://forums.velocitypowered.com/t/snap-run-bungeecord-plugins-on-velocity/608
> > ~have not tested yet~
> 
> It works and I am using it since. Just thought I should let you know.

I had a false positive with AuthMeBungee on Snap.
(The player skipped the "Authentication required" event, yes, after that I immediately had to go back to BungeeCord).

I know it has nothing to do with FastLogin but they do go hand in hand.

The second reason I don't trust Snap is that the dev doesn't seem to be willing to fix a bug or add a needed feature.

**Comment by 7wOv6ySCjo** [comment]
> > doesn't give us an official and concrete answer about adding support to Velocity? I
> 
> I followed the development of Velocity closely till today. At the beginning there were too many breaking changes. A few months ago, I took another look. I got the idea to start working on it for Velocity 2.0. However after this [announcement](https://forums.velocitypowered.com/t/an-unfortunate-update-on-2-0-0-and-an-exciting-announcement/772), plans have shifted.
> 
> So I'm now working towards implementing support for 1.1.X. However there are a few things I want to make to ensure future versions are easier to test, so changes can be made with less manual testing. The current plan is the following:
> 
> 1. Add integration tests: automatic testing environment of authentication process
> 2. Separate major optional features into modules: ProtocolLib vs ProtocolSupport, etc
> 3. Add velocity support
> 
> Velocity support won't be that complicated, because the proxy logic is rather minimal in comparison to Spigot. Nevertheless adding a new platform always adds more maintenance work.
> 
> Side note: I now understand that I should post more status updates. I was a little overwhelmed recently, so I took only the small steps like assign labels, give short answers, close, etc. I think this is something I need to change here.

Thank you very much for taking the time to respond. We value that these days. Thank you.
