### ISSUE TITLE
Verify if login was done over Bungee or over direct connect

### ISSUE THREAD

**Issue by Kongolan** [games647/FastLogin#316]
Sometimes and it's still possible and for my case preferred that some players don't login over the Bungee connection. For Authme it does protect the account like this still (the handshake and call over Bungee is different).

Case 1: Connect over Bungee - works as intended autologin + skin fetching
Case 2: Using direct IP + port - FastLogin will do nothing, no functionality at all.

Is it possible to check and have functionality on both cases when Bungee mode is actually on in spigot.yml?

**Comment by games647** [comment]
That also applies to servers without FastLogin. You should always put your Spigot protected behind a firewall. BungeeCord wiki mentions that in numerous places and even FastLogin mentions it in the setup guide.

**Comment by Kongolan** [comment]
Well, I have a specific use case where this I want to connect to the bungeed servers directly, instead of going over the Bungee.

**Comment by games647** [comment]
This allows to fake a BungeeCord proxy. Then players could inject custom uuids and ip addresses. It's not really safe do something like that.
