### ISSUE TITLE
Sending requst error

### ISSUE THREAD

**Issue by abhiram555** [games647/FastLogin#317]
when i do /premium it dosnt work its like sending requst and i have error in buangeecord my minecraft server host said to ask devloper to fix plugin 
![image](https://user-images.githubusercontent.com/63419731/78925462-13ec1980-7ab9-11ea-9419-af2ed0a374a3.png)

**Comment by abhiram555** [comment]
i fixed this but still Sending request but it adding name to mysql

**Comment by games647** [comment]
The original error means, that the plugin cannot connect to the MySQL server and therefore the plugin couldn't startup fully.

**Comment by abhiram555** [comment]
hmm i fixed that still sending request
and no asking for login / register i am using 1.15.2 but the plugin is for 1.12.2 and some listener error and i fixed it now its updated(no errors for 1.15.2) i edited your code to fix this is that okey? i mean is this open source or not?

**Comment by abhiram555** [comment]
and my old sql infomation was correct the error solved when i update sql driver

**Comment by games647** [comment]
> i mean is this open source or not?

That's the idea of Open Source. 

* Learn from it
* Contribute your own changes
* Make something new
* ...

However I wonder why you posted that the plugin is for 1.12.2. It supports all versions above 1.8.

**Comment by abhiram555** [comment]
yea i mean it support 1.8.8 to 1.12.12 not 1.15.2 so there was a listener
error and i fixed it now it work fine for 1.15.2

**Comment by games647** [comment]
Why do you think that? It also tested on 1.15.2

**Comment by abhiram555** [comment]
i am using paper and i have an listener error and it dint asked me to login
so i fixed it
by changing code

**Comment by games647** [comment]
Please post the error

**Comment by abhiram555** [comment]
ok

**Comment by abhiram555** [comment]
i can give you i deleted the server files

**Comment by abhiram555** [comment]
cant*

**Comment by games647** [comment]
The latest source code was directly tested with 1.15 and Paper. So I wonder what errors it caused. If you have issues, then it's important that it should be fixed for others too. Or could you post what you did change?

**Comment by abhiram555** [comment]
at that time i am not using latest plugin its been few mouths

**Comment by games647** [comment]
Even then it should be compatible. What changes did you made?
