### ISSUE TITLE
Error dispatching event PermissionCheckEvent

### ISSUE THREAD

**Issue by Nextopi** [games647/FastLogin#319]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
Error on pre login event, this was reported several times to luckperms and the cause seems to be  related authplugins such as fastlogin.

### Steps/models to reproduce:
After a while, this starts to show up in the logs constantly.

### Plugin list:

Luckperms, litebans, networkmsgs, fastlogin, changeskin, nuvotifier

### Environment description
[//]: # (Bungeecord, Minecraft 1.15.2, MariaDB,)

### Plugin version or build number (don't write latest):
1.11-SNAPSHOT-1375cf3

### Server Log:
[//]: # (No images please - only the textual representation)
https://hastebin.com/bimepefeqi.bash

### Configuration:
https://hastebin.com/gexidonoti.makefile

**Comment by games647** [comment]
Okay that's weird. LuckPerms especially [noted](https://github.com/lucko/LuckPerms/blob/efb958ba44a531ab742ccf0365510d0ec34af792/bungee/src/main/java/me/lucko/luckperms/bungee/listeners/BungeeConnectionListener.java#L54-L58) that UUID changing plugins can change the UUID on lowest priority like FastLogin does.

However just noticed that you use premiumUUID. This means that in combination with BungeeCord it will use BungeeCord's own standard onlinemode login mechanism. So there is even less chance for conflicts.

Could you post your LuckPerms version or even update it.

**Comment by Nextopi** [comment]
LuckPerms-Bungee-5.0.136 I have updated it like 1 or 2 days ago the error is still there.

**Comment by games647** [comment]
Yes, but then the error message and stacktrace should be different.

**Comment by Nextopi** [comment]
I actually have it enabled, here is another one 
https://paste.gg/p/anonymous/661832cb2efb4649a6d972e6b729c2d7/files/6ed7e93dd9da45a8b66c0969e23db8aa/raw

**Comment by games647** [comment]
I need the part at the time the user joins BungeeCord too.

**Comment by Nextopi** [comment]
Ah sorry, this is the part before the log I sent before
https://paste.gg/p/anonymous/75c0d616c47d47c886065022523e81dd/files/49e22c6fc2cd4354be1fdfe0d2b44c75/raw

I have checked the entire log and the uuid is always the same, if you are looking for that

**Comment by games647** [comment]
It appears that something went wrong loading it. Could you report it to LuckPerms? I tried to look into it, but I'm not much familiar with their code.

However as far as I read into this seems unrelated to FastLogin, especially in two ways. FastLogin in a BungeeCord setup uses the official API and therefore BungeeCord act like standard onlinemode logins and if the configuration option premium UUID is enabled the UUID is never  manually changed by FastLogin.

So like you can see the UUID never changed. That's a big indicator for the above points.
