### ISSUE TITLE
[QUESTION] Bundled Translation Files

### ISSUE THREAD

**Issue by Maxetto** [games647/FastLogin#32]
Do you accept Pull Request with bundled localization (example: messages_it.yml) inside the Jar?

Or should I only update the Wiki page with the new localization?

**Comment by games647** [comment]
Previously I thought it's better with the wiki, but I guess it's easier if we make a bundled localization and deploy it to the plugin folder..

**Comment by Maxetto** [comment]
I've added Italian to the Wiki and updated the English page to the newest messages file.

https://github.com/games647/FastLogin/wiki/Italian

Should I also state to save the file as UTF-8 as there are non-ASCII characters?

**Comment by games647** [comment]
>updated the English page to the newest messages file.

Thanks

>Should I also state to save the file as UTF-8 as there are non-ASCII characters?

Good point. I never thought about that. Yeah that would be great.
