### ISSUE TITLE
Database access not working on bungeecord

### ISSUE THREAD

**Issue by michele34** [games647/FastLogin#320]
I installed your plugins today, followed step-by-step the guide and everything was working except for the bungeecord database, but as you said sqlite is not supported on bungeecord so I decided to make a database for both the spigot and bungeecord plugins and I am now stuck with the spigot database working and the EXACT SAME CONFIGURATION on the bungeecord plugin giving me access errors. I have also tried to make a database only for the bungeecord, but it did not work (I still haven't undestood if they're supposed to work on the same database or not)
I have a lot of plugins using mysql with the same credentials and no problems whatsoever.
This is my actual configuration: `REMOVED`
I have tried to comment the lines below "# Single file SQLite database" but nothing changed.
I will only post one of my configuration since they are the same: `REMOVED`
Plugins on auth server: CoreProtect, PlaceholderAPI, BuycraftX, Multiverse-Core, SkinsRestorer, FastAsyncWorldEdit, PermissionsEx, ViaVersion, CustomJoinItems, PvPSword, Tablist, Vault, WorldEdit, AnimatedScoreboard, Essentials, ProtocolLib, WorldGuard, Citizens, ChestCommands, EssentialsProtect, EssentialsChat, EssentialsSpawn, AuthMe, HolographicDisplays, CitizensCMD, FastLogin
Plugins on bungeecord: AntiBotDeluxe, AntiVpn-Bungee, AuthMeBungee, BungeePerms, BungeeServerManager, ClientStats, FastLoginBungee, Litebans, SkinsRestorer
Spigot logs: https://pastebin.com/X4SnctZq
Bungee logs: https://pastebin.com/hfFDsu3V
Ps.: I am using the latest release of the plugins, paperspigot for 1.8.8 and the latest release of Waterfall.

**Comment by games647** [comment]
`Access denied for user 'root'@'localhost`

Is your BungeeCord server actually running on the same host than the MySQL/MariaDB server like your Spigot instances. If you use any special characters in your password, could you check if the file encoding is correct. It should always be UTF-8 and with consistent line endings (either i.e. LF).

**Comment by michele34** [comment]
All my servers are running on the same machine with MariaDB and my password does not contain any special characters and the file encoding is UTF-8.

**Comment by games647** [comment]
BTW: you forgot to remove it one of the pastebins. I removed the link. However pastebin is public, so you should still change it.

**Comment by games647** [comment]
Which plugin version do you use?

**Comment by michele34** [comment]
Oh I'm so sorry for the pastebin ahah, I am using the version 1.11-SNAPSHOT-5b1b609

**Comment by games647** [comment]
Which SQL server version do you use and could you check login with command line `mysql -u root -p`. It could print warnings on connection establishment.

**Comment by michele34** [comment]
I logged in like 3 minutes ago and everything is working fine with no errors or warnings. The version 10.3.22-MariaDB-1.

**Comment by games647** [comment]
Do you have a custom BungeeCord version, because normally BungeeCord would also print ` Access denied for user 'root'@'localhost' (using password: NO)`.

**Comment by michele34** [comment]
As I said in the first post, I am using Waterfall

**Comment by michele34** [comment]
Ok so this is the weirdest thing that has ever happened to me while using mysql. I tried to make a new user and set the password for 'user'@'%' instead of 'user'@'localhost' and it worked! I think the root user has a different password on other domains? But the question remains the same: why was it working on spigot and not on bungee?
Btw I'm closing the issue since my problem is solved.
Thank you for your time and excuse me for thinking that it was your fault.
Have a nice day.
