### ISSUE TITLE
Bungeecord problems

### ISSUE THREAD

**Issue by S4MON1X** [games647/FastLogin#321]
Hi, i have recently problem with Fastlogin on bungeecord.
My bungee console says this: https://pastebin.com/PN5QvrWE
My CFG: https://pastebin.com/BhsxAWqY

Spigot servers dosen´t log any problems.

**Comment by games647** [comment]
Why didn't you followed the issue template? There is a lot of information missing. Very important in this case are the installed plugins on BungeeCord.

**Comment by S4MON1X** [comment]
Sorry mate for my inactivity.
The issue was created by our server custom plugin.
You can close it.
