### ISSUE TITLE
FastLogin 1.11

### ISSUE THREAD

**Issue by Martinko366** [games647/FastLogin#329]
Where I can find FastLogin 1.11-SNAPSHOT-5b1b609? I can not found it on GitHub and Spigot.com. Can you please add it into spigot? Thanks!

**Comment by games647** [comment]
https://github.com/games647/FastLogin#development-builds

**Comment by Martinko366** [comment]
I can not find .jar file.

**Comment by games647** [comment]
Click on the build on the left side.
