### ISSUE TITLE
Missing inventory

### ISSUE THREAD

**Issue by jusobreira** [games647/FastLogin#330]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: # My premium players are loosing inventory when loggend in when they get back from a kick(/kick or afk kick)

### What behaviour is expected:
[//]: # That inventory don't desapear

### Steps/models to reproduce:
[//]: # A premium player get kicked by geting afk or by /kick and then when he login, the inventory desapear

### Plugin list:
[//]: # 
![image](https://user-images.githubusercontent.com/10175304/80265083-b76a2c00-866c-11ea-905d-b831cb6a754d.png)

### Environment description
[//]: # Spigot

### Plugin version or build number (don't write latest):
[//]: # 
![image](https://user-images.githubusercontent.com/10175304/80265108-d49efa80-866c-11ea-84b4-8b7c9c59edc8.png)

### Server Log:
[//]: # 
[//]: # https://pastebin.com/iGJg2s9u

### Configuration: 
[//]: #  https://pastebin.com/bKTG4SuC

**Comment by games647** [comment]
That's normal. See the comment above the premiumUUID configuration option.
