### ISSUE TITLE
Send updated auth key to legacy server?

### ISSUE THREAD

**Issue by Zilacon** [games647/FastLogin#332]
Hello, i run 7 older modpack servers that are all running on a custom bungeecord. Lately due to the corona virus traffic has increased for older modpacks. However on some days like today all clients below 1.7 are getting "bad login/not authenticated with minecraft.net/invalid session" etc errors.

My question is, could this plugin, since it does check the account with mojang, send the authentication information to legacy servers by using the updated auth servers?

So, Player tries to connect, bungee authenticates them on latest auth server, then transmits that information to the legacy server in the older format so older servers understand it.

If this could somehow be done im willing to pay for it if thats what it takes. Ive got 7 servers right now with 0 players as no one can connect, and i need some kind of solution. I cant just go to offline mode on bungee as that would affect all of my newer servers as well.

**Comment by games647** [comment]
>However on some days like today all clients below 1.7 are getting "bad login/not authenticated with minecraft.net/invalid session" etc errors.

This could also Mojang servers having issues, which they seemed to have recently.

>My question is, could this plugin, since it does check the account with mojang, send the authentication information to legacy servers by using the updated auth servers?
So, Player tries to connect, bungee authenticates them on latest auth server, then transmits that information to the legacy server in the older format so older servers understand it.

I don't really get that part. If you are using BungeeCord, BungeeCord is responsible for authentication. It only transfers the real IP and UUID back to the Spigot servers. There is no authentication data transfered.
