### ISSUE TITLE
Premium players can't join .

### ISSUE THREAD

**Issue by Patbox** [games647/FastLogin#333]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: # (What happened?)
Premium players can't join server with latest FastLogin and Tuinity (paper fork)

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
Use latest Tuinity with FastLogin
Try to join.

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
Tuinity 003c5b3 on Java 11
### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
1.11-SNAPSHOT-c298f3b

### Server Log:
[//]: # (No images please - only the textual representation)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error, stacktrace or the complete log (if any)
No logs

Probably related to https://github.com/games647/FastLogin/issues/331, but I'm not sure.

**Comment by Danifoxe** [comment]
Similar here:
**What behaviour is observed:**
Premium players can't join server with FastLogin and Paper-232 until Paper-236 (i tested until this version, the problem persists). i obtain this message: Connection Lost. Time out

**Steps/models to reproduce:**
Try Login in Paper-232 (or higher) with fastlogin. There are no server errors or crash in the console. When i do roll back to Paper-231 or below the problem solves, 

**Environment description**
This server is running Paper version git-Paper-232 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT). Plugins: AuthMe, CoreProtect, CourierNew, DiscordSRV, dynmap*, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, FastLogin, GriefPrevention, GSit, LuckPerms, ProtocolLib, Quests, QuickShop, SkinsRestorer, TimeVote, Vault, WorldEdit

**Plugin version or build number (don't write latest):**
FastLoginBukkit - Build #924 

**Server Log:**
There are no server errors or crash in the console.

**Comment by Danifoxe** [comment]
I just tried Paper-Build 239. For me, the problem is solved.
