### ISSUE TITLE
BungeeCord says Server is in online mode

### ISSUE THREAD

**Issue by TheSrMega** [games647/FastLogin#340]
### What behaviour is observed:
When I enter the bungeecord he kicks me saying that the authlobby is in online mode (
When I have fastlogin mode disabled, it doesn't, but when I turn it on and I relog if it does)

### What behaviour is expected:
I hope the bungee will let me in with fastlogin mode activated

### Steps/models to reproduce:
Join in the bungeecord
Logging in screen
Disconnnected with: Exception Connecting:QuietException : Server is online mode!

### Plugin list:
Bungee: Skinsrestorer, ServerListPlus, BlockServerCmds, LiteAnnouncer, Litebans, Quietcord, Always Online, RandomHUB, SQLite Driver, Ultimate Friends

### Environment description
The plugin is in the bungeecord and the authlobby
Bungeecord version: #1495
AuthLobby version: 1.8.8 spigot
### Plugin version or build number (don't write latest):
1.11-SNAPSHOT-d829c71
### Server Log:
No errors
### Configuration:
AuthLobby: https://gist.github.com/TheSrMega/814711e130af6409cc42ba3ec8b23b08 
BungeeCord: https://gist.github.com/TheSrMega/c9031c1d0f0efaef79c93f3d233e8a9f

**Comment by games647** [comment]
Please follow the setup guide: https://github.com/games647/FastLogin#how-to-install

**Comment by TheSrMega** [comment]
I have tried all the ways, but nothing, (Switching the plugins Fastlogin bukkit, and fastlogin bungee) the FastLoginBungee connects with the mysql but dont work

**Comment by games647** [comment]
Please post the server log of bungee and spigot.

**Comment by TheSrMega** [comment]
Bungee: https://gist.github.com/TheSrMega/122f984e9b875c89b462ac1f9c75c2b3
Spigot: https://gist.github.com/TheSrMega/c366d245736016ad7f7eeb8af90e8c2c

**Comment by TheSrMega** [comment]
Logs:
Bungee: https://gist.github.com/TheSrMega/aab53458798aa2904bd772a2bdbc035f
Spigot: https://gist.github.com/TheSrMega/211d82c46efe535c0553418fd078cb4e
(The plugin on the spigot works perfect)

**Comment by games647** [comment]
The spigot server is not configured in Bungee mode. Please enable it in the Spigot configuration like the guide says.

**Comment by TheSrMega** [comment]
Oh thanks, now it works. Thank you very very much

**Comment by JuanPabloUwU** [comment]
hola a mi me pasa algo parecido pero hice lo  que decia pero me sigue pidiendo logeo,tengo que tener el plugin de logeo en el  servidor  de  auth?
