### ISSUE TITLE
What is the premium status placeholder?

### ISSUE THREAD

**Issue by TheSrMega** [games647/FastLogin#341]
What is the placeholder of the premium status? I've tried with %fastlogin_status% but this don't work

**Comment by games647** [comment]
How do you tested it?

**Comment by TheSrMega** [comment]
I've only put
%fastlogin_status% in a menu that I made with deluxemenus, I wanted to make a menu where it would say if the fastlogin is active or not. (I am new to config theme)

**Comment by games647** [comment]
Do you installed PlaceholderAPI too?

**Comment by TheSrMega** [comment]
Yes, i have the version 2.10.6

**Comment by xion87** [comment]
Same here, don't work

**Comment by games647** [comment]
Does it print unknown or is it just not replaced at all.

**Comment by xion87** [comment]
not replaced at all

**Comment by xion87** [comment]
i suggest instead using Unknown (cracked) to use Not Premium or Premium

**Comment by xion87** [comment]
I suggest instead using "Unknown" to use "Not Premium"

**Comment by BingYanchi** [comment]
I tried /papi parse me %fastlogin_status% and it returned %fastlogin_status% as it is, which made me feel very confused

**Comment by BingYanchi** [comment]
I have the same situation as they, can the author fix it
