### ISSUE TITLE
FastLogin "Invalid Session" Error

### ISSUE THREAD

**Issue by SriTzAlex** [games647/FastLogin#343]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

I want to clarify that I speak Spanish and I am using the google translator excuse my grammar
### What behaviour is observed:
[//]: # (What happened?)
When users run the command: "/premium" when they try to log in to the server again, this "Invalid session" message appears. (and this error appears on the console)
(https://hastebin.com/nocoruhosi.bash)
### What behaviour is expected:
[//]: # (What did you expect?)
That when they use the "/premium" command I will let them log back into the server
### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
That users cannot enter the server. (Also every time I turn on the server I have to disable the plugin)
### Screenshots (if applicable)
[//]: # (You can drop the files here directly)
![Captura](https://user-images.githubusercontent.com/64871553/81124233-886c7980-8efa-11ea-8eda-9c4821fc0c01.JPG)

### Plugin list:
[//]: # (This can be found by running `/pl`)
![Captura](https://user-images.githubusercontent.com/64871553/81124203-7985c700-8efa-11ea-96b2-bef4e1fc5cc5.JPG)

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
Minecraft 1.8.8 - 1.12 "Spigot 1.8.8" 

### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
Fastlogin version: 1.10 (the latest version)

### Server Log:

https://hastebin.com/nocoruhosi.bash

### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Hastebin] (https://hastebin.com/yowupixizu.makefile)

**Comment by games647** [comment]
Outdated plugin version. Please update to dev build.

**Comment by SriTzAlex** [comment]
It is the last one that lets me download, would you pass me the link of the latest version?

**Comment by games647** [comment]
On the Jenkins site click on the left side for the specific builds, or click on status to see the latest builds.

**Comment by SriTzAlex** [comment]
thank you very much this problem has been bothering me for months (good complement and thanks for the good attention) ;)
