### ISSUE TITLE
cracked players cant join

### ISSUE THREAD

**Issue by moodrd** [games647/FastLogin#346]
When im using the plugin cracked players cant join, when i remove it they will be able to join fine

**Comment by games647** [comment]
Please follow the issue template. Which message do you get when you tried it?

**Comment by moodrd** [comment]
Session is invalid! Restart your game or try to refresh your session here.
when i try to login in crack launcher with original username that is registerd with mojang its doesn't allow me to join the server, but when i join a crack account not mojang registerd he let me join.

**Comment by games647** [comment]
https://github.com/games647/FastLogin/blob/master/core/src/main/resources/config.yml#L18
