### ISSUE TITLE
FastLogin not working with premium user (still need to give password)

### ISSUE THREAD

**Issue by Looowi** [games647/FastLogin#349]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: # (What happened?)
When login-in the server, password is asked, whereas i'm already on premium list

### What behaviour is expected:
[//]: # (What did you expect?)
I expected to log in automatically, without entering password

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
Enter the server with a premium account, set a password, register as a premium account with /premium, then logout and enter the server again.

### Screenshots (if applicable)
[//]: # (You can drop the files here directly)

### Plugin list:
[//]: # (This can be found by running `/pl`)
Plugins (31): AFK*, ClearLag, DeathCoordinates, dynmap*, Dynmap-Towny, EntityTrackerFixer, FastLogin, FirstJoinPlus*, Harbor, LimitPillagers, LoginSecurity*, LuckPerms, PrivateMessager*, ProtocolLib, Regionerator, ShopChest, SimpleDonations*, SkinsRestorer, SkQuery, Skript, StaffPlus, Suicide*, TheNewEconomy, Towny, TownyChat, Vault, VillagerOptimiser, Votifier*, VotingPlugin, WitherAC, WorldEdit

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
I used LoginSecurity, the build #933 of FastLogin (because the version of Spigot Website was causing errors with premium users and made connection to server impossible), and the last version available on Spigot website of ProtocolLib. The server is running under Paper 1.15.2 (build 205).

### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
Build #933

### Server Log:
[//]: # (No images please - only the textual representation)
[Hastebin](https://hastebin.com/fimufeyobi.cs/)

### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/uhiyugidup.makefile/)

**Comment by games647** [comment]
Your LoginSecurity version is outdated.
