### ISSUE TITLE
MySQL UUID is NULL

### ISSUE THREAD

**Issue by TheClub-Network** [games647/FastLogin#35]
Hello, first of all I'm sorry for my English. It's not my native language and sorry If this is not the right place where I can ask for help and I'm newbie on GitHub and barely know about this place.

For my sever I allowed cracked and premium id can join my server but I didn't allowed cracked user with premium name account to join at the first place and I have AutoIn handle auto-lgoin and fixed premium uuid for premium account.

I'm switching from AutoIn and trying to understand how does FastLogin work. And I have a few questions, It would be appreciated if you would kindly help, correct and suggest me.

- MySQL issues, that UUID column is NULL, as you can see, I logged in with 2 cracked accounts (non-premium account, UserID 1 and 2) and the plugin stored the data in MySQL table except UUID column. So, Is this normal?
I tried to re-logged a few time and still got the same result.
![screen shot 2559-07-09 at 1 51 29](https://cloud.githubusercontent.com/assets/20353071/16699022/9a91c1aa-457b-11e6-8755-4f20c8ccbee9.png)

- Then this picture, as you can see I tested by login with exiting premium account with premium luncher (UserID 3), the plugin won't generate the data in MySQL for the first time, I have to invoke /premium command then the data will be generated. This is how the plugin work right? I trying to re-logged but also still got NULL UUID for this premium account too.
![screen shot 2559-07-09 at 1 53 03](https://cloud.githubusercontent.com/assets/20353071/16699439/5c6258d8-457e-11e6-8fb4-efa745402a62.png)

- Another question, Is there any way to prevent cracked users invoke /premium command. For that cracked users who invoke /premium command, they will not be able to join the server, that's weird and Admin/me need to change the value back to 0 in Premium column in MySQL for those players one by one.

Thanks.
 
Here is my FastLogin config (bungeecord)
http://pastebin.com/XGcFcbbM

**Comment by TheClub-Network** [comment]
Opps sorry, Another question.

For the spigot server in config.yml do i need to configuration as the same setting as bungeecord?

**Comment by games647** [comment]
>the plugin won't generate the data in MySQL for the first time, I have to invoke /premium command then the data will be generated

Do you added the bungeecord id to the whitelist file?

>Another question, Is there any way to prevent cracked users invoke /premium command. 

You could run /cracked < name > and make use of the premium warning message. I'm planning to add way where the player have to relog in order to confirm that the player is actual premium.

>For the spigot server in config.yml do i need to configuration as the same setting as bungeecord?

No only if you use BungeeCord, only the configuration of BungeeCord will be used.

**Comment by TheClub-Network** [comment]
Yes i do, I added bungeecord id to the whitelist file.

**Comment by games647** [comment]
>Yes i do, I added bungeecord id to the whitelist file.

Does force logins work, because the column will only be updated after the first premium authentication. 

and the uuid column is only used for premium uuids. that's why it's null for cracked players.

**Comment by TheClub-Network** [comment]
I'm not sure what do you mean about force logins. Every exiting players have to run /login command even exiting premium players.

The plugin working fine, I tried to test many situation and It works as it should, If non existing premium player (new player) join the first time, the plugin will auto register, login and add that player data to MySQL as the way how I configuration except UUID is always NULL, It's the same as exiting premium player that they have NULL UUID in MySQL.

Refer to the picture no. 2 of MySQL table, for player "paramorepix" he is a premium account and he is existing player of the server before install FastLogin, but why his UUID is NULL in the MySQL table.

**Comment by games647** [comment]
What do you by mean "exiting player"?

**Comment by TheClub-Network** [comment]
The player who already registered to the server before.

**Comment by games647** [comment]
I think I found the cause of it.

**Comment by games647** [comment]
Thanks for reporting.

**Comment by TheClub-Network** [comment]
So what will happen if Premium player have NULL UUID in MySQL?

Thanks for your kindly help.

**Comment by games647** [comment]
Just the nameChangeCheck won't work.
