### ISSUE TITLE
Error within console

### ISSUE THREAD

**Issue by StefvanderMeer** [games647/FastLogin#350]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)
### What behaviour is observed:
[//]: # (What happened?)
Error in console
### What behaviour is expected:
[//]: # (What did you expect?)
No errors
### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
The user tried to join the server and the server produced an error. (The server is currently on a whitelist due to maintenance)
### Screenshots (if applicable)
[//]: # (You can drop the files here directly)
None
### Plugin list:
[//]: # (This can be found by running `/pl`)
AuthMeReloaded v5.6.0-SNAPSHOT b2388
AuthMeBungee-2.2.0-SNAPSHOT
Bot-Sentry-Bungee-6.1.2-BULLETPROOF

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
Travertine version git:Travertine-Bootstrap:1.15-SNAPSHOT:f63f310:132
MySQL
### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
1.11-SNAPSHOT-8ecb565
### Server Log:
[//]: # (No images please - only the textual representation)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error, stacktrace or the complete log (if any)
https://pastebin.com/ENRWARmd
### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file 
https://pastebin.com/ndxVRrVj

**Comment by games647** [comment]
The IP addresses you entered are not valid. FastLogin couldn't use them for a connection. Make sure your networking setup assigned them to your machine.

**Comment by Manu5656** [comment]
> The IP addresses you entered are not valid. FastLogin couldn't use them for a connection. Make sure your networking setup assigned them to your machine.

Could you please answer me in my discussion? I sent you what you needed, it's a very urgent problem to solve. Thanks

**Comment by StefvanderMeer** [comment]
> The IP addresses you entered are not valid. FastLogin couldn't use them for a connection. Make sure your networking setup assigned them to your machine.

Oh.. forgot about that! Thanks <3
