### ISSUE TITLE
Premium users not being automatically registered.

### ISSUE THREAD

**Issue by StefvanderMeer** [games647/FastLogin#354]
### What behaviour is observed:
[//]: # (What happened?)
A lot of players that have a premium Minecraft account still have to register and login as a cracked player. Their UUID is also not the correct premium one so it doesn't catch them as premium in the first login.
### What behaviour is expected:
[//]: # (What did you expect?)
I expected all players that are premium to be registered and logged in automatically as configured. Now, some players did get automatically registered but the majority isn't but are premium.
### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
Joining with a clean premium Minecraft account that isn't registered yet.
### Screenshots (if applicable)
[//]: # (You can drop the files here directly)
None
### Plugin list:
[//]: # (This can be found by running `/pl`)
AuthMeBungee-2.2.0-SNAPSHOT, Bot-Sentry-Bungee-6.1.2-BULLETPROOF, LuckPerms-Bungee-5.1.28,  and AuthMe-5.6.0-SNAPSHOT
### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
Travertine version git:Travertine-Bootstrap:1.15-SNAPSHOT:f63f310:132 (Accepting 1.7-1.15.2 clients on 1.8.9 paper spigot server)
### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
1.11-SNAPSHOT-8ecb565
### Server Log:
[//]: # (No images please - only the textual representation)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error, stacktrace or the complete log (if any)
https://pastebin.com/nQZCf4XQ (User joined with a premium account that wasn't registered yet)
### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file 
https://pastebin.com/newzjk8T

**Comment by games647** [comment]
Registration depends on the Spigot server. Please post the log of it too at the time it happens. However as you can see in the server log, the plugin detects the player as cracked, because they tried to login for the second time.

**Comment by StefvanderMeer** [comment]
Log:
https://pastebin.com/ZgDqSgYp

The player has joined for the first time and never joined before that. The console says it is logging in for the second time but this isn't true.

**Comment by StefvanderMeer** [comment]
I've done some testing and it seems to do with the secondAttemptCracked option. When on true there are premium players sometimes not getting registered as premium by the plugin but when on false it works perfectly fine.

Though this is an issue since we can't configure the message players see when not being able to connect as a cracked user joins with a premium IGN. This could make people think we are a premium server.

Anyway, I hope that this data is useful to look further into the issue.

**Comment by games647** [comment]
>I've done some testing and it seems to do with the secondAttemptCracked option. When on true there are premium players sometimes not getting registered as premium by the plugin but when on false it works perfectly fine.

One messages irritates me a lot. FastLogin messages first that it notices the player uses a premium username and then logs the about the second attempt. Considering that the second attempt check is done earlier this makes sense for two login attempts. No earlier attempt found, then check for premium username. Another join request: Attempt found -> log this message.

I have an assumption that the PreLoginEvent that FastLogin listens to fires twice. This would also explain LuckPerms message later. This not really correct behavior to the specification and could cause a lot of issues not only with FastLogin.

I added debug lines. Could you try it out with a similar setup like before. Greatly appreciate that.

>Though this is an issue since we can't configure the message players see when not being able to connect as a cracked user joins with a premium IGN. This could make people think we are a premium server.

Please take a look at the FAQ. It's a `frequently` asked question. Some cracked clients could however parse the info from the server, but I only have seen it once.
