### ISSUE TITLE
Rate Limit Hit, Premium get asked for password on ongoing bot attack

### ISSUE THREAD

**Issue by Redwolf223** [games647/FastLogin#357]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
When we are getting attacked by massive influx of bots, premium players are being asked to login with their password, this means that AutoLogin isn't working. 

Some of our premium players don't own a password. This is because we have migrated from another AutoLogin system so the AutoLogin was automatically active for them because they were already assigned as premium user on MySQL.

### What behaviour is expected:
[//]: # Auto Login to be performed.

### Steps/models to reproduce:
[//]: # Getting attacked by 800 bots/s.

### Screenshots (if applicable)
[//]: # (You can drop the files here directly)

### Plugin list:
Bungee server Plugins : Staffchat , SkinRestorer, ServerListPlus , MultiLobby , LuckPerms Bungee,
LiteBans , GlobalBroadcastBungee, FastLogin bungee, F3Name , BuyCraftX , BungeeReport, AuthmeBungee, AntiBotDeluxe universal

Authentication server Plugins (13): LuckPerms, FastAsyncWorldEdit, IPWhitelist, EasyWhitelist, ViaVersion, CustomAuth, ViaBackwards, ProtocolLib, ViaRewind, WorldEdit, AuthMe, HolographicDisplays, FastLogin

### Environment description
MySQL 

### Plugin version or build number (don't write latest):
1.11 , we tried with the build #949 but the problem persisted.

### Server Log:
[//]: #  31.05 23:22:10 [Server] WARN [FastLogin]: Rate Limit hit - Ignoring player [/51.77.68.123:55636|iSiu_-1971] <-> InitialHandler

### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file 

Config : https://pastebin.com/gk8kXh7K

**Comment by games647** [comment]
Update your config, you can adjust the values yourself:

https://github.com/games647/FastLogin/blob/master/core/src/main/resources/config.yml#L15

**Comment by Redwolf223** [comment]
We tried with the new config, but left it with the standard Antibot values and everytime we had more than 600 connections/s FastLogin stopped working.

Maybe we had to adjust the values better, do you think that adjusting it to 100000 connections and 1 minute for Expire makes any sense? Thank you

**Comment by games647** [comment]
>We tried with the new config, but left it with the standard Antibot values and everytime we had more than 600 connections/s FastLogin stopped working.

That's exactly what this feature is about. 

>Maybe we had to adjust the values better, do you think that adjusting it to 100000 connections and 1 minute for Expire makes any sense? Thank you

This setting is about CPU usage, because it drops all handling of the player. If your server has no problem fulfilling the database and network requests, you can turn it up.

**Comment by xion87** [comment]
i would suggest instead blocking autologin event, i woud blocking only players that are not present in fastlogin databse and allow onlnly login for the already registred player when the antibot is triggered , would be a more better clever idea i think, like the authme antibot

**Comment by games647** [comment]
>i would suggest instead blocking autologin event, i woud blocking only players that are not present in fastlogin databse and allow onlnly login for the already registred player when the antibot is triggered , would be a more better clever idea i think, like the authme antibot

This was implemented with the idea behind that it should have do no database or network lookups at all. The issuer complained about a too high database load. However it could be caused by the Minecraft servers too in that situation. I don't think Minecraft/Bungee plugin serve well for bot protection.

**Comment by xion87** [comment]
yeah i know but my teory should work like this, because your method is pretty useless and harmful (increasing the value too much will lead the server to crash)  i think vs the bots, i suggest to do this:
When rate limit happen:
- reject ONLY NEW USER premium connection (that is fine) and new user that attempt to register  (/premium command)
- allow EXISTING premium user to join and be verified 

Another solution would be to lower temporany the login priority so is protected by antibot or other antibot plugin.

I suggest to watch authme source and copy their antibot system, when a bot attack  happen, it allow existing user to join

**Comment by iSilviu-debug** [comment]
I also have this kind of problem, and I strongly recommend that we put a very low access priority by getting it to go first from an antibot. Then, if this doesn't work, lock the bot connections without passing them to MySQL while a player enters the server, using the antibot that kicka the bots, enable the premium function by passing it to mysql.

**Comment by games647** [comment]
>I also have this kind of problem, and I strongly recommend that we put a very low access priority by getting it to go first from an antibot.

FastLogin already has low priority events, but it's how BungeeCord is designed that still both plugins will work concurrently. I said that multiple times, that I'm happy if FastLogin could hook into these plugins as long as they provided a public accessible API. I didn't received a reply in two instances of paid plugins. Besides that it's also possible to cancel the login events that FastLogin fires. So both directions will work.

**Comment by madebyfusion** [comment]
Hey @games647,

I hope you are doing fine. I'm the developer of AntiBotDeluxe.
Could we chat somewhere to look at this issue?

Much appreciated.

**Comment by games647** [comment]
We already had a discussion on Discord. We could use the same channel again.

**Comment by madebyfusion** [comment]
Contacted you.
