### ISSUE TITLE
ClassCastException PropertyMap cannot be casted to MultiMap

### ISSUE THREAD

**Issue by Eufranio** [games647/FastLogin#36]
http://prntscr.com/bqvcrg
Is it normal?

**Comment by games647** [comment]
What version of ProtocolLib do you use?

**Comment by Eufranio** [comment]
ProtocolLib version 3.6.4 on a Thermos (cauldron fork) 1.7.10 server.

**Comment by games647** [comment]
Which build of Protocol lib?

**Comment by Eufranio** [comment]
Build 178

**Comment by games647** [comment]
Is was waaay more complex than I thought due different library versions of guava, but now it's fixed.
