### ISSUE TITLE
Deprecated PlayerLoginStartEvent

### ISSUE THREAD

**Issue by Drainer2002** [games647/FastLogin#365]
> [12:46:48 WARN]: [FastLogin] "FastLogin v1.10-git484855724b794de1fe057cf7360245362658b432" has registered a listener for protocolsupport.api.events.PlayerEvent on method "public void com.github.games647.fastlogin.bukkit.listener.protocolsupport.ProtocolSupportListener.onLoginStart(protocolsupport.api.events.PlayerLoginStartEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [games647, https://github.com/games647/FastLogin/graphs/contributors].

**Comment by games647** [comment]
That's not the latest version. v1.11 is newer, but only available as a development build.

**Comment by Drainer2002** [comment]
so what shall i do to solve the issue?

**Comment by games647** [comment]
Download a dev build.

**Comment by Drainer2002** [comment]
Can you give me the link, please?

**Comment by Drainer2002** [comment]
Hello ?

**Comment by games647** [comment]
I have also other stuff to do. A search would already helped you. https://github.com/games647/FastLogin#development-builds
as well on Spigot at the top of the resource page
