### ISSUE TITLE
Sync configs

### ISSUE THREAD

**Issue by Baterka** [games647/FastLogin#366]
[//]: # (Lines in this format are considered as comments and will not be displayed.)

### Is your feature request related to a problem? Please describe.
It is very annoying to always change config and messages twice (or more for more servers) when editing.

### Describe the solution you'd like
For example sync config and message files with bungee, so you need to edit it just once and it gets propagated on all servers.

**Comment by games647** [comment]
Good idea. For temporarily workaround you could use symlinks at least if the files are on the same server.
