### ISSUE TITLE
Paper 1.16.1 no errors but Entity can't be added, since it already exists

### ISSUE THREAD

**Issue by Kongolan** [games647/FastLogin#369]
Testing and running 1.16.1 now with paper. 

### What behaviour is observed:
If people join the nether or logout in the nether and join back in. They get stuck in void and can't move or talk: https://cdn.discordapp.com/attachments/540315459321331723/726983372290654228/2020-06-28_19.04.13.png

Pastebin of full Error: https://pastebin.com/kvBq2MnK

`[13:33:00] [Server thread/WARN]: java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world world: EntityPlayer['4_Rozerr_4'/869681, uuid='43b0b209-3c35-322a-b2b6-69c747c66473', l='ServerLevel[world]', x=-113.33, y=84.00, z=267.53, cx=-8, cz=16, tl=14156154, v=true, d=false](4_Rozerr_4 at -113.32618087950671,84.0,267.53226750452075) ALREADY CONTAINED (This would have crashed your server)`

Why do I think, it's a FastLogin problem? Because the paper devs suggested it.

### Steps/models to reproduce:
Logout in the nether with paper 1.16.1 build + Authme + FastLogin installed

### Plugin list:
Authme
FastLogin

### Environment description
This server is running Paper version git-Paper-12 (MC: 1.16.1)

### Plugin version or build number (don't write latest):
FastLogin version 1.11-SNAPSHOT-cae2f8f

**Comment by games647** [comment]
I built Paper from the latest `25c14f76fc71a1fd90660a0e4287a383b45006a4` and it worked flawlessly. I could also imagine that ProtocolLib didn't correctly intercepted the first packets. For my testing I used `fd93c1c55349540daab3d41cf0d4dff31bd9b8c2` or build `466`. Maybe you need to update it one of those.

Could you try it out and respond back?

**Comment by Kongolan** [comment]
I will try, i didn't fetch the newest build of ProtocolLib so far. Let's see what my players report.
