### ISSUE TITLE
BungeeCord premium skins (ChangeSkin)

### ISSUE THREAD

**Issue by Augustin37** [games647/FastLogin#37]
Hello, I'm using BungeeCord and ChangeSkin. When I do /premium, my skin do not appear anymore :/
And it do the same when I set forwardSkin to false.

Thank you :)

**Comment by Augustin37** [comment]
Also I don't know if the source of both of these problems are the same, but when we are in gamemode spectator, we can't get through walls

**Comment by games647** [comment]
>Also I don't know if the source of both of these problems are the same, but when we are in gamemode spectator, we can't get through walls (only when premium)

Do you have premiumUUid enabled?

**Comment by Augustin37** [comment]
I set premiumUUID to false, because I don't want my players to change UUID when they do /premium, because permissions will change, and they will not be able to open they locked chest etc

I'm using build 1167

**Comment by games647** [comment]
So the skin issue is properly fixed with: https://github.com/games647/FastLogin/commit/2b16f3341fa800a3165bf236bbbf5a5780e9ab73

I assume it's the same for gamemode thing, because it's the same packet.

**Comment by Augustin37** [comment]
Thank you ! :)

**Comment by Augustin37** [comment]
Will you soon put a compilated version on spigot which fix this problem please? Thank you!

**Comment by games647** [comment]
You could use the a dev-build from Jenkins: http://ci.xephi.fr/job/FastLogin/changes

**Comment by Augustin37** [comment]
Sorry I did not saw there was a jenkins ^^ I tested it, with no problem! Thank you again :D
