### ISSUE TITLE
something wrong with bungeecore

### ISSUE THREAD

**Issue by kamichizuru030** [games647/FastLogin#371]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
When I use /premium it appear something wrong // it say Do not forget to follow the BungeeCore setup guide
But I do all thing that the guide instruction. 
(sorry I have some sentences translated, there may be some problems)

### What behaviour is expected:
It can use ;(

### Steps/models to reproduce:
just use /premium

### Screenshots (if applicable)
[//]: # (You can drop the files here directly)

### Plugin [list:](url)
https://imgur.com/a/lpUP1Cf

### Environment description
paper1.15.2-366 // MySql

### Plugin version or build number (don't write latest):
#950 & #951

### Server Log:
https://pastebin.com/MaUk7JP2

### Configuration:
https://pastebin.com/85Kbyxhe

**Comment by games647** [comment]
Bug in BungeeCord. They already fixed it.
