### ISSUE TITLE
Error on thread pool on ongoing bot attack

### ISSUE THREAD

**Issue by Redwolf223** [games647/FastLogin#372]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: when someone is using bots to attack my server i get a log saying error on thread pool, this happens only when using mysql in the config. With the .db file nothing happens.

### What behaviour is expected:
[//]: # Getting no logs or warns.

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail) Use mysql and start a bot attack.

### Screenshots (if applicable)
[//]: # (You can drop the files here directly)

### Plugin list:
[//]: # serverlistplus , luckperms , antibotdeluxe , authmebungee , bungeeplugin , bungeereport , changeskin , fastlogin , globalbroadcastbungee , litebans , multilobby , staffchat

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
Pterodactyl,  Waterfall latest version , Mysql 
### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.) FastLogin 1.11-SNAPSHOT-de1487b

### Server Log:
[//]: # (No images please - only the textual representation)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error, stacktrace or the complete log (if any) https://pastebin.com/FSZAGVSV

### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file 
https://pastebin.com/h549diMP

**Comment by games647** [comment]
That's not the full error. I need the complete one.

**Comment by Redwolf223** [comment]
I am sorry, here the pastebin https://pastebin.com/XG9YhKKn this is from the log file of waterfall

**Comment by games647** [comment]
This error is not caused by FastLogin. See this post for the explanation: https://github.com/games647/FastLogin/issues/292#issuecomment-573190395
