### ISSUE TITLE
UUID errors and failure to auto login

### ISSUE THREAD

**Issue by SizzlinSeal** [games647/FastLogin#374]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: # (What happened?)
The plugin throws a bunch of errors on the waterfall console and fails to auto login premium players
### What behaviour is expected:
[//]: # (What did you expect?)
That the plugin auto logins premium players
### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
Add FastLoginBungee to waterfall
Add FastLogin to paper server
### Screenshots (if applicable)
[//]: # (You can drop the files here directly)
![ec2-user@ip-172-31-14-91_~_BungeeCord 2020-07-08 1_56_40 PM](https://user-images.githubusercontent.com/67880368/86969604-e5ff8b00-c122-11ea-954a-f746956e49bf.png)

### Plugin list:
[//]: # (This can be found by running `/pl`)
Waterfall:
AuthMeBungee
FastLoginBungee
Protocolize
SkinsRestorer
Paper:
AdvancedTeleport, AuthMe, AutoStop, ClearLag, DiscordSRV, FastLogin, LockettePro, LuckPerms, ProtocolLib, SkinsRestorer
### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
Java 14
Paper-80
Waterfall-361
### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
FastLogin version 1.11-SNAPSHOT-cae2f8f
### Server Log:
[//]: # (No images please - only the textual representation)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error, stacktrace or the complete log (if any)
https://hastebin.com/jewotiduxo.md
### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file 
https://hastebin.com/ovefiduwiq.makefile

**Comment by games647** [comment]
The UUID in your Waterfall server is invalid. It's too long. You can find it inside the `config.yml` of the proxy. Note it's not the config file of `FastLogin` rather from the proxy itself.

**Comment by SizzlinSeal** [comment]
Oh. I thought it was in the config of bungeecord.

**Comment by SizzlinSeal** [comment]
OK, so how do I add multiple proxies to proxy-whitelist.txt?

**Comment by games647** [comment]
You can add multiple lines.

**Comment by SizzlinSeal** [comment]
If i add multiple lines it says that the UUID string is too large

**Comment by games647** [comment]
Is the error now on Spigot? If not then, it's probably the same like the op error. Then you need verify the uuid of the proxy server not in any fastlogin configs.

**Comment by SizzlinSeal** [comment]
I fixed it! I just copied and pasted the same UUID across the two bungees!
