### ISSUE TITLE
[FastLogin] No on-going login session for player (Velocity not supported?)

### ISSUE THREAD

**Issue by Bodyash** [games647/FastLogin#378]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: # (What happened?)
Plugin can't detect premium session (installed only on Paper, because not supported on Velocity side)

### What behaviour is expected:
[//]: # (What did you expect?)
More debug info in console

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
Debian 10, Paper 1.15.2 (offline mode) + velocitypowered proxy (offline mode)

### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
FastLogin version 1.11-SNAPSHOT-cae2f8f

### Server Log:
[//]: # (No images please - only the textual representation)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error, stacktrace or the complete log (if any)
[FastLogin] No on-going login session for player: CraftPlayer{name=Bodyash} with ID *************:59644

### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file 
default config. sqlite db

**Comment by games647** [comment]
Yes, FastLogin needs to placed on the server that is responsible for authentication. This is in this case the velocity server. I'm closing this in favor of #311
