### ISSUE TITLE
not work on my server

### ISSUE THREAD

**Issue by mat41997** [games647/FastLogin#38]
file
https://www.dropbox.com/s/q6zlofg5r6fxwcu/s1.zip?dl=0
and
https://ci.destroystokyo.com/job/PaperSpigot/814/

**Comment by sgdc3** [comment]
Please use paste tools as pastebin or hastebin

**Comment by sgdc3** [comment]
Ah is it a mysql dump?

**Comment by games647** [comment]
There is no log?

What's the problem. Could you please describe it.
>Ah is it a mysql dump?

No the server setup

**Comment by sgdc3** [comment]
Ah ok, people should write what a download contains when publishing something online.

**Comment by mat41997** [comment]
logs
http://pastebin.com/Qq9wPzFK

**Comment by games647** [comment]
And what doesn't work?

**Comment by mat41997** [comment]
![2016-07-13_11 39 26](https://cloud.githubusercontent.com/assets/5884000/16798912/970d3f8e-48ee-11e6-94a9-d3b34d2b7200.png)

**Comment by games647** [comment]
You are already registered. FastLogin ignores already registered players in order to protect cracked players.

Either unregister or login and type /premium.

**Comment by mat41997** [comment]
config FastLogin
http://pastebin.com/nvkdL7aD

config AuthMe
http://pastebin.com/qb1h29uh

timings
https://timings.aikar.co/v2/?id=e6b8bf8a685e46e28f16404f2d64bf96

**Comment by games647** [comment]
See my last comment please.

**Comment by mat41997** [comment]
you can fix this?

**Comment by games647** [comment]
>Either unregister or login and type /premium.

**Comment by mat41997** [comment]
![2016-07-13_11 46 57](https://cloud.githubusercontent.com/assets/5884000/16799134/95987ef6-48ef-11e6-8c12-4bc878177829.png)

**Comment by mat41997** [comment]
not auto-register me

**Comment by mat41997** [comment]
you can fix this?

**Comment by games647** [comment]
It works for me. You should delete your database, unregister and that's it.

**Comment by mat41997** [comment]
oh my goodnes, a lot of work.

thx. for all
i'am stupid : P

**Comment by games647** [comment]
So you fixed it?

**Comment by mat41997** [comment]
NO!

**Comment by mat41997** [comment]
i will never use this plugin
so complicated

thanks for all : P

**Comment by games647** [comment]
`What about an TeamViewer session?

**Comment by mat41997** [comment]
i don't know : P

ok, why not : D

**Comment by games647** [comment]
Ok, then send me a private message over Spigot with the data.

**Comment by mat41997** [comment]
ok, i'am ready : O

**Comment by mat41997** [comment]
ok. thx for the lerning. XD
no you lost you time?
[new 1.txt](https://github.com/games647/FastLogin/files/361351/new.1.txt)

**Comment by games647** [comment]
So I think it's fixed?

**Comment by sgdc3** [comment]
@mat41997

**Comment by mat41997** [comment]
yes. ^^

thx

**Comment by sgdc3** [comment]
Thank you ;)

**Comment by sgdc3** [comment]
> sudo games647 close 38
