### ISSUE TITLE
/premium is broke, autologin doesn't work, etc

### ISSUE THREAD

**Issue by AguilaDB** [games647/FastLogin#381]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: # I am a premium user in the server I own. I executed /premium command in game, logged off, tried to log back in and it said: "Failed to log in: the authentication servers are down for maintenance" and it won't leg me log back in until I either put /cracked (my name here) thru console, or restart the whole FastLogin config.

And... something even stranger. Is that when I try to log into any other online mode server with that account it either says the exact same thing and doesn't allow me in, or plainly won't allow me in.

### What behaviour is expected:
[//]: # I would like to do the premium thing to bypass register and login with AuthMe and also see player's skin heads on the TAB. Unfortunately it seems like this won't work until I label myself as a premium user with the command mentioned above.

### Steps/models to reproduce:
[//]: # The command /premium, then logging off and trying to log back into the server.

### Screenshots (if applicable)
[//]: # https://i.imgur.com/IbIHCZl.png https://i.imgur.com/DGVHgDg.png https://i.imgur.com/xSLkkA3.png

### Plugin list:
[//]: # https://i.imgur.com/48pSuAC.png

### Environment description
[//]: # Minecraft 1.12.2 spigot (?) (Not sure what this question means, but I don't have MySQL/SQLite or anything like that)

### Plugin version or build number (don't write latest):
[//]: # FastLogin version 1.11-SNAPSHOT-cae2f8f

### Server Log:
[//]: # https://hastebin.com/licoxuludu.md

### Configuration:
[//]: # https://hastebin.com/evacedinup.makefile

**Comment by games647** [comment]
If you see this message on the client, then you have to check your connectivity to the Mojang servers. Check if you can reach the session servers. This is not really related to FastLogin specifically.
