### ISSUE TITLE
Support email field

### ISSUE THREAD

**Issue by hs-err** [games647/FastLogin#384]
### Is your feature request related to a problem? Please describe.
[//]: # (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])

### Describe the solution you'd like
Add email field when register

### Describe alternatives you've considered
Auto login without plugin account.

### Additional context

Add SodionAuth #383

**Comment by games647** [comment]
The plugin automatically registers the user. How should the email field be retrieved?

**Comment by hs-err** [comment]
> The plugin automatically registers the user. How should the email field be retrieved?

May impossible.
I read api wiki. I can't find methods to do it.
So....May "Auto login without account"?

**Comment by games647** [comment]
Is it for your plugin always necessary to enter an email address?

**Comment by hs-err** [comment]
> Is it for your plugin always necessary to enter an email address?

Yes. Almost all backends need "email address".

Input fake email address and random password may cause some problems.

Likes: Xenforo can't change password without email verify.

**Comment by ishland** [comment]
I think this can be implemented at the Auth Provider side. After registering players automaticlly, the Auth Provider can request for missing fields, such as email, 2FA, etc.

**Comment by games647** [comment]
> I think this can be implemented at the Auth Provider side. After registering players automaticlly, the Auth Provider can request for missing fields, such as email, 2FA, etc.

But this would be then saved at the auth plugin. FastLogin only saves only data relevant for associating them with their premium status. Everything else is saved at the auth plugin. So I don't know why FastLogin needs a field for that.

**Comment by ishland** [comment]
That is basically what I said. AuthPlugin can just request more fields to the players after FastLogin register them. There is nothing to do with FastLogin.

**Comment by games647** [comment]
Okay, wanted just to clarify. Closing then...
