### ISSUE TITLE
[Request] Player doesn't need to invoke command

### ISSUE THREAD

**Issue by Pijanista** [games647/FastLogin#39]
Is there possibilty to make in config that player doesn't need to invoke command. I'm trying to make Semi-Cracked server. So if premium users join he's automaticlly registered and register him as premium, but if cracked player join he's kicked until someone register him.

I turned on in authme "kickNonRegistered" and it kicks cracked player which are not registered and i turned on autoregister in FastLogin and it register automatic premium player, so i just need to invoke automatic that's he's premium and i'll manual register cracked player and invoke command for cracked player.

**Comment by games647** [comment]
I don't understand correctly. AutoRegister will automatically registers **new** players if they use a premium username. Those players doesn't need to invoke the /premium command.

**Comment by Pijanista** [comment]
Ok my bad, obvious i was already registered with authme while i was trying this. Back to authme support ;) Thanks.
