### ISSUE TITLE
How to make public key?

### ISSUE THREAD

**Issue by abhiram555** [games647/FastLogin#410]
https://github.com/games647/FastLogin/blob/d034e713316d497159f2d7faf1060bd21a2fbe4d/bukkit/src/main/java/com/github/games647/fastlogin/bukkit/listener/protocollib/ProtocolLibLoginSource.java#L32

hey i have seen there is a public key on this class constructor so how to make that public key?

**Comment by abhiram555** [comment]
and i want to how how you send encryption packet. and verifying premium players. code snippets would be appreciated.

**Comment by abhiram555** [comment]
@games647

**Comment by abhiram555** [comment]
Hello

**Comment by games647** [comment]
It's the public key from the Minecraft server. It's for data encryption. It will be created by FastLogin itself.

**Comment by abhiram555** [comment]
> It's the public key from the Minecraft server. It's for data encryption. It will be created by FastLogin itself.

alright thanks.
