### ISSUE TITLE
Couldn't enable encryption

### ISSUE THREAD

**Issue by kristupas098** [games647/FastLogin#414]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

NOTE: in spigot version you can join to server but in cracked mode, in paper nobody can join

### What behaviour is observed:
[//]: # (What happened?)
Premium players cannot login to server (disconnected)
Cracked player can login to server

### What behaviour is expected:
[//]: # (What did you expect?)
To join to server with premium account

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
Update fastlogin to version 1.11-SNAPSHOT-f2441ec and spigot to Spigot-37d799b-3eb7236 or paper-git-261

### Screenshots (if applicable)
[//]: # (You can drop the files here directly)

### Plugin list:
[//]: # (This can be found by running `/pl`)
Authme, ChatCo, CustomHelpMessage, FastLogin, InfoBook, JoinMessage, KISS-tpa, LuckPerms, NoCheatPlus, OldschoolKill, ProtocolLib, RandomSpawn, RealPing, Rules, ServerListPlus, SkinsRestorer

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
git-Spigot-37d799b-3eb7236, Minecraft 1.16.4, paper-git-261

### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
1.11-SNAPSHOT-f2441ec

### Server Log:
[//]: # (No images please - only the textual representation)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error, stacktrace or the complete log (if any)
https://hastebin.com/bejadatamu.yaml

### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file 
https://hastebin.com/ocupasoniy.yaml

**Comment by kristupas098** [comment]
NOTE: in papermc-256 puts error related to networkmanager

**Comment by games647** [comment]
Duplicate #412
