### ISSUE TITLE
Not working since I updated to 1.16.4

### ISSUE THREAD

**Issue by Saturn-w** [games647/FastLogin#419]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: # (What happened?)
So I updated to 1.16.4 and the plugin was not working 
then I saw that there was a new dev build with 1.16.4 support and put it on my server 
but everytime i try to do a command it display this message
<img width="622" alt="Capture d’écran 2020-11-10 à 17 20 34" src="https://user-images.githubusercontent.com/66163542/98700948-0c576080-2379-11eb-88f5-f0b1224ebce2.png">
I run my server on paper 1.16.4 

### Plugin list:
Essentials essentialschat essentialsGeoip EssentialsProtect EssentialsSPawn EssentialsXmpp Fatstlogin luckperms Protocolib Vault Xauth

**Comment by games647** [comment]
Please post the error that is in the server log.

**Comment by Saturn-w** [comment]
| [18:15:21 INFO]: tradonix issued server command: /cracked
mc_1     | [18:15:21 ERROR]: null
mc_1     | org.bukkit.command.CommandException: Cannot execute command 'cracked' in plugin FastLogin v1.11-SNAPSHOT-9ff404a - plugin is disabled.
mc_1     | 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2007) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1818) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1771) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by games647** [comment]
This means there must be an earlier error.

**Comment by Saturn-w** [comment]
[22:37:17 INFO]: [FastLogin] Enabling FastLogin v1.11-SNAPSHOT-9ff404a
mc_1     | [22:37:17 ERROR]: [FastLogin] Server has to be in offline mode
mc_1     | [22:37:17 INFO]: [FastLogin] Safely shutting down scheduler. This could take up to one minute.
mc_1     | [22:37:17 ERROR]: Error occurred while enabling FastLogin v1.11-SNAPSHOT-9ff404a (Is it up to date?)
mc_1     | java.lang.NullPointerException: null
mc_1     | 	at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onDisable(FastLoginBukkit.java:108) ~[?:?]
mc_1     | 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:58) ~[?:?]
mc_1     | 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:940) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

even if it says the server has to be in offline mode, The server is in offline mode

**Comment by Saturn-w** [comment]
![Capture d’écran 2020-11-10 à 22 44 12](https://user-images.githubusercontent.com/66163542/98737266-4428cd00-23a6-11eb-97f8-d1702f270940.png)

**Comment by Saturn-w** [comment]
nvm the file wouldn't save but now I have another problem: when I reload (so the plugins could work) I have this error even thought I am a premium player 
<img width="536" alt="Capture d’écran 2020-11-10 à 23 01 13" src="https://user-images.githubusercontent.com/66163542/98738851-a4207300-23a8-11eb-8626-e8965cbb88dd.png">
The logs are 


mc_1     | [23:02:20 INFO]: UUID of player tradonix is aa3c8f85-7f64-4b70-9a26-3d447b0fe30d
mc_1     | [23:02:21 INFO]: tradonix joined the game
mc_1     | [23:02:21 INFO]: tradonix[/86.252.78.116:50696] logged in with entity id 463 at ([world]-299.7361599673955, 64.0, 74.89285484004968)
mc_1     | [23:02:21 WARN]: [Essentials] Task #24212 for Essentials v2.17.2.0 generated an exception
mc_1     | java.lang.NullPointerException: null
mc_1     | 	at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:146) ~[?:?]
mc_1     | 	at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:113) ~[?:?]
mc_1     | 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1297) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by games647** [comment]
There is no error of FastLogin there. See the FAQ, in the default configuration FastLogin assumes all players are cracked unless they opt-in using the premium command.

**Comment by Saturn-w** [comment]
Sorry I didn't put context :
I tried to put /premium <useename> In rcon but It didn't send a 
 confirmation message 
![Capture d’écran 2020-11-11 à 11 02 20](https://user-images.githubusercontent.com/66163542/98797835-6275e380-240d-11eb-94cf-5b54df0b3891.png)

So after my last message I tried withUnregistering  myself of authme with this command   :  authme unregister tradonix  so I could do /premium after if it aws rcon that was'nt working 
![Capture d’écran 2020-11-11 à 10 57 51](https://user-images.githubusercontent.com/66163542/98797942-8e916480-240d-11eb-984b-5ebd4e8dfd70.png)

But after I registered myself I had the same error than before  
![Capture d’écran 2020-11-11 à 10 58 36](https://user-images.githubusercontent.com/66163542/98798170-d912e100-240d-11eb-9141-a9ac9835f9ad.png)

And this is when I do /pl 
![Capture d’écran 2020-11-11 à 10 58 42](https://user-images.githubusercontent.com/66163542/98798216-e8922a00-240d-11eb-9537-4efffe18e09b.png)
 
` [11:15:31 INFO]: [AuthMe] AuthMe 5.6.0-SNAPSHOT build n.2402 successfully enabled!
mc_1     | [11:15:31 INFO]: [FastLogin] Enabling FastLogin v1.11-SNAPSHOT-9ff404a
mc_1     | [11:15:31 ERROR]: [FastLogin] Server has to be in offline mode
mc_1     | [11:15:31 INFO]: [FastLogin] Safely shutting down scheduler. This could take up to one minute.
mc_1     | [11:15:31 ERROR]: Error occurred while enabling FastLogin v1.11-SNAPSHOT-9ff404a (Is it up to date?)
mc_1     | java.lang.NullPointerException: null
mc_1     | 	at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onDisable(FastLoginBukkit.java:108) ~[?:?]
mc_1     | 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at com.github.games647.fastlogin.bukkit.FastLoginBukkit.onEnable(FastLoginBukkit.java:58) ~[?:?]
mc_1     | 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:940) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
mc_1     | [11:15:32 INFO]: Starting remote control listener`




When i do the command ;
```
mc_1     | [11:14:02 INFO]: tradonix issued server command: /premium
mc_1     | [11:14:02 ERROR]: null
mc_1     | org.bukkit.command.CommandException: Cannot execute command 'premium' in plugin FastLogin v1.11-SNAPSHOT-9ff404a - plugin is disabled.
mc_1     | 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2007) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1818) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1771) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by Saturn-w** [comment]
I'm really sorry to annoy you and sorry If my english is not very good

**Comment by games647** [comment]
The plugin still thinks the server is in offline mode and therefore disables itself. Please check it. It has to be offline mode in the server-properties or BungeeCord has to be enabled. I noticed you posted a screenshot of a velocity configuration option. There is no support for it at the moment. #311

**Comment by Saturn-w** [comment]
yeah For the first screenshot with the velocity I was in the wrong offline mode (it. was in paper.yml and the real offline mode is in server.proprieties)and even if the server was in offline, the velocity was interfering with the launch of fastlogin.
Now fastlogin Launch but evrytime I do /premium and again /premium to confirm I have this error  

![Capture d’écran 2020-11-11 à 13 19 06](https://user-images.githubusercontent.com/66163542/98811109-91498500-2420-11eb-95da-25195f1ad117.png)

with  the logs : 
```
mc_1     | [13:18:42 INFO]: [AuthMe] tradonix logged in!
mc_1     | [13:18:44 INFO]: tradonix issued server command: /premium
mc_1     | [13:18:48 INFO]: tradonix issued server command: /premium
mc_1     | [13:18:48 ERROR]: [FastLogin] Failed to query profile: tradonix
mc_1     | org.sqlite.SQLiteException: [SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed)
mc_1     | 	at org.sqlite.core.DB.newSQLException(DB.java:1010) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at org.sqlite.core.DB.newSQLException(DB.java:1022) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at org.sqlite.core.DB.execute(DB.java:864) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:77) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at fastlogin.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[?:?]
mc_1     | 	at fastlogin.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[?:?]
mc_1     | 	at com.github.games647.fastlogin.core.AuthStorage.loadProfile(AuthStorage.java:142) ~[?:?]
mc_1     | 	at com.github.games647.fastlogin.bukkit.command.PremiumCommand.onPremiumSelf(PremiumCommand.java:55) ~[?:?]
mc_1     | 	at com.github.games647.fastlogin.bukkit.command.PremiumCommand.onCommand(PremiumCommand.java:29) ~[?:?]
mc_1     | 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2007) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1818) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1771) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
mc_1     | [13:18:48 ERROR]: null
mc_1     | org.bukkit.command.CommandException: Unhandled exception executing command 'premium' in plugin FastLogin v1.11-SNAPSHOT-9ff404a
mc_1     | 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2007) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1818) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1771) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1136) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
mc_1     | Caused by: java.lang.NullPointerException
mc_1     | 	at com.github.games647.fastlogin.bukkit.command.PremiumCommand.onPremiumSelf(PremiumCommand.java:56) ~[?:?]
mc_1     | 	at com.github.games647.fastlogin.bukkit.command.PremiumCommand.onCommand(PremiumCommand.java:29) ~[?:?]
mc_1     | 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	... 19 more
```

**Comment by games647** [comment]
Your `.db` file is broken. Try to rename it.

**Comment by Saturn-w** [comment]
okay I try that

**Comment by Saturn-w** [comment]
So I had put a username removed it and the command and now it works 
BUT
even if I added me in the premium list when I deconnect the game ask me a password 

and it give me this : 
```
mc_1     | [14:51:31 ERROR]: [FastLogin] Failed to save playerProfile StoredProfile{rowId=-1, premium=true, lastIp='', lastLogin=2020-11-11T13:51:31.696Z} StoredProfile{id=null, name='tradonix'}
mc_1     | org.sqlite.SQLiteException: [SQLITE_CORRUPT]  The database disk image is malformed (database disk image is malformed)
mc_1     | 	at org.sqlite.core.DB.newSQLException(DB.java:1010) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at org.sqlite.core.DB.newSQLException(DB.java:1022) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at org.sqlite.core.DB.execute(DB.java:864) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:54) ~[patched_1.16.4.jar:git-Paper-267]
mc_1     | 	at fastlogin.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[?:?]
mc_1     | 	at fastlogin.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[?:?]
mc_1     | 	at com.github.games647.fastlogin.core.AuthStorage.save(AuthStorage.java:207) ~[?:?]
mc_1     | 	at com.github.games647.fastlogin.bukkit.command.PremiumCommand.lambda$onPremiumOther$1(PremiumCommand.java:93) ~[?:?]
mc_1     | 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_212]
mc_1     | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
mc_1     | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
mc_1     | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

Should I delete and recreate a .db file or just rename it ? 
either way thanks for your help your plugin is amazing

**Comment by Saturn-w** [comment]
Nevermind
t I was registered with Authme, so  I did /authme unregister and it worked perfectly fine 
Thank you again for your help
