### ISSUE TITLE
Add feature for cracked play whitelist

### ISSUE THREAD

**Issue by ac9607** [games647/FastLogin#42]
Hello
I was migrated from Auto-in
Auto-in has a feature:
Whitelist for cracked player, and premium player can login bypass whitelist
Can you add this feature?

**Comment by games647** [comment]
You mean the switch-mode feature from Auto-In?

**Comment by ac9607** [comment]
I need a whitelist only for cracked player

In autoin, if the whitelist feature is enabled
Premium players are still able to register and login automatically
But cracked player must have their player name on the whitelist to join the server

**Comment by games647** [comment]
Ok, so not like the switch-mode.

**Comment by ac9607** [comment]
Yeah, because trolls with cracked id can switch their name and join server again instantly

But I don't want a universal whitelist to restrict new premium players

**Comment by Pijanista** [comment]
I had same question, maybe it's better if player is cracked and not registered, send message every x sec to visit xxx site to apply and then mod/admin has to register him. After registration he has normal usage of command /login.

**Comment by games647** [comment]
>I had same question, maybe it's better if player is cracked and not registered, send message every x sec to visit xxx site to apply and then mod/admin has to register him. 

This thing is more auth plugin related. You can change the please register message for unregistered users and premium player will be automatically registered.
