### ISSUE TITLE
Premium username change -> few "problems".

### ISSUE THREAD

**Issue by thomaboehi** [games647/FastLogin#423]
**Hi!**

**I use FastLogin with AdvancedLogin.**
FastLogin config: https://pastebin.com/QU3bn52S
AdvancedLogin (not very useful...): https://pastebin.com/29PUh85j

It's quite new on my server, as I began to have more and more players, and wanted something better for the players that changed their username. My server runs on OnlineMode=false.

One of my players changed his username from Jobeee to mvjik. AdvancedLogin saw that, did the change, and handles him as a "cracked"... didn't really understood why. So now when we parse %fastlogin_status% on him it returns "Unknown".

So he has to enter his passcode, and second issue, he is still considerated as Jobeee....?..... I don't know what I did wrong, but I did. When he write on the chat it is Jobeee, when we look on the Dynmap it is jobeee, but if we want to change permission (LuckPerms) then it is mvjik!....

Hope you will be able to help me. Thanks

**Comment by cicatrice74** [comment]
I have this issue on my server too, premium user changed his nickname and the system does'nt know him as the same but name-changed player, asking him to login, and the parse sees him as unknown, please fix this

**Comment by thomaboehi** [comment]
You speak la france @cicatrice74 ?

**Comment by cicatrice74** [comment]
I found a way to fix this, use protocolsupport and it will fix this strange issue

**Comment by cicatrice74** [comment]
> You speak la france @cicatrice74 ?

what ?

**Comment by thomaboehi** [comment]
You're username means scar in French so I supposed you were.

Thank you for the ProtocolSupport technic, it works as a charm and fixed all the issues.
@cicatrice74
