### ISSUE TITLE
I can't login to my server | 1.16.3

### ISSUE THREAD

**Issue by powerk123** [games647/FastLogin#430]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: # (What happened?)
When I'm trying to connect my server (with protocollib and fastlogin [up to date]) the server kicks me and it prints this message: "We are unable to inject you. Please try again!"
### What behaviour is expected:
[//]: # (What did you expect?)
I expect to join my server
### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
I just put in plugin folder the latest build of fastlogin, the latest build of protocollib, the latest version of login security and i turned off online mode and BOOM when I'm trying to join my server I can't.
### Screenshots (if applicable)
[//]: # (You can drop the files here directly)
(2 - screen shots!)
![Screenshot_418](https://user-images.githubusercontent.com/76841799/103440715-a4264c00-4c50-11eb-97b2-95b83c35c080.png)
![Screenshot_417](https://user-images.githubusercontent.com/76841799/103440716-a4bee280-4c50-11eb-88fe-0c62d89fd77f.png)

### Plugin list:
[//]: # (This can be found by running `/pl`)
![Screenshot_419](https://user-images.githubusercontent.com/76841799/103441000-58c16d00-4c53-11eb-991b-1bba5f7c082d.png)

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
latest paper spigot version for 1.16.3
### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
959
### Server Log:
[//]: # (No images please - only the textual representation)
[16:34:36 INFO]:  [FastLogin]  Handling player (player_name)
### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
default Config

**Comment by games647** [comment]
Neither FastLogin nor ProtocolLi does print this message. It seems to related to Geyser.
