### ISSUE TITLE
Does FastLogin work with GeyserMC?

### ISSUE THREAD

**Issue by WalrusSlayer** [games647/FastLogin#432]
Hello!

Just curious, does this work with Geyser & Floodgate?

Thanks!

**Comment by zerrium** [comment]
It works with GeyserConnect, I can confirm this
But doesnt work with Floodgate (I have tried by myself, using premium account and premium UUID enabled)

I think it wont work with Floodgate because instead of trying to connect to MSA or Mojang authentication server for your indentity, it just uses your logged in Xbox account identity on your Bedrock Edition Minecraft

Anyway Geyser and Floodgate works flawlessly with AuthMeReloaded

**Comment by WalrusSlayer** [comment]
> It works with GeyserConnect, I can confirm this
> But doesnt work with Floodgate (I have tried by myself, using premium account and premium UUID enabled)
> 
> I think it wont work with Floodgate because instead of trying to connect to MSA or Mojang authentication server for your indentity, it just uses your logged in Xbox account identity on your Bedrock Edition Minecraft
> 
> Anyway Geyser and Floodgate works flawlessly with AuthMeReloaded

Is it possible to use fastlogin for Java players but not bedrock players?

**Comment by zerrium** [comment]
> 
> Is it possible to use fastlogin for Java players but not bedrock players?

Let me elaborate, here are what I have tested:
1) Java player using Mojang account, login from Java: yes (obviously, even with Floodgate and Geyser plugin installed)
2) Java player using Mojang account, login from bedrock via GeyserConnect: yes (even with FastLogin premium enabled)
3) Bedrock player, using Xbox account login from bedrock with Floodgate installed: yes (but you need to set that player as cracked in FastLogin)
4) Java player using Mojang account login from bedrock with Floodgate installed: no (need to set that player as cracked in FastLogin to let that player join the server)
5) Bedrock player, using Xbox account login from bedrock via GeyserConnect: obviously not if that player doesn't have a Mojang account

**Comment by WalrusSlayer** [comment]
> 3. Bedrock player, using Xbox account login from bedrock with Floodgate installed: yes (but you need to set that player as
How do I set this up> I am using AuthMeReloaded.

Currently, if people change their bedrock name, they lose access to their account :(

**Comment by WalrusSlayer** [comment]
BUMP

**Comment by zerrium** [comment]
> 
> 
> > 1. Bedrock player, using Xbox account login from bedrock with Floodgate installed: yes (but you need to set that player as
> >    How do I set this up> I am using AuthMeReloaded.
> 
> Currently, if people change their bedrock name, they lose access to their account :(

That's because if they change their gamer tag, the UUID for bedrock changed, there is no UUID per account on bedrock afaik
