### ISSUE TITLE
Mysql error: Public Key Retrieval is not allowed

### ISSUE THREAD

**Issue by PinkFloyd1213** [games647/FastLogin#433]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: # (What happened?)
When I try to use the plugin on my bungeecord server, at launch I get an error, which says "Public Key Retrieval is not allowed". 

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
Set up the plugin on a bungeecord. In the config, configure a Mysql server. The error appears at launch, in the logs. 

### Plugin list:
[//]: # (This can be found by running `/pl`)
Plugins Bungee: 
- FastLoginBungee

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
Bungeecord 1.12.2

### Plugin version or build number:
[//]: # (This can be found by running `/version plugin-name`.)
Build #959

### Server Log:
[//]: # (No images please - only the textual representation)
[Hastebin](https://hastebin.com/ifucosowuy.sql) link

### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/cejowaxeye.yaml) link

**Comment by games647** [comment]
Do you checked if the username password combination is correct for your MySQL server?

**Comment by N4M3L355** [comment]
Hello, I was having this problem too and I solved it using this solution: https://stackoverflow.com/questions/50379839/connection-java-mysql-public-key-retrieval-is-not-allowed . There is no direct way to tell plugin to allow public ke retrieval, but you can "hack" used connection string — just append the `?allowPublicKeyRetrieval=true&useSSL=false` to your database name in Fastlogin/config.yml. (Example: my database name was `'fastlogin'` so I changed it to `'fastlogin?allowPublicKeyRetrieval=true&useSSL=false'`)

**Comment by Jaedotmoe** [comment]
Got the same thing on a Waterfall server, the hack demonstrated by N4M3L355 works.

**Comment by Smart123s** [comment]
I came across this issue today, and I thought I'd drop this here.

> Hello, I was having this problem too and I solved it using this solution: https://stackoverflow.com/questions/50379839/connection-java-mysql-public-key-retrieval-is-not-allowed . There is no direct way to tell plugin to allow public ke retrieval, but you can "hack" used connection string — just append the `?allowPublicKeyRetrieval=true&useSSL=false` to your database name in Fastlogin/config.yml. (Example: my database name was `'fastlogin'` so I changed it to `'fastlogin?allowPublicKeyRetrieval=true&useSSL=false'`)

Note that allowPublicKeyRetrieval=True could allow a malicious proxy to perform a MITM attack to get the plaintext password, so it is False by default and must be explicitly enabled.
Source: https://stackoverflow.com/a/50438872/9767089
