### ISSUE TITLE
FastLogin 1.16.4 Support

### ISSUE THREAD

**Issue by DorimeDoge** [games647/FastLogin#435]
**Hello**, I want to ask, does FastLogin supports PaperMC 1.16.4 version?

**Comment by zerrium** [comment]
Yes, it does. I have been using it for long on 1.16.4
I'm curious tho, does FastLogin support premium account with MSA? (as of Dec 2020, newly bought Minecraft Java Edition copy requires Microsoft account instead of Mojang account)

**Comment by DorimeDoge** [comment]
**Hello @zerrium**, where did you downloaded the plugin? From this GitHub or from Spigot?

**Comment by zerrium** [comment]
> 
> 
> **Hello @zerrium**, where did you downloaded the plugin? From this GitHub or from Spigot?

From Jenkins

**Comment by DorimeDoge** [comment]
**Hello @zerrium**, thanks for helping!
