### ISSUE TITLE
[Suggestion] Switch cracked -> premium without lose items

### ISSUE THREAD

**Issue by Eufranio** [games647/FastLogin#44]
Is there a way to, when a player use /premium command, he become a premium user without losing items? When i type /premium (i'm premium) and re-join the server i lose everything, it is not migrated to the new UUID.

**Comment by games647** [comment]
You could try to turn off premiumUUID

**Comment by Eufranio** [comment]
If i do it, the cracked players will lose items anyway.

**Comment by games647** [comment]
No they will keep their cracked uuid. Same UUID, same .dat file -> same inventory.

**Comment by Eufranio** [comment]
They lose the inventory.

**Comment by games647** [comment]
I tried it now and I keep my inventory.

**Comment by games647** [comment]
How do you tested it?

**Comment by Eufranio** [comment]
Let me explain.

A time ago, a couple of players lose their inventories, when switching from AutoIn for FastLogin. So, i turned the server OFFLINE-MODE and i reseted the UUIDs and all playerdata.
Currently, i have some PREMIUM players (premium nicks) with the offline UUID. So, everytime that they join the server, they need use /login.
That way, i can't change their status because there is more than just a simple inventory, i run a modded server and a lot of modded things are included in the playerdata.

**Comment by games647** [comment]
>A time ago, a couple of players lose their inventories, when switching from AutoIn for FastLogin

That's proparly because they were using premium UUIDs before and FastLogin doesn't know that these players are premium.

>Currently, i have some PREMIUM players (premium nicks) with the offline UUID. So, everytime that they join the server, they need use /login.

yeah but they keep their offline uuid if you turn off premium uuid and convert all existing premium uuids to cracked.

**Comment by Eufranio** [comment]
Is there something to convert automatically these UUIDs? I have so many files... :/

**Comment by games647** [comment]
I think this is what you need: https://www.spigotmc.org/resources/uuid-playername-save-file-converter.558/

**Comment by Eufranio** [comment]
Okay, thank you by help me :smile: 
Closing the issue, as the feature already exists :P
