### ISSUE TITLE
Velocity Proxy Support ?

### ISSUE THREAD

**Issue by NekoMeowy** [games647/FastLogin#440]
[//]: # (Lines in this format are considered as comments and will not be displayed.)

### Is your feature request related to a problem? Please describe.
[//]: # (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])

### Describe the solution you'd like
[//]: # (A clear and concise description of what you want to happen.)

### Describe alternatives you've considered
[//]: # (A clear and concise description of any alternative solutions or features you've considered.)

### Additional context
[//]: # (Add any other context or screenshots about the feature request here.)
I thought that FastLogin only supports Bungeecord, and doesn't support Velocity either, I hope this can be considered!

**Comment by Lerbiq** [comment]
Would like to see it too.
As far as I know, it's being worked on but it needs a complete rewrite of the plugin since velocity has its own API.

**Comment by DoctaEnkoda** [comment]
up

**Comment by TheCompieter** [comment]
up would love to be able too try velocity for once

**Comment by games647** [comment]
Duplicate of #311
