### ISSUE TITLE
Custom AuthPlugin won't work...

### ISSUE THREAD

**Issue by xXSchrandXx** [games647/FastLogin#447]
Hey,

I wanted to create a hook for your plugin, but everytime I use a static variable, it is null...
( Tested static getAPI() and getInstance() )
Maybe you could help me with that.

<details>
<summary>Code for new AuthPlugin</summary>

```JAVA
package com.github.games647.fastlogin.bungee.hook;

import java.sql.SQLException;

import com.github.games647.fastlogin.core.hooks.AuthPlugin;

import org.slf4j.Logger;

import de.xxschrandxx.bca.bungee.BungeeCordAuthenticatorBungee;
import de.xxschrandxx.bca.bungee.api.BungeeCordAuthenticatorBungeeAPI;

import net.md_5.bungee.api.connection.ProxiedPlayer;
import net.md_5.bungee.api.plugin.Plugin;

/**
 * GitHub:
 * https://github.com/xXSchrandXx/SpigotPlugins/tree/master/BungeeCordAuthenticator
 *
 * Project page:
 *
 * Spigot: https://www.spigotmc.org/resources/bungeecordauthenticator.87669/
 */
public class BungeeCordAuthenticatorHook implements AuthPlugin<ProxiedPlayer> {

    public BungeeCordAuthenticatorBungeeAPI api;

    public boolean register(Plugin plugin, Logger log) {
        if (plugin instanceof BungeeCordAuthenticatorBungee) {
          BungeeCordAuthenticatorBungee bcab = (BungeeCordAuthenticatorBungee) plugin;
          if (bcab != null) {
            api = bcab.getAPI();
          }
        }
        else {
            log.warn("BungeeCordAuthenticatorBungee is null!");
            BungeeCordAuthenticatorBungee bcab = BungeeCordAuthenticatorBungee.getInstance();
            if (bcab != null) {
                api = bcab.getAPI();
            }
            else {
                log.warn("BungeeCordAuthenticatorBungee is null, again!");
            }
        }
        if (api == null) {
            return false;
        }
        else {
            return true;
        }
    }

    @Override
    public boolean forceLogin(ProxiedPlayer player) {
        if (api.isAuthenticated(player)) {
            return true;
        } else {
            try {
                api.setAuthenticated(player);
            }
            catch (SQLException e) {
                e.printStackTrace();
                return false;
            }
            return true;
        }
    }

    @Override
    public boolean isRegistered(String playerName) {
        try {
            return api.getSQL().checkPlayerEntry(playerName);
        }
        catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    @Override
    public boolean forceRegister(ProxiedPlayer player, String password) {
        try {
            return api.createPlayerEntry(player, password);
        }
        catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }
}
```

</details>

Here is the Link to my class with onEnable(): https://github.com/xXSchrandXx/SpigotPlugins/blob/master/BungeeCordAuthenticator/src/main/java/de/xxschrandxx/bca/bungee/BungeeCordAuthenticatorBungee.java

With best regards

xXSchrandXx

**Comment by xXSchrandXx** [comment]
I can't even cast the Plugin to my main class...

**Comment by xXSchrandXx** [comment]
[new registerHook()](https://github.com/xXSchrandXx/FastLogin/blob/951946ee4ad149a44568b2b81764f767d4aa7a82/bungee/src/main/java/com/github/games647/fastlogin/bungee/FastLoginBungee.java#L94)

[new BungeeCordAuthenticatorHook](https://github.com/xXSchrandXx/FastLogin/blob/main/bungee/src/main/java/com/github/games647/fastlogin/bungee/hook/BungeeCordAuthenticatorHook.java)

**Comment by games647** [comment]
It's properly null at the moment you want to register it. You need to set a dependency in the `plugin.yml` file, that FastLogin loads after your plugin.

**Comment by xXSchrandXx** [comment]
It is in the [softdepend](https://github.com/xXSchrandXx/FastLogin/blob/7ca514f8d2400d59a85ad6a61524046131e9341c/bungee/src/main/resources/bungee.yml#L14), it is [getting set](https://github.com/xXSchrandXx/SpigotPlugins/blob/bdb3555a30da0ad9c397c4fa6fc91b10cb27af01/BungeeCordAuthenticator/src/main/java/de/xxschrandxx/bca/bungee/BungeeCordAuthenticatorBungee.java#L28) and FastLogin has to load after BCA...

Even in my plugin it can use the method `getInstance()` without getting Null...

**Comment by games647** [comment]
Your plugin name is incorrect: https://github.com/xXSchrandXx/SpigotPlugins/blob/bdb3555a30da0ad9c397c4fa6fc91b10cb27af01/BungeeCordAuthenticator/src/main/resources/plugin.yml#L1

**Comment by xXSchrandXx** [comment]
BungeeCord will use the [bungee.yml](https://github.com/xXSchrandXx/SpigotPlugins/blob/bdb3555a30da0ad9c397c4fa6fc91b10cb27af01/BungeeCordAuthenticator/src/main/resources/bungee.yml) and the [filter](https://github.com/xXSchrandXx/SpigotPlugins/blob/bdb3555a30da0ad9c397c4fa6fc91b10cb27af01/pom.xml#L113) is set as well.

**Comment by xXSchrandXx** [comment]
Moved this here: https://www.spigotmc.org/threads/getinstance-an-getapi-returns-null-in-second-plugin.485542/
