### ISSUE TITLE
Can't connect to bungeecore

### ISSUE THREAD

**Issue by shishir9747** [games647/FastLogin#448]
I put bukkit version on bukkit server and bungee version on bungee server. then put server stats from bungee config.yml to allowed-proxies.txt but still not working. I am not sure. if it is ok or I have to do anything.

**Comment by XenderLord** [comment]
Yeah i also don't know how to get this to work, do we also have to setup a database like MySQL or MariaDB, and how do we do that? I have never made something like a database because I never needed to. Please someone help us.

**Comment by games647** [comment]
You should not skip the last step. BungeeCord has only support for MySQL/MariaDB, so it is **required**. @shishir9747 Check your logs for any errors.
