### ISSUE TITLE
Access token cannot be null

### ISSUE THREAD

**Issue by mat41997** [games647/FastLogin#45]
logs
`[23:35:17] [Server thread/INFO]: /192.168.7.50:51261 lost connection: Disconnected`

ss
![1](https://cloud.githubusercontent.com/assets/5884000/17264119/498b6a98-55e5-11e6-923c-579c88e5720d.png)

config
http://pastebin.com/zpQQD81z

my nick
![2](https://cloud.githubusercontent.com/assets/5884000/17264207/be50ecc2-55e5-11e6-81f7-825375f80402.png)

timings
https://timings.aikar.co/v2/?id=f49c723a57c94466a015b6ede3533054

**Comment by games647** [comment]
FastLogin requests a premium authentication from you, but you doesn't seem to be authenticated with that launcher.

**Comment by mat41997** [comment]
no,

i can join to server on nick "test13"

**Comment by games647** [comment]
Yes but your username activated premium authentication.

**Comment by mat41997** [comment]
yes

**Comment by mat41997** [comment]
you can add support this message "Failed to login: Access Token can not be null or empty."

to message.yml file?

**Comment by games647** [comment]
No that's an message included in the client jar.

**Comment by mat41997** [comment]
ok
