### ISSUE TITLE
microsoft account support

### ISSUE THREAD

**Issue by cicatrice74** [games647/FastLogin#456]
Some player of my server just bought minecraft premium but they now have only microsoft account to enter launcher but it is not recognised by fastlogin as a premium user, can this be fixed, i think it will become the only way in the next future to log on the minecraft's laucnher.

**Comment by games647** [comment]
Please provide an example username

**Comment by cicatrice74** [comment]
Kutateki_ is a nickname of a premium msa account minecraft, i had to manage him like cracked to let him login, neither he is auto kicked for using premium name but not recognised

**Comment by cicatrice74** [comment]
Is the developer looking to support MSA system ?
I provided username but can someone tell me if the resource will be ever updated or not ?

**Comment by ham1255** [comment]
in my case fastlogin does recoingze it as minecraft username

**Comment by games647** [comment]
I took a look into it. The Mojang API reports the player in the same way as before like a Mojang account. There are no differences to the previous system. Please provide the log at the time it's happening again and include your server configuration. It can reopened once reproduced.

**Comment by games647** [comment]
I guess it took some time until the bought status is reflected in the API.
