### ISSUE TITLE
nameChangeCheck: true [Broken]

### ISSUE THREAD

**Issue by WalrusSlayer** [games647/FastLogin#457]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: # (What happened?)
nameChangeCheck: true 
Does not work.
### What behaviour is expected:
[//]: # (What did you expect?)
My issue is that when a premium user, for instance: "Anthony555" changes his name to "DogLover115", it treats doglover115 as a different account even though its the same premium user. Based on the info in the config, it should automatically sign you in if you change your name and are a premium user. Everything else in the plugin works flawlessly.
### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
Simply enable nameChangeCheck: true in the config, and have a premium account change its name. It won't auto log them in. Instead, it treats them as a separate cracked user. even when premium UUID's are enabled as well.
### Screenshots (if applicable)
[//]: # (You can drop the files here directly)
![image](https://user-images.githubusercontent.com/40503028/107146553-1573b180-6917-11eb-98a5-45a19249765e.png)
### Plugin list:
[//]: # (This can be found by running `/pl`)
![image](https://user-images.githubusercontent.com/40503028/107146841-91bac480-6918-11eb-84b0-2753680651f7.png)
### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
PaperMC #465 (1.16.5) Waterfall #395, MySQL.
### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
1.11-SNAPSHOP-9ff404a
### Server Log:
[//]: # (No images please - only the textual representation)
Paper: https://paste.gg/p/Walrus2020/ba5f3eba66204f6aa6304c2bb6d6e7f9
Waterfall: https://paste.gg/p/Walrus2020/d393622969a4435f8675cec3cac57f5c
### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
https://paste.gg/p/Walrus2020/ad08b1a9fed447e59e750c025c742765

**Comment by Kamilkime** [comment]
It's not a perfect solution, but I've managed to 'repair' it in #437

**Comment by WalrusSlayer** [comment]
> It's not a perfect solution, but I've managed to 'repair' it in #437

Thanks mate! Fingers crossed it works!

Is it an ongoing solution or do I need to reset it everytime someone changes their username?

Additionally, do I need to do it on every server (ex. creative & survival), or just my hub server?

Thanks!

**Comment by Kamilkime** [comment]
> Is it an ongoing solution or do I need to reset it everytime someone changes their username?
Changing `user-cache-size` to 0 just disables it so you only need to do that once

> Additionally, do I need to do it on every server (ex. creative & survival), or just my hub server?
On every server where you use FastLogin - that solution works locally, on a specific server. I don't know how is it with bungeecord, but might be similar

**Comment by WalrusSlayer** [comment]
> > Is it an ongoing solution or do I need to reset it everytime someone changes their username?
> > Changing `user-cache-size` to 0 just disables it so you only need to do that once
> 
> > Additionally, do I need to do it on every server (ex. creative & survival), or just my hub server?
> > On every server where you use FastLogin - that solution works locally, on a specific server. I don't know how is it with bungeecord, but might be similar

Thanks for the quick reply!

On bungee, I only need fastlogin & authme on the hub server, so that's why I assume it works the same, but I don't know :D

**Comment by Kamilkime** [comment]
> On bungee, I only need fastlogin & authme on the hub server, so that's why I assume it works the same, but I don't know :D

I meant that FastLogin has a bungeecord version, bungeecord probably also has a similar usercache - which would break the name change

**Comment by WalrusSlayer** [comment]
> > On bungee, I only need fastlogin & authme on the hub server, so that's why I assume it works the same, but I don't know :D
> 
> I meant that FastLogin has a bungeecord version, bungeecord probably also has a similar usercache - which would break the name change

Ah I see. I don't believe it has a user cache. At least, I couldn't find it :D

**Comment by WalrusSlayer** [comment]
> > On bungee, I only need fastlogin & authme on the hub server, so that's why I assume it works the same, but I don't know :D
> 
> I meant that FastLogin has a bungeecord version, bungeecord probably also has a similar usercache - which would break the name change

Just tested and it does not work :(

**Comment by Kamilkime** [comment]
Is the usercache.json file in your server folder empty?

**Comment by WalrusSlayer** [comment]
> Is the usercache.json file in your server folder empty?

Yes

**Comment by Kamilkime** [comment]
So now... Maybe that's the minecraft being stupid - after name change you need to at least restart the game, sometime also logout and login again into the launcher

**Comment by WalrusSlayer** [comment]
Tested, but still does not work :(

**Comment by Kamilkime** [comment]
Hmm... I have no more ideas for now :/
I'll try to implement a more permanent solution in a couple days

**Comment by WalrusSlayer** [comment]
> Hmm... I have no more ideas for now :/
> I'll try to implement a more permanent solution in a couple days

Thanks mate!

Someone said this would fix it, is this true?
![image](https://user-images.githubusercontent.com/40503028/107164025-edb63500-697a-11eb-9dca-cabb5ca22aa6.png)

**Comment by Kamilkime** [comment]
If I understand the whole problem correctly - right now the only fix could be disabling the usercache, that caching should be the only issue. FastLogin makes all the checks before Spigot actually starts logging the player in, and that logging (using the cache because of online-mode set to false) is overwriting the actual session from the player. So if disabling usercache doesn't work... Right now I have no more ideas :/

On my server - it correctly sees the new player names now, but because AuthMe still uses names instead of UUIDs - it has to autoRegister the player again, but it all works automatically now

**Comment by WalrusSlayer** [comment]
> If I understand the whole problem correctly - right now the only fix could be disabling the usercache, that caching should be the only issue. FastLogin makes all the checks before Spigot actually starts logging the player in, and that logging (using the cache because of online-mode set to false) is overwriting the actual session from the player. So if disabling usercache doesn't work... Right now I have no more ideas :/
> 
> On my server - it correctly sees the new player names now, but because AuthMe still uses names instead of UUIDs - it has to autoRegister the player again, but it all works automatically now

Could it be an AuthMeReloaded issue or is it definitely FastLogin?

**Comment by Kamilkime** [comment]
> Could it be an AuthMeReloaded issue or is it definitely FastLogin, or even LuckPerms?

Definitely FastLogin + online-mode set to false - Spigot uses that cache, because if you've disabled online-mode - new nickname should mean a new UUID. But because FastLogin logs some players using a fake online-mode - they still have the same UUID, even after nickname change. But the server thinks its in offline-mode - so it just ignores session data and uses the cache, it's quicker that way. So what FastLogin has to do - set the UUID and nickname in the player's gameprofile before the server tries to use the cache, and that's what's missing from FastLogin and why disabling the cache should work for most people

**Comment by WalrusSlayer** [comment]
> > Could it be an AuthMeReloaded issue or is it definitely FastLogin, or even LuckPerms?
> 
> Definitely FastLogin + online-mode set to false - Spigot uses that cache, because if you've disabled online-mode - new nickname should mean a new UUID. But because FastLogin logs some players using a fake online-mode - they still have the same UUID, even after nickname change. But the server thinks its in offline-mode - so it just ignores session data and uses the cache, it's quicker that way. So what FastLogin has to do - set the UUID and nickname in the player's gameprofile before the server tries to use the cache, and that's what's missing from FastLogin and why disabling the cache should work for most people

Any chance you could come on my server? It's mcvantage.net

Were you able to read over my configs attached in the original post?

I really need this to work, and I'm worried that it's a separate issue :(

**Comment by WalrusSlayer** [comment]
> > > Could it be an AuthMeReloaded issue or is it definitely FastLogin, or even LuckPerms?
> > 
> > 
> > Definitely FastLogin + online-mode set to false - Spigot uses that cache, because if you've disabled online-mode - new nickname should mean a new UUID. But because FastLogin logs some players using a fake online-mode - they still have the same UUID, even after nickname change. But the server thinks its in offline-mode - so it just ignores session data and uses the cache, it's quicker that way. So what FastLogin has to do - set the UUID and nickname in the player's gameprofile before the server tries to use the cache, and that's what's missing from FastLogin and why disabling the cache should work for most people
> 
> Any chance you could come on my server? It's mcvantage.net
> 
> Were you able to read over my configs attached in the original post?
> 
> I really need this to work, and I'm worried that it's a separate issue :(

It seems /premium does not let them move even after successfully initiating it either which I tried to do as a workaround.

**Comment by WalrusSlayer** [comment]
Okay, it worked when they entered their mojang password.

**Comment by Kamilkime** [comment]
My changes including a more permanent fix were merged into the official repository, so a .jar with them should be available soon at https://ci.codemc.io/job/Games647/job/FastLogin/ (it will be build #960)

**Comment by WalrusSlayer** [comment]
> My changes including a more permanent fix were merged into the official repository, so a .jar with them should be available soon at https://ci.codemc.io/job/Games647/job/FastLogin/ (it will be build #962)

Thanks mate!
