### ISSUE TITLE
Can i implement FastLogin check by myself? 

### ISSUE THREAD

**Issue by gepron1x** [games647/FastLogin#461]
Hello, im developing a bungeecord auth plugin, and i think it would be cool to have FastLogin support. Can i do it by myself or should i request you?

**Comment by ElCholoGamer** [comment]
I'm not sure if this is absolutely correct, but the way I have implemented the plugin works fine.

What I did was [implement the AuthPlugin](https://github.com/ElCholoGamer/userlogin/blob/master/src/main/java/com/elchologamer/userlogin/util/FastLoginHook.java) class along with its methods, and [register the hook](https://github.com/ElCholoGamer/userlogin/blob/master/src/main/java/com/elchologamer/userlogin/UserLogin.java#L68) at startup.
