### ISSUE TITLE
Bot Attack

### ISSUE THREAD

**Issue by WalrusSlayer** [games647/FastLogin#466]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: # (What happened?)
https://paste.gg/p/Walrus2020/8169509e265c4c36b76e58ca9fecb2be
### Plugin list:
[//]: # (This can be found by running `/pl`)
![image](https://user-images.githubusercontent.com/40503028/107831886-14021900-6d5d-11eb-9ec4-02285611b092.png)
![image](https://user-images.githubusercontent.com/40503028/107831927-2ed48d80-6d5d-11eb-84ba-34fb25b17925.png)

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
Paper #467. Waterfall #395
### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
![image](https://user-images.githubusercontent.com/40503028/107831993-575c8780-6d5d-11eb-8480-f070258633a9.png)

### Server Log:
[//]: # (No images please - only the textual representation)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error, stacktrace or the complete log (if any)
https://paste.gg/p/Walrus2020/8169509e265c4c36b76e58ca9fecb2be
### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
https://paste.gg/p/Walrus2020/354957472a1f4a2abbebcb7907c7a5f8

I talked to a papermc dev and was told this:
![image](https://user-images.githubusercontent.com/40503028/107832205-d782ed00-6d5d-11eb-8340-a6b31423c5e8.png)
Thanks!

**Comment by games647** [comment]
"Rate Limit your firewall"

**Comment by games647** [comment]
FastLogin **already** begins ignoring new players. LuckPerms begins to throw errors.
