### ISSUE TITLE
Not working on Bungeecord

### ISSUE THREAD

**Issue by Warrior-of-San** [games647/FastLogin#470]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
FastLogin doesnt log premium players in, even after manually adding them to premium list (bungeecord)

### What behaviour is expected:
That it would login premium players when they enter the lobby.

### Steps/models to reproduce:
Do things from https://github.com/games647/FastLogin#bungeecordwaterfall-1
Note: I was putting the FastLoginBungee and FastLoginBukkit in any combination, on bungee and the other servers, as it is not clear to me if i need the bukkit ones and where, and it never worked

### Plugin list:
Authme, Fastlogin, Protocolib,  Skinrestorer

### Environment description
Bungeecord - build 1500
Minecraft Version - 1.15.2
Fastlogin Version - 
Authme Version - AuthMe v5.6.0-SNAPSHOT-b2440
Database - MySQL

### Plugin version or build number (don't write latest):
FastLogin v1.11-SNAPSHOT-aa73485

### Server Log:
If it Starts, then there is "error":
[Server thread/INFO]: [FastLogin] Hooking into auth plugin: AuthMeHook
[Server thread/INFO]: [FastLogin] BungeeCord setting detected. No auth plugin is required

If you try to enter the server, there is:
[FastLogin] No on-going login session for player: CraftPlayer{name=NAME} with ID PLAYER_IP

### Configuration:
https://gist.github.com/Warrior-of-San/d3f84c6d2f1937e9947aea6d4fb40dc9

**Comment by games647** [comment]
>If it Starts, then there is "error":

This isn't an error. Please post your bungee log.

**Comment by Warrior-of-San** [comment]
https://gist.github.com/Warrior-of-San/f8b094d56209bee852ba92dbe28d780b here you go, log from a first mention of FastLogin

**Comment by games647** [comment]
Please post it at the time when the player logs in.

**Comment by Warrior-of-San** [comment]
11:42:43 [INFO] [FastLogin] Incoming login request for NAME from /IP
11:42:43 [INFO] [FastLogin] Handling player NAME
11:42:43 [INFO] [FastLogin] Requesting premium login for registered player: NAME
11:42:44 [INFO] [FastLogin] Overridden UUID from UUID1 to UUID2 (based of NAME) on [NAME,/IP] <-> InitialHandler

**Comment by games647** [comment]
Could you show the full server log at the time of the login. It seems to fail to forward the Bungee message.

**Comment by Warrior-of-San** [comment]
Finally got it to work, turns out MySQL, bungeecord and minecraft server started in a wrong order, after modifying the startup script to start server at the end, it all works fine
