### ISSUE TITLE
Premium login doesnt work (errors)

### ISSUE THREAD

**Issue by NockyCZ** [games647/FastLogin#477]
Hi guys, i need please help. When a player enables Premium and connect, so autologin doesnt work. And it write this error
I using AdvancedLogin plugin

https://paste.gg/p/anonymous/5cc9ec59bb1e4070b70f8d5dec7c4570

**Comment by Kamilkime** [comment]
You're probably using and old FastLogin build, you can download the newest one here: https://ci.codemc.io/job/Games647/job/FastLogin/967/changes

**Comment by NockyCZ** [comment]
I have latest version - Build #967 (Thu Feb 18 17:27:03 UTC 2021) FastLoginBukkit.jar for my Spigot server

**Comment by games647** [comment]
>v1.10-git484855724b794de1fe057cf7360245362658b432

That's the outdated version. You properly have still the old version installed, because it has different name.
