### ISSUE TITLE
Possible bug when loggin in, sometimes not loading inventary

### ISSUE THREAD

**Issue by ricsal1** [games647/FastLogin#481]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

Hi there,

Just found on my server, using multicore for several worlds, that sometimes I loggin with my stuff and sometimes I login without my stuff.

Using LoginSecurity-3.0.3-SNAPSHOT-Bukkit pluggin for secondary autentication.

Do you know any issued that can create this?

The server is tontito.mooo.com:25599

### What behaviour is observed:
[//]: # (What happened?)
that sometimes I loggin with my stuff and sometimes I login without my stuff (inventory)

### What behaviour is expected:
[//]: # (What did you expect?)
Always login with my stuff

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)

### Screenshots (if applicable)
[//]: # (You can drop the files here directly)

### Plugin list:
[//]: # (This can be found by running `/pl`)

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
Paper version this this week, no sql database

### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
LoginSecurity-3.0.3-SNAPSHO
FastLogin v1.11-SNAPSHOT-ff2e5c0
Some other pluggins that shouldn't be related

### Server Log:
[//]: # (No images please - only the textual representation)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error, stacktrace or the complete log (if any)

### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file

**Comment by Kamilkime** [comment]
Could you please provide the full plugin list?

**Comment by ricsal1** [comment]
![imagem](https://user-images.githubusercontent.com/25226624/109714629-8a46ae00-7b9a-11eb-8551-8f198d87e2ae.png)

**Comment by ricsal1** [comment]
Hello, I confirm the issue exists.

Please try tontito.mooo.com and grab something.

Then logout and login several times

**Comment by games647** [comment]
The auth plugin is responsible for restoring the inventory. FastLogin only issues the command to start the login process.
