### ISSUE TITLE
First time players are told to either use /login or authenticate with Minecraft. How do I configure fastlogin so that it does not say these things?

### ISSUE THREAD

**Issue by WalrusSlayer** [games647/FastLogin#482]
Players currently are told to login even though they have not set a password. Others are told this:
![image](https://user-images.githubusercontent.com/40503028/109775209-37d3b480-7bcf-11eb-9465-5ca91a571b35.png)
^^ The above seems to happen if a user crashes on first login.

How do I configure fastlogin so that it will work? (I also use authmereloaded, geysermc, and floodgate)

Thanks!

**Comment by games647** [comment]
Please post your configuration

**Comment by WalrusSlayer** [comment]
https://paste.gg/p/Walrus2020/752882cad7134b1ab5a78899ea15ae7e

Thanks for the quick response!

**Comment by WalrusSlayer** [comment]
> Please post your configuration
https://paste.gg/p/Walrus2020/752882cad7134b1ab5a78899ea15ae7e

Thanks for the quick response!

**Comment by WalrusSlayer** [comment]
> Please post your configuration


https://paste.gg/p/Walrus2020/752882cad7134b1ab5a78899ea15ae7e

Thanks for the quick response!

**Comment by games647** [comment]
You have autoRegister enabled. That's part of the setting. Check the warning above that configuration option.

**Comment by WalrusSlayer** [comment]
> You have autoRegister enabled. That's part of the setting. Check the warning above that configuration option.

How can I allow it to still auto login premium users if I set it to false?

What will premium users have to do if they are not auto-registered?

**Comment by WalrusSlayer** [comment]
> You have autoRegister enabled. That's part of the setting. Check the warning above that configuration option.

Okay, I can confirm this did not fix it. I even tried unregistering their account. Unfortunately, there was no change.

**Comment by WalrusSlayer** [comment]
> You have autoRegister enabled. That's part of the setting. Check the warning above that configuration option.

Thanks!

**Comment by WalrusSlayer** [comment]
> You have autoRegister enabled. That's part of the setting. Check the warning above that configuration option.

So now everyone has to do /premium to be able to join. Is there a way to get it to be automatic?

**Comment by games647** [comment]
>What will premium users have to do if they are not auto-registered?

Type the premium command

>So now everyone has to do /premium to be able to join. Is there a way to get it to be automatic?

If you disable autoRegister all players are able to join, because everyone is assumed to be cracked (except with switchMode). This option automatically enables it. However with the mentioned downside. See the header above the configuration option for more details.

**Comment by WalrusSlayer** [comment]
> > What will premium users have to do if they are not auto-registered?
> 
> Type the premium command
> 
> > So now everyone has to do /premium to be able to join. Is there a way to get it to be automatic?
> 
> If you disable autoRegister all players are able to join, because everyone is assumed to be cracked (except with switchMode). This option automatically enables it. However with the mentioned downside. See the header above the configuration option for more details.

Ok so I tried the autoRegister enabled and not a single cracked player can connect through any means, making the feature pointless.

**Comment by WalrusSlayer** [comment]
I set autoRegister to false now and literally no one can login.

**Comment by WalrusSlayer** [comment]
Using authme, if I do /authme forcelogin it works for that session (logging out has the same issue), but I'm quite certain it's a fastlogin issue as it is the only thing I have touched and their Discord support believes it's a fastlogin issue.

**Comment by games647** [comment]
That exactly documented as I said earlier. There a lot of people who like this option. It's your choice.

**Comment by games647** [comment]
You can combine it with secondAttempt. However it still has the documented limitation. There is no way to change it. Therefore I'm closing this.
