### ISSUE TITLE
Only op players are detected as premium. Normal players are not. [Failed to check premium state]

### ISSUE THREAD

**Issue by Vexcenot** [games647/FastLogin#488]
I can't seem to get the plugin to detect premium users properly. They still need to register and are not being put into their premium uuid that was generated before the server went offline. Here's my config https://mcpaste.io/ef2e1179f713ac81

No errors in console, I'm using the latest dev build

It's only detecting the op player, CC69, of having a premium uuid but any other normal player (CharAlore) does not https://pastebin.com/sDxNZ5Vb

Is there a permission to get the premium uuid that I'm supposed to add? Might not be a plugin exclusive issue since the same thing with Anvil login where it is not detecting players as premium but honestly Idk what's wrong at this point. 

If there's something you need to test on my server then please be my guest

**Comment by games647** [comment]
You have an invalid configuration file. The nameChangeCheck value is invalid.

**Comment by Vexcenot** [comment]
> You have an invalid configuration file. The nameChangeCheck value is invalid.

oh lmao. I feel very stupid for taking the comment seriously. Ye, so far I think it's working as intended now. I Will update if it doesn't
