### ISSUE TITLE
fast loginc error

### ISSUE THREAD

**Issue by pinuxio** [games647/FastLogin#489]
Hi, I just installed fastlogin I set everything as per tutorial unfortunately when I go to do the Premium command I get this error.
Sending request... (Do not forget to follow the BungeeCord setup guide)
the whole thing is on a bungeecord server for Minecraft 1.16.1 5

**Comment by games647** [comment]
Well... Do you followed the setup guide?

**Comment by pinuxio** [comment]
yes

**Comment by games647** [comment]
You have to follow it completely. BungeeCord has no driver for SQLite and therefore doesn't create a db file. You need to switch to MySQL/MariaDB. Check your BungeeCord logs.

**Comment by pinuxio** [comment]
> Devi seguirlo completamente. BungeeCord non ha driver per SQLite e quindi non crea un file db. Devi passare a MySQL / MariaDB. Controlla i tuoi registri BungeeCord.

in a previous version it used the sqlLite db, however I followed the guide step by step

**Comment by games647** [comment]
As I said BungeeCord doesn't support it. You have to use MySQL or MariaDB.

**Comment by pinuxio** [comment]
> Come ho detto, BungeeCord non lo supporta. Devi usare MySQL o MariaDB.

why is this in the config?
# Single file SQLite database
driver: 'org.sqlite.JDBC'
# File location
database: '{pluginDir} /FastLogin.db'

**Comment by games647** [comment]
This configuration is shared between Spigot and BungeeCord. Check the Bungee logs. You can also include the SQLite driver manually, but it's complicated to do so. Nevertheless, this plugin offers you to do so.

**Comment by pinuxio** [comment]
> Questa configurazione è condivisa tra Spigot e BungeeCord. Controlla i registri Bungee. Puoi anche includere manualmente il driver SQLite, ma è complicato farlo. Tuttavia, questo plugin ti offre di farlo.
So I'll explain: the first time I installed Quick Access I did it on egis with paper version 1 16.4 and it worked fine following the guide you posted online, it had automatically created the file for me without any problem. now I have redone everything with Bungeecord and paper 1.16.5 because aegis gives me problems but this time also following the step by step guide releases me The error I posted above. or even set for mysql but nothing The error remains the same.

**Comment by games647** [comment]
Please post the Bungee log.

**Comment by pinuxio** [comment]
> Pubblica il registro Bungee.

I managed to install the plugin is to make it work even giving the pins the permissions when a user I no longer type the command Premium Premium It gives me this message even if in pex I put the following permissions:
pex     - fastlogin.bukkit.command.premium
    - fastlogin.bukkit.command.cracked
    - fastlogin.command.premium.other
    - fastlogin.command.cracked.other
	
message non op
not enough permissions

 Also I can not understand why every time I have to enter the password

**Comment by pinuxio** [comment]
> Questa configurazione è condivisa tra Spigot e BungeeCord. Controlla i registri Bungee. Puoi anche includere manualmente il driver SQLite, ma è complicato farlo. Tuttavia, questo plugin ti offre di farlo.

I solved it by installing the following SQLite-for-BungeeCord.jar plugin in the bungecoord folder, the only problem is that while giving permissions, those who are not OPs do not have permissions

**Comment by games647** [comment]
Then I'm closing this ticket in favor of the other one.
