### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by friishon** [games647/FastLogin#49]
i have a bungee server, and i use loginsecurity, but all the time i have to write /login mypassword
i use mysql in both of them

**Comment by games647** [comment]
Do you followed the setup guide: https://github.com/games647/FastLogin#bungeecordwaterfall-1
Do you have autoRegister enabled? If so it's only activated for new unregistered players.

**Comment by friishon** [comment]
thanks , just happens with my account , other users can enter without problems

**Comment by games647** [comment]
You could also activate premium logins after registration with /premium. The autoRegister is only used for new players.

**Comment by friishon** [comment]
i put /premium, but all time i have to write /login

**Comment by games647** [comment]
That could mean that your whitelist file is incorrect

**Comment by friishon** [comment]
only happends on my acount, because, i create my user before put your plugin, it,s my error, sorry

**Comment by games647** [comment]
You know that you need to perform /premium twice to accept the warning?

**Comment by friishon** [comment]
yes, i do that

**Comment by games647** [comment]
What does your database record from FastLogin look like?

**Comment by friishon** [comment]
i don't look it, the problem is mine, because, i create the user in login security before put fastlogin
 i try in another server, to create the user and write /premium and it's work
