### ISSUE TITLE
Premium Java players have to do /premium. Is there a way to bypass this?

### ISSUE THREAD

**Issue by WalrusSlayer** [games647/FastLogin#491]
Premium Java players have to do /premium. Is there a way to bypass this? Thanks!

**Comment by Wolfcoool** [comment]
Line 37 of config.yml, set "autoRegister: true".

**Comment by WalrusSlayer** [comment]
> Line 37 of config.yml, set "autoRegister: true".

Issue with this: #482

**Comment by games647** [comment]
autoRegister makes a decision based on the player name. If the player choose a premium username, the plugin request an online mode authentication. The client will just disconnect, if it cannot provide that. See the explanation in the config for more details.

**Comment by WalrusSlayer** [comment]
> autoRegister makes a decision based on the player name. If the player choose a premium username, the plugin request an online mode authentication. The client will just disconnect, if it cannot provide that. See the explanation in the config for more details.

If they re-join, can they choose a different name or do /cracked?

**Comment by games647** [comment]
The name is chosen by the Minecraft client. The server just receives it. Second attempt will likely do what you want. There they do not have rename them self and could still join as cracked.
