### ISSUE TITLE
Floodgate 2.0 support

### ISSUE THREAD

**Issue by KeyloHyum** [games647/FastLogin#498]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: # (What happened?)
When I switched from Floodgate 1.0 to Floodgate 2.0 my FastLogin stopped working. It says that:
`[FastLogin] No on-going login session for player: `
Here are logs when using Floodgate 2.0 and without floodgate 2.0 (with floodgate 1.0 it works):

Without floodgate 2.0: https://pastebin.com/r15g0HZ4
With floodgate 2.0: https://pastebin.com/Q2RrJzsP
### What behaviour is expected:
[//]: # (What did you expect?)
It should normally work.
### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
1. Download Floodgate 2.0 and try join the server with activated FastLogin (via /premium) or automatically on first join.
2. You wouldn't be auto logged in.
### Screenshots (if applicable)
[//]: # (You can drop the files here directly)
Aren't needed.
### Plugin list:
[//]: # (This can be found by running `/pl`)
Isn't needed.
### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
MySQL
### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
![image](https://user-images.githubusercontent.com/76599428/112759064-9c790800-8ff1-11eb-9f35-4a7627dcde88.png)

![image](https://user-images.githubusercontent.com/76599428/112759065-9d119e80-8ff1-11eb-9d51-6496b24e3a46.png)

### Server Log:
[//]: # (No images please - only the textual representation)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error, stacktrace or the complete log (if any)
Without floodgate 2.0: https://pastebin.com/r15g0HZ4
With floodgate 2.0: https://pastebin.com/Q2RrJzsP
### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file 
I had to use another website, cause on pastebin & hastebin it didn't work. https://paste.ee/p/9CJQ7

Maybe, isn't it due to allowed proxies and some private keys from Floodgate 2.0?

**Comment by bobhenl** [comment]
Link: https://github.com/games647/FastLogin/issues/498#issue-842772795

**Comment by Smart123s** [comment]
@bobhenl https://github.com/games647/FastLogin/pull/494 is for Bukkit only servers, not for Bungeecord, so that will be a separate PR. But the Bukkit only implementation in https://github.com/games647/FastLogin/pull/494 is also broken.

**Comment by Smart123s** [comment]
Apparently, `FloodgateAPI` was changed to `FloodgateApi` in v2.0, and the first one is used in FastLogin, so that might be the root cause of the problem. I'll try changing it if I'll have some spare time.

**Comment by cmod31** [comment]
is it also possible to login bedrock only players who didnt link their java account/profile?
