### ISSUE TITLE
Premium UUID

### ISSUE THREAD

**Issue by games647** [games647/FastLogin#5]
Add a configuration option to use a premium UUIDs if the player logged in as a premium player.

**Comment by SkymaxPlay** [comment]
I think that, you can do this when send to the server fake start packet and change: UUID.randomUUID(); to UUID gave from minecraft api website by send username.

**Comment by games647** [comment]
Good idea I thought that too, but the uuid is ignored there. A login start packet only contains the player name. 

My idea is to indirectly fake a handshake packet. BungeeCord can forward the real IP, UUID and profile properties to a Spigot server (if the bungeecord support is activated). This is done with the Handshake packet. Recently I failed with creating fake handshake packets, but I found out that we could still set the this forwarding uuid with Reflection. 

As you can see [here](https://github.com/bergerkiller/CraftSource/blob/master/net.minecraft.server/LoginListener.java#L88) Spigot only checks if the value is set and not if the config option is activated. 

On offline mode servers this value is read on an incoming loginstart packet. So we could set this value between a handshake and loginstart packet.

**Comment by SkymaxPlay** [comment]
OK,
Sorry, I thought about packet Login Success. This packet contains username and UUID. I think that after receive this packet bukkit set player's UUID from this packet.

**Comment by games647** [comment]
>Sorry,

No problem

> Login Success

This packet is sent from the server to the player. So we would only modify it for the receiving player.

**Comment by SkymaxPlay** [comment]
hmmm, Ok, Where is the method when bukkit set the UUID of player?

**Comment by games647** [comment]
Offline Mode:
https://github.com/bergerkiller/CraftSource/blob/master/net.minecraft.server/LoginListener.java#L93
https://github.com/bergerkiller/CraftSource/blob/master/net.minecraft.server/LoginListener.java#L96

Online mode:
https://github.com/bergerkiller/CraftSource/blob/master/net.minecraft.server/LoginListener.java#L202

**Comment by SkymaxPlay** [comment]
Hmmm ok, Why you don't create new instance of class LoginListener and set the field "i" to your data and use method "a" from LoginListener with parameter "PacketLoginInEncryptionBegin". Create fake packet and edit content with your's data and execute the method?

**Comment by games647** [comment]
This would require a lot of work with Reflection, because we need to replace the existing class at runtime which is created on every new connection. Moreover the project would be heavily dependent on minecraft code which could change often. But yes it's an alternative solution which could work. Maybe we could implement it as a fallback or configurable.
