### ISSUE TITLE
[Paper] How does the skin influence name change

### ISSUE THREAD

**Issue by krystalgamer** [games647/FastLogin#506]
Greetings,

I noticed this file and reading the respective PR I couldn't understand how it works: https://github.com/games647/FastLogin/blob/d6a02aa5385ef7eb6c8b2f2169dfae1a351ef5b8/bukkit/src/main/java/com/github/games647/fastlogin/bukkit/listener/PaperPreLoginListener.java#L48

How does setting the skin influence the name? Or `skin.getValue()` includes the `name` field?

**Comment by games647** [comment]
Paper likely matches on the complete `GameProfile` including the skin and not only the UUID and name. Maybe @Kamilkime could explain it in more detail.

**Comment by krystalgamer** [comment]
@Kamilkime thanks so much for the in-depth explanation!
