### ISSUE TITLE
FastLogin on Snap!

### ISSUE THREAD

**Issue by 7wOv6ySCjo** [games647/FastLogin#509]
Hi. I have FastLogin running on [Snap!](https://forums.velocitypowered.com/t/snap-run-bungeecord-plugins-on-velocity/608) on Velocity.

FastLogin Requires a stats-id that Velocity and Snap don't give me, how can I replace this?
Velocity don't use stats id.

I just need this stat-id to get everything ready for production.
Thanks.

**Comment by games647** [comment]
FastLogin doesn't support Snap. FastLogin only supports the Bungee API. Snap has to add support for static proxy ids. 

Supporting a specific implementation of an API is a bad idea, that's why FastLogin recently drops it's requirements to the Bungee API, but without offline UUID support.
