### ISSUE TITLE
Error when premium player joins

### ISSUE THREAD

**Issue by itzJOHv** [games647/FastLogin#515]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
Error when premium player joins

### What behaviour is expected:
Basic autologin

### Steps/models to reproduce:
1. Install LogicSecurity
2. Install FastLogin
3. Join server and execute `/premium`
4. rejoin, see error in console

### Plugin list:
Plugins (17): AdvancedBan*, AdvancedTabOverlay, Chatty, CoreProtect, DiscordSRV, EasyWhitelist*, FastLogin*, GSit, LoginSecurity*, LuckPerms, OpenInv, PlaceholderAPI, PlugMan, ProtocolLib, ServerlistMOTD*, SkinsRestorer, sleep-most

### Environment description
This server is running Yatopia version git-Yatopia-"99e3c5d" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT), built-in SQLite.

### Plugin version or build number (don't write latest):
FastLogin version 1.10-git484855724b794de1fe057cf7360245362658b432

### Server Log:
[Pastebin](https://pastebin.com/0YFRe9T9)

### Configuration:
[Pastebin](https://pastebin.com/iSbpKJsk)

**Comment by games647** [comment]
Outdated plugin version

**Comment by itzJOHv** [comment]
where can I get latest?

**Comment by games647** [comment]
Download a dev build. Link is on the project page.
