### ISSUE TITLE
Config error?

### ISSUE THREAD

**Issue by crazyhoorse961** [games647/FastLogin#52]
Hello everyone, i have a problem, probably a my error, but i'm not sure,
when i join (i'm premium!) it gives me an error:
'Please add the server in your server list! Please make sure the Server MOTD shows up before trying to login again!'
The MOTD shows up, and the error too, any solution?
If you need my config.. feel free to ask

**Comment by games647** [comment]
This doesn't seems to be related to FastLogin. FastLogin doesn't display this message. 

Maybe this an feature of your auth or serverlist plugin.
