### ISSUE TITLE
Premium name change

### ISSUE THREAD

**Issue by Fleodas** [games647/FastLogin#53]
On my bungee server some players are always shown as connected even if they are not. So if the player tries to reconnect he gets kicked because he is already connected, it happens randomly to players, both premium and cracked.
The /glist returns player name like if he was connected, it causes bugs with other bungee plugins, for example /msg spams with errors.
I hope you understand ^^, random players are considered connected by bungee (only bungee), they can't connect and it causes issues with other plugins.

Another issue: if a premium player joins the server after changing his name he has to login but I have enabled autoRegister and players don't know their password.

Java version: 1.8.0_101 (Java HotSpot(TM) 64-Bit Server VM)
Bungee version: git:Waterfall-Bootstrap:1.10-SNAPSHOT:8627c86:unknown (MC: 1.8.x, 1.9.x, 1.10.x)
FastLogin version: 1.7.1

Config file (same for both bungee and spigot): http://pastebin.com/yJtZUm8D

**Comment by games647** [comment]
The first one sounds like a proxy issue.

>Another issue: if a premium player joins the server after changing his name he has to login but I have enabled autoRegister and players don't know their password.

This means the name was registered earlier.

**Comment by Fleodas** [comment]
This problem happens since Fastlogin 1.7 if it can help. We always use latest Waterfal build.

**Comment by games647** [comment]
You mean both?

**Comment by Fleodas** [comment]
Only the proxy bug, I will disable autoRegister for my second problem.

**Comment by games647** [comment]
Which authplugin do you use?

**Comment by Fleodas** [comment]
I use Authme 5.2-BETA3

**Comment by Fleodas** [comment]
Let me explain my setup:
- Default server is auth so all players are sent the the auth server on login.
- Fastlogin is installed on bungee and auth server.
- Authme is installed on auth server.
- I made a plugin so players are sent to hub when they are logged in.

**Comment by games647** [comment]
Do you have nameChangeCheck enabled?

**Comment by Fleodas** [comment]
Yes

**Comment by games647** [comment]
Looks like the source of the "Players still considered connected"-issue is found. I remove it from the ticket here.

**Comment by Fleodas** [comment]
Let's summarize: premium players are asked to login on name change but autoRegister automaticaly creates a password and nobody cares. I could disable autoRegister but I don't want cracked players to connect with premium usernames.
The best way to resolve this would be an option to disable automatic password creation so premium players can choose their password.
In this way on name change they will be able to login with the password they have chosen.

**Comment by games647** [comment]
I think I found the source of this bug. I'll investigate a bit further.

**Comment by Fleodas** [comment]
Any news about that?

**Comment by games647** [comment]
I spent a lot of time testing it and I think it's fixed.

**Comment by games647** [comment]
Report me if it happens again with the new version.
