### ISSUE TITLE
The plugin block SkinsRestorer skin update in premium mode

### ISSUE THREAD

**Issue by andris155** [games647/FastLogin#531]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)
If I enable premium mode the SkinsRestorer /skin name or /skin set name name commands no update the skin.

### What behaviour is observed:
[//]: # (What happened?)
If I enable premium mode the SkinsRestorer /skin name or /skin set name name commands no update the skin.

### What behaviour is expected:
[//]: # (What did you expect?)
If I enable premium mode the SkinsRestorer /skin name or /skin set name name commands update the skin.

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
1. Install the Fastlogin and the Skinsrestorer to the Bungee and Paper server.
2. Disable join skins in Skinsrestorer.
3. Login to the server and enable premium mode.
4. Relogin.
5. /skin name or /skin set name name commands no update the skin.

### Plugin list:
[//]: # (This can be found by running `/pl`)
<img width="119" alt="Screenshot 2021-05-16 222032" src="https://user-images.githubusercontent.com/8324198/118411452-f2cf0280-b694-11eb-86bc-7f0b84c48ff9.png">

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
Waterfall 1.16-R0.5-SNAPSHOT build 416, SQLite.

### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
1.11-SNAPSHOT-7192dcd

### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
https://pastebin.com/f3rW00Wr

**Comment by games647** [comment]
That is something SkinsRestorer has to fix. FastLogin doesn't override the skin by default. BungeeCord does that. SkinsRestorer needs to handle onlinemode connections.
