### ISSUE TITLE
No autologin 

### ISSUE THREAD

**Issue by kacpiklPL** [games647/FastLogin#536]
I have created a separate server where I only log in and then move to the lobby. I use LoginEvent from AUTHME, but it doesn't always work. In 30% of cases, automatic login does not work and you have to log in using a command and password. If I leave and enter from the server, automatic login will work. What I should do now?

**Comment by games647** [comment]
This could be a timing issue. FastLogin sends a delayed force login command on BungeeCord. How and when do you redirect players? Does the LoginEvent only fires if works?

**Comment by games647** [comment]
Maybe add some example code, so we could reproduce it.

**Comment by kacpiklPL** [comment]
I have authme only paper engine, fast login bungee and paper engine. I have server when is only LOGIN. I use my plugin 

`import fr.xephi.authme.events.LoginEvent;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;

public class onLoginListener implements Listener {

    @EventHandler
    public void onLogin(LoginEvent event){
        Player player = event.getPlayer();
        // WYSLIJ DO LOBBY
        String data = player.getName() + ";" + "lobby-1" + ";" + player.getName();
        RedisManager.sendJedis("switchserver", data);
    }

}`

LoginEvent is authme event and FAST LOGIN sometimes it doesn't work and don't login automate

**Comment by games647** [comment]
So if I understand that correctly, it doesn't auto login and fire the event? Do you also redirect players if they are not logged in. I am assuming this could be cause.

**Comment by kacpiklPL** [comment]
Authme event detects autologing, but sometimes it doesn't log in automatically and tells you to enter /login password

**Comment by games647** [comment]
But this then sounds more like an AuthMe issue doesn't it? Do you see the log statements that FastLogin issues a auto login request?
