### ISSUE TITLE
Is there still no Floodgate support? 

### ISSUE THREAD

**Issue by cmod31** [games647/FastLogin#537]
I saw that in #494 floodgate support was merged to main but i think its not on codemc yet. If i try to install the newest build(995) the autologin for bedrock players still doesn't work like before. I even updated the config myself because it didn't automatically or its not even in this build.

**Comment by games647** [comment]
Please describe your server setup. Like floodgate version, server version and current configuration.

**Comment by cmod31** [comment]
I closed my server and i made a new one with vanilla 1.17 i wait for the new paper/spigot release and until its there i close this issue

**Comment by Smart123s** [comment]
@cmod31 in case you'll need it in the future: https://github.com/games647/FastLogin/issues/535#issuecomment-860215211 and https://github.com/games647/FastLogin/issues/535#issuecomment-860751786
