### ISSUE TITLE
Error joining into the server (premium player)

### ISSUE THREAD

**Issue by CookieCraftMcSrv** [games647/FastLogin#541]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: # (What happened?)

Error:

https://gist.github.com/CookieCraftMcSrv/98fac520a0f059293339a3e5e6555e6c

### What behaviour is expected:
[//]: # (What did you expect?)

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)

This error in console when it's joining a premium player. The player fails to enter, and the message error occured appears on the screen. The error does not always occur, but in most cases it does.

### Screenshots (if applicable)
[//]: # (You can drop the files here directly)

![image](https://user-images.githubusercontent.com/85307938/121648960-57189280-ca98-11eb-9bcc-311da464c0aa.png)

### Plugin list:
[//]: # (This can be found by running `/pl`)

[09:35:31 INFO]: Plugins (28): AntiCheatReloaded, AuthMe, AutomaticBroadcast, ChatManager, Citizens, DiscordSRV, Essentials, FastLogin, Geyser-Spigot, GSit, Hack_Control*, HolographicDisplays, LuckPerms, Multiverse-Core, Multiverse-Inventories, NametagEdit*, OnePlayerSleep*, PlotSquared, PlugMan, ProtocolLib, SkinsRestorer, SuperVanish, TitleManager, Vault, ViaVersion, VoidGenerator, WonderChat, WorldEdit

### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)

PaperSpigot, 1.16.5

### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)

[09:36:13 INFO]: FastLogin version 1.11-SNAPSHOT-7192dcd
[09:36:13 INFO]: Automatically login premium (paid accounts) player on a offline mode server

[09:36:13 INFO]: Website: https://www.spigotmc.org/resources/fastlogin.14153/fastlogin.bukkit/
[09:36:13 INFO]: Authors: games647 and https://github.com/games647/FastLogin/graphs/contributors

### Server Log:
[//]: # (No images please - only the textual representation)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error, stacktrace or the complete log (if any)

https://gist.github.com/CookieCraftMcSrv/98fac520a0f059293339a3e5e6555e6c

### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file 

https://gist.github.com/CookieCraftMcSrv/52cf4beaa0cade7873aa26cc9671a83e

Please Help Me.

**Comment by games647** [comment]
This means your server cannot resolve the IP of Mojang. Check your DNS settings in your server host.

**Comment by CookieCraftMcSrv** [comment]
How can I check it? Host: FalixNodes

**Comment by games647** [comment]
They need to verify their DNS settings. This error would happen for onlinemode servers too.

**Comment by games647** [comment]
There is nothing we can do at this end, so I'm closing it.
