### ISSUE TITLE
Doesn't work on Waterfall with SodionAuth

### ISSUE THREAD

**Issue by MAX-XiaoKui** [games647/FastLogin#547]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

### What behaviour is observed:
[//]: # (What happened?)
Doesn't work on Waterfall with SodionAuth
fastlogin's commands don't work

### What behaviour is expected:
[//]: # (What did you expect?)
plugin can be normally used
### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
just install the plugins and start the server
### Plugin list:
[//]: # (This can be found by running `/pl`)
AllMusic
FastLogin
LuckPerms
SodionAuth
ViaVersion
AdvancedBan
Geyser-BungeeCord
Minecraft_QQ
ViaBackwards
### Environment description
[//]: # (Server software with exact version number, Minecraft version, SQLite/MySQL/MariaDB, ...)
waterfall-1.17-436
openjdk-11
### Plugin version or build number (don't write latest):
[//]: # (This can be found by running `/version plugin-name`.)
build 996
### Server Log:
[//]: # (No images please - only the textual representation)
https://hastebin.com/ruqalagemi.csharp
### Configuration:
[//]: # (No images please - only the textual representation)
[//]: # (remember to delete any sensitive data)
https://hastebin.com/exaxinugel.yaml

**Comment by games647** [comment]
Please explain what exactly doesn't work. Just "doesn't work" isn't helpful here. What have you tried? Are the commands unavailable? Does the login process work etc.

**Comment by games647** [comment]
Furthermore this seems to be more a bug in SodionAuth

**Comment by MAX-XiaoKui** [comment]
,it says I have registered when I jioned again.
It seems a sodionauth bug.
