### ISSUE TITLE
Velocity support

### ISSUE THREAD

**Issue by games647** [games647/FastLogin#549]
>doesn't give us an official and concrete answer about adding support to Velocity? I

I followed the development of Velocity closely till today. At the beginning there were too many breaking changes. A few months ago, I took another look. I got the idea to start working on it for Velocity 2.0. However after this [announcement](https://forums.velocitypowered.com/t/an-unfortunate-update-on-2-0-0-and-an-exciting-announcement/772), plans have shifted. 

So I'm now working towards implementing support for 1.1.X. However there are a few things I want to make to ensure future versions are easier to test, so changes can be made with less manual testing. The current plan is the following:

1. Add integration tests: automatic testing environment of authentication process
2. Separate major optional features into modules: ProtocolLib vs ProtocolSupport, etc
3. Add velocity support

Velocity support won't be that complicated, because the proxy logic is rather minimal in comparison to Spigot. Nevertheless adding a new platform always adds more maintenance work.

_Originally posted by @games647 in https://github.com/games647/FastLogin/issues/311#issuecomment-861442453_

**Comment by games647** [comment]
FastLogin modules will depend on Velocity 3.0. It features an event system for asynchronous processing which seems to be very helpful for this project.

**Comment by MAX-XiaoKui** [comment]
So what auth plugin will be supported?

**Comment by games647** [comment]
Velocity only covers the proxy area. You don't need a proxy auth plugin. FastLogin will support bridged auth plugins from BungeeCord, but also the already existing in Spigot.

**Comment by MAX-XiaoKui** [comment]
What if I have vanilla or fabric subservers?

**Comment by games647** [comment]
This would require support for this platform too. However a proxy only could also work out.

**Comment by kubo6472** [comment]
The SNAP workaround stopped working as of move to velocity 3.0 as the stable and official version. Logs: https://hastebin.com/zajasiniqi.properties

**Comment by MAX-XiaoKui** [comment]
> The SNAP workaround stopped working as of move to velocity 3.0 as the stable and official version. Logs: https://hastebin.com/zajasiniqi.properties

FastLogin doesn't support Snap.
See #509

**Comment by kubo6472** [comment]
> FastLogin doesn't support Snap.

Hi, thanks for the link. It worked for me on v1.1.x somehow. But now it does not anymore. Gotta wait for the official support then.

**Comment by games647** [comment]
> > The SNAP workaround stopped working as of move to velocity 3.0 as the stable and official version. Logs: https://hastebin.com/zajasiniqi.properties
> 
> FastLogin doesn't support Snap.
> See #509

https://github.com/games647/FastLogin/commit/4bc328c37c4831b103739317c5ec0d39d1ef4269

should address this. You have a version newer than that, but I cannot pinpoint the source of the error, because your line numbers don't match up with current version of the plugin.

**Comment by OverBrave** [comment]
Ok, it's great that this plugin supports the latest versions, but BungeeCord is outdated now and can't handle packages well enough for the latest version of Minecraft, causing a lot of problems. @games647 you need to put everything you have planned for this plugin in the background and bring Velocity support urgently. It will be a very nice update for both me and other people.

**Comment by OverBrave** [comment]
@games647 Most things seem done. When exactly is it published?

**Comment by kubo6472** [comment]
@OverBrave 
Mind your tone! I do not think you support Mr games647 financially to create this project. If you do, then pardon me. But I objectively find the feel I get from your messages as very selfish & rude. Devs are working on minecraft plugins in their free time. No one should be entitled to talk like this to them. Correct me if I am wrong, or I got wrong what you meant. But if not, please, steer clear of this kind of behavior in the future. ✌ no harm intended.

**Comment by OverBrave** [comment]
I didn't say anything to the developer. I don't understand how you understood what I wrote. I just saw that there should be progress on the project and in the last "Pull Request" almost everything is finished. What makes you misunderstand?

**Comment by kubo6472** [comment]
> @games647 you need to put everything you have planned for this plugin in the background and bring Velocity support urgently.

These are mainly the words that got me. I never used the word malicious or that you insulted someone. Just that the wording made it seem rude. I apologize if you did not mean it that way.

**Comment by OverBrave** [comment]
What I meant here was about the plugin. Of course, I didn't want him to do such a thing in real life. It would be foolish to ask for such a thing.
I mentioned what to do in "RoadMapte".
https://github.com/games647/FastLogin/projects/1

No problem. It may have been misunderstood because I used missing words.

**Comment by kubo6472** [comment]
It probably got lost in translation, sorry.
