### ISSUE TITLE
Support for 1.17

### ISSUE THREAD

**Issue by games647** [games647/FastLogin#552]
https://github.com/dmulloy2/ProtocolLib/issues/1221

**Comment by cicatrice74** [comment]
Is this closed because is fixed or what, i'm still having this error.

**Comment by games647** [comment]
Yes it's fixed, but you need the updated ProtocolLib version.

**Comment by cicatrice74** [comment]
I still have the same error, encryption error, do i need to report to protocollib issue tracker ?

**Comment by games647** [comment]
Found the source. The CI didn't triggered for the latest changes.

**Comment by games647** [comment]
Sorry missed that one.

**Comment by games647** [comment]
The CI currently has some issues. I made a new version available here:
https://github.com/games647/FastLogin/releases/tag/mc-1-17

**Comment by games647** [comment]
@cicatrice74 **Next time fill out the issue template. It exists for a reason.** Then I would the exactly the plugin version you were using including the ProtocolLib version and don't make assumptions like that you need to update ProtocolLib like I mentioned earlier.

**Comment by games647** [comment]
CI is back, so you can download it from there too.
