### ISSUE TITLE
Premium uuid not working ?

### ISSUE THREAD

**Issue by SLDDL** [games647/FastLogin#554]
Heyy, i installed the plugin, configured it then enabled offline mode but when i log on, apparently my uuid switched to an offline one and i lost my inventory, permissions .... how can i get the premium uuid working ?

**Comment by SLDDL** [comment]
[latest.log](https://github.com/games647/FastLogin/files/6662851/latest.log)

**Comment by games647** [comment]
Please follow the issue template of the bug report: Reference:
https://raw.githubusercontent.com/games647/FastLogin/main/.github/ISSUE_TEMPLATE/bug_report.md

Particular important is your configuration file.

**Comment by SLDDL** [comment]
---
name: premium UUID ?
about: Something isn't working
title: 'Premium uuid doesnt seems to work'
labels: 'bug'

---

### What behaviour is observed:
When i enable premium UUID, it keeps the crack Uuid

it gives me uuid : 282335b6-e6a5-3c7c-8b96-dc8503bdece1


### What behaviour is expected:
it automatically changes the uuid of premium users to their premium uuid

mine is : 11d03eab92e74bdabc54b4a1983e95b7

### Steps/models to reproduce:
enabling premium uuid on 1.17

### Plugin list:
DeathCounter, WorldEdit, PlaceholderAPI, InvSeePlusPlus, AutoPluginLoader, RHLeafDecay, WeatherNews, ViaVersion, NBTAPI, floodgate, ViaBackwards, CoreProtect, LuckPerms, dynmap, FastLogin, AngelChest, Essentials, BetterSleeping3, BetterBees, DiscordSRV, EssentialsChat, Geyser-Spigot, SmoothTimber, EssentialsSpawn, TAB


### Environment description
spigot : 3104-Spigot-a09c0bb-d747f8e
mc: 1.17

### Plugin version or build number (don't write latest):
FastLogin version 1.11-SNAPSHOT-01c9b55

### Server Log:
[2021-06-16-7.log](https://github.com/games647/FastLogin/files/6666237/2021-06-16-7.log)
(i removed always online after and it was still not working ) 
### Configuration:
https://dl.dropboxusercontent.com/s/ilc2mgvesp2vevd/config.yml
(yml not supported by github ?)

**Comment by games647** [comment]
Read your server log:
>
[14:13:05] [Server thread/INFO]: FastLogin - Start completed.
[14:13:05] [Server thread/WARN]: [FastLogin] Either ProtocolLib or ProtocolSupport have to be installed if you don't use BungeeCord

**Comment by SLDDL** [comment]
Thanks for the quick reply :) but now im getting this error when i try to join
https://dl.dropboxusercontent.com/s/jqi4mxoa7sj9li9/latest.log

**Comment by SLDDL** [comment]
fixed by installing protocol support alongside protocol lib :)

**Comment by games647** [comment]
Then it's an issue of the plugin. There should be no need for installing both.

**Comment by games647** [comment]
See #552 for more details
