### ISSUE TITLE
Errors regarding UUID index

### ISSUE THREAD

**Issue by Fleodas** [games647/FastLogin#56]
On plugin startup I get errors regarding UUID index in MySQL.
I have the same config on spigot and bungee but the error only appears in bungee.

Error: http://pastebin.com/GbV6tjbe

I'm not sure it's an issue, maybe a simple debug message.

**Comment by games647** [comment]
https://github.com/games647/FastLogin/issues/55#issuecomment-238799661

See the second section. It's just a temp debug message. Sorry for the confusion.
