### ISSUE TITLE
FastLogin doesn't auto register/login players

### ISSUE THREAD

**Issue by Wizertex** [games647/FastLogin#564]
Hi, 
I tried using FastLogin so I could auto register and login premium players (so I have autoRegister and premiumUuid set to TRUE) but I doesn't work. I also use AuthMe Reloaded.
These are the only plugins I have:

AuthMe-5.6.0-beta2 (1)
FastLogin (1.10)
ProtocolLib

My server runs on Spigot 1.8.8 and I don't use BungeeCord (as it's only one server).
I tried using FastLoginBukkit yesterday (I don't exactly know where I got it) and it let me in but it didn't auto register/login me.
Now, I tried using 1.10 but it says Invalid session when I try to join (Failed to verify session).

**Comment by games647** [comment]
1.10 is totally out of date for your Spigot version, update to a dev build. BTW: If something doesn't work, it's more a bug than a question.

**Comment by Wizertex** [comment]
Okay, updated it to the bukkit one (https://ci.codemc.io/job/Games647/job/FastLogin/999/)
The plugin works fine when I register/login manually and then type /premium twice only first time. Now, it auto logins me.

But I enabled autoRegister and premiumUuid in config but it still doesn't auto register/login me.

**Comment by games647** [comment]
autoRegister only registers new players as mentioned in the configuration file. This is necessary, because otherwise cracked player could get irritated if they get a "Invalid session" error message when they try to login.

**Comment by Wizertex** [comment]
Well, when I tested autoRegister, I deleted both AuthMe and FastLogin folders in the plugins folder  (so I would be a  "new player") then restarted the server so they are created again, changed FastLogin's config (autoRegister, premiumUuid to true) and restarted again but it still didn't auto register me

**Comment by games647** [comment]
Please post the server log at that timestamp where you tested the new player behavior.

**Comment by Wizertex** [comment]
Update: so I tried resetting all files now and it seems to work perfectly... Don't know why it didn't work yesterday when I tested it (I'm assuming that, when I deleted AuthMe and FastLogin folders and restarted the server, I probably forgot to restart it again after changing config). But for now, it works as intedend. I'll post again just in case if there are any issues. Thank you!
