### ISSUE TITLE
Floodgate and Fastlogin in Bungeecoord

### ISSUE THREAD

**Issue by syukisihor** [games647/FastLogin#565]
Hi, Its possible to auto register/login floodgate users with fastlogin in bungeecoord/waterfall?

**Comment by Smart123s** [comment]
You should be able to do it after commit  https://github.com/games647/FastLogin/commit/d1daec436c0b2eacd277be4193bb527c1dcacfc6, but the CI server is not doing it's job (again).

@games647 could you please take a look on why the CI server is stuck at [build \#999](https://ci.codemc.io/job/Games647/job/FastLogin/999/)? I saw that you have pushed the commit mentioned above to https://github.com/AuthMe/FastLogin, so it's not that this time.

**Comment by games647** [comment]
@Smart123s Thank you for notifying. I changed the repository to this repo, but the wrong branch was configured. (master and not main)

**Comment by Smart123s** [comment]
If you use `auth-type=online` in Geyser's config (which asks you for your Java edition credentials when joining), you don't need Floodgate. Floodgate is used for Xbox Live authentication only.

So if you have Floodgate installed while using Java auth, Fastlogin might get confused? Or is there any reason you need Floodgate? Could you test your server without it?

**Comment by Smart123s** [comment]
>>>  I want xbox live authentication so I use floodgate

Then I misunderstood you, sorry. I'll look into the new issue.
