### ISSUE TITLE
FastLogin register premium player as a cracked player

### ISSUE THREAD

**Issue by NhProGamer** [games647/FastLogin#567]
### What happened?

FastLogin register premium player as a cracked player

### What did you expect?

FastLogin does register premium player as a premium player (the player must do /premium to be registered as premium player)

### Steps/models to reproduce

I have a bungeecord(flamecord java16), login server(1.8.8 Paper java 8) and lobby(Purpur java16)

Player login Bungeecord ==> player login on the login server ==> after login the player is mooved to lobby

this is my fastlogin config
bungeecord il correctly setup

### Plugin list

Bungeecord: https://imgur.com/N1qQDAP
Login: https://imgur.com/YVhzpG5
Lobby: https://imgur.com/0y0vXB9

### Configuration file

https://hastebin.com/zupewakocu.yaml

### Plugin version

1.11-SNAPSHOT-f17f9d9

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets - if there are, please upvote them and not create new ones

**Comment by games647** [comment]
Is the user auto logged in by FastLogin? It defaults to always cracked with the `autoRegister: false` with the option to opt in.

**Comment by NhProGamer** [comment]
Is there any way for premium players to be registered as premium with `autoRegister: false`?

**Comment by games647** [comment]
If you want to enable auto registration, you have to enable the option. That's the point of this configuration option. FastLogin somehow has to make this decision to enable onlinemode. This option exists for a user-configurable way. You can also activate `secondAttempt` if you want.

**Comment by NhProGamer** [comment]
okay thanks :)
