### ISSUE TITLE
Premium players sometimes do not register..

### ISSUE THREAD

**Issue by Tim-NL** [games647/FastLogin#57]
Hello, 

I'm using FastLogin with bungeecord and it seems that some players have to use /login in the lobby and they aren't set in the FastLogin database. The solution for me is simple; Unregister the player with authme so FastLogin will see the player as "new" or by adding him/her manual to the database with premium state. 

Is there a possibility to check if the user is in the FastLogin database instead of the AuthPlugin database? Because I have seen ~5 players that didn't exist in the FastLogin database but they did exist in the AuthMe database. So they still need to use /login password and the didn't have a skin.

**Comment by games647** [comment]
>Is there a possibility to check if the user is in the FastLogin database instead of the AuthPlugin database? Because I have seen ~5 players that didn't exist in the FastLogin database but they did exist in the AuthMe database. So they still need to use /login password and the didn't have a skin.

FastLogin does that to protect cracked players from stealing their account. Do you mean those should have been auto registered?

**Comment by Tim-NL** [comment]
Yes those accounts should be autoregistered, they are premium (for what NameMC says), but they only got added to the AuthMe database. And because FastLogin checks if the player is registered there it won't make a request to Mojang so those accounts stay "locked" for the owners until I add them manualy.

**Comment by games647** [comment]
Maybe they were registered even before FastLogin knows those players

**Comment by Tim-NL** [comment]
No they are not, I installed AuthMe & FastLogin together my server was premium online before I stared using FastLogin and both database where empty :)

**Comment by games647** [comment]
I could be caused by an old version. I guess or are they new players, because FastLogin doesn't remove anything?

**Comment by Tim-NL** [comment]
Well, the player will get autoregistered (They have an account) but they don't know the password. And the player isn't added to the FastLogin database. So the autoregister thing works? But the autologin doesn't because the player doesn't exist in the FastLogin database.

**Comment by games647** [comment]
FastLogin only inserts the player record if it got a success notification from bukkit. 

Are those new players?

**Comment by Tim-NL** [comment]
Kind off, they have been in that lobby map before but then the lobby didn't have a account on AuthMe because I didn't have that plugin.

**Comment by games647** [comment]
So I mean new authme players?

**Comment by Tim-NL** [comment]
Yes they are new AuthMe players, but if I'm the only one with this problem I can make a small work around for myself. If only seems to happen to ~5 players and my server has 1050 players registered since I'm using fastlogin. 

(My idea (for myself (isn't a good idea for a public plugin I think.); 
When a player joins the server and they didn't login within 10 seconds > send a request to mojang that asks if the user is premium, and if he is I'll add them manual to the fastlogin database using a SQL query. I think that should work, but it isn't the best solution :P

**Comment by games647** [comment]
> And it only seems to happen to ~5 players and my server has 1050 players registered since I'm using fastlogin.

Report me if it happens again for a new player. I'll look into it maybe I find something. 

>When a player joins the server and they didn't login within 10 seconds > send a request to mojang that asks if the user is premium, and if he is I'll add them manual to the fastlogin database using a SQL query. I think that should work, but it isn't the best solution :P

The problem is you have to validate that it's really the owner of that premium account. This can only be done during the login phase.

**Comment by Tim-NL** [comment]
> The problem is you have to validate that it's really the owner of that premium account. This can only be done during the login phase.

I know, but I think fastlogin handles that? if FastLogin thinks a premium player is cracked (and some random player joined using that playername) and my plugin will make that player (the name & UUID from mojang) premium by adding them to the fastlogin database. And kicking them after its done. 

So if the player joins again (cracked) he won't be able to login because he is set as premium within fastlogin. So only the owner will be able to play after the manual insert?

**Comment by games647** [comment]
This means you want to make premium players be able to steal the account of a cracked one.

**Comment by Tim-NL** [comment]
Oh no, I'll make a get request to Mojang first to check if the name is premium :) And if the is I'll add him.

**Comment by games647** [comment]
But this means cracked player accounts who uses premium usernames are insecure. Examples

New premium player bough that name
Premium player changed his/her name to that cracked player

**Comment by Tim-NL** [comment]
Hmm indeed, I think that chance is small on my server. I only have 19 players as cracked (Authme rows - Fastlogin rows) So that isn't a *big* problem. 

But I think i can do; 
Runnable (10 seconds) 
Didn't login yet? > 
Request UUID from mojang >

Player is cracked > Add him to my own database (only for cracked players)

Player is premium > Check if that name exists in my own database if not >
Register player in the FastLogin database and if he is in my own database just return and do nothing.
