### ISSUE TITLE
Latest build link

### ISSUE THREAD

**Issue by wtlgo** [games647/FastLogin#576]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

[//]: # (This ticket is about suggestions for a feature or particular enhancement)

### Is your feature request related to a problem? Please describe.
[//]: # (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])
Not a real issue, but a little inconvenience in my opinion. The link to the latest build (`https://ci.codemc.io/job/Games647/job/FastLogin/changes`) is IMHO placed in a rather uncomfortable place. It always takes me some time to find it, even though I know where it is. It took me even more time when I encountered this plugin the first time. I believe I'm not alone.

### Describe the solution you'd like
[//]: # (A clear and concise description of what you want to happen.)
Maybe, place it somewhere in a more visible place. And maybe also add it to the top of the description on Spigot?

### Describe alternatives you've considered
[//]: # (A clear and concise description of any alternative solutions or features you've considered.)
I don't actually know.

### Additional context
[//]: # (Add any other context or screenshots about the feature request here.)
None.

**Comment by games647** [comment]
Thanks, this shows how important it is to have a different perspective. I thought it was not an issue.
