### ISSUE TITLE
tcpshield 2.5 and fastlogin incompatibility

### ISSUE THREAD

**Issue by cicatrice74** [games647/FastLogin#577]
### What happened?

I have a 1.16.5 paper server and i use fastlogin (latest 17jun dev) and latest authme reloaded dev but if i use tcpshield 2.5 it asks for login on premium users, if i use tcpshield 2.4 it works normally, can u please try this and tell me what i need to do or what i need to report on tcpshield/authme/fastlogin githubs ?

### What did you expect?

i expext to let premium users auto login as before

### Steps to reproduce

fastlogin jun17 dev , authme latest dev and tcpshield 2.5

### Plugin list

authme reloaded,fastlogin,protocollib,tcpshield2.5

### Plugin version

fastlogin build #999

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Please post the server log at the login and the configuration file. Do you tried invoking the premium command?

**Comment by cicatrice74** [comment]
I normally use it on tcpshield 2.4 with no issue, it only happens using
latest tcpshield 2.5

Il giorno mar 13 lug 2021 alle ore 10:48 games647 ***@***.***>
ha scritto:

**Comment by games647** [comment]
This doesn't answer my questions.

**Comment by Kociak7331** [comment]
yes, I have the same problem - when I try to enter /premium being on the tcpshield server, I write that it sends a query and to see the faq of the fastlogin installation on bungeecord

[20:06:41] [Server thread/INFO]: [FastLogin] BungeeCord setting detected. No auth plugin is required

There is no error when entering and typing /premium in the console

**Comment by games647** [comment]
Please post the content of your spigot.yml file.

**Comment by Kociak7331** [comment]
currently I have bungeecord enabled so that there is no problem with #578

**Comment by games647** [comment]
The problem occurs, because you have Bungeecord enabled.

**Comment by games647** [comment]
The plugin cannot work if you enable BungeeCord server configuration, but don't use the BungeeCord. It's not possible with Spigot.

**Comment by games647** [comment]
This isn't unsupported setup configuration. You can't even login if BungeeCord is enabled and you have no proxy running.

**Comment by Kociak7331** [comment]
Okay, by fixing bug #578  I disabled the bungeecord in spigot.yml - and did a little test.

When tcpshield is active on the server - auto login doesn't work, but when tcpshield is turned off auto login works fine
