### ISSUE TITLE
 error when entering via premium

### ISSUE THREAD

**Issue by Kociak7331** [games647/FastLogin#578]
### What happened?

When joining the server with premium, it crashes from the server because of &4Error occured

### What did you expect?

Such that I can enter the server through premium without any problem

### Steps to reproduce

I upload the latest authme protocollib and fastlogin bukkit files (builds)
I go to the server, log in and sign in /premium 2 times
After typing, I exit the server and enter the server, which causes this problem

### Plugin list

 AuthMe, FastLogin, ProtocolLib, ViaBackwards, ViaVersion

### Configuration file

https://gist.github.com/Kociak7331/6c248da6b45fe6529aaab5d89d8aab59

### Server log

```shell
https://pastebin.com/raw/YAMxBdxx
```

### Plugin version

 1.11-SNAPSHOT-0a24d36 (1002 build)

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Okay that's really weird. None of your plugins change something here with the online mode. Could you check if it's also happening with Paper?

**Comment by Kociak7331** [comment]
there is also an error on the paper, I would like to point out that the files paper.yml server.proporties etc are defective

**Comment by Marcos03BR** [comment]
The same error is happening to me

**Comment by games647** [comment]
@Marcos03BR Similarity in the server setup like plugins or server software? It makes pin pointing the source easier.

**Comment by Marcos03BR** [comment]
Of course.

I'm using the default configuration of spigot.yml, server.properties, etc. (bypassing online-mode: false).

I'm using the latest current version of PaperMC 1.16.5: #782

I am using the latest versions of the following plugins:
![image](https://user-images.githubusercontent.com/45741056/125651304-4cc6d53f-cef5-4e37-9135-4aed746299e1.png)

AuthMe was updated about an hour ago, if that's any help. 
My server is not a Bungeecord. 
I'm using Java 11

**Comment by games647** [comment]
Found the source, working on it.

**Comment by games647** [comment]
Builds < 999 should work.

**Comment by HuJK** [comment]
> Builds < 999 should work.

And build 1003 works now?

**Comment by games647** [comment]
yes

**Comment by HuJK** [comment]
Oh, thank you a lot!

**Comment by Kociak7331** [comment]
Thanks, everything is working fine now
