### ISSUE TITLE
New thing

### ISSUE THREAD

**Issue by friishon** [games647/FastLogin#58]
sorry about put this here
can you put an option to delete user?
some times premium user can't aoutologin, but when i delete de db and write /premium 2 times
they can aoutologin.
sorry about my english, i hope you can understand me
i use authme reloaded to login

**Comment by games647** [comment]
>some times premium user can't aoutologin

It will only work for new users or those who activated premium logins.

**Comment by friishon** [comment]
when i put /premium, the plugin say that i already in premium list,but  i have to write /login
and other friend has the same problem

**Comment by friishon** [comment]
the problem is only with mysql

**Comment by games647** [comment]
Do you use BungeeCord?

**Comment by friishon** [comment]
yes

**Comment by games647** [comment]
Do filled in your proxy whitelist file?

**Comment by friishon** [comment]
no, it's clear

**Comment by games647** [comment]
Follow this setup:

https://github.com/games647/FastLogin#bungeecordwaterfall-1

**Comment by friishon** [comment]
where is my stats id from the BungeeCord?

**Comment by games647** [comment]
>from the BungeeCord config

**Comment by friishon** [comment]
i have to copy all the config or wich part?

**Comment by games647** [comment]
Just the uuid from the stats-id as described in the guide.

**Comment by friishon** [comment]
that 
stats: 8635ec1b-a3d2-4905-8619-867d0fa941c9

**Comment by games647** [comment]
only the uuid so without the "stats: "

**Comment by friishon** [comment]
ok, thanks

**Comment by friishon** [comment]
in bungee cord i haven't got the white list 
but in the spigot servers yes

**Comment by friishon** [comment]
i solve the problem, copy the stats in the spigot servers
