### ISSUE TITLE
 support for two or more bungeecords

### ISSUE THREAD

**Issue by Kocimietka7192** [games647/FastLogin#581]
### Is your feature request related to a problem? Please describe.
[//]: # (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])

Yes, because I can't put up a second bungeecord server to do "loadbalancing"

### Describe the solution you'd like
[//]: # (A clear and concise description of what you want to happen.)
I would suggest that it be possible to paste the second id-stats into the allowed-proxies file
### Describe alternatives you've considered
currently nothing.
[//]: # (A clear and concise description of any alternative solutions or features you've considered.)

### Additional context
[//]: # (Add any other context or screenshots about the feature request here.)

**Comment by games647** [comment]
You can use a round-robin DNS entry. What FastLogin doesn't support are nested BungeeCords, but multiple are supported by putting each id into a new line
