### ISSUE TITLE
/premium doesnt works

### ISSUE THREAD

**Issue by aSashaaa** [games647/FastLogin#588]
### What happened?

Installed the newest build from CI and followed the bungeecord setup.
There is no response from the server if i use /premium to log me in as a premium user.

### What did you expect?

I used /premium but nothing happened there is nothing in the console or in the chat.

### Steps to reproduce

Use /premium command, with an account that is premium and already joined the server before the installation of FastLogin.

### Plugin list

AuthMe, FastLogin, ProtocolLib

### Configuration file

https://hastebin.com/ajohujidus.yaml

### Server log

```shell
https://hastebin.com/mulakobace.yaml
```

### Plugin version

1.11-SNAPSHOT-4d4ecf3

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Do you use symbolic links or something otherwise special with the proxy file? Java failed to check for its existence.
