### ISSUE TITLE
%fastlogin_status% is not working due to class PlaceholderHook is no longer supported

### ISSUE THREAD

**Issue by N0rule** [games647/FastLogin#589]
### What happened?

can't get %fastlogin_status% to work

### Steps to reproduce

![image](https://user-images.githubusercontent.com/30196774/127479808-74433dfc-9622-4036-b5ec-51e6657f301e.png)
![image](https://user-images.githubusercontent.com/30196774/127479902-d9e40d7f-9652-48ae-b78d-c3d94ec308e9.png)

### Plugin version

v.1.10

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Outdated plugin version
