### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by shootcraft** [games647/FastLogin#59]
is there a way to let  premium player to auto register and only let cracked player  register with commands  ?
i am using authme reloaded, how can I install fast login without it interfere with players that had registered ?

**Comment by games647** [comment]
Just make use of autoregister. It will only be activated for new players with premium usernames.

**Comment by shootcraft** [comment]
what if a cracked player with premium username, will it autoregister for it ? then how will it authenticate the cracked player account with premium username ?

**Comment by games647** [comment]
https://github.com/games647/FastLogin/blob/master/core/src/main/resources/config.yml#L17

># Furthermore the premium player check have to be made based on the player name
# This means if a cracked player connects to the server and we request a paid account login from this player
# the player just disconnect and sees the message: 'bad login' or 'invalid session'

**Comment by shootcraft** [comment]
It means cracked player with premium username will unable to connect ?

**Comment by games647** [comment]
yes

**Comment by shootcraft** [comment]
okay thanks :)
