### ISSUE TITLE
FastLogin/Floodgate in Bungeecord with no auth plugin on Bungee

### ISSUE THREAD

**Issue by tuilakhanh** [games647/FastLogin#594]
### What happened?

I can't use autologin/register with floodgate

### What did you expect?

In bungeecord: [04:21:56 ERROR] [FastLogin]: An error has occured while checking if player ... is registered

In backend: [FastLogin] No on-going login session for player: CraftPlayer{name=..} with ID  ip:port

### Plugin list

AuthMe, FastLogin, floodgate, ProtocolSupport

### Server log

```shell
https://hastebin.com/obibinadiz.yaml
```

### Plugin version

1.11-SNAPSHOT-4d4ecf3

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by TanToan99** [comment]
same issues

**Comment by games647** [comment]
Could you please post the bungee log? The link you posted expired.

**Comment by tuilakhanh** [comment]
> Could you please post the bungee log? The link you posted expired.

https://hastebin.com/faxixenosu.sql

**Comment by tuilakhanh** [comment]
now i am getting this error
![image](https://user-images.githubusercontent.com/17153084/129694581-ac56dd5b-00f3-41b0-a681-8f5533c23996.png)

**Comment by games647** [comment]
Looks like a bug in the newest version. You don't need to update. I didn't addressed your bug yet.
