### ISSUE TITLE
Fast Login Bungeecord Not Work

### ISSUE THREAD

**Issue by cmod31** [games647/FastLogin#607]
### Discussed in https://github.com/games647/FastLogin/discussions/605

<div type='discussions-op-text'>

<sup>Originally posted by **LM-Matti** August 22, 2021</sup>
Hi I can't set up FastLogin with Bungeecord
I follow the guide but every time it says sending request without doing anything
As a second authentication plugin I use AuthMe</div>

**Comment by games647** [comment]
>.ConnectException: Connection refused

Check your database settings. There is no database server responding to the configuration. Make sure you have either MySQL or MariaDB installed, if you are running a self managed server (like VPS or root server).

**Comment by cmod31** [comment]
i installed it and it now runs succesfully on the wtaerfall proxy server but the plugin behaves like it doesn't even exists on the target lobby server

waterfall: https://mclo.gs/jJ4fSMg
paper: https://mclo.gs/yLzcApF
![alt text](https://i.ibb.co/M9MQvjj/Screenshot-2021-08-29-021733.png)

**Comment by games647** [comment]
Why do you put FastLoginBungee in that folder. You need to put it in the bungee / waterfall folder.

**Comment by cmod31** [comment]
I tried both the Bungee and the Bukkit version on the Paper server. It still doesn't show up at all in the console. it looks like it doesn't even exist. https://mclo.gs/6b2O1pi

**Comment by cmod31** [comment]
oh man sorry thats embarissing so i tried both and then i put it for any reason in the fastlogin folder itself i definetly need more sleep lol

**Comment by cmod31** [comment]
oh my god it works lol but maybe you could put in the wiki [https://github.com/games647/FastLogin#bungeecordwaterfall-1](https://github.com/games647/FastLogin#bungeecordwaterfall-1) for dumb people like me that you actually have to install mariadb and make a new mariadb user with the credentials in the config and that you still have to use the bukkit version for bukkit lol
