### ISSUE TITLE
A bug with FastLogin.

### ISSUE THREAD

**Issue by Renic4l** [games647/FastLogin#613]
### What happened?

So, When someone with a premium account runs /fastlogin and confirms then relogs it says "Invalid Session"
I've seen a bug report but I want to know where i can download the Dev Version of it.

### Plugin version

1.10

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Take a look at the project page. There you can see the download link.
