### ISSUE TITLE
Fabric support/alternative

### ISSUE THREAD

**Issue by leoNillo-bananasplit** [games647/FastLogin#617]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

[//]: # (This ticket is about suggestions for a feature or particular enhancement)

### Is your feature request related to a problem? Please describe.
[//]: # (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])
Well, no, but i'd love if this was a thing.
### Describe the solution you'd like
[//]: # (A clear and concise description of what you want to happen.)
Making a port of fastlogin but for fabric
### Describe alternatives you've considered
[//]: # (A clear and concise description of any alternative solutions or features you've considered.)
Making a separate plugin that does the same, but for fabric
### Additional context
[//]: # (Add any other context or screenshots about the feature request here.)
No.

**Comment by games647** [comment]
Sorry, but fabric is too small to be worth it to support.

**Comment by Hexality** [comment]
too small? lmao

**Comment by games647** [comment]
@Hexality Do you have any data on that? If you compare the usage between Fabric **servers** and Spigot servers, my assumption is that Spigot or forks of it are much more common. Maybe I'm wrong, so you could correct me. Fabric is often used on the client side, but as authentication happens on the server, it would require a server side plugin.

**Comment by Boden-C** [comment]
@games647 It's obviously a little difficult finding numbers for this, especially finding numbers of Spigot servers who are willing to configure their server to this extent (surprisingly a lower amount)

The closest way I could find is comparing mod/plugin downloads for the same thing on Curseforge, though this is also a little difficult as mods are usually made for client and server while plugins are only made for server. The best I could find is [Dynmap](https://www.curseforge.com/minecraft/search?page=1&search=dynmap), which I believe should be mostly server, which has 2.4m:0.9m plugin to mod comparison, meaning mods makes up **~27% of the userbase**.

This obviously isn't a perfect study, and also it is up to you whether 27% is "too small". It is also noted that this is Forge/Fabric, unfortunately CurseForge doesn't list Fabric amounts.
