### ISSUE TITLE
No autologin

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [games647/FastLogin#618]
### What happened?

Players are not auto logged in, and are required to write password

### What did you expect?

Premium players from database to be auto logged in

### Steps to reproduce

Join your server after you do /premium

### Plugin list

AuthmeBungee, Fastloginbungee

### Server log

```shell
[FastLogin] No on-going login session for player: CraftPlayer{name=NoobKing994} with ID
```

### Plugin version

[14:36:07 INFO]: FastLogin version 1.11-SNAPSHOT-8b4d458 [14:36:07 INFO]: Automatically login premium (paid accounts) player on a offline mode server

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Do you followed the setup guide of FastLogin for BungeeCord?

**Comment by TDMidkwhatisxd** [comment]
It seems that sqlite its not supported, can you tell me a proxy that is supported?

**Comment by games647** [comment]
Velocity and all BungeeCord based proxies are supported. The issue is the driver for connecting to the storage database. BungeeCord only includes MySQL/MariaDB. So you need to use that.

**Comment by TDMidkwhatisxd** [comment]
I can't, so i need to use waterfall, or travertine?

**Comment by TDMidkwhatisxd** [comment]
Or, cant i just use fastlogin on my lobby server? Or it will glitch the authmebungee?

**Comment by TDMidkwhatisxd** [comment]
Fixed, found a bungee plugin that allows me to use sql
