### ISSUE TITLE
Can't use /cracked

### ISSUE THREAD

**Issue by Eufranio** [games647/FastLogin#62]
As you know, i have a BungeeCoord network, and i have a modded server that ran in offline mode (until i install FastLogin). So, some players lose their playerdata because they changed UUID. So, i tried use /cracked them, and i het this error in the console:
```
>cracked PotterCraft_
[17:00:19 INFO]: [FastLogin] No player online to send a plugin message to the proxy
[17:00:19 INFO]: Sending request...
```
And nothing happens.

**Comment by games647** [comment]
>No player online to send a plugin message to the proxy

In BungeeCord plugin<->plugin communication is established through the plugin-channels of the players. This means a player have to be online at this state. That's why the request couldn't be sent.

But you could use the BungeeCord console directly.

**Comment by Eufranio** [comment]
The player is/was online, and he could not use /cracked

**Comment by Eufranio** [comment]
:smile:
