### ISSUE TITLE
FloodgateAutoLogin and FloodgateAutoRegister not working

### ISSUE THREAD

**Issue by frafol** [games647/FastLogin#630]
### What happened?

/premium not working on bedrock users and after re-login it generate errors.

### What did you expect?

Automatic login of a bedrock user is provided.

### Steps to reproduce

Join with a bedrock account
Do /premium
Re Login in the server
See BungeeCord Console

### Plugin list

VulcanBungee, UltimateAntiBot, StaffReport, SkinsRestorer, ServerListPlus, MultiLobby, Maintenance, LuckPerms, LiteBans, Geyser, floodgate, FastLogin, CraftingSTore, ChatSentinel, BungeeStaff, BungeePing, BungeeGuard, AuthMeBungee, AntiBungeePluginSteal, AjQueue.

### Configuration file

https://pastebin.com/raw/qydmiJ6X

### Server log

```shell
https://pastebin.com/raw/Stq39z2A
```

### Plugin version

1.11-SNAPSHOT-1f83a65

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
The player `.frafolreal5350` is saved as premium in the database. This implies that a premium authentication should be requested.

**Comment by frafol** [comment]
also missing plugin.yml in the bukkit version

Could not load 'plugins/FastLoginBukkit.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml

**Comment by frafol** [comment]
Same error if i am a cracked bedrock user and i enable FloodgateAutoRegister in config.yml

https://hastebin.com/rakizovino.sql
