### ISSUE TITLE
Velocity ClassNotFoundException: com.mysql.jdbc.Driver

### ISSUE THREAD

**Issue by frnacyello** [games647/FastLogin#643]
### What happened?

error with velocity plugin not work im using airplane for lobby and plugin it work

### Configuration file

https://pastebin.com/qkjBD24W

### Server log

```shell
https://pastebin.com/MiHKeaes
```

### Plugin version

fastlogin.velocity-1.11-20211024.182444-8.jar

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by frnacyello** [comment]
mariadb database

**Comment by games647** [comment]
> If on velocity use 'fastlogin.mysql.cj.jdbc.Driver' as driver

you need to update your configuration file.

**Comment by frnacyello** [comment]
same error

**Comment by frnacyello** [comment]
https://pastebin.com/mmgwQRnN

**Comment by frnacyello** [comment]
@games647

**Comment by frnacyello** [comment]
so?

**Comment by games647** [comment]
This is a hobby project. Please wait a bit. I fixed it now. The driver was at the wrong location. The new build now uses 'fastlogin.mariadb.jdbc.Driver'.
