### ISSUE TITLE
BUG WIth /premium

### ISSUE THREAD

**Issue by frnacyello** [games647/FastLogin#644]
### What happened?

i type /premium in my velocity server but when i type and i quit and relogin i can't log

### Server log

```shell
error
https://pastebin.com
```

### Plugin version

latest

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by FakeKoktis** [comment]
it happens to me too... Did you find a solution?

**Comment by games647** [comment]
Your pastebin post expired. I can't access it anymore
