### ISSUE TITLE
Bug with Floodgate (only nicknames with Space)

### ISSUE THREAD

**Issue by jassyel** [games647/FastLogin#647]
### What happened?

Players can't join if cointain spaces in nicknames

### What did you expect?

Play like someone

### Steps to reproduce
0.- Enable auto-login and auto register for floodgate in config
1.- Create a account with space (xbox)
2.- Try to join server
3.- See first time you CAN join to the server
4.- Re-join and now you can see you can't join in the server

### Plugin list

Floodgate, Geyser-Spigot, Authme, FastLogin

### Server log

```shell
https://pastebin.com/WeZmPjwM
```

### Plugin version

FastLogin version 1.11-SNAPSHOT-5612ca7

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by Smart123s** [comment]
Hi, are you using ProtocolLib or ProtocolSupport?
