### ISSUE TITLE
An option to disable auto login (i.e. 2FA)

### ISSUE THREAD

**Issue by stan60250** [games647/FastLogin#65]
This project is really awesome!
Is there any option to disable auto login for all premium accounts?
I really need that because of some security issue.
(works like two factor auth, Mojang + AuthPlugin)
Thanks!

**Comment by Eufranio** [comment]
In the config, autoRegister: false

**Comment by Eufranio** [comment]
Why not remove the plugin then?

**Comment by games647** [comment]
Security issues?

**Comment by stan60250** [comment]
Some player with premium accounts still want to use the "login" command,
because they share premium account with their family member.

Remove the FastLogin plugin can fix this,
but I still need other features like detect user name changed.

This is just a suggestion. If you think this is not necessary, just ignore it.
Thanks for reply :)

**Comment by games647** [comment]
Yes I'm going to implement it. GoToFinal (author of AutoIn) suggested this feature too. As I see there is actual demand for it, I will add it to FastLogin.

**Comment by stan60250** [comment]
OK! Thank you
