### ISSUE TITLE
Change kick message for non-premium players

### ISSUE THREAD

**Issue by LeCraft2Ouf** [games647/FastLogin#650]
Hello, 

Your plugin works perfectly under my bungee, the only problem is that if a player with Launcher Crack tries to connect with a Premium nickname. It kicks him and says "This server requires a MOJANG account".

Ok, but the problem is that I accept cracks, so I would like to know, how can I change the message? Players who see this message think that the server is only open to non crack players, but it's not.

I would like if possible to modify, or simply change the message to "You are trying to log in with a premium user name. Please change your username and try again".

Thanks to you, hoping to find a solution, I have been looking for a long time and I could not find how to change this, it would change my life and all my players.

Have a nice day

**Comment by games647** [comment]
There is no way to change it. This message is client-sided. There is no way to check the account so that this message doesn't occur.

**Comment by LeCraft2Ouf** [comment]
But it's completely stupid, my server is open to crack and my players get this? It doesn't make sense

**Comment by games647** [comment]
The server requests the premium authentication. It can make this request only based on the player name and connection details (IP address, country, etc.). Everything that comes next is handled on the client. The client is the one that disconnects from the server if that server requests an onlinemode connection. There is no server-side kicking involved.
