### ISSUE TITLE
Velocity: Backend server is online-mode! (It isn't)

### ISSUE THREAD

**Issue by ElTodoFull** [games647/FastLogin#656]
### What happened?

When you join the premium list and rejoin, you can't join the main server and print's an error on the proxy's (velocity console)

### What did you expect?

I join and log in automatically using AuthMe

### Steps to reproduce

Install fastlogin.velocity and FastLoginBukkit on their respective servers, restart, configure them accordingly (attached both) restart the server. Join and type /premium 2 times, rejoin, I can't rejoin.

### Plugin list

Velocity: authmevelocity, botsentry, fastlogin, floodgate, geyser, luckperms, skinsrestorer, spark... Purpur: 40ServidoresMC, ArmorStandTools, AsyncWorldEdit, AuthMe, AutoMessager, BlockLocker, BlocksHub, Captcha, ChatSentinel, ChestShop, ClaimChunk, CMILib, CommandHook, ConditionalEvents, ConsoleSpamFix, CoreProtect, CustomCrafting, CustomHeads*, DiscordSRV, dynmap, Essentials, Essentials_WarpGUI, EssentialsSpawn, ExtraContexts, FancyBags, FastLogin, floodgate, FurnitureLib, FurnitureMaker, GHolo, GMusic, Graves, GSit, ImageMaps, Insights, InteractiveBoard, InventoryRollbackPlus, Jobs, KauriVPN, LibsDisguises, LimitCreative, LiteBans, LuckPerms, MessageFilter*, MobBanners, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Parkour, PL-Hide, PlaceholderAPI, Plan, PlayerParticles, ProtocolLib, PvPManager, RegionRaid, Shopkeepers, SimplePets, SkinsRestorer, SuperbVote, SuperVanish, TAB, Themis, TreasureChest, TreeGravity, Vault, VentureChat, ViewDistanceTweaks, Votifier, WolfyUtilities, WorldEdit, WorldGuard, WorldGuardExtraFlags, XP-Deposit*

### Configuration file

https://www.toptal.com/developers/hastebin/yuxeqijifu.yaml

### Server log

```shell
https://pastebin.com/pLF47i1A
```

### Plugin version

1.11-20211104.093019-9

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Do you followed the BungeeCord setup guide? It also applies to Velocity, because it's also a proxy.

**Comment by galacticwarrior9** [comment]
I also experience the issue on both Velocity 3.0 and 3.1.

**Comment by games647** [comment]
The backend Spigot server needs to detect that there is a proxy running in front of it. So you have to enable it in the `config.yml` of the Spigot server (not plugin).

**Comment by galacticwarrior9** [comment]
Works as of build [1024](https://ci.codemc.io/job/Games647/job/FastLogin/1024/)

**Comment by ElTodoFull** [comment]
I have updated to build 1024 and velocity 3.1.0
When I tried to enable bungeecord on spigot, I wouldn't let players join the server with this error:
"_serverIP:playerport_ lost connection: If you wish to use IP forwarding, please enable it in your BungeeCord config as well!"
But since I use velocity modern forwarding, I don't have an option in bungeecord, there is no config anywhere.
When I disabled bungeecord, now it can't even "send the request" it gets stuck at "sending request..." Since I can't enable bungeecord on spigot, I'm, confused as to what I should do

**Comment by games647** [comment]
You still need to follow the rest of the guide. In the latest build, enable velocity in the paper configuration file. The proxy id however is still necessary. Otherwise the Spigot plugin doesn't the legitimate sender for logins and doesn't respond to requests.

The proxy file will be created after you enabled either proxy options in the server configuration (spigot/paper - not plugin).

**Comment by ElTodoFull** [comment]
Velocity was activated already on paper. The allowed-proxies (generated after enabling bungeecord on spigot), since I have velocity instead of bungeecord I should use the forwarding secret of velocity (it's equivalent to the stats-id)?

**Comment by ElTodoFull** [comment]
Ok, I palced yhe id of the proxy on that new config of fast login, and enabled bungeecord on spigot.yml
Now players can't enter the server with the same error as before:
serverIP:playerport lost connection: If you wish to use IP forwarding, please enable it in your BungeeCord config as well!"
But I have no bungeecord config file.

**Comment by ElTodoFull** [comment]
> 

Since it's no longer necessary, that means I can use velocity's modern forwarding and still have this plugin work?
I still get the same error: Sending request... (Do not forget to follow the Bungeecord setup guide)
But there is no bungeecord on my network, and I also tried following the guide, with no success. I think it'd be better to have a different guide for velocity (or at least explain it a bit more). I'd be very very thankful.

**Comment by ElTodoFull** [comment]
oh, i didn't want to close this

**Comment by games647** [comment]
>But there is no bungeecord on my network, and I also tried following the guide, with no success. I think it'd be better to have a different guide for velocity (or at least explain it a bit more). I'd be very very thankful.

Yeah the guide isn't updated for Velocity, but very similar. You enable modern forwarding in the proxy and the backend server (Paper). FastLogin will print a log message on the backend server if it detected the server running in proxy mode. Then you need to put the proxy id created in the plugins folder into the `allowed-proxies.txt`.

**Comment by ElTodoFull** [comment]
Thank you so much. I fianlly understood and now it's working correctly. For anyone who needs help:
Install fastlogin-velocity on your proxy.
fastlogin-bukkit on your backend servers.
Have them connected to the same database, it's necessary (I guess?)
Remember to use the database setting for velocity one line above the config.
Restart proxy and backend servers.
On the proxy, a file called `proxyId.txt` will be generated. Don't change it and copy its contents.
In the backends, a file called `allowed-proxies.txt` will be generated. Paste it inside and restart backend.
Done!
Remember to configure everything to offline mode and use modern forwarding on velocity.
