### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by shootcraft** [games647/FastLogin#66]
Is it compulsory for me to setup fast login with bungee cord method if I am using bungee cord to connect my server or can I just setup fast login on my auth server only ?

**Comment by games647** [comment]
That depends on your bungeecord setup. In general you should follow this guide: https://github.com/games647/FastLogin#bungeecordwaterfall-1

**Comment by shootcraft** [comment]
my fast login isn't working with my authme reloaded-5.2.snapshot plugin

**Comment by games647** [comment]
Do you followed the setup?

**Comment by shootcraft** [comment]
So it is a must to follow the setup for bungee cord, I thought it can work without bungee cord setup method, Okay I will try :)

**Comment by shootcraft** [comment]
Now there is proxy-whitelist file in the FastLogin folder Put your stats id from the BungeeCord config into this file ----- I dont understand this step

**Comment by games647** [comment]
In your config.yml of your bungeecord server, you see the stats-id like:

```yaml
stats: efa7993d-d313-4991-b7a7-2cd8e80c82dd
```

This id should be inserted to the file. (Only the id not 'stats: '-part)

**Comment by shootcraft** [comment]
Thanks, should I install fast login on all my spigot server or auth and bungee server only ?

**Comment by games647** [comment]
All servers

**Comment by shootcraft** [comment]
okay, the bungee cord id stat should be inserted on every server proxy-whitelist file or only auth server

**Comment by games647** [comment]
on every one. Then the bukkit module can accept the force login command from the bungeecord server.

**Comment by shootcraft** [comment]
my fast login file does not generate on my other server might be because don t have auth plugin ?

**Comment by games647** [comment]
No it might be because didn't enabled bungeecord support in the spigot.yml

**Comment by shootcraft** [comment]
i did

**Comment by shootcraft** [comment]
oh I forgot install protocollib

**Comment by shootcraft** [comment]
am I right ? , should i setup the configuration of fast login to be all the same

**Comment by shootcraft** [comment]
or I only setup the bungee cord ?

**Comment by games647** [comment]
>oh I forgot install protocollib

ProtocolLib isn't necessary on BungeeCord setup. 

>only setup the bungee cord ?

only bungeecord

**Comment by shootcraft** [comment]
But why fast login yaml didn't generate on my server ?

**Comment by games647** [comment]
Because the config isn't needed there...

**Comment by shootcraft** [comment]
on every one. Then the bukkit module can accept the force login command from the bungeecord server.

should I install bungee cord id stats on every spigot fast login proxy-whitelist file
but it didn't generate that file

**Comment by games647** [comment]
https://github.com/games647/FastLogin/issues/66#issuecomment-243442595

**Comment by shootcraft** [comment]
driver: org.sqlite.JDBC how to change this to mariadb and what is mariadb

**Comment by games647** [comment]
MariaDB is a fork of MySQL. IF you want to use the MariaDB driver, you have to have MariaDB installed too.

**Comment by shootcraft** [comment]
how to use mysql

**Comment by shootcraft** [comment]
# Single file SQLite database
driver: MySQL
# File location
database: '{pluginDir}/FastLogin.db' <--- what to write ?

**Comment by games647** [comment]
BungeeCord only supports MySQL by default. So you need to change the settings to MySQL.

**Comment by games647** [comment]
#driver: com.mysql.jdbc.Driver
#host: localhost
#port: 3306
#database: fastlogin
#username: myUser
#password: myPassword

**Comment by shootcraft** [comment]
driver is ?

**Comment by games647** [comment]
com.mysql.jdbc.Driver

**Comment by shootcraft** [comment]
# Single file SQLite database
driver: MySQL
# File location
database: '{pluginDir}/FastLogin.db'

# MySQL
driver: com.mysql.jdbc.Driver
host: localhost
port: 3306
database: fastlogin
username: 15990
password: ea2aasdfasd2

**Comment by shootcraft** [comment]
is what i Setup correct ?

**Comment by shootcraft** [comment]
is not working, I am using multicraft

**Comment by games647** [comment]
>is what i Setup correct ?

No you need to remove the SQLite part.

**Comment by shootcraft** [comment]
which one

**Comment by games647** [comment]
># Single file SQLite database
driver: MySQL
# File location
database: '{pluginDir}/FastLogin.db'

**Comment by shootcraft** [comment]
Thanks for guiding me all the way however, fast login still not working but I am glad that I still have the chance to continue it tomorrow

**Comment by games647** [comment]
I don't have access to your server, so you actually **need** data to check what's wrong. So you should check the startup log of the bungeecord server. I think you have invalid credentials.

**Comment by shootcraft** [comment]
I dont understand this 


1.08 01:29:15 [Server] INFO ^[[2K^M01:13:25 [INFO] Could not load native library: /tmp/bungeecord-native-cipher923074379900334289.so: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory^J^[[m^[[2K^M01:13:25 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.^J^[[m^[[2K^M01:13:25 [INFO] Using native code compressor^J^[[m^[[2K^M01:13:25 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.10-SNAPSHOT:eca9957:1168^J^[[m^[[2K^M01:13:25 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop^J^[[m^[[2K^M01:13:25 [INFO] Epoll is working, utilising it!^J^[[m^[[2K^M01:13:25 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())^J^[[m^[[2K^M01:13:25 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())^J^[[m^[[2K^M01:13:25 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())^J^[[m^[[2K^M01:13:25 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())^J^[[m^[[2K^M01:13:25 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())^J^[[m^[[2K^M01:13:25 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())^J^[[m^[[2K^M01:13:25 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m^[[2K^M01:13:25 [INFO] Loaded plugin cmd_find version git:cmd_find:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m^[[2K^M01:13:25 [INFO] Loaded plugin FastLogin version 1.8 by games647, http://github.com/games647/FastLogin/graphs/contributors^J^[[m^[[2K^M01:13:25 [INFO] Loaded plugin cmd_server version git:cmd_server:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m^[[2K^M01:13:25 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m^[[2K^M01:13:25 [INFO] Loaded plugin ServerListPlus version 3.4.5 by Minecrell <https://github.com/Minecrell>^J^[[m^[[2K^M01:13:25 [INFO] Loaded plugin cmd_send version git:cmd_send:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m^[[2K^M01:13:25 [INFO] Loaded plugin cmd_list version git:cmd_list:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m^[[2K^M01:13:26 [WARNING] Forced host server pvp is not defined^J^[[m^[[2K^M01:13:26 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m^[[2K^M01:13:26 [INFO] Enabled plugin cmd_find version git:cmd_find:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m^[[2K^M01:13:26 [SEVERE] Aug 31, 2016 1:13:26 AM com.zaxxer.hikari.HikariDataSource <init>^JINFO: HikariPool-1 - Started.^J^J^[[m^[[2K^M01:13:26 [SEVERE] Aug 31, 2016 1:13:26 AM com.zaxxer.hikari.pool.HikariPool shutdown^JINFO: HikariPool-1 - Close initiated...^J^J^[[m^[[2K^M01:13:26 [SEVERE] Aug 31, 2016 1:13:26 AM com.zaxxer.hikari.pool.HikariPool shutdown^JINFO: HikariPool-1 - Closed.^J^J^[[m^[[2K^M01:13:26 [WARNING] Exception encountered when loading plugin: FastLogin^Jcom.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure^J^JThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.^Jat com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:516)^Jat com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:118)^Jat com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)^Jat com.github.games647.fastlogin.core.AuthStorage.<init>(AuthStorage.java:42)^Jat com.github.games647.fastlogin.core.FastLoginCore.setupDatabase(FastLoginCore.java:63)^Jat com.github.games647.fastlogin.bungee.FastLoginBungee.onEnable(FastLoginBungee.java:68)^Jat net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)^Jat net.md_5.bungee.BungeeCord.start(BungeeCord.java:267)^Jat net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)^Jat net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)^JCaused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure^J^JThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.^Jat sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)^Jat sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)^Jat sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)^Jat java.lang.reflect.Constructor.newInstance(Constructor.java:422)^Jat com.mysql.jdbc.Util.handleNewInstance(Util.java:377)^Jat com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1036)^Jat com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:338)^Jat com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2232)^Jat com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2265)^Jat com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2064)^Jat com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)^Jat com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)^Jat sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)^Jat sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)^Jat sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)^Jat java.lang.reflect.Constructor.newInstance(Constructor.java:422)^Jat com.mysql.jdbc.Util.handleNewInstance(Util.java:377)^Jat com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)^Jat com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)^Jat com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)^Jat com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)^Jat com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:316)^Jat com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:506)^J... 9 more^JCaused by: java.net.ConnectException: Connection refused^Jat java.net.PlainSocketImpl.socketConnect(Native Method)^Jat java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)^Jat java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)^Jat java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)^Jat java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)^Jat java.net.Socket.connect(Socket.java:589)^Jat com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213)^Jat com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:297)^J... 25 more^J^[[m^[[2K^M01:13:26 [INFO] Enabled plugin cmd_server version git:cmd_server:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m^[[2K^M01:13:26 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m^[[2K^M01:13:26 [INFO] [ServerListPlus] [Core] Reloading configuration...^J^[[m^[[2K^M01:13:26 [INFO] [ServerListPlus] [Core] Loaded configuration: ServerStatusConf^J^[[m^[[2K^M01:13:26 [INFO] [ServerListPlus] [Core] Loaded configuration: PluginConf^J^[[m^[[2K^M01:13:26 [INFO] [ServerListPlus] [Core] Reloading saved player identities...^J^[[m^[[2K^M01:13:26 [INFO] [ServerListPlus] Successfully loaded!^J^[[m^[[2K^M01:13:26 [INFO] Enabled plugin ServerListPlus version 3.4.5 by Minecrell <https://github.com/Minecrell>^J^[[m^[[2K^M01:13:26 [INFO] Enabled plugin cmd_send version git:cmd_send:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m^[[2K^M01:13:26 [INFO] Enabled plugin cmd_list version git:cmd_list:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m>^[[2K^M01:13:27 [INFO] Listening on s5.minespan.com/209.133.198.218:26202^J^[[m>^[[2K^M01:13:34 [INFO] Netty is not using direct IO buffers.^J^[[m>^[[2K^M01:13:34 [INFO] [/88.198.62.168:41554] <-> InitialHandler has connected^J^[[m>^[[2K^M01:13:53 [INFO] [/170.253.242.207:59399] <-> InitialHandler has connected^J^[[m>^[[2K^M01:14:10 [INFO] [/2.84.69.129:64397] <-> InitialHandler has connected^J^[[m>^[[2K^M01:14:14 [INFO] [/60.52.116.243:50924] <-> InitialHandler has connected^J^[[m>^[[2K^M01:14:16 [INFO] [/60.52.116.243:50926] <-> InitialHandler has connected^J^[[m>^[[2K^M01:14:16 [INFO] [chingchuen93] <-> ServerConnector [Lobby] has connected^J^[[m>^[[2K^M01:14:26 [INFO] [chingchuen93] <-> ServerConnector [Skyblock] has connected^J^[[m>^[[2K^M01:14:26 [INFO] [chingchuen93] <-> DownstreamBridge <-> [Lobby] has disconnected^J^[[m>^[[2K^M01:14:58 [INFO] [/170.253.242.207:59479] <-> InitialHandler has connected^J^[[m>^[[2K^M01:15:49 [INFO] [chingchuen93] -> UpstreamBridge has disconnected^J^[[m>^[[2K^M01:15:50 [INFO] [chingchuen93] disconnected with: ^[[0;37;1m[Proxy] Lost connection to server.^J^[[m>^[[2K^M01:15:50 [INFO] [chingchuen93] <-> DownstreamBridge <-> [Skyblock] has disconnected^J^[[m>^[[2K^M01:15:53 [INFO] [/60.52.116.243:50929] <-> InitialHandler has connected^J^[[m>^[[2K^M01:15:53 [INFO] [/92.222.160.58:34404] <-> InitialHandler has connected^J^[[m>^[[2K^M01:16:02 [INFO] [/170.253.242.207:59561] <-> InitialHandler has connected^J^[[m>^[[2K^M01:17:11 [INFO] [/170.253.242.207:59631] <-> InitialHandler has connected^J^[[m>^[[2K^M01:18:08 [INFO] [/170.253.242.207:59692] <-> InitialHandler has connected^J^[[m>^[[2K^M01:18:13 [INFO] [/203.106.152.146:11335] <-> InitialHandler has connected^J^[[m>^[[2K^M01:18:17 [INFO] [/50.116.54.77:37496] <-> InitialHandler has connected^J^[[m>^[[2K^M01:19:05 [INFO] [/170.253.242.207:59748] <-> InitialHandler has connected^J^[[m>^[[2K^M01:20:02 [INFO] [/170.253.242.207:59808] <-> InitialHandler has connected^J^[[m>^[[2K^M01:20:06 [INFO] [/203.106.152.146:11373] <-> InitialHandler has connected^J^[[m>^[[2K^M01:20:49 [INFO] [/5.196.10.200:49478] <-> InitialHandler has connected^J^[[m>^[[2K^M01:20:52 [INFO] [/192.95.59.147:55900] <-> InitialHandler has connected^J^[[m>^[[2K^M01:20:58 [INFO] [/170.253.242.207:59867] <-> InitialHandler has connected^J^[[m>^[[2K^M01:21:09 [INFO] [/159.203.194.216:47595] <-> InitialHandler has connected^J^[[m>^[[2K^M01:21:55 [INFO] [/170.253.242.207:59926] <-> InitialHandler has connected^J^[[m>^[[2K^M01:22:52 [INFO] [/170.253.242.207:59983] <-> InitialHandler has connected^J^[[m>^[[2K^M01:23:01 [INFO] [/188.122.88.176:42393] <-> InitialHandler has connected^J^[[m>>>^[[2K^M01:23:16 [INFO] ^[[0;31;1mCommand not found^J^[[m>^[[2K^M01:23:16 [INFO] ^[[0;31;1mCommand not found^J^[[m>^[[2K^M01:23:32 [INFO] [/88.198.62.168:36651] <-> InitialHandler has connected^J^[[m>^[[2K^M01:23:49 [INFO] [/170.253.242.207:60042] <-> InitialHandler has connected^J^[[m>^[[2K^M01:24:32 [INFO] [/143.176.175.201:53786] <-> InitialHandler has connected^J^[[m>^[[2K^M01:24:45 [INFO] [/170.253.242.207:60100] <-> InitialHandler has connected^J^[[m>^[[2K^M01:24:46 [INFO] [/50.116.54.77:45718] <-> InitialHandler has connected^J^[[m>^[[2K^M01:25:26 [INFO] [/2.84.69.129:64469] <-> InitialHandler has connected^J^[[m>^[[2K^M01:25:42 [INFO] [/170.253.242.207:60156] <-> InitialHandler has connected^J^[[m>^[[2K^M01:25:50 [INFO] [/37.187.63.146:58267] <-> InitialHandler has connected^J^[[m>^[[2K^M01:26:39 [INFO] [/170.253.242.207:60211] <-> InitialHandler has connected^J^[[m>^[[2K^M01:27:35 [INFO] [/170.253.242.207:60267] <-> InitialHandler has connected^J^[[m>^[[2K^M01:28:32 [INFO] [/170.253.242.207:60323] <-> InitialHandler has connected^J^[[m>>>^[[2K^M01:28:35 [INFO] ^[[0;31;1mCommand not found^J^[[m>^[[2K^M01:28:35 [INFO] ^[[0;31;1mCommand not found^J^[[m>/usr/bin/java $START

**Comment by games647** [comment]
Please use hastebin, pastebin or something similar.

**Comment by shootcraft** [comment]
okay

**Comment by shootcraft** [comment]
http://pastebin.com/QMgm4Mqc

**Comment by games647** [comment]
>The driver has not received any packets from the server

Check your connection settings. Either the host or the port is wrong or there is no running mySQL there.

**Comment by shootcraft** [comment]
do u have team viewer ?

**Comment by shootcraft** [comment]
I had no idea what going wrong

# MySQL
driver: com.mysql.jdbc.Driver
host: s5.minespan.com
port: 26202
database: 15990
username: 15990
password: *********

**Comment by shootcraft** [comment]
should I  config inside the database first ?

**Comment by shootcraft** [comment]
![image](https://cloud.githubusercontent.com/assets/20242540/18121357/c6549a48-6f96-11e6-91cd-30ba0f036418.png)

**Comment by games647** [comment]
No only create the database if it doesn't exist. Everything else will be made automatically.

**Comment by shootcraft** [comment]
how can I setup fast login without bungee cord method such as run fast login only in auth server ?

**Comment by games647** [comment]
Then install it on BungeeCord and the auth server, but make sure they join on that server first (if they are new players).

**Comment by shootcraft** [comment]
I dont want to install it on bungee cord cause mysql can't really connect, so is there any way only install on server ?

**Comment by shootcraft** [comment]
# Database configuration
# Recommened is the use of MariaDB (a better version of MySQL)

MySQL:
 driver: com.mysql.jdbc.Driver
 host: s5.minespan.com
 port: 3306
 database: 15990
 username: 15990
 password: ea2a1fdee3

**Comment by shootcraft** [comment]
is this correct ?

**Comment by games647** [comment]
No remove the "MySQL:" line

**Comment by shootcraft** [comment]
how to 
Copy the contents (the "org"-folder) from the SQLite driver to BungeeCord ?

**Comment by shootcraft** [comment]
is that means copy the whole sqlite content into my server jar directory

**Comment by games647** [comment]
No open both jars with a archiver program like WinRar or 7Zip. Then copy the mentioned over.

**Comment by shootcraft** [comment]
i just copy everything from the file i download into bungee cord

**Comment by shootcraft** [comment]
10.09 03:29:53 [Server] INFO Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.
10.09 03:29:53 [Server] INFO Could not load native library: /tmp/bungeecord-native-cipher3720444739139789323.so: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by shootcraft** [comment]
no idea

**Comment by shootcraft** [comment]
please tell me how to fix this ?
http://pastebin.com/nhygKFM3

**Comment by games647** [comment]
First this isn't a FastLogin issue. Second just follow the message

>To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.

**Comment by shootcraft** [comment]
lol what is that

**Comment by games647** [comment]
Just follow the message, but BungeeCord will also work without. It's just for better performance.

**Comment by shootcraft** [comment]
I just want fastlogin to work, I got check my auth server using /premium command but it just replied some message

**Comment by games647** [comment]
What message and why do think is this wrong?

**Comment by shootcraft** [comment]
sending request ......
and there is no database file generated, only config.yml and message.yml in bungee cord

**Comment by games647** [comment]
Then there must be an error as I see there:  Failed to load class of driverClassName org.sqlite.JDBC. Looks like you didn't copied it correctly over

**Comment by shootcraft** [comment]
![image](https://cloud.githubusercontent.com/assets/20242540/18410709/7f9008d8-779b-11e6-9122-104c06bcf5f5.png)

**Comment by games647** [comment]
You download the wrong file. It's actually here: https://bitbucket.org/xerial/sqlite-jdbc/downloads

**Comment by shootcraft** [comment]
I copied everything inside it and paste it on bungee cord

**Comment by shootcraft** [comment]
sqlite-jdbc-3.8.11.2 wrong ?

**Comment by games647** [comment]
No just the wrong download source. It's a jar file not a zip.

**Comment by shootcraft** [comment]
so i just have to copy the org and the meta-inf dont have to ?

**Comment by games647** [comment]
just the org content yes

**Comment by shootcraft** [comment]
yes  !!! I dont whether I did it right, I think it is done, it showed warning: this command should only be invoked if you are the owner of this paid minecraft account type /premium again to confirm, finally after a week i manage to use fast login ultimately thanks for guiding me without you I might not able to use plugin .....

**Comment by shootcraft** [comment]
how to enable auto login for cracked account ?

**Comment by games647** [comment]
They just need to type /premium or you activate autoRegister for **new** players.

**Comment by shootcraft** [comment]
I can't is it because of cracked username ?

**Comment by games647** [comment]
What can't you do?

**Comment by shootcraft** [comment]
![image](https://cloud.githubusercontent.com/assets/20242540/18411056/3d2e3954-77a2-11e6-81aa-6db4e8840342.png)

**Comment by games647** [comment]
Your BungeeCord still refused to accept it

**Comment by games647** [comment]
You have to check for errors.

**Comment by shootcraft** [comment]
http://pastebin.com/Wt08me1L

**Comment by games647** [comment]
Are you sure you are connected over BungeeCord.

**Comment by shootcraft** [comment]
how to check whether it is connected ?

**Comment by games647** [comment]
You just have to connect through your BungeeCord connections settings.

**Comment by shootcraft** [comment]
My bungee server and auth serve is connected and cracked player with premium username unable to join my server because autoregister was true

**Comment by games647** [comment]
That's correct.

**Comment by shootcraft** [comment]
but the problem is I used /premium command with my cracked account and it replied warning and tell to excecute second time but then it showed sending request.....

**Comment by games647** [comment]
Then it doesn't seems you are connected over the BungeeCord server.
