### ISSUE TITLE
Paid users have to login on name change

### ISSUE THREAD

**Issue by Fleodas** [games647/FastLogin#67]
When a premium user changes name, he has to login even if the account wasn't registered before.
I tried with empty databases.

Steps to reproduce:
- Paid user joins and is auto registered and logged
- Paid user changes his name
- Paid user is auto registered on login again with a different password but he's not auto logged in (I don't understand this)
- The user has to login before playing, he is never auto logged in, not that the login works if user uses the password created by auto registration the second time

Weird thing: the new name (after changing name) is not registered in fastlogin database but there is an entry in the authme database.

Config: [http://pastebin.com/4EFg1Ysv](http://pastebin.com/4EFg1Ysv)
I use Authme and Waterfall, config is the same for both bungee and bukkit.

**Comment by games647** [comment]
Found the source. Working on it. Big sorry for that.
