### ISSUE TITLE
nlogin support

### ISSUE THREAD

**Issue by MrTokyo12345** [games647/FastLogin#676]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: # (Before reporting make sure you're running the **latest build** of the plugin and checked for existing issues!)

[//]: # (This ticket is about suggestions for a feature or particular enhancement)
feature support nlogin (https://www.nickuc.com/en/details/nlogin)

**Comment by games647** [comment]
They have their own premium mode support now.
