### ISSUE TITLE
FastLogin isnt working. 

### ISSUE THREAD

**Issue by koba-n-delete** [games647/FastLogin#677]
### What happened?

FastLogin is not loading the inventory etc. of the players on my offline 1.14.4 Craftbukkit server (Git 43183eabc2d).

With Version 1.10 i only get the "Invalid Session" Error in red (worked tho before i tried relogging), versions after 1.11 appear to not do anything besides logging me in.

### What did you expect?

Expected it to read the uuid of the players, load inventories etc.

it did not

### Steps to reproduce

???

### Plugin list

WorldEdit, LoginSecurity, PermissionsEx, ClearLag, Vault, SimpleSit, WorldGuard, Multiverse-Core, ProtocolLib, LibsDisguises, SkinsRestorer, FastLogin, WorldEditSUI, Essentials, EssentialsChat, EssentialsSpawn

### Server log

```shell
https://pastebin.com/zNvpk7QF
```

### Plugin version

FastLogin version 1.11-82ec71e

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
>FastLogin is not loading the inventory etc. of the players on my offline 1.14.4 Craftbukkit server (Git 43183eabc2d).

This depends on your configuration. The change of onlinemode can influence the UUID and therefore which player data is loaded.
