### ISSUE TITLE
Premium users can't use fastlogin

### ISSUE THREAD

**Issue by LOLEMO** [games647/FastLogin#678]
### What happened?

I used /premium with a premium account, but if i try to reconnect the server says: "Server is in Online Mode!
![Minecraft Screenshot 2021 12 14 - 18 01 21 47](https://user-images.githubusercontent.com/47610068/146046618-097c9d95-1b16-4914-8ebe-e34e64a5d016.png)
"

### What did you expect?

Joining the server without useing /login

### Steps to reproduce

1. Register as premium useing /premium twice
2. Log out
3. Log in
4. Get the error

### Plugin list

Authme Viaversion Userlogin

### Configuration file

https://www.toptal.com/developers/hastebin/surimoyiba.yaml

### Server log

```shell
https://www.toptal.com/developers/hastebin/eravopigig.md
```

### Plugin version

+

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Please follow the proxy setup guide mentioned on the plugin page.
