### ISSUE TITLE
FastLogin Generated an Exception

### ISSUE THREAD

**Issue by rad1914** [games647/FastLogin#683]
### What happened?

The plugin generates an exception spam when people enter my server, Generally it tends to spam too much when they enter, since I get the exception every time someone enters, and I am worried that it is affecting the performance of my server.

### What did you expect?

Normal behavior, no errors or exceptions when entering players

### Steps to reproduce

I'm using Floodgate, PlaceholderAPI and AdvancedLogin, and simply when I finish starting my server and start entering people, the plugin sends this message every time a person enters

### Plugin list

AdvancedLogin, PlaceholderAPI, Oraxen, FastLogin, Spark, plugman, Worldedit, WorldGuard, EssentialsX

### Configuration file

https://gist.github.com/rad1914/1764bcca8ebe53dfa268ff075fd49b89

### Server log

```shell
https://gist.github.com/rad1914/7028fe2290bfbecec45016a85ffd2853
```

### Plugin version

1.11-SNAPSHOT-06a8d6c

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Could you please post which Floodgate version do you use including its configuration. The posted error is about a lack of the source IP address.

**Comment by rad1914** [comment]
I am using the build 2.1.0-SNAPSHOT.. this is the link of the config
https://gist.github.com/rad1914/ddfbe2131939693df2a6093da1cdd363

**Comment by games647** [comment]
It now uses the raw connection address that Spigot has. So it should be fixed now.
