### ISSUE TITLE
Setting `floodgatePrefixWorkaround` to true gives "Your username contains illegal characters" to Bedrock Clients

### ISSUE THREAD

**Issue by some1chan** [games647/FastLogin#689]
### What happened?

Title more-or-less says it all. 

If you set `floodgatePrefixWorkaround` to true, you'll get the message "Your username contains illegal characters" upon connecting to the server. This message will go away if this variable was set to false, or the plugin is unloaded/uninstalled.

### Extra Details
* I tried manually merging [this pull request](https://github.com/games647/FastLogin/pull/681), and building a JAR from it. [You can find it here, if you're curious.](https://github.com/some1chan/FastLogin) I don't know what I'm doing at all, but it did compile. It didn't solve the issue though.
* I created a new issue, instead of commenting on #632. I figured the original issue was solved, but had an edge case worth documenting in more detail with the template. If not though, that's alright!

### What did you expect?

A Bedrock client is able to auto-register and login, with the Floodgate prefix.

### Steps to reproduce

1. Set `floodgatePrefixWorkaround` to true in the `config.yml` file
2. Connect to the server on a Bedrock client

### Plugin list

AuthMe, CoreProtect, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, FastLogin, floodgate, Geyser-Spigot, GeyserSkinManager, LuckPerms, PlugManX (PlugMan), ProtocolLib, SkinsRestorer, Vault, ViaVersion

### Configuration file

https://gist.github.com/some1chan/def3e8efcad45e0252abc17c3ba9b74a

### Server log

```shell
[02:19:08] [Network Listener - #2/INFO]: [Geyser-Spigot] /CENSORED:61259 tried to connect!
[02:19:09] [Network Listener - #2/INFO]: [Geyser-Spigot] Player connected with username DummyUsername
[02:19:09] [defaultEventLoopGroup-5-1/INFO]: [Geyser-Spigot] DummyUsername (logged in as: DummyUsername) has connected to the Java server
[02:19:10] [FastLogin Pool Thread #0/INFO]: [FastLogin] Handling player .DummyUsername
[02:19:10] [FastLogin Pool Thread #0/INFO]: [FastLogin] Floodgate Prefix detected on cracked player
[02:19:10] [Geyser Spigot connection thread-4-2/INFO]: [floodgate] Floodgate player logged in as .DummyUsername disconnected
[02:19:10] [Server thread/INFO]: /CENSORED:0 lost connection: Disconnected
[02:19:10] [defaultEventLoopGroup-5-1/INFO]: [Geyser-Spigot] DummyUsername has disconnected from the Java server because of Your username contains illegal characters
[02:19:10] [Network Listener - #2/INFO]: [Geyser-Spigot] Bedrock user with ip: /CENSORED has disconnected for reason CLOSED_BY_REMOTE_PEER
```

### Plugin version

1.11-SNAPSHOT-4a5516c

### Platform

Spigot (Paper version git-Paper-108)

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by Smart123s** [comment]
`allowFloodgateNameConflict` is missing from your [config.yml](https://gist.github.com/some1chan/def3e8efcad45e0252abc17c3ba9b74a). You should add it, and set it to `true`.

https://github.com/games647/FastLogin/blob/4a5516c9f9234f48421d29cf033b44b8dbcfe3e7/core/src/main/resources/config.yml#L208-L229

**Comment by Smart123s** [comment]
But why do you need https://github.com/games647/FastLogin/pull/681? That bug only affects server that are connected bungee (AFAIK), but `floodgatePrefixWorkaround` is only needed if you use Bukkit without bungee.

**Comment by some1chan** [comment]
> But why do you need #681? That bug only affects server that are connected bungee (AFAIK), but `floodgatePrefixWorkaround` is only needed if you use Bukkit without bungee.

The answer is simple: I genuinely don't know what I'm doing. Sorry about that 😅 

> `allowFloodgateNameConflict` is missing from your [config.yml](https://gist.github.com/some1chan/def3e8efcad45e0252abc17c3ba9b74a). You should add it, and set it to `true`.
> 
> https://github.com/games647/FastLogin/blob/4a5516c9f9234f48421d29cf033b44b8dbcfe3e7/core/src/main/resources/config.yml#L208-L229

As for setting `allowFloodgateNameConflict` to true, this didn't fix the issue. Log output is the more-or-less the same.

**Comment by some1chan** [comment]
Also sorry for the late reply, missed the email update.

I have no idea how to program server plugins, so I'm somewhat confused of what to really do. I think you meant to log what class executes `onPacketReceiving()` first, in which case, ManualNameChange triggers first.

**Comment by Smart123s** [comment]
Yes, I wanted exactly that. The problem is that ProtocollibListener (hlehic is responsible for the "illegal character" part)assumes that Floodgate players don't have a prefix, if ProtocolLib is installed. But if ManualNameChangeChecks runs before PLibListener, than the user will have a prefix. But the order of the event processing seems to be random.
