### ISSUE TITLE
Premium users aren't being auto-registered

### ISSUE THREAD

**Issue by Eufranio** [games647/FastLogin#69]
When a Premium player joins my server, he is not auto-registered, and have to use /login every time he join. I'm using latest FastLogin from Spigot, and AuthMe Reloaded, latest stable build from Jenkins and AuthMeBridge.

Also i have a Bungee network and a modded server, both with AuthMe and FastLogin. The issue started when i switched from BungeeAuth to AuthMe (as BungeeAuth needs a auth server, i can't use Forced Hosts).

**Comment by games647** [comment]
>he is not auto-registered,

Then it's maybe a already registered which FastLogin doesn't know.

**Comment by Eufranio** [comment]
Sorry?

**Comment by games647** [comment]
FastLogin only auto registers player if they are not already registered to protect cracked players from stealing their account by premium players.

**Comment by Eufranio** [comment]
Well, here they are not registered, and i'm sure. New players aren't auto registered, they need to use /register.

**Comment by games647** [comment]
Do you activated autoRegister in the config?

**Comment by Eufranio** [comment]
Yes

**Comment by games647** [comment]
Do you use BungeeCord and followed the guideline on the main page of this project?

Please activate debug logging in the spigot.yml. And try to login with a premium username that FastLogin and your auth plugin doesn't know.

**Comment by Eufranio** [comment]
Yes i followed.

Spigot debug didn't show anything special except some log spam:

``` 
Something's taking too long! 'root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.connection.keepAlive.root.levels' took aprox 261.194618 ms
```

**Comment by games647** [comment]
Okay then BungeeCord is responsible for activating it. I need your BungeeCord log at the time.

**Comment by Eufranio** [comment]
Is there a BungeeCord debug? There is no stacktraces in the Bungee log when joining (with a premium account not known, ofc).

**Comment by games647** [comment]
>Is there a BungeeCord debug?

BungeeCord logs everything 

>here is no stacktraces in the Bungee log when joining (with a premium account not known, ofc).

Doesn't need to be. I just need the debug logging.

**Comment by Eufranio** [comment]
Nothing special (?)
```
07:46:46 [INFO] [/189.81.128.187:59423] <-> InitialHandler has connected
07:46:49 [INFO] [/189.81.128.187:59424] <-> InitialHandler has connected
07:46:50 [INFO] [+] PotterCraft_
07:46:50 [INFO] [PotterCraft_] <-> ServerConnector [MagiTech] has connected
```

**Comment by Eufranio** [comment]
I tested some times, and realized that maybe there is a error in somewhere. I was succesfully registered in 1 of 8 times i tried, and tested with other players, they are registered kinda 1/8 or 1/6 times.

**Comment by games647** [comment]
>Nothing special (?)

Either FastLogin knows this player, or it's deactivated, because there is a missing "Player {0} uses a premium username"-message

Try to use a dev-build from here: http://ci.xephi.fr/job/FastLogin/changes

**Comment by Eufranio** [comment]
Fixed!

**Comment by games647** [comment]
Thanks for the info.
