### ISSUE TITLE
Velocity: UUID are not saved on database after a user invoked /premium

### ISSUE THREAD

**Issue by Malachiel87** [games647/FastLogin#690]
### What happened?

uuid are not saved on mysql table, after the user correct switch to premium account

### What did you expect?

UUID should be filled if that account is on premium state

### Steps to reproduce

install and configure the plugin correct with mariadb database,
User will do /premium 2 times and relog, make the account premium, shutdown the server, look the tables uuid will be not saved

### Plugin list

Authme Bungee

### Plugin version

build #1039

### Platform

Velocity

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by Malachiel87** [comment]
bump

**Comment by Smart123s** [comment]
@games647 https://github.com/games647/FastLogin/pull/709 is not related to this issue.
