### ISSUE TITLE
Sending Request

### ISSUE THREAD

**Issue by WorkWolf2** [games647/FastLogin#691]
### What happened?

I followed the guide exactly. The plugin in the console do not give error. The database is configured correctly, but at the execution of the command /premium the plugin give "Sending request..."

### Plugin list

VoidGen, WorldEdit, Skript, PlaceholderAPI, ViaVersion, ProtocolLib, ViaRewind, LuckPerms, Citizens, FastLogin, DeluxeHub, Essentials, BungeeGuard, AuthMe, TAB, LPC

### Plugin version

v1.10-git48485572ab794de1fe057cf7360245362658b432

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Outdated plugin version. Do you followed the setup guide for BungeeCord?

**Comment by WorkWolf2** [comment]
> d

Yes, I followed the bungeecord configuration. Now, however, I try again with a new version

**Comment by NeoNasta** [comment]
The same thing happens to me, I followed the configuration help they offer but I get "sending request"

**Comment by games647** [comment]
@NeoNasta Check your server log of both servers for any errors.

**Comment by NeoNasta** [comment]
> @NeoNasta Check your server log of both servers for any errors.

That is the thing there is no log or anything, it only appears "usse command: / premium" but in the lobby console and bungeecord nothing appears and in the minecraft chat I get "sending request" and I followed the installation of the plugin as what he said in his guide

**Comment by games647** [comment]
Check the server startup too.
