### ISSUE TITLE
Players are removed from premium list if they join with floodgate

### ISSUE THREAD

**Issue by YellowZaki** [games647/FastLogin#696]
### What happened?

Players are removed from premium list if they join with floodgate, when they had enabled /premium on java.

https://github.com/games647/FastLogin/issues/633 have the same problem but they have premiumUuid: true and all the comments are related to uuids. I have premiumUuid:false so I don't think there is a issue with uuids.

premiumUuid: false
autoLoginFloodgate: false
allowFloodgateNameConflict: true (I had to because players with premium nicks couldn't join on bedrock even if they hadn't used /premium)
autoRegisterFloodgate: false
floodgatePrefixWorkaround: true

### What did you expect?

I expect players with premium enabled, being on offline mode when they enter in bedrock, so they are requested the authme password.
And when they rejoin on java, join with online mode on.

### Steps to reproduce

1. Player joins in java and type /premium successfully.
2. Player quit and joins from Minecraft Bedrock (Floodgate) and have to type authme password
3. Player is removed from premium list (Premium == 0 on database) as soon as he enters through Bedrock.

### Plugin list

Authme, Floodgate

### Configuration file

https://www.toptal.com/developers/hastebin/yoyagoxudi.yaml

### Plugin version

1.11-SNAPSHOT-4a5516c

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by Smart123s** [comment]
In the Floodgate database, players are identified by their names. If you set `autoLoginFloodgate` to `false`, Floodgate players will be treated as cracked. And as a result, their name will be set to cracked in the database.

I'm planning to differentiate Floodgate and Java players in the database, but it'll take some coding, and I'll also have to do some kind of backwards compatibility for existing players.
