### ISSUE TITLE
Floodgate issue

### ISSUE THREAD

**Issue by WongIong** [games647/FastLogin#698]
### What happened?

So if you have global linked on geyser's server, you will get kicked when you use bedrock account to login:
![image](https://user-images.githubusercontent.com/36799194/148717155-45913a17-5424-4e27-91fb-304a039a4a7e.png)

Player has used /perm before on his java account, but then i have /cracked him after this. still not able to join with bedrock.

### What did you expect?

No error

### Plugin list

floodgate

### Configuration file

https://pastebin.com/Cfthi9AW

### Server log

```shell
11:50:28 [INFO] [FastLogin] Incoming login request for XXXXX from /XX.231.XX.83:0
11:50:28 [INFO] [FastLogin] Handling player XXXXXX
11:50:28 [SEVERE] [FastLogin] Could not check whether Bedrock Player XXXXXX's name conflicts a premium Java player's name.
11:50:28 [INFO] [floodgate] Floodgate Player XXXXXX Disconnected
11:50:28 [INFO] [Geyser-BungeeCord] AAAAAA has disconnected from the Java server because of Could not check if your name conflicts an existing premium Java account's name.
This is usually a serverside error.
11:50:28 [INFO] [Geyser-BungeeCord] Bedrock user with ip: /XX.231.XX.83 has disconnected for reason CLOSED_BY_REMOTE_PEER
```

### Plugin version

1.11-SNAPSHOT-4a5516c

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
I added some additional logging. It could be, because your server hit the Mojang API rate limit.

**Comment by WongIong** [comment]
I don't think it is caused by the limit.
because my server has only 20 players and others player either bedrock or java edition didn't receive this msg.

**Comment by games647** [comment]
At least with new version, we can see the exact reason.

**Comment by ZappySK** [comment]
I have the same problem as you @games647 do you still have this problem?

**Comment by WongIong** [comment]
@ZappySK After updated to newest version of Fastlogin and changed the login plugin, it doesnt show up again

**Comment by WongIong** [comment]
I still experiencing this issue
No errors or logs show up on backend console

**Comment by Smart123s** [comment]
> and others player [...] didn't receive this msg

Did the player have any special characters (like a space) in their name? That's known to be problematic.

**Comment by WongIong** [comment]
floodgate turned "replace space with _" on.
also that player's name doesn't contain space
prefix for bedrock has set to "-"

**Comment by Smart123s** [comment]
@WongIong could you test b41311e, and send logs?

Here's a prebuilt version if you can't build it manually: [FastLoginBungee-b41311e.zip](https://github.com/games647/FastLogin/files/7919060/FastLoginBungee-b41311e.zip) I had to put it in a zip file, because GitHub [doesn't allow sharing .jar files](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files).

**Comment by WongIong** [comment]
https://pastebin.com/YuhY0cZj
@Smart123s

**Comment by Smart123s** [comment]
> java.net.BindException: Cannot assign requested address

It seems to be a problem on your end, and not with the code.

Answers from here might be useful:
https://stackoverflow.com/questions/8965155/cannot-assign-requested-address-using-serversocket-socketbind

**Comment by WongIong** [comment]
Is the plugin not able to connect to mojang's api?

**Comment by Smart123s** [comment]
Something to do with that, but even I'm not 100% sure here. Maybe try to run the server on a different computer/network, if nothing helps?

**Comment by WongIong** [comment]
This error is from a server i rent
I have no ways to change the network :(

**Comment by games647** [comment]
Please comment out the ip-address section in the configuration file. I assume the error is from IP spoofing feature.

**Comment by WongIong** [comment]
are there any kind of reload command? or i have to restart the bungee?

**Comment by games647** [comment]
Restart

**Comment by WongIong** [comment]
![image](https://user-images.githubusercontent.com/36799194/151629672-0ab87aeb-8c68-49bf-9292-d1a8cd827338.png)
It is showing this to me now

**Comment by Smart123s** [comment]
You should change `allowFloodgateNameConflict` to `linked`, because with `false`:

https://github.com/games647/FastLogin/blob/9b04ea5c89e0b99bc273d28a1d9b0483c0a1b903/core/src/main/resources/config.yml#L222-L224

You could argue that `linked` should be the default in the first place (it'd be logical), but I'm not changing that until Floodgate support is experimental.

**Comment by WongIong** [comment]
Its my fault, i have read the config long time ago.
From then i have set it to linked, but after the problem of this issue, i have changed it back to false

I have not yet restart so don't know if that is working or not, will report here asap

**Comment by WongIong** [comment]
It works now, thank you all!
