### ISSUE TITLE
Config to auto-login users by name instead UUID

### ISSUE THREAD

**Issue by Eufranio** [games647/FastLogin#70]
Would be cool a config that allow succesfully connected premium players (players that were not kicked by Invalid Session) to log in automatically, checking their names instead UUIDs. The reason is that in my server, all my premium players get offline UUID (i don't know why) and they need to use /login every time they join.

The system would be like this:
Player <-> Server
Player has a premium account, and active mojang session
Player connects to the server
FastLogin checks if the nick `Player` is premium or cracked
If the nick is premium, it automatically logs in the Player
If not, the player can't connect, getting Invalid Session (same happens when cracked try to join with a premium username).

**Comment by games647** [comment]
>The reason is that in my server, all my premium players get offline UUID (i don't know why) and they need to use /login every time they join

Then they are properly not known to be premium by FastLogin. If you activate autoRegister, **new** players are assumed to be premium.

**Comment by Eufranio** [comment]
It's not a ready solution, what about the feature?

**Comment by games647** [comment]
The feature you are talking is already implemented. It's the autoRegister feature.

**Comment by Eufranio** [comment]
It's only for new players, i would like a feature that checks every time they join.

**Comment by games647** [comment]
That would allow premium players to steal your account and would be kicked every time you login as cracked player.

**Comment by Eufranio** [comment]
:/
The premium state is stored in FastLogin database, or it checks by the UUID? If we use /premium we lose the items (i've already stated here in a older issue), and if i replace the UUID files other mods/plugins will be confused and act like the player is new and different...

**Comment by games647** [comment]
>The premium state is stored in FastLogin database, or it checks by the UUID?

It checks it by the username. For new players it will check if it's a premium username and then request a premium authentication if autoRegister is activated.

>If we use /premium we lose the items (i've already stated here in a older issue)

As in the other issue, deactivate premiumUUID.

**Comment by Eufranio** [comment]
My username is premium and i need to use /login every time that i join, same as all other premium users.

**Comment by Eufranio** [comment]
lol now there are a lot of MOTD
http://prntscr.com/cdzm4t

**Comment by games647** [comment]
I'm closing this as regard of #69

**Comment by Eufranio** [comment]
Other users seems to auto log in, but my user exactly won't auto log in when using a cracked UUID. When i use /premium, i am auto logged-in. Any ideas?

**Comment by games647** [comment]
Please explain it more.

**Comment by Eufranio** [comment]
**Previously having Cracked UUID/Cracked state**
- I log in the server
- I need to use /login, cause it doesn't detect that i am premium

**Previously having Premium UUID/Premium state**
- I log in the server
- I don't need use /login, i am auto-logged in.

If i use **/premium** and reconnect, i am auto-logged, but when i join with a cracked state i am not.

**Comment by games647** [comment]
What do you mean with cracked state?

**Comment by games647** [comment]
So you mean with cracked state, premium uuid?

**Comment by Eufranio** [comment]
Cracked state = I am cracked in the database

**Comment by games647** [comment]
Then it's normal. The premium stands for that.

**Comment by Eufranio** [comment]
But while i am cracked, i can't be auto logged in

**Comment by games647** [comment]
Yes that's correct. It means cracked players still can player on your server and premium can just bypass the  password authentication, because they are the owners of a minecraft account.

**Comment by Eufranio** [comment]
I can't toggle my state to premium, that's why the issue...
**Config to auto-login users by name instead UUID**
Is there a way to do it?

**Comment by games647** [comment]
It's already by name and not uuid

**Comment by games647** [comment]
Just activate either autoRegister or invoke /premium twice.

**Comment by Eufranio** [comment]
If i invoke /premium twice i lose all my stuff.

**Comment by games647** [comment]
As mentioned before then turn off premiumUUID.

**Comment by Eufranio** [comment]
Already did

**Comment by games647** [comment]
Then this issue about a **complete** different thing. You use BungeeCord right?

**Comment by Eufranio** [comment]
Yes

**Comment by games647** [comment]
I need your BungeeCord FastLogin config and your bungeecord plugin list.

**Comment by Eufranio** [comment]
![screenshot_5](https://cloud.githubusercontent.com/assets/17598280/18317159/a17008a4-74f3-11e6-927c-35f65f7686d7.png)

**Comment by games647** [comment]
I tried it with those plugins. It still works. What's your backend server?

**Comment by Eufranio** [comment]
BungeeCord by HexagonMC (?)

**Comment by games647** [comment]
No the server behind.

**Comment by Eufranio** [comment]
Spigot 1.8.9 with ProtocolSupport, ProtocolLib, AuthMe, AuthMeBridge and FastLogin

**Comment by games647** [comment]
Try out this one: https://github.com/games647/FastLogin/releases/tag/debug-uuid and give me the logging output
