### ISSUE TITLE
/premium command not working

### ISSUE THREAD

**Issue by CasealbyOfficial** [games647/FastLogin#710]
### What happened?

When I try to use /premium I get "sending request" and nothing more happen

### What did you expect?

That the command works

### Steps to reproduce

Login to the server, _**/premium**_ command 

### Plugin list

AuthMe, Crafting5tore, DeluxeHub, DeluxeMenus, Essentials, EssentialsChat, FastLogin, Horizon, LuckPerms, LunarClient-API, LunarUtility, NamelessMC, PlaceholderAPI, ServersNPC, TAB, Vault, ViaBackwards, ViaRewind, ViaVersion, WorldEdit, WorldGuard

### Configuration file

https://www.toptal.com/developers/hastebin/ufixibejuk.yaml

### Server log

```shell
https://www.toptal.com/developers/hastebin/kuxuxineqi.yaml
```

### Plugin version

1,10-git484855724b794delfe057cf7360245362658b432

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by CasealbyOfficial** [comment]
I also tried to regenerate the config

**Comment by games647** [comment]
You are using a very outdated version

**Comment by CasealbyOfficial** [comment]
Oh, my fault. Sorry
