### ISSUE TITLE
Configurable prevent-proxy option

### ISSUE THREAD

**Issue by From-pErfo** [games647/FastLogin#718]
### What happened?

"Invalid session" appears when using ipv6 network
Works fine on ipv4 network

### Steps to reproduce

use ipv6 to connect to the server

### Plugin list

FastLogin, LoginSecurity, ProtocolLib

### Plugin version

1.11-SNAPSHOT-8a01ddc

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Where do you see invalid session? The plugin is tested under a IPv6 only network, so I wonder where this happens.

**Comment by array41175** [comment]
> Where do you see invalid session? The plugin is tested under a IPv6 only network, so I wonder where this happens.

"Invalid session" is displayed on client
This is server log: 
`[FastLogin] Handling player player
[FastLogin] Requesting premium login for registered player: player
[FastLogin] Enabling onlinemode encryption for UNKNOWN[/[IPv6]:port]
[Server thread/INFO]: /[IPv6]:port lost connection: Disconnected`

I use "online-mode" in server.properties, player login normal

**Comment by array41175** [comment]
> This should mean that the player isn't logged in, because the verification between client and Mojang failed. Do you use the vanilla client? Any mods installed? What Minecraft version do you run?

I am using vanilla client
no mods installed
MC Version 1.17.1

**Comment by array41175** [comment]
Not using VPN and IPv6 privacy extensions
My players also have this problem, can log in normally using the server online-mode, so I can't find the reason
I'm still doing more detailed testing )

**Comment by games647** [comment]
Could you test it with `prevent-proxy-connections=` enabled in the server properties. This is what FastLogin uses all the time. So please test it with online-mode, this option enabled and without the plugin.

**Comment by array41175** [comment]
These are the test results:
Maybe I understand the problem, but don't know how to fix it )

`prevent-proxy-connections=true; online-mode=true; no plugin`
IPv6: can not login, server: Username 'player' tried to join with an invalid session
IPv4: normal login

`prevent-proxy-connections=false; online-mode=true; no plugin`
IPv6: normal login, IPv4: normal login

**Comment by games647** [comment]
You could verify the IP of the player from the server log with https://myip.is/. At least the IPv6 prefix should match. If there is an exact match, privacy extensions are disabled (I assume it's enabled by default in all OS). Otherwise the first bits should match if it's the same connection. 

I could add an configuration option to disable the prevent-proxy feature.

**Comment by array41175** [comment]
This site returns an ipv4 address.... Can I change this question to a feature request?

**Comment by games647** [comment]
>This site returns an ipv4 address.... 

For me it's IPv6. Well then, specific alternative like: https://ipv6-test.com/ should work.

**Comment by games647** [comment]
Looks like this feature is completely broken. I tried it with a vanilla server (no spigot/craftbukkit/etc.), but still not working. Disabling the IPv6 privacy extensions had no influence either. So this seems to be an issue on Mojang's end.

**Comment by array41175** [comment]
? Sorry, I don't understand what you mean ?
I haven't found any solution these days...
But me and our player always look forward to this feature ?

I is using  IPv6 and FRP proxy MCserver, because there is no money to buy IPv4
in my test FastLogin only works properly under FRP and internal network [IPv4]

**Comment by games647** [comment]
>? Sorry, I don't understand what you mean ?

I tried the prevent-proxy feature with the Mojang original server to find the source of this issue. It looks like Mojang api server implementation is to blame here. 

>But me and our player always look forward to this feature ?

Okay, I'll address it. I'll upload a fix that will disable this feature for IPv6 only.

**Comment by array41175** [comment]
The update has helped me with the issue of IPv6 players not being able to log in, But I just found out now that there is something wrong with the FRP I have been using: 

genuine players who use FRP to connect to the server can pass FastLogin but will not automatically log in, and two saves are generated on the server, a offline player and a genuine player

But I enabled "autoRegister", which blocks offline accounts
Could this be related to "prevent-proxy"?

**Comment by games647** [comment]
Do you enabled premiumUUID?

**Comment by array41175** [comment]
> 您是否启用了高级 UUID？

YES

**Comment by array41175** [comment]
Etc, two archives were not generated, and then I found that the backpacks were synchronized
Just not doing automatic login

**Comment by games647** [comment]
Resolved with #722
