### ISSUE TITLE
/cracked <player> does not work if player has not joined server

### ISSUE THREAD

**Issue by Azfaloth** [games647/FastLogin#72]
I am using the assume premium option where premium players can directly join with no issues. But there is a cracked player who has a premium name and wants to play. I thought I could use the /cracked <player> command to add his name to the list of cracked players so he can play. But the plugin says "player is not in premium list" and he cannot play.

Is there any feature/option where I can allow this to happen?

Thanks once again for all your work on this project. :)

**Comment by Eufranio** [comment]
Update to the last version, and ask the player to connect 2 times.

**Comment by Azfaloth** [comment]
As far as I can see, that was added in 1.9 after issue 51. Version 1.9 has not been put on spigot yet. Is there somewhere to get that dev build or am I supposed to compile the master branch here?

**Comment by Eufranio** [comment]
Xephi's jenkins

**Comment by Azfaloth** [comment]
ah sorry for the late reply. I lost internet connection for a few days. I got it from xephis jenkins. Thanks for the help. I haven't been able to see if it works but I assume it does. I will re-open this if I have any problems with it. But thank you very much for your help!
