### ISSUE TITLE
Session not found with IP-changing plugins (i.e. TCPShield, HAProxyDetector)

### ISSUE THREAD

**Issue by games647** [games647/FastLogin#722]
Plugins that change the IP address during the login process break FastLogin, because it matches an ongoing login process based on the socket information.

Affected plugins:
* TCPShield
* HAProxyDector

Related #595
Temporarily solution: https://github.com/games647/FastLogin/releases/tag/tcpshield_update

**Comment by gabuch2** [comment]
Can the temporary solution be upgraded with the latest changes?

**Comment by games647** [comment]
Integrated into the main branch now.
