### ISSUE TITLE
Stuck on "sending request"

### ISSUE THREAD

**Issue by Jakubk15** [games647/FastLogin#723]
### What happened?

When player executes '/premium' command, it shows a message of "Sending request..." (configurable in messages.yml), and it is stuck on it. I'm using Velocity 3.1.1, with Purpur 1.18.1 as servers, with TCPShield. I have installed FastLoginVelocity on Velocity, FastLoginBukkit on my subserver (special TCPShield release fix), and AuthMe (dev build from CodeMC) on subserver. 

My only IPTables rule is:

![image](https://user-images.githubusercontent.com/77227023/153048862-7237b7b0-931d-4876-af64-623618672b9d.png)

### What did you expect?

/premium command is executed, request is being sent + player is registered as premium.

### Steps to reproduce

Install FastLoginVelocity on proxy, FastLoginBukkit (tcpshield fix) on subserver, and https://ci.codemc.io/job/AuthMe/job/AuthMeReloaded/lastSuccessfulBuild/artifact/target/AuthMe-5.6.0-SNAPSHOT.jar on subserver. Use TCPShield.

### Plugin list

Velocity: commandwhitelist, fastlogin, luckperms, minimotd-velocity, skinsrestorer, tcpshield | Subserver (Purpur): Authme, Citizens, CommandWhitelist, ConsoleSpamFix, DeluxeHub, DeluxeMenus, FastLogin, LuckPerms, PlaceHolderAPI, ProtocolLib, TAB, ViaBackwards, ViaVersion, WorldEdit

### Configuration file

```shell
https://pastebin.com/MD0Dir0t
```

### Server log

```shell
https://pastebin.com/HgXXaR0v
```

### Plugin version

v1.11-SNAPSHOT-d4a424f

### Platform

Velocity

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
There is your error message:

>[18:59:09] [Velocity Async Event Executor - #0/WARN]: This driver org.sqlite.JDBC is not supported on this platform
[18:59:09] [Velocity Async Event Executor - #0/WARN]: Please choose MySQL (Spigot+BungeeCord), SQLite (Spigot+Sponge) or MariaDB (Sponge)
java.lang.ClassNotFoundException: org.sqlite.JDBC

**Comment by Jakubk15** [comment]
So, do I need to use BungeeCord? Because none of listed storages above supports Velocity

**Comment by games647** [comment]
MySQL for Velocity as it's a proxy too.

**Comment by Jakubk15** [comment]
Ok, I will install it on my server and let you know what happened next ;)
