### ISSUE TITLE
Driver fastlogin.mariadb.jdbc.Driver claims to not accept jdbcUrl

### ISSUE THREAD

**Issue by Szymzal** [games647/FastLogin#724]
### What happened?

FastLogin cannot connect to MariaDB database.

### What did you expect?

Successfully connect to MariaDB database.

### Steps to reproduce

- Install Velocity 3.1.1 version 
- Install FastLogin into plugins folder 
- Install XAMPP 8.1.2 with MySQL (MariaDB) on Windows. 
- Configure MariaDB database in FastLogin config with 'fastlogin.mariadb.jdbc.Driver' driver.

### Plugin list

authmevelocity, fastlogin, luckperms

### Configuration file

https://www.toptal.com/developers/hastebin/desuveyutu.yaml

### Server log

```shell
https://www.toptal.com/developers/hastebin/obukutifek.sql
```

### Plugin version

v1.11-SNAPSHOT-6f16700

### Platform

Velocity

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Ah that's the breaking change from #717, I'll fix that.
