### ISSUE TITLE
second attempt cracked can be used on registered premium accounts

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [games647/FastLogin#725]
### What happened?

players can use registered premium accounts

### What did you expect?

players to get kicked from registered premium accounts

### Steps to reproduce

1. Autoregister using premium account
2. Use second attempt cracked feature and use a cracked launcher with premium username.

### Plugin version

[14:36:07 INFO]: FastLogin version 1.11-SNAPSHOT-8b4d458 [14:36:07 INFO]: Automatically login premium (paid accounts) player on a offline mode server

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by TDMidkwhatisxd** [comment]
is there a option to kick if the user is registered?

**Comment by games647** [comment]
To clarify: secondAttempt switches the player to offline mode although the account is registered as premium?

Could you please append the server log for that event.

**Comment by TDMidkwhatisxd** [comment]
It got fixed in newer versions, until now i had it off because of this problem :D, thx for fast response and sorry xd
