### ISSUE TITLE
Can't make this plugin work

### ISSUE THREAD

**Issue by Wearwolfy** [games647/FastLogin#73]
I tried everything single way of being able to let the plugin work but it just does not at all. I have the following plugins installed (to test) Authme 5.2 BETA3 spigot, Fastlogin and protocolib on 1.9 spigot (tried 1.10 and 1.10.2 and 1.8 as i said i tried everything), i enabled auto register and disabled it to see if it works but it does not make a difference here are my logs and server properties. Plz i need help :(
![schermopname 19](https://cloud.githubusercontent.com/assets/21149078/18449634/2a4536a0-7930-11e6-8ef8-aa5aefbf573e.png)

**Comment by Wearwolfy** [comment]
http://pastebin.com/khyP6Cja

**Comment by games647** [comment]
Auto register is only activated for unregistered usernames

**Comment by Wearwolfy** [comment]
I tried true and false but it does not work, i tried everything

**Comment by games647** [comment]
>Auto register is only activated for **unregistered** usernames

See the unregistered above. It's only activated if FastLogin and your auth plugin doesn't know this player.

Please read the config of FastLogin more carefully.

This is already mentioned at the autoRegister part.
>1. An existing cracked account shouldn't exist

**Comment by Wearwolfy** [comment]
Ik that, everytime, i try to test it, i remove all the folders and have just the 3 jar files in my plugin folder but still does not work

**Comment by games647** [comment]
Then please enable debug logging in the spigot.yml and send me your server log.

**Comment by Wearwolfy** [comment]
http://pastebin.com/hfmKtD9r

**Comment by games647** [comment]
You have to join the server too.

**Comment by Wearwolfy** [comment]
This time i left autoregister to false and registered using /register but then it should automatically log me in but nope
http://pastebin.com/YrvYn62a

**Comment by games647** [comment]
It only logins you in automatically if you activate autoRegister or invoke /premium. (knows that you are premium)

**Comment by Wearwolfy** [comment]
so do i have to do it with auto register enabled?

**Comment by Wearwolfy** [comment]
cause it doesn't log me in automatically aswell

**Comment by games647** [comment]
Then send me the log as I already mentioned before.........................................

**Comment by Wearwolfy** [comment]
http://pastebin.com/YrvYn62a

**Comment by games647** [comment]
Try to invoke /premium twice and report me if it works.

**Comment by Wearwolfy** [comment]
Yep this works but i don't want players to register using /register or login using /login and then typing /premium twice ...., I was looking for something Auto in

**Comment by games647** [comment]
Make sure you delete both .db files and then activated autoRegister. Start your server only after you activated this.

**Comment by Wearwolfy** [comment]
WTF, you did it

**Comment by Wearwolfy** [comment]
Ok imma try to do this on bungeecord now :)
Thnx

**Comment by games647** [comment]
Here is a guide for BungeeCord. https://github.com/games647/FastLogin#bungeecordwaterfall-1
