### ISSUE TITLE
FastLogin doesn't work on Spigot 1.15

### ISSUE THREAD

**Issue by Yashirodev** [games647/FastLogin#733]
Hi,

I have make a Minecraft Server but i use FastLogin for the players.
But He doesn't work on my server.

Server Information:

`Spigot Version : 1.15`
`Java Version : 11.0.13`

**Comment by Smart123s** [comment]
Didn't test it, but while I was looking at the source code, I came across this, an thought that it might be related: https://github.com/games647/FastLogin/commit/fe1499f1fb33449590b9b3f16b2ed5f95744542c#diff-17b182dc61d02e0f561017c1a01a3943f073b681fc32cc2f85ff606444964317R55

**Comment by games647** [comment]
Hard to tell without the server log or the plugin version in use.
