### ISSUE TITLE
Is it working with AuthMe web register?

### ISSUE THREAD

**Issue by Eufranio** [games647/FastLogin#74]
AuthMe has a feature that allow players register in a forum like Xenforo, and the same pw is used in the minecraft login. 
Will FastLogin cause problems if the in-game registering is disabled? Because it checks the player in their first login...

**Comment by games647** [comment]
That's a though question. Yes it fail, but doesn't notices that, because AuthMe has no sucess checking in their API. 

Is this plugin then really useful for you if they need the password from their form account?
