### ISSUE TITLE
Bungeecord support 

### ISSUE THREAD

**Issue by Wearwolfy** [games647/FastLogin#75]
So after the spigot worked i tried to do it with bungeecord wich works fine. I use BungeeAuth as the auth plugin but there is 1 problem. The autoregister and autologin works fine but when a cracked player with a premium name joins they get this error "Java.lang.NullPointerExecption", non premium names do work with fastlogin, then they just have to /register and /login
Another question. You said you need to install fastlogin on both servers (bungee and spigot) but since i am using bungeeauth, i tried only on the bungeecord server aswell and there was no difference. So my question do i still need fastlogin in spigot plugins folder? (Note: I tried this aswell to fix the first issue but that didn't work)
PS: Thanks for the fast an awesome support!

**Comment by Eufranio** [comment]
Did you enable the offline-mode in Bungee config.yml?

**Comment by Wearwolfy** [comment]
Yep it is onlinemode = false

**Comment by games647** [comment]
Send me your log. I need the stacktrace of the NPE. Moreover do you configured MySQL instead of SQLite, because BungeeCord has no driver for SQLite by default.

**Comment by Wearwolfy** [comment]
Yep i used mysql

**Comment by Wearwolfy** [comment]
What log do you want? Bungeecord doesn't have a log? I will give you the spigot log then

**Comment by games647** [comment]
BungeeCord has a log called proxy.log

**Comment by Wearwolfy** [comment]
wierd that are only the logs that had errors in the begin when i had to start it up, but i don't have recent logs where premium names can't join

**Comment by games647** [comment]
Just give me the log.

**Comment by Wearwolfy** [comment]
http://pastebin.com/Qb7YiB26

**Comment by games647** [comment]
You do not configured MySQL

>Failed to load class of driverClassName org.sqlite.JDBC

**Comment by Wearwolfy** [comment]
I did
but as i said This is the only log i have, it seems like it only logs the crashes, this is one of the logs in the beginning where i installed it

**Comment by games647** [comment]
Could you post your config of FastLogin inside BungeeCord.

**Comment by Wearwolfy** [comment]
http://pastebin.com/zj5Nvzx0 = Bungee config
http://pastebin.com/70mZBQRb = fastlogin config

**Comment by games647** [comment]
Are you sure that config is located in bungeecord-server/plugins/fastlogin  and not on the spigot/bukkit server.

**Comment by Wearwolfy** [comment]
Yep 100% sure, i don't even have it on spigot since i have bungeeauth

**Comment by games647** [comment]
You still need it on Spigot btw.

**Comment by games647** [comment]
Your log doesn't correspond to your log.

**Comment by Wearwolfy** [comment]
What log? do you want my spigot log?

**Comment by games647** [comment]
No your proxy log

**Comment by Wearwolfy** [comment]
You didn't respond to this "Another question. You said you need to install fastlogin on both servers (bungee and spigot) but since i am using bungeeauth, i tried only on the bungeecord server aswell and there was no difference. So my question do i still need fastlogin in spigot plugins folder? (Note: I tried this aswell to fix the first issue but that didn't work)
PS: Thanks for the fast an awesome support!", it seems like i don't need to install it on spigot since it works perfectly fine just on bungee and it is perfect only issue is that cracked players with premium names can't join

**Comment by games647** [comment]
https://github.com/games647/FastLogin/issues/75#issuecomment-247012547

**Comment by Wearwolfy** [comment]
But then why does it work perfectly fine wih only on the bungee cord server?

**Comment by games647** [comment]
It doesn't work fine. It won't save new data.

**Comment by Wearwolfy** [comment]
Ok what auth plugin do you recommend?

**Comment by Wearwolfy** [comment]
Maybe BungeeAuth is a bad authplugin

**Comment by games647** [comment]
It will work with BungeeAuth. Just install FastLogin on spigot too.

**Comment by games647** [comment]
FastLogin just can't load, because of your bad config:

>    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
22:30:15 [WARNING] Exception encountered when loading plugin: FastLogin
while parsing a block mapping
 in 'reader', line 22, column 1:
    autoRegister: true
    ^
expected <block end>, but found Scalar
 in 'reader', line 140, column 2:
     MySQL
     ^
 
    at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.prod

**Comment by Wearwolfy** [comment]
I did but it made no difference? Btw i tried installing it on both servers aswell but still cracked players with premium names couldn't join

**Comment by Wearwolfy** [comment]
Yeah i fixed that

**Comment by Wearwolfy** [comment]
It starts without errors

**Comment by games647** [comment]
>Btw i tried installing it on both servers aswell but still cracked players with premium names couldn't join

That's correct if you use autoRegister. The check is name based.

**Comment by Wearwolfy** [comment]
But there is no log of the perfect startup, it seems like it only logs crashes/bad startups

**Comment by games647** [comment]
Then send me the log............

**Comment by Wearwolfy** [comment]
So what you are saying is that if i enable autoregister that cracked players with premium names can't join??

**Comment by Wearwolfy** [comment]
Send me the log?? I just said it doesn't generate logs unless it is a crash wich atm the server doesn't do

**Comment by games647** [comment]
**You should really read the config** man.

    # Furthermore the premium player check have to be made based on the player name
    # This means if a cracked player connects to the server and we request a paid account login from this   player
    # the player just disconnect and sees the message: 'bad login' or 'invalid session'

**Comment by Wearwolfy** [comment]
i did read that and its bs because it doesn't say bad login or invalid session

**Comment by Wearwolfy** [comment]
Ok another thing, can i have it so that when a premium players logs in that they don't see the /login password message?

**Comment by games647** [comment]
>i did read that and its bs because it doesn't say bad login or invalid session

It depends on your launcher.

>they don't see the /login password message?

There is no API for that in BungeeAuth atm. Sorry

**Comment by Wearwolfy** [comment]
Ok well thanks for your help, you may close/remove the ticket ;)

**Comment by Eufranio** [comment]
is there a API for that in AuthMe? Because i see the /login message

**Comment by games647** [comment]
>is there a API for that in AuthMe? Because i see the /login message

No, but there is pr.
