### ISSUE TITLE
[SOLVED] Player doesn't automaticly auto register or auto login.

### ISSUE THREAD

**Issue by Scoooolzs** [games647/FastLogin#753]
### What happened?

Me doesn't automaticly auto register or auto login. I'm using Paper.

### What did you expect?

Can automatically register and automatically login.

### Steps to reproduce

I'm just trying to set according to the wishes of FastLogin and AuthMe.

### Plugin list

AuthMe, FastLogin, SkinRestorer. And more plugins.

### Configuration file

https://srcb.in/UZ6napt33x

### Server log

```shell
https://sourceb.in/wZ0mLNx2kx
```

### Plugin version

1.10-git484855724b794de1fe057cf7360245362658b432

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
You are not using the latest build. It's way out of date.

**Comment by Scoooolzs** [comment]
> You are not using the latest build. It's way out of date.

After updating to the latest, and it the same but with no error in console.

**Comment by Scoooolzs** [comment]
> Please post the newest log and the process of using the premium command

Uh i'm sorry, i didn't check using `/premium` in the newest auto login, but are on this plugin have automatic check if that player is premium or not?
