### ISSUE TITLE
AuthmeBridge for bungeecord?

### ISSUE THREAD

**Issue by Wearwolfy** [games647/FastLogin#76]
Is there a way to make this plugin work with AuthmeBridge bungeecord?

**Comment by games647** [comment]
What doesn't work?

**Comment by Wearwolfy** [comment]
No but is AuthmeBridge supported cause its not on the supported plugins list

**Comment by games647** [comment]
It's included with AuthMe

**Comment by Wearwolfy** [comment]
Now, how do you install it?
fastlogin on spigot and bungee, authme on spigot and authmeebridge on bungee and it should all work right?

**Comment by games647** [comment]
But you should also follow the guide on the main page.

**Comment by sgdc3** [comment]
> It's included with AuthMe

? :/ What do you mean @games647

**Comment by games647** [comment]
The support is covered by only mentioning AuthMe.
