### ISSUE TITLE
Fastlogin non funzionano 

### ISSUE THREAD

**Issue by eternominecraft** [games647/FastLogin#762]
Salve, sto provando a fare funzionare fastlogin ma non funziona, se faccio /premium o /cracked non da il messaggio che è stato settato con successo, nel database non viene salvato uud e se sei premium. Come risolvo?

**Comment by eternominecraft** [comment]
Hi, I'm trying to make fastlogin work but it doesn't work, if I do / premium or / cracked it doesn't give the message that it has been set successfully, uud is not saved in the database and if you are premium.  How do I resolve?

**Comment by games647** [comment]
Then please create a ticket that is called bug and fill out the template.
