### ISSUE TITLE
fastlogin doesn't work

### ISSUE THREAD

**Issue by eternominecraft** [games647/FastLogin#763]
### What happened?

hi, when a user does / premium or / cracked in the database is not updated and the message is not activated the "premium or sp" mode, I have as jar NachoSpigot.jar, I tried to replace it with spigot 1.8.x and it works but if they follow camado / premium says console: "/ premium [player]" if you try to do / premium EternoOfficial returns: "/ premium [player]"

### What did you expect?

that doing the command / premium or / cracked returns user set "premium or sp"

### Steps to reproduce

/premium EternoOfficial > console ssh / minecraft chat. 
/cracked EternoOfficial > console ssh / minecraft chat. 
error returned:  /premium [player] o /cracked [player]

### Plugin list

[15:13:22 INFO]: Plugins (21): WorldEdit, PlaceholderAPI, PlugMan, ViaVersion, ProtocolLib, WorldGuard, ViaRewind, LuckPerms, FastLogin, Vulcan, HolographicDisplays, Vault, LPC, Citizens, FateHubCore, Essentials, NamelessMC, AuthMe, TAB, CommandNPC, LiteBans >

### Configuration file

https://pastebin.com/WcabK6a9

### Server log

```shell
https://pastebin.com/BvmMfiuV

Version Spigot: spigot-1.8.8-R0.1-SNAPSHOT-latest.jar
Start.sh: 
/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar NachoSpigot.jar nogui
```

### Plugin version

1.10-git484855724b794de1fe057cf7360245362658b432

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by eternominecraft** [comment]
sorry but on spigot it is that

**Comment by games647** [comment]
Yes, but there is also a download link for the dev builds

**Comment by eternominecraft** [comment]
sorry but on the link https://ci.codemc.io/job/Games647/job/FastLogin/ it is always the build 10

**Comment by eternominecraft** [comment]
this is the one just downloaded [13:19:16 INFO]: FastLogin version 1.10-git484855724b794de1fe057cf7360245362658b432

**Comment by games647** [comment]
Where do you link there? The latest build is `#1063`. How come that you something with build number 10?

**Comment by eternominecraft** [comment]
look I downloaded builder # 1063 but it tells me it looks like: 1.10-git484855724b794de1fe057cf7360245362658b432

**Comment by games647** [comment]
Check the plugins folder if you still have the old version installed.

**Comment by eternominecraft** [comment]
I deleted and recreated the folder.  the version returned always that

**Comment by eternominecraft** [comment]
can you kindly provide me the direct download link

**Comment by eternominecraft** [comment]
![Screenshot_20220326-141421_JuiceSSH](https://user-images.githubusercontent.com/53921168/160241175-f22ad69c-6354-4187-b907-134f13a6ecee.jpg)

**Comment by eternominecraft** [comment]
![Uploading Screenshot_20220326-142143_JuiceSSH.jpg…]()

**Comment by eternominecraft** [comment]
![Screenshot_20220326-142143_JuiceSSH](https://user-images.githubusercontent.com/53921168/160241454-9ef778a6-60f8-47d9-a6ff-e635e7b2fed1.jpg)

**Comment by From-pErfo** [comment]
> can you kindly provide me the direct download link

Is it this one? `1.11-SNAPSHOT-812cf21`
https://ci.codemc.io/job/Games647/job/FastLogin/

**Comment by eternominecraft** [comment]
Yes

**Comment by games647** [comment]
@eternominecraft Note the different file name. Check if the old version is still installed. Only *Bukkit.jar should be installed.

**Comment by eternominecraft** [comment]
@games647 this is what's in the server folder

![Screenshot_20220326-145803_Admin Hands](https://user-images.githubusercontent.com/53921168/160242786-1b5619b8-64d5-446e-b859-c9cb047f71d7.jpg)

**Comment by eternominecraft** [comment]
@games647 this is what's in the server folder

![Screenshot_20220326-145803_Admin Hands](https://user-images.githubusercontent.com/53921168/160242861-3a9a42c8-d4c2-4500-89ca-a90dd3777a21.jpg)

**Comment by From-pErfo** [comment]
penultimate? FastLogin(1.10).jar

**Comment by eternominecraft** [comment]
ok, i solved the version but the problem persists

![Screenshot_20220326-150342_JuiceSSH](https://user-images.githubusercontent.com/53921168/160243047-392e2959-32e5-4874-9585-111372f27637.jpg)
![Screenshot_20220326-150314_ChatCraft](https://user-images.githubusercontent.com/53921168/160243048-d84dbd34-8013-443b-a914-7c3d7765d882.jpg)
![Screenshot_20220326-150238_JuiceSSH](https://user-images.githubusercontent.com/53921168/160243052-f94ac568-7620-47ce-92fc-97c1b230834a.jpg)
![Screenshot_20220326-150615_Chrome](https://user-images.githubusercontent.com/53921168/160243127-7fb8844e-4ba6-4f07-adaa-0dd8283dc1a3.jpg)

**Comment by games647** [comment]
If the user already exists, the user has to enable it manually using the premium command.

**Comment by eternominecraft** [comment]
the premium and crack system does not work.  in the database does not add you as premium or cracked.  nom doesn't even send the message he added to you

**Comment by eternominecraft** [comment]
now i have deleted user and it makes the same mistake, i also tried with another same user

**Comment by eternominecraft** [comment]
![Screenshot_20220326-150926_Chrome](https://user-images.githubusercontent.com/53921168/160243276-ad9a03eb-c2d3-4bc6-9ea2-341fdc038072.jpg)

**Comment by eternominecraft** [comment]
@games647 this is what happens

![Screenshot_20220326-151123_JuiceSSH](https://user-images.githubusercontent.com/53921168/160243339-c824146d-47b4-4541-9356-675c3255725c.jpg)
![Screenshot_20220326-151150_JuiceSSH](https://user-images.githubusercontent.com/53921168/160243344-021e0570-75c1-4662-a3c2-e0b2cc405f2f.jpg)
![Screenshot_20220326-150926_Chrome](https://user-images.githubusercontent.com/53921168/160243345-98c0f150-c091-429f-8840-50cdba96ad37.jpg)

**Comment by games647** [comment]
Check the startup log

**Comment by eternominecraft** [comment]
this is the log

@https://pastebin.com/Qz4VZcx8

**Comment by eternominecraft** [comment]
@games647 it seems to me that I see no errors

**Comment by From-pErfo** [comment]
Line 108 has sql error
Check the database?
I don't have this problem when I use SQLite, If the problem persists, do you want to consider changing the database and try it?

**Comment by eternominecraft** [comment]
now I connected it with SQLite but it gives an error: "Kicked whilst connecting to Hub: Server is not fully started yet. Please retry"

**Comment by From-pErfo** [comment]
It may be that other plugins are preventing the server from finishing starting, Wait for a while or see if there are any wrong plugins

**Comment by eternominecraft** [comment]
it appears to me online in the console and I have no plugins that give an error in loading

**Comment by eternominecraft** [comment]
File Log 
https://pastebin.com/7MSebkXv

**Comment by From-pErfo** [comment]
Sorry, this may not be within my capabilities
you can try to put `ProtocolLib, FastLogin, AuthMe` in a separate server [that is, temporarily remove all other plugins] to determine what the problem is

**Comment by eternominecraft** [comment]
needed authme, but now from further error 
![Uploading Screenshot_20220326-162043_ChatCraft.jpg…]()

**Comment by eternominecraft** [comment]
@games647 needed authme, but now from further error
![Screenshot_20220326-162043_ChatCraft](https://user-images.githubusercontent.com/53921168/160246039-1c91b2f2-dc9a-4ba0-9865-086611e16e00.jpg)

**Comment by eternominecraft** [comment]
the server is put in offline mode I don't understand the problem

**Comment by From-pErfo** [comment]
if you are using BC, you must also add FastLogin on BC and configure MySQL

**Comment by eternominecraft** [comment]
if i use fastlogin on MySQL it doesn't work

**Comment by eternominecraft** [comment]
@games647 @From-pErfo 

here is what happens when i connect mysql to fastlog and authme, here is the log
https://pastebin.com/rzzZEnjL

Questo è il config di authme 
https://pastebin.com/Y6wbaSnX

Questo è il config di FastLogin 
https://pastebin.com/KcZcMWPy

**Comment by eternominecraft** [comment]
@games647 @From-pErfo

here is what happens when i connect mysql to fastlog and authme, here is the log
https://pastebin.com/rzzZEnjL

This is the config of authme
https://pastebin.com/Y6wbaSnX

This is the config of FastLogin
https://pastebin.com/KcZcMWPy

**Comment by From-pErfo** [comment]
I see from the log that these two plugins are not connected to MySQL
But LuckPerms seems to be able to connect
Could it be that the database directory is not created for the plugin?

**Comment by eternominecraft** [comment]
how do i solve?

**Comment by From-pErfo** [comment]
Do you have directory ` fastlogin/` in your database directory? At the same time, the AuthMe plugin does not seem to be configured with MySQL

**Comment by eternominecraft** [comment]
@games647 @From-pErfo 

as you can see from the config authme and fast login have the data to access the database.  I am attaching a screenshot of the database
![Screenshot_20220327-115617_Chrome](https://user-images.githubusercontent.com/53921168/160276290-df49d48f-169a-4574-a80d-a63069c47773.jpg)

**Comment by From-pErfo** [comment]
There seems to be a big problem with the log format, do you consider uploading a clear one and waiting for others to support it?

**Comment by eternominecraft** [comment]
@From-pErfo I did not understand

**Comment by eternominecraft** [comment]
how can i fix this error?

**Comment by From-pErfo** [comment]
It's just that the log lacks line breaks and is not easy to read.
I tested MariaDB[MySQL] + plugin locally and it worked perfectly without any issues, even with your configuration
So I can't find any other questions...

**Comment by eternominecraft** [comment]
I am attaching the complete log
![Screenshot_20220327-121116_Log Viewer](https://user-images.githubusercontent.com/53921168/160276704-ed7c9ee3-bbfb-4461-9d29-192d46cdcd85.jpg)
![Screenshot_20220327-121129_Log Viewer](https://user-images.githubusercontent.com/53921168/160276706-feadaf9d-a660-4d93-97d2-0e0031cdaa4d.jpg)
![Screenshot_20220327-121142_Log Viewer](https://user-images.githubusercontent.com/53921168/160276709-9b00b89e-36d6-46cc-99b9-57f9ef13c92a.jpg)
![Screenshot_20220327-121157_Log Viewer](https://user-images.githubusercontent.com/53921168/160276711-55fc9c46-2171-4347-b2ca-b67fc8663df1.jpg)
![Screenshot_20220327-121208_Log Viewer](https://user-images.githubusercontent.com/53921168/160276715-048c187a-b01a-4aca-998c-aa0593bc2eb8.jpg)
![Screenshot_20220327-121217_Log Viewer](https://user-images.githubusercontent.com/53921168/160276716-dde8706f-65d1-4acb-84eb-60497930f2fd.jpg)
![Screenshot_20220327-121226_Log Viewer](https://user-images.githubusercontent.com/53921168/160276717-0d4eb264-7aa0-4df2-bf6b-32d248ab82eb.jpg)
![Screenshot_20220327-121232_Log Viewer](https://user-images.githubusercontent.com/53921168/160276721-58315d9c-b9d9-4dce-b844-841cd01b557f.jpg)

**Comment by eternominecraft** [comment]
@From-pErfo I apologize but I'm out of office and can't use the PC, I sent him the complete log via screenshot.  sorry again, hope they are clear

**Comment by eternominecraft** [comment]
@From-pErfo here is the complete log, the one provided a little while ago was the Lastlog.log
https://pastebin.com/dubw0Vzu

**Comment by eternominecraft** [comment]
@From-pErfo ha me does not really start the server if they are connected to MYSQL.  the server turns off automatically, I don't understand why

**Comment by From-pErfo** [comment]
This is my configuration, I hope it can give you reference
`The database is MariaDB, username root, password cc`

AuthMe: 
```
DataSource:
    # What type of database do you want to use?
    # Valid values: SQLITE, MYSQL, POSTGRESQL
    backend: MYSQL
    # Enable the database caching system, should be disabled on bungeecord environments
    # or when a website integration is being used.
    caching: true
    # Database host address
    mySQLHost: 127.0.0.1
    # Database port
    mySQLPort: '3307'
    # Connect to MySQL database over SSL
    mySQLUseSSL: false
    # Verification of server's certificate.
    # We would not recommend to set this option to false.
    # Set this option to false at your own risk if and only if you know what you're doing
    mySQLCheckServerCertificate: true
    # Username to connect to the MySQL database
    mySQLUsername: root
    # Password to connect to the MySQL database
    mySQLPassword: 'cc'
    # Driver Name of the MySQL database
    mySQLDriverClassName: com.mysql.cj.jdbc.Driver
    # Database Name, use with converters or as SQLITE database name
    mySQLDatabase: AuthMe
    # Table of the database
    mySQLTablename: authme
```

FastLogin:
```
driver: com.mysql.cj.jdbc.Driver
host: 127.0.0.1
port: 3307
database: FastLogin
username: root
password: cc
```

**Comment by From-pErfo** [comment]
> @From-pErfo ha me does not really start the server if they are connected to MYSQL. the server turns off automatically, I don't understand why

This is the protection mechanism of AuthMe. If there is no database, the server will be shut down to prevent players from stealing accounts.

**Comment by eternominecraft** [comment]
how do i manually create directories in database?

**Comment by From-pErfo** [comment]
> how do i manually create directories in database?

Didn't you encounter this step when using the database?
I will create an empty directory named plugin name for the plugin directly under the data directory, and then specify the corresponding directory in the plugin's configuration. plugin will automatically store data files in the directory

**Comment by eternominecraft** [comment]
honestly I got lost in the middle of the message

**Comment by From-pErfo** [comment]
Maybe it has something to do with the translation software I use... but I check every time the translation is correct...

**Comment by eternominecraft** [comment]
no it's that I'm not understanding

**Comment by From-pErfo** [comment]
Do you really need to use BC?
If you don't have a group server, you can learn about single server

**Comment by eternominecraft** [comment]
BC things

**Comment by eternominecraft** [comment]
and a public server, so I need this system

**Comment by eternominecraft** [comment]
@From-pErfothings C, and a public server, so I need this system.  how can i fix it?

**Comment by eternominecraft** [comment]
*BC

**Comment by From-pErfo** [comment]
Sorry for not replying to you, in fact I can not give a direct solution, I think this has nothing to do with software

**Comment by eternominecraft** [comment]
Ok sorry

**Comment by games647** [comment]
You run a bungeecord network, so please follow the setup guide for those environments referenced on the project page of Spigot and here.
