### ISSUE TITLE
 Authme Integration Doesn't Work

### ISSUE THREAD

**Issue by KaspianDev** [games647/FastLogin#765]
### What happened?

Even after console message that fastlogin logged me automatically, authme wants me to use /register command (and when i run that command nothing happens)

### Plugin list

Authme, Protocollib, Fastlogin

### Configuration file

https://www.toptal.com/developers/hastebin/wuziyomevo.yaml

### Plugin version

#1061

### Platform

Spigot

### Relevance

- [X] I tried the latest build
- [x] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Please post the server log from that time.

**Comment by From-pErfo** [comment]
There is a temporary solution: [#772 ](https://github.com/games647/FastLogin/issues/722)

**Comment by KaspianDev** [comment]
Yes that helped, do you know when possibly this will be permamently fixed?
