### ISSUE TITLE
Compatibility with AntiBotAttack

### ISSUE THREAD

**Issue by Eufranio** [games647/FastLogin#77]
I'm using FastLogin and AntiBotAttack (https://www.spigotmc.org/resources/anti-bot-attack.18540/) on my bungee network. I use FastLogin to separate Premium players from Cracked players and obtain the correct UUIDs, etc.
The problem is, when AntiBotAttack starts the AntiBot, all players joining the server are logged as cracked, ignoring FastLogin. Would be cool if, when a player connects the server when AntiBot is active, FastLogin be able to separate the stuff correctly. Do you get it?

**Comment by games647** [comment]
Not FastLogin's fault. AntiBotAttack is overriding the UUID on the highest event priority. This runs after all other listeners finished (including FastLogin).

You could disable protection or protection.offline. Looks like the last one is for this case:
># OFFLINE - If your server is offline, leave this as true. If you have a mixed-mode server,
# it means you log your online players as in an online server, so put this as false.
