### ISSUE TITLE
[BUG] The premium command dosent work sometimes

### ISSUE THREAD

**Issue by kedavlar** [games647/FastLogin#776]
### What happened?

Some player do command /premium 2 times, slog and relog and they are not counted as premium account, they need to put the password anyways

### What did you expect?

Autologin . Yes i have the config with autologin, for myself work correct

### Steps to reproduce

new player enter the lobby, do /premium 2 times , slog and relog

### Plugin list

authme, fastlogin

### Plugin version

1.11 0bdcc93

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Please post the server log from that timestamp

**Comment by kedavlar** [comment]
this is an example of one player https://pastebin.com/2ABaSBGt

**Comment by games647** [comment]
There you have an exact error message: No on-going login session for player

This means it couldn't find the player state. Check if the ID matches the IP.

**Comment by kedavlar** [comment]
its possible that the problem is caused by tcpshiled? anyways , the ip is the same

**Comment by games647** [comment]
Yes, because that plugin changes the IP during the login process. There is pinned issue for that.

**Comment by kedavlar** [comment]
oh sorry, i didnt see it, ill download now
