### ISSUE TITLE
When a Premium player joins, everyone crashes.

### ISSUE THREAD

**Issue by Maxetto** [games647/FastLogin#78]
I'm having this strange issue today where every player crashes with
`Internal Exception: net.minecraft.util.io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.`
when a Premium player joins.
After some tests it seems it's an issue with FastLogin, but I don't know really what causes it since some Premium players can join fine (maybe because they were already online in BungeeCord?) but mostly cannot.

Previously I have received a DDoS attack and got this in Console:

```
15:30:46 [SEVERE] Error authenticating TheGiantBoy with minecraft.net
io.netty.handler.timeout.ReadTimeoutException
```

In the server console I got this error, but I don't know if it's related:
http://pastebin.com/8TxqwFRV

Using:
BungeeCord b1118 (For 1.7 and 1.8)
Spigot 1.7.10 b1657
Spigot 1.8.8 git-Spigot-db6de12-18fbb24
FastLogin v1.7.1

**Comment by games647** [comment]
Why don't you use 1.8 of FastLogin?

**Comment by games647** [comment]
>In the server console I got this error, but I don't know if it's related:
http://pastebin.com/8TxqwFRV

This error is related to the tablist. Maybe from a skin plugin.

**Comment by Maxetto** [comment]
> Why don't you use 1.8 of FastLogin?

I'm slow with updates.

> This error is related to the tablist. Maybe from a skin plugin.

So might be related to this?
http://pastebin.com/cRk1yKre

**Comment by games647** [comment]
Could be. It's a guess. It sounds like there were invalid data in that packet. I found out that this happens when sending two packets at the same time.

**Comment by Maxetto** [comment]
I did more testing and it's indeed FastLogin. The other error is not related to this problem.

This is all I get in console:
`Internal Exception: net.minecraft.util.io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.`

And in my client I have a generic:
`[Proxy] Lost connection to server`

Seems to happen when the "AUTO_LOGIN" plugin message is sent, or at least not instantly right when I join (there's a fraction of second where I can see chat messages and a bit of spawn)

**Comment by games647** [comment]
>Seems to happen when the "AUTO_LOGIN" plugin message is sent, or at least not instantly right when I join (there's a fraction of second where I can see chat messages and a bit of spawn)

Yes that's and intended. What's your authplugin including version?

**Comment by Maxetto** [comment]
AuthMe v3.4

**Comment by Maxetto** [comment]
I readded FastLogin v1.7.1 and it works again. I think it happened because I got rate limited or Mojang servers were down (I saw some reports on a Forum where they were down yesterday at 16:30 CEST).

That also explains why it started doing this only today.

I'm updating to 1.8 but I did not see anything that might have fixed this issue.

**Comment by games647** [comment]
How do you tested that is caused by FastLogin. I think it could be also the combination of onlinemode and skins/tablist.

Could you make clear when the error happens.

>15:30:46 [SEVERE] Error authenticating TheGiantBoy with minecraft.net
io.netty.handler.timeout.ReadTimeoutException

This one seems normal when the session servers were down.

**Comment by Maxetto** [comment]
I removed plugins one by one till it didn't crash anymore. And that was when I removed FastLogin. After that I re-added every plugin but FastLogin and it worked. In Late Night I tried to re-add the old FastLogin and it worked fine again.

The error happened when Mojang servers were down (or at least experiencing heavy load), in Bungee I find error 502 when getting the Skin from the Skin Server and that error with Authentication server (whether this was caused by Mojang outage or a DDoS i don't know)
In Spigot Console, when that error happens, player doesn't connect. If he retries and this error doesn't show, the player connects to the server and crashes everyone with Internal Error.

**Comment by games647** [comment]
>the player connects to the server and crashes everyone with Internal Error.

What internal error?

**Comment by Maxetto** [comment]
> What internal error?

The one I wrote in the first post:
```
Internal Exception: net.minecraft.util.io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.
```

**Comment by games647** [comment]
Nothing else. No stacktrace?

**Comment by Maxetto** [comment]
Nothing more is given. Client sees "[Proxy] Lost connection to the server"

**Comment by games647** [comment]
I'm still assuming it's the combination the onlinemode and your other plugins, because when BungeeCord is available. FastLogin doesn't do much in the internals. 

The lost connection kick message could also come from the tablist plugin, because BungeeCord disconnects the player after it cannot parse a packet like the one you posted above.

Besides that I'm going to test it to be sure.

**Comment by Maxetto** [comment]
Might be. When a Player gets Premium Authentication they can see player heads in the Tablist. But I don't get why every player on that server must crash when someone Premium joins.

**Comment by games647** [comment]
I guess invalid data while encoding data into packets.

**Comment by games647** [comment]
I couldn't reproduce it. Could I get your plugins list? 

Then I would let this open and mark it awaiting answer. Maybe another person has this issue too, then this ticket can be used.

**Comment by Maxetto** [comment]
From Spigot:
`Plugins (33): icJukeBox, WorldEdit, SkinsModule, Essentials, BarAPI, PremiumUtil, PlugMan, Buycraft, SuperCensor, BungeePlayerCounter, ProtocolLib, WorldGuard, ParticleMenu, NoCheatPlus, LibsDisguises, BungeePortals, ChestCommands, EssentialsChat, PermissionsEx, AntiJoinBot, BungeeTabListPlus_BukkitBridge, CustomJoinItems, EssentialsSpawn, RealTime, WorldEditSelectionVisualizer, HubBasics, FastLogin, AuthMe, ClickEdit, HolographicDisplays, HolographicDisplaysPatch, AuthMeBridge, DonationsHolograms`

From BungeeCord:
`Plugins (11): FastLogin, easyBungeeChat, SkinsRestorer, ServerListPlus, BungeeTabListPlus, BungeeAuthMeBridge, BungeeTools-HubCommand, MoveMeNow, RedisBungee, SimpleCommands, SwitchAnnounce`

**Comment by games647** [comment]
Thanks a lot

**Comment by Maxetto** [comment]
I fixed it, but don't know how. Maybe it got fixed with time.
Since no one answered in 2 months, I guess I was the only with this issue.

We can close this. I'll update if this happens again at some point.

**Comment by games647** [comment]
Big sorry, but I could reproduce it. I tried a most everything. Next time you get something like that post the client log too.

It's really hard to simulate such situations. I'm really sorry that I couldn't help you.

**Comment by Maxetto** [comment]
Don't worry. It happened randomly and randomly got away.
I still think it has something to do with Offline Authentication servers, but I can't know.

As I said, I'll reopen the ticket if it happens again.
