### ISSUE TITLE
Players have the same IP address without any proxies (192.168.0.1)

### ISSUE THREAD

**Issue by games647** [games647/FastLogin#780]
### What happened?

All players have the same IP. `192.168.0.1`

### What this issue is about?

This ticket is only about server setups without reverse proxies involved. Please use an existing ticket or create a new for that. For example:

* Plugins in combination with reverse proxies: HAProxy or TCPShield: See #722
* Minecraft proxies like BungeeCord/Velocity: See #728

### Is this relevant for me?

* You don't use BungeeCord/Velocity.
* You are not using HAProxy, TCPShield or similar local proxies.

### What information this ticket needs?

It's important for us to get all the information to reproduce it and find the source. So please provide the following details:

* Server software with exact version number
* Plugin version
* Which type of login logic you are using, namely if you are using ProtocolLib or ProtocolSupport and in which version.
* Full server log
* Plugin configuration file
* Special steps to reproduce?

In order to find the source of this bug, please provide the smallest reproducible setup. This means:

* Only FastLogi, auth and protocol plugin installed
* Please state explicitly if happens too without any plugins installed at all.
<details>
Motivation is unexpected server hoster changes, which we also saw in the past.
</details>

* Doesn't happen with the other protocol plugin too? Then maybe it's an issue there or the integration of this.

Original:
<details>
@HuJK 

>I think it's FastLogin's bug

Doesn't have to be, it's only a correlation. First lets get the smallest reproducible configuration.

@HuJK @CroaBeast Please try it out with only auth plugin and FastLogin installed. There is a lot of chaos about what exactly the server configurations are. It's very important which server software you are using and what plugins are installed. Including if Minecraft native proxies are involved, see below. That's why I'm splitting up the tickets for proxy and without proxy setups.

There are big differences between a Minecraft proxy setup like the OP and ProtocolLib, ProtocolSupport spigot only handling. With Minecraft proxies the integration is not so deep. The plugin uses the direct BungeeCord/Velocity API onlinemode changes. The forwarding of details to Spigot then is done by BungeeCord and is the same like normal online mode. The Spigot plugin of FastLogin only gets the command to authenticate to the auth plugin. There are no changes to Minecraft internals here.

_Originally posted by @games647 in https://github.com/games647/FastLogin/issues/728#issuecomment-1094202486_

</details>

**Comment by games647** [comment]
I updated the issue description. Please provide all details asked to help us find the cause efficiently and fast.

**Comment by HuJK** [comment]
The buggy version is download from here: https://github.com/games647/FastLogin/releases

Problem resolved by upgrade to the latest version(Build 1070) of FastLogin downloaded from https://ci.codemc.io/job/Games647/job/FastLogin/

**Comment by games647** [comment]
@HuJK The version uploaded on GitHub is from a different branch with TCPShield in mind. However it's good to know that it's no longer happening. It's still fascinating, because the changes there...

Wow, just realized debug code in it. Exactly setting the local IP. However that version is out of date and isn't even the normal release like mentioned special branch for TCPShield.

**Comment by games647** [comment]
I'm closing this one in favor of the old ticket. @HuJK Thanks for hint. It was then easy to check the differences between the two versions.
