### ISSUE TITLE
Server has to be in offline mode

### ISSUE THREAD

**Issue by adalmo** [games647/FastLogin#782]
### What happened?

i installed latest plugin version 1070 build from ci but it keeps saying server didn't started up even i using latest paper version and already server has been started 

### What did you expect?

install latest 1070 build from ci
and got this message when i try to join server

### Steps to reproduce

just install latest build #1070
and launch server and try to join get error message

### Plugin list

Geyser,floodgate

### Plugin version

#1070 build

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Please post the server log as requested in the template.

**Comment by adalmo** [comment]
Duplicate of #

**Comment by adalmo** [comment]
[2022-04-16-2.log](https://github.com/games647/FastLogin/files/8500094/2022-04-16-2.log)

**Comment by adalmo** [comment]
[2022-04-16-2.log](https://github.com/games647/FastLogin/files/8500097/2022-04-16-2.log)

**Comment by games647** [comment]
>
[23:31:17] [Server thread/INFO]: [Geyser-Spigot] Done (2.28s)! Run /geyser help for help!
[23:31:17] [Server thread/INFO]: [FastLogin] Enabling FastLogin v1.11-SNAPSHOT-a327916
[23:31:17] [Server thread/ERROR]: [FastLogin] Server has to be in offline mode

**Comment by adalmo** [comment]
i set online mode to offline on server proper and geyser config but it still happens

**Comment by adalmo** [comment]
> i set online mode to offline on server proper and geyser config but it still happens
did i do something wrong on config? 
but i checked it again and again what's wrong with online mode

**Comment by From-pErfo** [comment]
> i set online mode to offline on server proper and geyser config but it still happens

You will presumably need to continue to provide logs

**Comment by adalmo** [comment]
can i send the logs on discord? Somehow i can't send the full logs on here

**Comment by From-pErfo** [comment]
Waiting for developer reply..
*Don't care, I'm not a developer, I just want to understand the problem*

**Comment by games647** [comment]
Please post then the `server.properties`

**Comment by adalmo** [comment]
#Minecraft server properties
#Sat Apr 16 23:37:46 KST 2022
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
enable-command-block=false
enable-query=false
generator-settings={}
level-name=world
motd=A Minecraft Server
query.port=25565
pvp=true
generate-structures=false
difficulty=hard
network-compression-threshold=512
require-resource-pack=false
max-tick-time=60000
use-native-transport=true
max-players=100
online-mode=false
enable-status=true
allow-flight=true
broadcast-rcon-to-ops=true
view-distance=5
server-ip=
resource-pack-prompt=
allow-nether=true
server-port=25565
enable-rcon=false
sync-chunk-writes=false
op-permission-level=4
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=5
rcon.password=
player-idle-timeout=0
debug=false
force-gamemode=true
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
function-permission-level=2
level-type=default
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
resource-pack-sha1=
spawn-protection=0
max-world-size=29999984

**Comment by games647** [comment]
Sorry, but the server configuration always sets it to onlinemode. Check if it's caused by some plugins by uninstalling them one by one. Or maybe your startup parameters load a different properties file.

I see that the Java process is started by root. If this is the case, because inside a container, check if the uploaded properties file is mounted inside. Nevertheless the Java process should never run as an administrator.

**Comment by adalmo** [comment]
how can i prevent to open bat with root (admin) i tried to edit it to not run in adminster mode but there is none option to turn it off (exe file can edit it to not run as admin)

**Comment by games647** [comment]
@adalmo I imagine in Windows the running should be not an administrator, but I'm the wrong person to answer this. It's unrelated to the cause of this issue.

@YanHanr Check your server.properties file too.

**Comment by YanHanr** [comment]
```
#Minecraft server properties
#Sun Apr 17 23:48:38 CST 2022
enable-jmx-monitoring=false
rcon.port=25575
level-seed=648240
gamemode=survival
enable-command-block=false
enable-query=false
generator-settings={}
level-name=srs
motd=A Minecraft Server
query.port=25565
pvp=true
generate-structures=true
difficulty=easy
network-compression-threshold=256
require-resource-pack=false
max-tick-time=60000
use-native-transport=true
max-players=20
online-mode=false
enable-status=true
allow-flight=true
broadcast-rcon-to-ops=true
view-distance=5
server-ip=
resource-pack-prompt=
allow-nether=true
server-port=25565
enable-rcon=false
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=3
rcon.password=
player-idle-timeout=0
debug=false
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
function-permission-level=2
level-type=default
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
resource-pack-sha1=
spawn-protection=16
max-world-size=29999984
```

**Comment by adalmo** [comment]
Seems like my win acc is running with adminster acc so should i make other acc and reinstall paper and plugin or just disable adminster from acc?

**Comment by games647** [comment]
Of course you then need to make the necessary folders accessible by the related user.

**Comment by adalmo** [comment]
is this plugin support about paper i saw the update logs on jenkins and it said FastLogin For spigot only and i can't not find a way to turn off administer with d drive access

**Comment by games647** [comment]
Yes FastLogin supports Paper. It's a fork of Spigot.

**Comment by games647** [comment]
Regarding onlinemode, you should try to remove the other plugins and add them one-by-one to find the causing plugin.

**Comment by adalmo** [comment]
ok i will try thx for reply :)

**Comment by adalmo** [comment]
it's works now but when i and my friends are tried to join with premium account or cracked account of java it requires /login password everytimes i rejoin server so how can i make auto login for them?

**Comment by games647** [comment]
Run the premium command. Autoregister, if activated in configuration, is only enabled for new players.
