### ISSUE TITLE
Geyser Bug

### ISSUE THREAD

**Issue by JohnnyX071** [games647/FastLogin#786]
### What happened?

i tried using FastLogin with AuthMe on my crossplay server. I tested with my bedrock account and I could join. However after I relog it kept kicking me and saying: Your username contains illegal characters and for some reason said detected cracked player in the console even though I have bough bedrock account. I tried removing FaastLogin and it worked fine.

### What did you expect?

The expected behavior would be to let bedrock players always join.

### Steps to reproduce

I just used the AuthMe plugin with FastLogin

### Plugin list

Admin-GUI, AdvancedCrates, AdvancedEnchantments, AdvancedHelp, AuctionHouse, AureliumSkills, AuthMe, BKCommonLib, Citizens, ClearLag, CommandPanels, CustomCrafting, DeluxeMenus, DriveBackupV2, EliteArmor, Essentials, EssentialsChat, ExecutableItems, FastAsyncWorldEdit (WorldEdit), FastLogin, floodgate, Geyser-Spigot, HolographicDisplays, HubThat, ItemJoin, JumpPads, LuckPerms, MiningBlocks, Multiverse-Core, NexEngine, NoPlugins, PlaceholderAPI, PlugMan, ProtocolLib, Quests, SCore, ShopGUIPlus, SimpleScore, spark, SuperiorSkyblock2, SuperVanish, TAB, TelePads*, UltimateCore, UltimateCore-Farm, UltimateKits, UltraMinions, Vault, ViaBackwards, ViaVersion, VoidGen, Votifier, VotingPlugin, WolfyUtilities, WorldGuard

### Configuration file

https://gist.github.com/JohnnyX071/84d71a67eb62f7206220380b7ab4cc58

### Server log

```shell
[FastLogin] Floodgate Prefix detected on cracked player
```

### Plugin version

Beta #1069

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by Smart123s** [comment]
> #### Server log
> ```
> [FastLogin] Floodgate Prefix detected on cracked player
> ```

This message should only show up when a cracked Java player joins, and when their name contains the Floodgate prefix. Did you get this message when a bedrock player was joining?

**Comment by JohnnyX071** [comment]
Yes that's when I got it. Well it doesn't matter now since I have switched to online mode. Thanks for your reply though! :)
