### ISSUE TITLE
Disconnect player first time join

### ISSUE THREAD

**Issue by kedavlar** [games647/FastLogin#788]
### What happened?

Every proxy restart, every players join first time got disconnected with message ''disconnect'' and after that they can reconnect normally. I try without fastlogin on proxy and it work normally.

I use lastest velocity version on proxy, the #1069

For spigot i use the last modified version for TCPshield problem with ip (127.168.0.1)

### What did you expect?

Join without disconnect

### Plugin version

v1.11-SNAPSHOT-4f3c8ad

### Platform

Velocity

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Please add the missing server log.

**Comment by kedavlar** [comment]
yep, sorry. https://pastebin.com/07ci9Cmm

**Comment by games647** [comment]
Please post the Spigot log. That's more relevant in this case.

**Comment by kedavlar** [comment]
sure, but remember that work on waterfall. https://pastebin.com/uSHD6CVA

**Comment by games647** [comment]
According to that log, it's normal. Paper delays the processing of the communication message from a proxy, regardless of Velocity and Waterfall. Therefore, you see the `no on-goging` message, but still logs you in after that.

In this log, everything seems to be working fine. Can you confirm? I'll need the part where it doesn't work.

**Comment by kedavlar** [comment]
the part where it dosent work just say ''no on-goging message'' , nothing else

**Comment by kedavlar** [comment]
solved for now

**Comment by CormacZ** [comment]
wait, how you fix the "CraftPlayer" thing. i cant relog in my server each time I tried to

**Comment by games647** [comment]
@kedavlar Please post the server log at the time. We need to know the state of the plugin at that time.

**Comment by games647** [comment]
That's exactly what I need to know. What kind of messages does it print? Then I can analyze the steps it took. As well as which plugin version you now use and the Spigot (or which fork) server version.

**Comment by CormacZ** [comment]
> Nvm.. its just a coincidence... with a LOT of test i detect the problem. Ty for the help.

tell mee
