### ISSUE TITLE
Anti-bot lag/crash server

### ISSUE THREAD

**Issue by CormacZ** [games647/FastLogin#796]
### What happened?

I turn the anti bot and test it with the free version of bot raid and TPS when down so bad. I tried with BotSentry/UltimateAntiBot and disabled anti-bot on fast login and got the same result either crash or just massive lag. UltimateAntiBot just gonna disconnect you from the game but when I remove the Fast login plugin and test another raid, it starts working smoothly back without disconnecting players.

### What did you expect?

Work fine with other anti-bot plugins without any massive lags or crash

### Plugin version

1.11-SNAPSHOT-a327916

### Platform

Spigot

### Relevance

- [x] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
FastLogin needs to intercept the packets very early in the process on networking level. Anti Bot plugins might not catch it at this stage. Therefore either the Anti-Bot plugin needs to run at earlier connection stage, use a more lower layer solution (packet-based) or listen to FastLogin events. FastLogin has a simple Anti-Bot feature, that will ignore all ignore at certain stage. You can tune that in the configuration file.

**Comment by CormacZ** [comment]
Alright new problem, FastLogin run before the player got WHITELISTED which is an inconvenience!

**Comment by games647** [comment]
That's exactly what I wrote earlier.

**Comment by TDMidkwhatisxd** [comment]
I got that too, its from a free bot attack site.

anti-bot:
  enabled: true
  # Image the following like bucket. The following is total amount that is allowed in this bucket, while expire
  # means how long it takes for every entry to expire.
  # Total number of connections
  connections: 200
  # Amount of minutes after the first connection got inserted will expire and made available
  expire: 1


Will this help me with the tps problem?

**Comment by games647** [comment]
As stated in its comments, this feature drops any load made by FastLogin. So yes they login as cracked, because even the database connection will not be made. Other load by FastLogin is the same as any other onlinemode server.

Make stress test before you tune anything to find the source of performance issues. Timings reports are very helpful, but you can also use Java profilers. You could also try to disable `autoRegister`, although this already gets disabled after 600 request per 10 minutes (Mojang rate limit).
