### ISSUE TITLE
Fastlogin issue

### ISSUE THREAD

**Issue by sebastiaannnn** [games647/FastLogin#797]
### What happened?

Hey, im owning quite a big network (peak time 300+) And i got a few issues with fastlogin, would you mind contacting me on discord?
 thats faster & easier to explain! 
 Discord: ! ASebastiaan#7350
 

### Plugin version

Build #1070 (Fri Apr 08 23:05:45 UTC 2022)

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by sebastiaannnn** [comment]
Alright so basically:
i own a network with different lobbies and also different proxies. i use the same database for both of them

In short:
sometimes on 1 of the servers the fastlogin feature stops working, and then on the other server it still runs completly fine. A reboot of the lobby + proxy would fix this but doing that a few times a day kind of hurts with a few hunderd players online.

**Comment by sebastiaannnn** [comment]
No errors etc are given

**Comment by games647** [comment]
Please post the log of the proxy and the spigot server at the time it doesn't login the user.
