### ISSUE TITLE
1.19 compatibility

### ISSUE THREAD

**Issue by games647** [games647/FastLogin#809]
Microsoft/Mojang changed a lot of the authentication protocol. This requires a lot of work and testing. As protocol changes are very recent, not a lot of research was done about the internal changes. Furthermore, the login authentication is a critical area, so requires careful code design and tests. As I don't have much time for a hobby project, because of personal issues, expect some delay.

# Status:
### ProtocolLib
Won't work - not tested, but strongly appears so from the code.

### ProtocolSupport
Could work - not tested

## Proxy-side
The supported proxies allows for enabling onlinemode using an API call. Therefore breaking changes are very unlikely.

### BungeeCord
Fixed in https://github.com/games647/FastLogin/commit/6665c0359b1cc45845a6b0277081f62a018ac4f9

Now always requires the latest version, because BungeeCord is backwards compatible.

### Velocity
No changes required from FastLogin.

**Comment by Tander** [comment]
Can provide some info:

with ProtocolLib #559 - getting this error, autologin doesn't work
`[23:17:22 WARN]: [ProtocolLib] Loaded class com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener from FastLogin v1.11-SNAPSHOT-6665c03 which is not a depend or softdepend of this plugin.
[23:17:22 ERROR]: [FastLogin] Unhandled exception occurred in onAsyncPacket() for FastLogin
com.comphenix.protocol.reflect.FieldAccessException: No field with type com.mojang.authlib.GameProfile exists in class PacketLoginInStart.
	at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216) ~[ProtocolLib.jar:5.0.0-SNAPSHOT-b559]
	at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib.jar:5.0.0-SNAPSHOT-b559]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.onLogin(ProtocolLibListener.java:126) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.ProtocolLibListener.onPacketReceiving(ProtocolLibListener.java:96) ~[FastLoginBukkit.jar:?]
	at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:642) [ProtocolLib.jar:5.0.0-SNAPSHOT-b559]
	at com.comphenix.protocol.async.AsyncListenerHandler.listenerLoop(AsyncListenerHandler.java:596) [ProtocolLib.jar:5.0.0-SNAPSHOT-b559]
	at com.comphenix.protocol.async.AsyncListenerHandler.access$200(AsyncListenerHandler.java:48) [ProtocolLib.jar:5.0.0-SNAPSHOT-b559]
	at com.comphenix.protocol.async.AsyncListenerHandler$2.run(AsyncListenerHandler.java:229) [ProtocolLib.jar:5.0.0-SNAPSHOT-b559]
	at com.comphenix.protocol.async.AsyncListenerHandler$3.run(AsyncListenerHandler.java:300) [ProtocolLib.jar:5.0.0-SNAPSHOT-b559]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82) [spigot-1.19-R0.1-SNAPSHOT.jar:3507-Spigot-fa893f0-c3f219e]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.19-R0.1-SNAPSHOT.jar:3507-Spigot-fa893f0-c3f219e]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
`

with ProtocolSupport #673 it just doesn't output any errors, and autologin doesn't work too

**Comment by gavenda** [comment]
ProtocolLib recently added wrappers for ProfileKeyData which is now being used by 1.19 login:

https://github.com/dmulloy2/ProtocolLib/commit/84a0b5ffdd7de13ef0fbbe6c9fc2a697e8ce9770#diff-3f954902d97423b8e2d9515f479ff251c366fb2444b6461d7d42b3b6850b41e5

**Comment by games647** [comment]
@comonier This always means there is an issue with the plugin not responding on the proxy. Please check your proxy logs. You are likely running a FastLogin that isn't compatible with your proxy version. Newer FastLogin version require the last proxy.

**Comment by games647** [comment]
> ProtocolLib recently added wrappers for ProfileKeyData which is now being used by 1.19 login:
> 
> [dmulloy2/ProtocolLib@84a0b5f#diff-3f954902d97423b8e2d9515f479ff251c366fb2444b6461d7d42b3b6850b41e5](https://github.com/dmulloy2/ProtocolLib/commit/84a0b5ffdd7de13ef0fbbe6c9fc2a697e8ce9770#diff-3f954902d97423b8e2d9515f479ff251c366fb2444b6461d7d42b3b6850b41e5)

Thanks for noticing that. However, the signature data is more important at the moment. The verification of profile keys is introduced as optional feature by Mojang and we could do the same. The client -> served online mode acknowledgement is now cryptographic signed too. This signature field is encapsulated behind an `Either` field. This is a lot trickier to get to and as far as I know not available in ProtocolLib as of now. 

Furthermore the Mojang verification logic still has to be implemented by FastLogin. Most of it is already is implemented. However it still lacks some test cases.

**Comment by gavenda** [comment]
> @gavenda
> 
> > ProtocolLib recently added wrappers for ProfileKeyData which is now being used by 1.19 login:
> > [dmulloy2/ProtocolLib@84a0b5f#diff-3f954902d97423b8e2d9515f479ff251c366fb2444b6461d7d42b3b6850b41e5](https://github.com/dmulloy2/ProtocolLib/commit/84a0b5ffdd7de13ef0fbbe6c9fc2a697e8ce9770#diff-3f954902d97423b8e2d9515f479ff251c366fb2444b6461d7d42b3b6850b41e5)
> 
> Thanks for noticing that. However, the signature data is more important at the moment. The verification of profile keys is introduced as optional feature by Mojang and we could do the same. The client -> served online mode acknowledgement is now cryptographic signed too. This signature field is encapsulated behind an `Either` field. This is a lot trickier to get to and as far as I know not available in ProtocolLib as of now.
> 
> Furthermore the Mojang verification logic still has to be implemented by FastLogin. Most of it is already is implemented. However it still lacks some test cases.

I basically have a fork of your codebase ported over Kotlin right [here](https://github.com/gavenda/yawa/tree/master/yawa/src/main/kotlin/work/gavenda/yawa/login) and offline mode with premium login already works. But the code isn't backwards compatible and just runs assuming you're on 1.19.

I just experimented with it and somehow made it work. I stored the public key data if it exists (or sent by client) in a session and used that to fake a login packet.

Related code:
https://github.com/gavenda/yawa/blob/3fb25d7e011dbb220480c41cd3e5e3d6cda3d7a6/yawa/src/main/kotlin/work/gavenda/yawa/login/LoginListener.kt#L58

https://github.com/gavenda/yawa/blob/3fb25d7e011dbb220480c41cd3e5e3d6cda3d7a6/yawa/src/main/kotlin/work/gavenda/yawa/login/LoginEncryptionTask.kt#L172-L192

It should be comfortable with you since its really just a miniature port of this plugin.

**Comment by games647** [comment]
@gavenda Maybe I'm missing it, but where do verify the nonce/verify token? That's the part I'm talking about earlier. It's necessary to prevent relay attacks.

**Comment by gavenda** [comment]
> 

I'm missing on that as well, the nonce token somehow became missing on ENCRYPTION_BEGIN, reading index 1 just throws an index out of bounds. It seems like they're using the public key data for signing somehow (starting 1.19 ?). I just skipped the verification part in my end but it will be critical for this plugin.

I can try to experiment a bit more and see if the public key data can be used to verify something on our end.

**Comment by Jairusu9100** [comment]
Do you already have an ETA on when auto login will work for premium players? This plugin is just what we are waiting for for our 1.19 papermc server to open. Thank you!

**Comment by games647** [comment]
Look at #821 to see the current status.
