### ISSUE TITLE
Exception encountered when loading plugin.

### ISSUE THREAD

**Issue by Kydaix** [games647/FastLogin#812]
### What happened?

When I start the Bungeecord _(Aegis Escanor 1.7.3)_, the plugin does not load correctly. It generates an error, then if I connect with my Premium account, it does not work and makes it like if it was a cracked account.

**Version:** 1078
**_This bugs appears after the 1075 build._**

It only does that on the Bungeecord server.

### What did you expect?

The plugin should load correctly without errors and if a player connects as premium, make it premium.

### Steps to reproduce

Install FastLogin-1078 on Bungeecord (maybe it's related to Aegis).
Install FastLogin-1078 on the spigot server.
Start both servers.

### Plugin list

CommandBlockerFull [2.1.2], FastLogin [1078], LuckPerms [5.4.26], TAB [3.1.1], TAB-Additions [1.6.3], UltraEconomy [2.1.0]

### Configuration file

https://www.toptal.com/developers/hastebin/iyokedeqav.yaml

### Server log

https://www.toptal.com/developers/hastebin/awisimekoj.yaml

### Plugin version

Build 1078

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Your BungeeCord version is outdated.

>Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.protocol.Property

**Comment by Kydaix** [comment]
So should I contact the developper of my Bungeecord and report him the error?

**Comment by games647** [comment]
If you have a custom version, yes.

**Comment by Kydaix** [comment]
Ok, thank you!
