### ISSUE TITLE
Is this possible?

### ISSUE THREAD

**Issue by Wearwolfy** [games647/FastLogin#82]
Is it possible like to enable autoRegister and let cracked players login with premium names but when the premium users joins it clears the cracked user and this way the premium player can play?

**Comment by games647** [comment]
So you want to ban your active cracked player if a premium player joins?

**Comment by Wearwolfy** [comment]
nah not ban, just erease the data from the cracked player and let the premium player play like he never knew some1 used his account

**Comment by games647** [comment]
That's nearly the same. That will be very frustrating for your players. Don't let **active** cracked players join the server and delete all data if a premium player with the same name joins the server. 

Furthermore you can just buy the username of a famous cracked player on your server and that player cannot longer join the server. I won't add such thing.
