### ISSUE TITLE
Fastlogin randomly stopped working

### ISSUE THREAD

**Issue by Kheeto** [games647/FastLogin#820]
### What happened?

Every fastlogin command just stopped working, but it doesn't give any error, the command just doesn't respond, but there is a much bigger issue, now the server asks all players that were using /premium to do /login with theiir password, even if they don't have a password, because they were using /premium

However i still get fastlogin messages in the server console, but no errors
[22:55:41 INFO] [FastLogin]: Incoming login request for Kheeto67 from (my ip address)
[22:55:41 INFO] [FastLogin]: Handling player Kheeto67
[22:55:41 INFO] [FastLogin]: Requesting premium login for registered player: Kheeto67

### Steps to reproduce

I didn't do anything it just happened

### Plugin list

Bungee: BungeeGuard, BuycraftX, CleanMOTD, CMIB, FastLoginBungee, floodgate-bungee, Geyser, LiteBans, Luckpermsbungee, Skinsrestorer, Slashserver, Ultrastaffchat - Hub: ajParkour, BungeeGuard, Citizens, CMI, CMILib, CoreProtect, DiscordSRV, FastLoginBukkit, GUIPlus, Holograms, HubPvPSword, ItemJoin, LoginSecurity, Luckperms, PAPI, ProtocolLib, scoreboard, skinsrestorer, TAB, vault, viaversion, vulcan, worldedit, worldguard, xprotect

### Configuration file

https://www.toptal.com/developers/hastebin/zinuzehiva.yaml

### Server log

[bungee log:](https://www.toptal.com/developers/hastebin/qedabimugu.yaml)
[hub log 1](https://www.toptal.com/developers/hastebin/xelowezale.sql)
[hub log 2](https://www.toptal.com/developers/hastebin/ipozokomop.yaml)
[hub log 3](https://www.toptal.com/developers/hastebin/hesiwimeqo.yaml)

### Plugin version

v1.11-SNAPSHOT-d802193

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
The server log is necessary not only to show errors, but also at what stage the player is. So please add it. It would be really helpful.

**Comment by Kheeto** [comment]
i added the logs

**Comment by games647** [comment]
Well there it is:

>org.yaml.snakeyaml.scanner.ScannerException: while scanning a simple key
 in 'reader', line 94, column 1:
    Type &a/premium&6 again to confirm'
    ^
could not find expected ':'
 in 'reader', line 96, column 1:
    # ========= Bungee/Waterfall onl ... 
    ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:465) ~[paper.jar:]
	at org.yaml.snakeyaml.scann

You have an invalid message.yml file. This causes the spigot version to fail to startup.
