### ISSUE TITLE
(waterfall) bedrock side fastlogin (autologin) isn't working with bungeeauth,authme 

### ISSUE THREAD

**Issue by adalmo** [games647/FastLogin#826]
### What happened?

floodgateautologin isn't working on bedrock they still need to do /login

### What did you expect?

[latest.log](https://github.com/games647/FastLogin/files/8984232/latest.log)

### Plugin list

Geyser,floodgate,authmebungee,fastloginbunngee

### Configuration file

https://gist.github.com/adalmo/440720ca74cc48a47951e0c49bd599c6

### Server log

[latest.log](https://github.com/games647/FastLogin/files/8984234/latest.log)

### Plugin version

Build #1089

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Please keep it on GitHub, so that others can find it too.
