### ISSUE TITLE
FastLoginBukkit doesn't load on Paper 1.8.8

### ISSUE THREAD

**Issue by draand28** [games647/FastLogin#828]
### What happened?

Since when you bumped the required java version to 17, from 8, the plugin won't load on Paper 1.8.8. 
Paper 1.8.8 **requires** Java 8. It won't run with any of the newer versions.

### Plugin version

can't load, latest dev build #1089

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
At the moment there are no plans to backport it, because it requires too much effort.

**Comment by refractored** [comment]
I was able to use windspigot which supports Java 17. Works fine.

**Comment by draand28** [comment]
Can you tell me what is the configuration feature that is not working?
Also, if you don't mind, could you share the changes that let you compile Paper 1.8.8 with Java 18? I tried it myself with mvn 3.8.6 and java 17 and the compilation of Paper API fails.

**Comment by games647** [comment]
@draand28 It's `stackableBuckets`, because it's no longer possible to modify the the final Java field using Reflection. No I compiled it with Java 8 using a Docker image to be precise, but ran it using Java 18.

**Comment by games647** [comment]
As I said you need to disable native transport. However this could potential impact your server performance.

**Comment by draand28** [comment]
Thanks! It works indeed.
