### ISSUE TITLE
After a while ask to login again??

### ISSUE THREAD

**Issue by Wearwolfy** [games647/FastLogin#83]
First of all i want to say thanks for helping me each and everytime and being so helpful.
So i setup bungee with authme and Authmebridge it works fine and everything (i put autoregister on).
As i saw everything was perfect and running good i started working on skyblock on the network after 15-30 minutes it freezes me and says i need to login again but since I joined with premium i can't do /login password then it just says "wrong password".
A solution would be to only have authme and fastlogin on the hub server and bungeecord would that cause any side problems?
Note: Attached image is the message i get when i am frozen.
![2016-09-26_22 46 45](https://cloud.githubusercontent.com/assets/21149078/18851876/3fff3f18-843e-11e6-81b7-c5e51998a588.png)

**Comment by Wearwolfy** [comment]
if i relog into the network it works again for 15-30 min but i don't want my players to relog every 15-30 min that would be stupid ....

**Comment by games647** [comment]
Update your AuthMe version. It's a bug of AuthMe.

**Comment by Wearwolfy** [comment]
Ok it hink it worked ;)
Thanks for the fast response and ik my last idea was very stupid, i realise that now.
1 last thing, is it possible if a cracked players joins with a premium name it kicks the player (like normal if autoregister is enabled) but with a customizable message?

**Comment by Wearwolfy** [comment]
Can you answer to my last question?

**Comment by games647** [comment]
No it's not possible without client modifications. See the FAQ.

**Comment by Wearwolfy** [comment]
Ah ok you could have said that in the first place but thanks again
