### ISSUE TITLE
Duplicate entry: META-INF/services/fastlogin.slf4j.spi.SLF4JServiceProvider

### ISSUE THREAD

**Issue by alexwastakenn** [games647/FastLogin#832]
Steps to reproduce:
Clone repo
Switch to 1.19 compat branch
Compile with clean install shade:shade
Should:
Create an uber jar with all modules
Instead:
console log shows v
`duplicate entry: META-INF/services/fastlogin.slf4j.spi.SLF4JServiceProvider`

**Comment by games647** [comment]
The shade goal is redundant. It's already part of the package goal.

**Comment by games647** [comment]
It already does that.

**Comment by games647** [comment]
Then you need to create an universal maven module where it includes all the other projects as dependencies with keeping all the correct dependencies in mind.

**Comment by alex-mono** [comment]
Mind telling me how?

**Comment by games647** [comment]
FastLogin had something like that in the past, but it was harder to maintain. I don't have the time to update, but it may give you starting point:

https://github.com/games647/FastLogin/blob/1.10/universal/pom.xml

You will likely update the dependency list, include new modules, etc.

**Comment by alex-mono** [comment]
I see thanks. Could I also ask, should it work without being in an uber jar + do you have any idea why it throws InvalidDescriptionException: Invalid plugin.yml even though the plugin.yml is there

**Comment by games647** [comment]
>should it work without being in an uber jar

Do you mean if the modules work without shading them all together? Yes. For example `FastLoginBukkit` includes the core module and then works on any Spigot server. You only need to build it. As part of the package goal in `bukkit` it will shade the core module. Therefore the output there is ready to be used.

>InvalidDescriptionException: Invalid plugin.yml 

The exact error message is relevant and needed here. One thing I could assume is an invalid replacement of the variables in the file. The project relies heavily on variables provided by Maven, which are replaced on the package goal. 

[`https://github.com/games647/FastLogin/blob/main/bukkit/src/main/resources/plugin.yml`](https://github.com/games647/FastLogin/blob/e781eb6c688146be07771ffd26dbc8eeb7a538e1/bukkit/src/main/resources/plugin.yml)
