### ISSUE TITLE
Error on Waterfall

### ISSUE THREAD

**Issue by Gladnii** [games647/FastLogin#840]
### What happened?

this is the server error:
https://pastebin.com/D06s9WmW

This is on Waterfall (1.18.2 server version, Using Latest build (at the moment) (#1098)

### Steps to reproduce

Start server lol

### Plugin list

ajQueue, TCPShield, AuthMeReloaded, Protocolize-Bungeecord, SkinsRestorer, LuckPerms

### Plugin version

#1098 Build (i can't check version cuz it does not work)

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by Gladnii** [comment]
Also there is no folder in plugins file, but there is in spigot server so yeah I have no idea what happend.

**Comment by games647** [comment]
>com/github/games647/fastlogin/bungee/FastLoginBungee has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0

This means you have an out of date Java version in use for the server.

**Comment by Gladnii** [comment]
Oh yeah that removed that error, and when I set up database I got new error:
https://pastebin.com/WL3Yyyv0

**Comment by games647** [comment]
Outdated Waterfall version.

**Comment by Gladnii** [comment]
> Outdated Waterfall version.

Yeah, updating Waterfall fixed that, thanks a lot
