### ISSUE TITLE
Disabled after resetting config and updated to 1.19

### ISSUE THREAD

**Issue by ElTodoFull** [games647/FastLogin#841]
### What happened?

Fastlogin is disabled on startup of the backend server.
In velocity, seemingly starts ok, without errors.

### What did you expect?

To be enabled and allow auto-loggin

### Steps to reproduce

Update from 1.18.2 to 1.19.
Update fastlogi nto the latest devbuild available.
update protocollib to the altest dev build available for 1.19.
delete files of fastlogin.
restart server.
configure fastlogin with the DB and the proxy-id generated in velocity
restart server.

### Plugin list

40ServidoresMC, AdvancedChests, AuthMe, BlockLocker, Captcha, ChatItem, ChatSentinel, CMILib, ConditionalEvents, ConsoleSpamFix, CoreProtect, CustomCrafting, DailyRewardsPlus, DeluxeMenus, DiscordSRV, Essentials, EssentialsSpawn, ExcellentCrates, ExtraContexts, FancyBags, FarmControl, FastLogin, floodgate, GHolo, GMusic, Graves, GSit, HuskHomes, HuskSync, ImageMaps, Insights, InteractiveBoard, InventoryRollbackPlus, Jobs, LiteBans, LuckPerms, MessageFilter*, MobBanners, Multiverse-Core, Multiverse-NetherPortals, NexEngine, PinataParty, PL-Hide, PlaceholderAPI, Plan, ProCosmetics, ProtectionStones, ProtocolLib, PvPManager, RegionRaid, Shopkeepers, SkinsRestorer, spark, squaremap, SuperVanish, TAB, TreasureChest, UltimateShops, UpgradeableHoppers, Vault, VentureChat, ViewDistanceTweaks, Votifier, VotingPlugin, Vulcan, WolfyUtilities, WorldEdit, WorldGuard, WorldGuardExtraFlags, XConomy, XP-Deposit*

### Configuration file

https://www.toptal.com/developers/hastebin/lerimacaxa.yaml

### Server log

https://pastebin.com/DTF1HUwJ

### Plugin version

v1.11-SNAPSHOT-e781eb6

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by ElTodoFull** [comment]
Additional info:
Proxy (latest build): Velocity 3.1.2-SNAPSHOT (git-e8bf6ab5-b161)
Protocollib(latest build): ProtocolLib version 5.0.0-SNAPSHOT-b575

**Comment by games647** [comment]
As you can see the driver is not available for your platform. You run Spigot, so you have to use the MySQL or SQLite there.

**Comment by games647** [comment]
Wait I noticed that the plugin should run in proxy mode, so no database connection is required. Therefore please use this build [1]. The changes were reverted until a proper fix is merged, which is currently in the 1.19 compatibility branch.

[1] https://ci.codemc.io/job/Games647/job/FastLogin/1086/

**Comment by ElTodoFull** [comment]
> Wait I noticed that the plugin should run in proxy mode, so no database connection is required. Therefore please use this build [1]. The changes were reverted until a proper fix is merged, which is currently in the 1.19 compatibility branch.
> 
> [1] https://ci.codemc.io/job/Games647/job/FastLogin/1086/

Thank you so much! It worked :D
Thanks too for the very fast response!
