### ISSUE TITLE
Add ability to customise the 'you got Force-logged in by FastLogin'

### ISSUE THREAD

**Issue by MyWorldNetwork** [games647/FastLogin#845]
The wording is very awkward and I genuinely cringe a little every time I see it on screen.

If it must remain hard-coded some suggestions would be;

'You were automatically logged-in by FastLogin'
'FastLgin automatically logged you in'
'You were auto-logged in'

**Comment by games647** [comment]
Then it's not from FastLogin. If we didn't missed something, then everything user-facing can be customized.
