### ISSUE TITLE
Fastlogin does not start in 1.19

### ISSUE THREAD

**Issue by Minoo1233** [games647/FastLogin#849]
### What happened?

the plugin does not start, and the following error is displayed in console

### What did you expect?

that the plugin will work, as I am on the latest build #1103.

### Steps to reproduce

1: install fastlogin Build #1103
2: start the server

### Plugin list

ActionHealth, AdvancedArmorStands, AdvancedRegionMarket, AltDetector, AngelChest, AnimatedScoreboard, ArmorStandTools, AuctionHouse, AuthMe, BanAnnouncer, BannerText, BCommons*, BetterRTP, BetterTeams, BlockLocker, BlockVillagerTrade, BuycraftX, ChatBrawl, ChatManager, ChestSort, Chunky, ChunkyBorder, Citizens, CleanMOTD, CMILib, Codex, CommandWhitelist, ConditionalEvents, CoreProtect, CreativeManager, CustomCrafting, CustomDrops, DeathMessages, DecentHolograms, DeluxeMenus, DiscordSRV, EconomyShopGUI, Elevator, EliteMobs, EpicPluginLib, Essentials, ExcellentCrates, FastAsyncWorldEdit (WorldEdit), FastLogin, floodgate, Geyser-Spigot, GSit, HeadsPluginAPI, HomeGUI, InteractionVisualizer, InteractiveBooks, InventoryRollbackPlus, InvSeePlusPlus, ItemEditor, ItemRarityGlow, Jobs, JumpPads, LibertyBans, LibsDisguises, LuckPerms, Maintenance, MineableSpawners, MobArena, ModelEngine, Multiverse-Core, MyCommand, MythicMobs, NBTAPI, NexEngine, NoChunkLag, NoPlugins, ntdLuckyBlock, Oraxen, PacketListenerApi, PaPiTest, PlaceholderAPI, PlayerKits, PlayerWarps, PlayMoreSounds, PlugManX (PlugMan), PrefiX, ProtectionStones, ProtocolLib, PvPManager, Quests, QuickShop, RotatingHeads, SepareWorldItems, Shopkeepers, SimplePortals, SimpleTpa*, SkinsRestorer, sleep-most, Slimefun, SmoothTimber, spark, Spicord, StaffPlus, StaffPlusPlusDiscord, SuperVanish, T2CodeLib, TAB, TimedRewards, TrollingFreedom, UltimateAutoRestart, Vault, ViaBackwards, ViaVersion, VoidGen, VoidSpawn, Votifier, VotingPlugin, WarpSystem, WDLCompanion*, WGEF-Reborn, WolfyUtilities, WorldGuard

### Configuration file

https://www.toptal.com/developers/hastebin/ewoqarocup.yaml

### Server log

https://www.toptal.com/developers/hastebin/ilapikekez.yaml

### Plugin version

FastLogin Build #1103

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by Minoo1233** [comment]
Yes, it is 
![image](https://user-images.githubusercontent.com/79604787/179379939-300cb0bd-0797-414a-b6e4-7857b0edcfc6.png)

**Comment by games647** [comment]
Could you check the newest when it's finished building?

**Comment by Minoo1233** [comment]
Ready, now it works with the latest build. 👍🏿
