### ISSUE TITLE
Fastlogin don't work "sending request..." (italian)

### ISSUE THREAD

**Issue by Krypto7494** [games647/FastLogin#850]
### What happened?

Non è la prima volta che cerco di utilizzare fastlogin, mi era gia successo seguendo la guida ufficiale + dei tutorial che ogni volta che facevo /premium o anche semplicemente mettendo l' autoregister a true non mi autenticava come un player premium, con lo stesso problema, Sending request... all infinito.

### Plugin list

AuthMe, ProtocolLIB, fastlogin

### Server log

Nessun errore

### Plugin version

1.10-git484855724b794de1fe057cf7360245362658b432

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by Krypto7494** [comment]
@games647

**Comment by games647** [comment]
Please read again the checklist. You are not using the latest dev build.

**Comment by Krypto7494** [comment]
Where i can find that build @games647

**Comment by Krypto7494** [comment]
I find it, let me try if that works

**Comment by Krypto7494** [comment]
![image](https://user-images.githubusercontent.com/101934462/179353308-7dccbc50-322b-4cde-ba8c-419062ed7cdf.png)
I have the dev build FastloginBungee on bungeecord and fastloginbukkit on the spigot server (paper 1.18.2 java 17)

**Comment by Krypto7494** [comment]
@games647

**Comment by games647** [comment]
Do you followed the setup guide for proxies like it says on the server log and project page? And please don't tag anyone.

**Comment by Krypto7494** [comment]
Yes

**Comment by games647** [comment]
Please post the server log of the Spigot and bungee server.

**Comment by Krypto7494** [comment]
[bungee.txt](https://github.com/games647/FastLogin/files/9125764/bungee.txt)
[lobby.txt](https://github.com/games647/FastLogin/files/9125765/lobby.txt)

**Comment by games647** [comment]
[14:46:35] [main/WARN]: Exception encountered when loading plugin: FastLogin
java.lang.NoClassDefFoundError: net/md_5/bungee/protocol/Property

Outdated BungeeCord proxy.

**Comment by Krypto7494** [comment]
Fixed thank you

**Comment by Krypto7494** [comment]
Best dev
