### ISSUE TITLE
Timed out when using Premium username

### ISSUE THREAD

**Issue by AresMineCrypto** [games647/FastLogin#853]
### What happened?

When someone with a cracked client tries to join with a paid Minecraft name he gets: "Timed out" error 

### What did you expect?

I expected it to give a better error (and do it faster) like "Bad login"

### Steps to reproduce

1. Create a Bungee and Spigot server with the provided config
2. Try to join with a cracked client using a premium username

### Plugin list

AdvancedBan, AuthMe, FastAsyncWorldEdit (FAWE), FastLogin, ProtocolLib

### Configuration file

https://www.toptal.com/developers/hastebin/ovokadowoq.yaml

### Server log

```
5:45:34 [INFO] [FastLogin] Handling player Notch
15:45:34 [INFO] [FastLogin] GameProfile Notch uses a premium username
```

### Plugin version

Build #1109

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
At least more from the time the player logged in.
