### ISSUE TITLE
Issues with AutoLogin 

### ISSUE THREAD

**Issue by jacobvd0** [games647/FastLogin#855]
### What happened?

If I relog Autologin does not work. It starts working again after around a minute of my last login. I tested this with someone else and it worked for them. We are both using paid accounts and we're on the same testing server.

### What did you expect?

I should be able to relog without breaking Autologin.

### Steps to reproduce

Join then relog and you should be prompted to login even though Autologin is enabled.

### Plugin list

AuthMeReloaded, ProtocolLib, FastLogin, FastAsyncWorldEdit, ImageOnMap

### Configuration file

https://pastebin.com/3w8K2hRD

### Server log

https://mclo.gs/feAcEeZ

### Plugin version

1.12-SNAPSHOT-8df5b11

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [x] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
I added new debug code. Could you post the log with the new version.

**Comment by jacobvd0** [comment]
Sure, https://mclo.gs/D9H0JDV

**Comment by games647** [comment]
Looks like ProtocolLib failed to intercept the packet the second time. This seems to be a bug in ProtocolLib. I could try to perform the processing synchronous, maybe that fixes. However it will be highly experimental and not have good performance. So here a test version:

https://github.com/games647/FastLogin/releases/tag/test

**Comment by jacobvd0** [comment]
Thanks! I'll try it out in a moment.

**Comment by jacobvd0** [comment]
Doesn't work at all now. https://mclo.gs/F15eM3b

**Comment by games647** [comment]
Okay the change was more complicated than thought. Here is the newer version: https://github.com/games647/FastLogin/releases/tag/protocollib-bug

**Comment by jacobvd0** [comment]
Seems to still have the issue with relogging. https://mclo.gs/yQu9yBz

**Comment by games647** [comment]
Okay then it's a bug in ProtocolLib.

**Comment by games647** [comment]
Could you try out the new version. Same link. I moved the debug to earliest possible moment to really make sure the origin of this bug.

**Comment by Krakenied** [comment]
```
[11:56:15 INFO]: [FastLogin] New packet START[class=PacketLoginInStart, id=0] from com.comphenix.protocol.injector.temporary.TemporaryPlayerInvocationHandler@1ccee00a; Cancellation: false, Auth-Plugin: com.github.games647.fastlogin.bukkit.hook.AuthMeHook@27b0d91c, Initialized: false, Meta: Optional.empty
[11:56:15 INFO]: [FastLogin] Handling player Krakenied
[11:56:15 INFO]: [FastLogin] Requesting premium login for registered player: Krakenied
[11:56:16 INFO]: [FastLogin] New packet ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1] from com.comphenix.protocol.injector.temporary.TemporaryPlayerInvocationHandler@1ccee00a; Cancellation: false, Auth-Plugin: com.github.games647.fastlogin.bukkit.hook.AuthMeHook@27b0d91c, Initialized: false, Meta: Optional.empty
[11:56:16 ERROR]: [FastLogin] No verify token sent if requested without player signed key com.comphenix.protocol.injector.temporary.TemporaryPlayerInvocationHandler@1ccee00a
[11:56:16 INFO]: /x.x.x.125:60758 lost connection: Disconnected

**Comment by games647** [comment]
@Krakenied Your error is different. ProtocolLib catches the player packets, but FastLogin could verify the connection, because the client sent a encrypted token without sending a public key first.

**Comment by jacobvd0** [comment]
> Could you try out the new version. Same link. I moved the debug to earliest possible moment to really make sure the origin of this bug.

Seems to be the same issue again. https://mclo.gs/DBC6ScT

**Comment by games647** [comment]
@jacobvd0 No that's very helpful. Somehow the packet got repeated. See the metadata. FastLogin means it's fake packet and shouldn't be processed by us. I could never reproduce that.

**Comment by games647** [comment]
I found now where the bug occurred. Now it's interesting to find out the cause of it. I'll added two new versions. Could you test both and post the corresponding server log. 

Sorry you with all this, but I really cannot reproduce it locally.

**Comment by jacobvd0** [comment]
Yeah, sure!

**Comment by jacobvd0** [comment]
quality test build: https://mclo.gs/zY09L49
skip filtering build: https://mclo.gs/ILcxdOP
Nothing has changed on these builds so far just seems to be the same issue with relogging.

**Comment by games647** [comment]
It appears as the server re-use packet instances, which makes the identity check unsafe. I made fix into the main plugin.

**Comment by jacobvd0** [comment]
Just tried it and it works! Thank you for the help.
