### ISSUE TITLE
floodgatePrefixWorkaround set to true, not working on 1.19 (onAsyncPacket() error)

### ISSUE THREAD

**Issue by SajmonOriginal** [games647/FastLogin#856]
### What happened?

When the server is with **GeyserMC** and **Floodgate** plugins together with **Fastlogin**, which has `floodgatePrefixWorkaround: true` in the config, an error is printed in the console when the user logs in Java Edition the user is logged in fine, when the user logs in from Bedrock Edition, the same error appears in the console, but the user does not connect to the server with the error `"Your name conflicts an existing premium Java account's name"`

#### Bedrock connect:
![image](https://user-images.githubusercontent.com/49367587/180653271-55d95115-98f6-4bd6-ac49-8f90d22559f5.png)

#### Java connect:
![image](https://i.imgur.com/Ncjcy1N.png)

I only saw this error when the FastLogin plugin was not updated to 1.19 and the plugin had compatibility problems with this version, so I think that somehow this workaround was forgotten when working on compatibility with 1.19.

### Here is the mentioned error from the log:

`[14:48:53 ERROR]: [FastLogin] Unhandled exception occurred in onAsyncPacket() for FastLogin
com.comphenix.protocol.reflect.FieldAccessException: No field with type com.mojang.authlib.GameProfile exists in class PacketLoginInStart.
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:216) ~[ProtocolLib (11).jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib (11).jar:?]
        at com.github.games647.fastlogin.bukkit.listener.protocollib.ManualNameChange.onPacketReceiving(ManualNameChange.java:72) ~[FastLoginBukkit (11).jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.processPacket(AsyncListenerHandler.java:642) ~[ProtocolLib (11).jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.listenerLoop(AsyncListenerHandler.java:596) ~[ProtocolLib (11).jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler.access$200(AsyncListenerHandler.java:48) ~[ProtocolLib (11).jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler$2.run(AsyncListenerHandler.java:229) ~[ProtocolLib (11).jar:?]
        at com.comphenix.protocol.async.AsyncListenerHandler$3.run(AsyncListenerHandler.java:300) ~[ProtocolLib (11).jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-58]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.jar:git-Paper-58]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:48:53 INFO]: [FastLogin] Handling player SajmonOriginal
[14:48:53 INFO]: [FastLogin] Bedrock Player SajmonOriginal's name conflicts an existing premium Java account's name
[14:48:53 INFO]: [floodgate] Floodgate player logged in as SajmonOriginal disconnected
[14:48:53 INFO]: [Geyser-Spigot] SajmonOriginal has disconnected from the Java server because of Your name conflicts an existing premium Java account's name
[14:48:53 INFO]: /**.**.**.**:0 lost connection: Disconnected
`

### What did you expect?

I'm trying to get **Floodgate** or **offline** auth on **GeyserMC** compatible with **Fastlogin** on **Paper** server. I've been looking around this repository variously and saw that there are some pull requests about this that have some recent activity, so I believe some compatibility with **Floodgate** is still in the works. Anyway, I tried to use the so-called `floodgatePrefixWorkaround`, which seemed to finally realize my dream that Bedrock users would not have to log into their Microsoft accounts every time they connect. Unfortunately **Fastlogin** doesn't support **Floodgate** prefixes (but I already found an issue for that here), so this was my last hope to enable this.

### Steps to reproduce

Start Paper server on version 1.19 along with the latest dev builds of **FastLogin**, **ProtocolLib**, **GeyserMC** and **FloodGate** plugins. In **Geyser config**, change the `auth-type:` to `offline` or `floodgate`. In the **FastLogin config**, add `floodgatePrefixWorkaround: true`.

### Plugin list

AuthMe, FastLogin, floodgate, Geyser-Spigot, ProtocolLib

### Configuration file

https://www.toptal.com/developers/hastebin/ezedulajen.yaml

### Server log

Server log when connecting from Bedrock Edition: [[Paper server log [#RYnvduW] - mclo.gs](https://mclo.gs/RYnvduW)](https://mclo.gs/RYnvduW)

Server log when connecting from Java Edition: [[Paper server log [#Fgzlemx] - mclo.gs](https://mclo.gs/Fgzlemx)](https://mclo.gs/Fgzlemx)

### Plugin version

FastLogin version 1.12-SNAPSHOT-8df5b11

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by SajmonOriginal** [comment]
Damn, now I noticed someone had the same problem 2 days ago, but I tried to elaborate quite a bit and provide as much material as possible and it took a bit of time, whereas he just copied the error and answered everything in one sentence (not saying he did anything wrong :D), so i'll just mention that issue: #854

**Comment by games647** [comment]
Fixes with #854

**Comment by SajmonOriginal** [comment]
> Fixes with #854


Login from Bedrock edition:
[[Paper server log [#RszgaX6] - mclo.gs](https://mclo.gs/RszgaX6)](https://mclo.gs/RszgaX6)

Login from Java edition
[[Paper server log [#tQM7fFt] - mclo.gs](https://mclo.gs/tQM7fFt)](https://mclo.gs/tQM7fFt)

I'm still having the same problem on the latest dev build of `FastLogin version 1.12-SNAPSHOT-05708a2` even though `#1116 (Mon Jul 25 08:29:24 UTC 2022)` says it's fixed.. anyway, I don't know if it's related but on that build with the fix there's also a cross and message that it failed: 

![image](https://i.imgur.com/0um4Lxz.png)


but on `#1118` it still throws an error:
####   Bedrock Edition connect:
![image2](https://i.imgur.com/HNhy1vy.png) 

####   Java Edition connect:
![image6](https://i.imgur.com/IBHENlQ.png) 



Unfortunately you can't connect from either edition of the game on this plugin build.. i've attached two logs with connections from both editions


### Connecting from Java edition (i have Bedrockify mod so the menu looks like Bedrock edition but it's Java):

![image3](https://i.imgur.com/XiR2xTv.png)
![image4](https://i.imgur.com/Q85pD3Z.png)

### Connecting from Bedrock edition:

![image5](https://i.imgur.com/a94u01G.png)

**Comment by SajmonOriginal** [comment]
I don't know if you'll read this since this issue is closed and I'd better create a new one, but I'll try to comment on this one first  :smile:

**Comment by SajmonOriginal** [comment]
By the way now I found out that the same error appears on Java edition even if `floodgatePrefixWorkaround: false`, so it looks like some bug in the entire plugin build

**Comment by SajmonOriginal** [comment]
By the way now I found out that the same error appears on Java edition even if `floodgatePrefixWorkaround: false` or deleted completely from config, so it looks like some bug in the entire plugin build

**Comment by games647** [comment]
>I don't know if you'll read this since this issue is closed and I'd better create a new one, but I'll try to comment on this one first smile

Yes, thank you. I still get a notification.

I forgot updating the reading part too. Only writing were fixed. For the ProtocolLib error with FieldUtils, you'll need to use an older build of ProtocolLib. There are currently doing many breaking changes.

**Comment by SajmonOriginal** [comment]
Sorry to keep bothering you, but it still throws me the error _"Your name conflicts an existing premium Java account's name"_ when I connect on Bedrock edition, but Java edition works as it should and no error is thrown in the console anymore.. anyway, the `floodgatePrefixWorkaround` still seems to have no effect because I tried with `true`, `false` and change `auth-type:` to `offline` or `floodgate` in Geyser config, but still the same result.


![image1](https://i.imgur.com/Sd0CF32.png)


Server log:

[[Paper server log [#YcKP6PV] - mclo.gs](https://mclo.gs/YcKP6PV)](https://mclo.gs/YcKP6PV)

`FastLogin version 1.12-SNAPSHOT-94979a3`
`ProtocolLib version 5.0.0-SNAPSHOT-b575`

**Comment by SajmonOriginal** [comment]
Ok, so I made it work by adding `allowFloodgateNameConflict: true` to the config. Anyway, I have another question again and that is if it is possible to make autologin work when a person connects from bedrock. Because currently autologin only works in java, but when I connect via floodgate or offline it wants /login command and autoregister doesn't work on Bedrock edition. Thank you

**Comment by games647** [comment]
You are missing some configuration options. See this for example:

https://github.com/games647/FastLogin/blob/94979a3cf6aa1981c1a05077e5caa60c4e5925eb/core/src/main/resources/config.yml#L251

**Comment by SajmonOriginal** [comment]
Thank you very much, I didn't know where to find this list of experimental config settings. Anyway, I played around with it a bit and it works exactly as I imagined, although sometimes the skins don't forward on Bedrock, but that's a small thing... SkinRestorer fixed that.

**Comment by SajmonOriginal** [comment]
And I look forward to Floodgate support being fully integrated into Fastlogin (I'm watching Pull requests actively) and what it will look like in the future!
