### ISSUE TITLE
console spamming erros

### ISSUE THREAD

**Issue by comonier** [games647/FastLogin#857]
### What happened?

spamming warns etc on console

### What did you expect?

solve it

### Steps to reproduce

turn on server or player do login

### Plugin list

a lot check it on server log

### Configuration file

https://www.toptal.com/developers/hastebin/ugovociyil.yaml

### Server log

https://www.toptal.com/developers/hastebin/ezanidizul.sql

### Plugin version

BungeeCord 1655

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Outdated BungeeCord version.

>solve it

You can solve it yourself.
