### ISSUE TITLE
Hooking into AuthMe freezes server

### ISSUE THREAD

**Issue by Calamity34** [games647/FastLogin#858]
### What happened?

Server boots up fine, but upon hitting  
`[FastLogin] Hooking into auth plugin: AuthMeHook`  
freezes for 2 minutes and kills itself.

Both AuthMe and FastLogin are the latest dev build.

### What did you expect?

That it would not freeze the server and connect (like it usually does)

### Steps to reproduce

I honestly have no idea. It worked yesterday, didn't work today. Didn't even change anything, it just did that overnight.

### Plugin list

Plugins (14): AuthMe, Chatty, Chunky, CoreProtect, DeadChest, FastLogin, GSit, Pl3xMap, PlasmoVoice, ProtocolLib, SkinsRestorer, spark, TAB, WorldEdit

### Configuration file

https://pyt.igorek.dev/bin/config.yml

### Server log

https://www.toptal.com/developers/hastebin/dakonaxeyu.yaml

### Plugin version

1.12-SNAPSHOT-05708a2

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
I need the full thread dump at the time of the freeze.

**Comment by Calamity34** [comment]
https://www.toptal.com/developers/hastebin/xakacuzari.yaml

a log from a bit earlier (and on **`v1.12-SNAPSHOT-423bfa2`** (the internet was probably down at the time and the server tends to restart itself)

**Comment by Calamity34** [comment]
Somehow disabling query fixes the errors. Will close the issue for now and will reopen in case something happens
