### ISSUE TITLE
.NoClassDefFoundError: com/comphenix/protocol/reflect/FieldUtils

### ISSUE THREAD

**Issue by kamil445** [games647/FastLogin#859]
### What happened?

When i connect to the server, game stucks on "encrypting", after a while "timed out".

### Plugin list

AdvancedPortals, AppleTree*, AreaShop, AuthMe, AutoMessage*, BeautyIndicator*, BetterDrops, BetterSleeping3, ChangeSkin, ChestShop, CMILib, CombatLogX, CoreProtect, Essentials, EssentialsChat, EssentialsSpawn, FarmControl, FastLogin, Geyser-Spigot, InfoBook*, Jobs, LWC, Multiverse-Core, Multiverse-NetherPortals, OnTime*, PermissionsEx*, PlaceholderAPI, ProtocolLib, Residence, SirBlobmanCore (SirBlobmanAPI, XSeries), spark, TAB, Themis, Vault*, ViaBackwards, ViaVersion, Wild, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags

### Server log

[14:14:00] [Protocol Worker #1 - FastLogin - [recv: ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1], START[class=PacketLoginInStart, id=0], send: ]/INFO]: [FastLogin] New packet START[class=PacketLoginInStart, id=0] from com.comphenix.protocol.injector.temporary.TemporaryPlayerInvocationHandler@361ed39a
[14:14:00] [Craft Scheduler Thread - 55 - FastLogin/INFO]: [FastLogin] Handling player kamil445
[14:14:00] [Craft Scheduler Thread - 55 - FastLogin/INFO]: [FastLogin] Requesting premium login for registered player: kamil445
[14:14:00] [Protocol Worker #1 - FastLogin - [recv: ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1], START[class=PacketLoginInStart, id=0], send: ]/INFO]: [FastLogin] New packet ENCRYPTION_BEGIN[class=PacketLoginInEncryptionBegin, id=1] from com.comphenix.protocol.injector.temporary.TemporaryPlayerInvocationHandler@361ed39a
[14:14:00] [Craft Scheduler Thread - 64 - FastLogin/INFO]: [FastLogin] Enabling onlinemode encryption for UNKNOWN[/[2001:470:71:447:0:0:0:1]:52622]
[14:14:00] [Craft Scheduler Thread - 64 - FastLogin/WARN]: [FastLogin] Error occurred on thread pool
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/comphenix/protocol/reflect/FieldUtils
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.jar:git-Purpur-1730]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.jar:git-Purpur-1730]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: com/comphenix/protocol/reflect/FieldUtils
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.getNetworkManager(VerifyResponseTask.java:201) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.enableEncryption(VerifyResponseTask.java:226) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.verifyResponse(VerifyResponseTask.java:130) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.run(VerifyResponseTask.java:107) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.core.AsyncScheduler.process(AsyncScheduler.java:70) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.core.AsyncScheduler.lambda$runAsync$0(AsyncScheduler.java:61) ~[FastLoginBukkit.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.reflect.FieldUtils
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.getNetworkManager(VerifyResponseTask.java:201) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.enableEncryption(VerifyResponseTask.java:226) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.verifyResponse(VerifyResponseTask.java:130) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.bukkit.listener.protocollib.VerifyResponseTask.run(VerifyResponseTask.java:107) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.core.AsyncScheduler.process(AsyncScheduler.java:70) ~[FastLoginBukkit.jar:?]
	at com.github.games647.fastlogin.core.AsyncScheduler.lambda$runAsync$0(AsyncScheduler.java:61) ~[FastLoginBukkit.jar:?]
	... 7 more
[14:14:30] [Server thread/INFO]: Disconnecting /[2001:470:71:447:0:0:0:1]:52622: Took too long to log in
[14:14:30] [Server thread/INFO]: /[2001:470:71:447:0:0:0:1]:52622 lost connection: Took too long to log in

### Plugin version

#1119

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
From: #856 

>For the ProtocolLib error with FieldUtils, you'll need to use an older build of ProtocolLib. They are currently doing many breaking changes.

**Comment by kamil445** [comment]
I tried downgrading ProtocolLib to 4.8.0, now i can join the server, but auto login doesn't work

log:

> [14:33:48] [Server thread/INFO]: kamil445[/[2001:470:71:447:0:0:0:1]:52877] logged in with entity id 1665 at ([survival_nether]-53997.563550968385, 249.0, 68228.59109466257)
> [14:33:48] [Server thread/INFO]: [FastLogin] No on-going login session for player: CraftPlayer{name=kamil445} with ID 2001:470:71:447:0:0:0:1:52877. 
> [14:33:48] [Server thread/INFO]: [FastLogin] Setups using Minecraft proxies will start delayed when the command from the proxy is received
> [14:34:02] [Netty Server IO #1/WARN]: [ProtocolLib] [DetailedErrorReporter] Internal exception count: 4096!
> [14:34:02] [Netty Server IO #1/INFO]: Error Unable to intercept a read client packet. (java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart) occured in com.comphenix.protocol.injector.netty.ChannelInjector@156b6ae9.
> [14:34:02] [Netty Server IO #1/ERROR]:   [ProtocolLib] INTERNAL ERROR: Unable to intercept a read client packet.
>   If this problem hasn't already been reported, please open a ticket
>   at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
>   Stack Trace:
>   java.lang.IllegalArgumentException: Unable to find a field null with the type com.mojang.authlib.GameProfile in net.minecraft.network.protocol.login.PacketLoginInStart
>   	at ProtocolLib.jar//com.comphenix.protocol.reflect.FuzzyReflection.getFieldByType(FuzzyReflection.java:397)
>   	at ProtocolLib.jar//com.comphenix.protocol.reflect.accessors.Accessors.getFieldAccessor(Accessors.java:57)
>   	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.handleLogin(ChannelInjector.java:658)
>   	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:591)
>   	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
>   	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
>   	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
>   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>   	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
>   	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
>   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>   	at ProtocolLib.jar//com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:292)
>   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>   	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
>   	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
>   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>   	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
>   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>   	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
>   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
>   	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
>   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
>   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
>   	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
>   	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
>   	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
>   	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
>   	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
>   	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
>   	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
>   	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
>   	at java.base/java.lang.Thread.run(Unknown Source)
>   Dump:
>   Parameters: 
>     io.netty.buffer.PooledUnsafeDirectByteBuf@6eac12ad[
>       memoryAddress=1158619200
>       recyclerHandle=io.netty.util.Recycler$DefaultHandle@3f338747
>       chunk=Chunk(15527a9d: 23%, 950272/4194304)
>       handle=562980018192384
>       memory=java.nio.DirectByteBuffer[pos=0 lim=4194304 cap=4194304]
>       offset=8192
>       length=13
>       maxLength=16
>       cache=io.netty.buffer.PoolThreadCache@3f4c7ace
>       tmpNioBuf=<null>
>       allocator=PooledByteBufAllocator(directByDefault: true)
>       refCnt=2
>       readerIndex=13
>       writerIndex=13
>       markedReaderIndex=0
>       markedWriterIndex=0
>       maxCapacity=2147483647
>     ]
>     manager:
>       com.comphenix.protocol.injector.PacketFilterManager@60ef8961[
>         unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@16f3091e
>         packetListeners=[PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[PONG[class=ServerboundPongPacket, id=29]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=ListeningWhitelist[priority=NORMAL, packets=[EXPLOSION[class=PacketPlayOutExplosion, id=28]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[POSITION[class=PacketPlayInPosition, id=17], GROUND[class=d, id=20], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], LOOK[class=PacketPlayInLook, id=19]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[POSITION[class=PacketPlayInPosition, id=17], GROUND[class=d, id=20], POSITION_LOOK[class=PacketPlayInPositionLook, id=18], LOOK[class=PacketPlayInLook, id=19]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=BetterDrops, sending=ListeningWhitelist[priority=NORMAL, packets=[SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Themis, sending=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=NORMAL, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=15], KEEP_ALIVE[class=PacketPlayOutKeepAlive, id=33]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=BetterDrops, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=13]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=WorldGuardExtraFlags, sending=ListeningWhitelist[priority=NORMAL, packets=[REMOVE_ENTITY_EFFECT[class=PacketPlayOutRemoveEntityEffect, id=59]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=AuthMe, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=22], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=20]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=Themis, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[ABILITIES[class=PacketPlayInAbilities, id=25]], gamephase=PLAYING, options=[]]], com.comphenix.protocol.async.NullPacketListener@4c40162f]
>         packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@762acbfe
>         playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@1874d5a4
>         inputBufferedPackets=[]
>         recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@4ccf34a
>         sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@a79b134
>         hasClosed=false
>         classLoader=PluginClassLoader{plugin=ProtocolLib v4.8.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
>         reporter=com.comphenix.protocol.ProtocolLib$1@2a2cfebe
>         server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1730,minecraftVersion=1.19}
>         library=ProtocolLib v4.8.0
>         asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@777e30ca
>         knowsServerPackets=true
>         knowsClientPackets=true
>         phaseLoginCount=1
>         phasePlayingCount=13
>         packetCreation=true
>         nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@311fee79
>         pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@4f500695
>         hasRecycleDistance=true
>         minecraftVersion=(MC: 1.19.0)
>         debug=false
>       ]
>   Sender:
>     com.comphenix.protocol.injector.netty.ChannelInjector@156b6ae9[
>       decodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler.decode(io.netty.channel.ChannelHandlerContext,io.netty.buffer.ByteBuf,java.util.List) throws java.lang.Exception
>       encodeBuffer=protected void com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler.encode(io.netty.channel.ChannelHandlerContext,java.lang.Object,io.netty.buffer.ByteBuf) throws java.lang.Exception
>       factory=com.comphenix.protocol.injector.netty.InjectionFactory@67b89bda
>       player=CraftPlayer{name=kamil445}
>       updated=<null>
>       playerName=kamil445
>       playerConnection=net.minecraft.server.network.PlayerConnection@5eca5437
>       networkManager=net.minecraft.network.NetworkManagerServer@3ce61aa
>       originalChannel=[id: 0x82bcdcee, L:/[2a06:a003:9025:0:0:0:0:2]:25565 - R:/[2001:470:71:447:0:0:0:1]:52877]
>       channelField=VolatileField [accessor=DefaultFieldAccessor [field=public io.netty.channel.Channel net.minecraft.network.NetworkManager.m], container=net.minecraft.network.NetworkManagerServer@3ce61aa, previous=[id: 0x82bcdcee, L:/[2a06:a003:9025:0:0:0:0:2]:25565 - R:/[2001:470:71:447:0:0:0:1]:52877], current=com.comphenix.protocol.injector.netty.ChannelInjector$3@2ed39543, previousLoaded=true, currentSet=true, forceAccess=true]
>       packetMarker={}
>       currentEvent=<null>
>       finalEvent=<null>
>       unfilteredProcessedPackets=com.comphenix.protocol.injector.netty.PacketFilterQueue@60a19e52
>       vanillaDecoder=com.viaversion.viaversion.bukkit.handlers.BukkitDecodeHandler@109270dd
>       vanillaEncoder=com.viaversion.viaversion.bukkit.handlers.BukkitEncodeHandler@54bf09d9
>       finishQueue=[]
>       channelListener=com.comphenix.protocol.injector.netty.ProtocolInjector@311fee79
>       processor=com.comphenix.protocol.injector.NetworkProcessor@a4ba602
>       injected=true
>       closed=false
>       cumulation=PooledUnsafeDirectByteBuf(ridx: 13, widx: 13, cap: 13)
>       cumulator=io.netty.handler.codec.ByteToMessageDecoder$1@72797619
>       singleDecode=false
>       first=true
>       firedChannelRead=false
>       selfFiredChannelRead=true
>       decodeState=1
>       discardAfterReads=16
>       numReads=0
>       added=true
>     ]
>   Version:
>     ProtocolLib v4.8.0
>   Java Version:
>     17.0.3
>   Server:
>     git-Purpur-1730 (MC: 1.19)
> 

Is there a way to run fastlogin on 1.19 ?

**Comment by games647** [comment]
I pushed a new update. I didn't ProtocolLib truncated the older builds.

**Comment by games647** [comment]
The latest build fails, because I cannot target the newer ProtocolLib version, because it's not yet available for development...

Related https://github.com/dmulloy2/ProtocolLib/issues/1783
