### ISSUE TITLE
Unparseable date SQLite

### ISSUE THREAD

**Issue by shootcraft** [games647/FastLogin#86]
http://pastebin.com/sf0DFEE7

I had no idea what going wrong

**Comment by games647** [comment]
What's your version?

**Comment by games647** [comment]
Already replied in earlier posts. It's a known bug in the new driver version of SQLite. Use either an older version (like 3.7.2 in Crafbukkit) or an dev-build of FastLogin where I fixed it.

**Comment by shootcraft** [comment]
Can you send me the development build, I cant find it

**Comment by games647** [comment]
http://ci.xephi.fr/job/FastLogin/
