### ISSUE TITLE
Cannot execute command 'premium' in plugin FastLogin- plugin is disabled.

### ISSUE THREAD

**Issue by dinobossytnew** [games647/FastLogin#860]
### What happened?

https://mcpaste.io/ac5bba77e368701c

### What did you expect?

https://mcpaste.io/ac5bba77e368701c

### Steps to reproduce

https://mcpaste.io/6ca83c0bc2e5d6ec config fastlogin

https://mcpaste.io/b4d580c0a87cf6ee mesagges 

purpur 1.19

### Plugin list

aAlonsoLeaderboardsf, aAuthMef, aBetterReportsf, aBetterRTPf, aChangeSkinf, aChatManagerf, aCitizensf, aCMILibf, aCommandPanelsf, aCoreProtectf, aCrazyCratesf, aCryDonationsf, aDailyRewardsf, aDeluxeTagsf, aEasyCommandBlockerf, aEssentialsf, aEssentialsSpawnf, cFastLoginf, aInventoryRollbackPlusf, aJobsf, aLuckPermsf, aMultiverse-Coref, aNBTAPIf, aPixelMOTD*f, aPlaceholderAPIf, aPlayerKitsf, aProtectionStonesf, aProtocolLibf, aShopkeepersf, asleep-mostf, asparkf, aTABf, aUltimateClansf, aVaultf, aViaBackwardsf, aViaRewindf, aViaVersionf, aVoidTeleportPlusf, aWorldEditf, aWorldGuardf, azAuctionHouseV3

### Configuration file

https://mcpaste.io/b4d580c0a87cf6ee

### Server log

https://mcpaste.io/

### Plugin version

Build #1122 (Wed Jul 27 18:30:55 UTC 2022)

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
The plugin is disabled. Check the startup log.
