### ISSUE TITLE
No verify token sent if requested without player signed key

### ISSUE THREAD

**Issue by Nikox3003** [games647/FastLogin#861]
### What happened?

If premium player tries to join, they will be disconnected and error will be displayed in console.
```
[FastLogin] No verify token sent if requested without player signed key com.comphenix.protocol.injector.temporary.TemporaryPlayerInvocationHandler@554c3b07
```
Server version: 1.19.1 (`git-Purpur-1736 (MC: 1.19.1)`)

### What did you expect?

Premium login should be handled correctly.

### Steps to reproduce

1. Install latest FastLogin an AuthMe on 1.19.1 
2. Register and add yourself to the premium list
3. Try joining again

### Plugin list

AuthMe, Chunky, CoreProtect, Essentials, EssentialsChat, FastLogin, LuckPerms, ProtocolLib, spark, Vault

### Configuration file

https://www.toptal.com/developers/hastebin/jamatamoja.yaml

### Server log

https://www.toptal.com/developers/hastebin/nahozovufi.sql

### Plugin version

1.12-SNAPSHOT-25c8be6 (build #1126)

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Fixed with ed45fada59d5e8721a70b2bb3c3656119d5806ca
