### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by shootcraft** [games647/FastLogin#87]
I executed /premium then it list me in premium and I cant join back the server because of cracked account, how can I change it back through console commands ?

How can enable autologin for cracked username ? If so can you tell me how it works ?

How to check whether the autoregister is working for premium ?

**Comment by games647** [comment]
>I executed /premium then it list me in premium and I cant join back the server because of cracked account, how can I change it back through console commands ?

/cracked

>How can enable autologin for cracked username ? If so can you tell me how it works ?

/premium playerName, but do that only if you know that they own the account

>How to check whether the autoregister is working for premium ?

Test it on a test server

**Comment by shootcraft** [comment]
it said 
04.10 03:58:33 [Server] INFO Sending request...
04.10 03:58:33 [Server] INFO No player online to send a plugin message to the proxy

**Comment by games647** [comment]
>No player online to send a plugin message to the proxy

It has to be at least one player online. The spigot cannot communicate with the bungee server otherwise.

**Comment by shootcraft** [comment]
Could not enable autoregister for cracked user, once I premium them, he or she cannot join already

**Comment by games647** [comment]
Are you sure they are premium?...

**Comment by shootcraft** [comment]
no, but I asked how to enable autoregister for cracked ?

**Comment by shootcraft** [comment]
so means there is no way to autologin or register for cracked player ?

**Comment by games647** [comment]
Why would you want that. If they don't own a premium account you should not do that.

**Comment by shootcraft** [comment]
Okay :+1:  Thanks !
