### ISSUE TITLE
Autologin not working with tcpshield

### ISSUE THREAD

**Issue by realGretix** [games647/FastLogin#873]
### What happened?

When i join my server with tcpshield i have to login with command

### What did you expect?

I expect fastlogin to login me automatically

### Steps to reproduce

- setup tcpshield
- join server

### Plugin list

tcpshield 2.5.6, fastlogin 1.11-snapshot-e781eb6, protocollib 4.8.0

### Configuration file

https://hastebin.com/ulekejepet.yaml

### Server log

https://hastebin.com/ejojavapud.yaml

### Plugin version

fastlogin 1.11-snapshot-e781eb6

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Could you please try the previous workaround: 

https://github.com/games647/FastLogin/releases/tag/tcpshield_update-1

Originally this workaround should be merged into FastLogin, but maybe something went wrong.

**Comment by DarrylSSY** [comment]
I am having the same issue where i get the error "invalid session". The previous workaround doesn't work for 1.19.2

**Comment by games647** [comment]
@DarrylSSY  Please post the full log with the standard version
