### ISSUE TITLE
User can not log in without a password

### ISSUE THREAD

**Issue by WilliamEstrela** [games647/FastLogin#88]
I installed the plug-in spigot server and BungeeCord server, even after entering the command / premium 2x the User can not log in without a password

**Comment by games647** [comment]
Do you followed this guide?

https://github.com/games647/FastLogin#bungeecordwaterfall-1

**Comment by WilliamEstrela** [comment]
Yes

**Comment by games647** [comment]
Then enable debug logging in spigot and relogin.

**Comment by WilliamEstrela** [comment]
http://prntscr.com/cv2jsx ?

**Comment by WilliamEstrela** [comment]
http://prntscr.com/cv2n9o

**Comment by games647** [comment]
Then relogin and send me your bungee and spigot log.

**Comment by WilliamEstrela** [comment]
Server "login" http://prntscr.com/cv2t7w
Server "Bungee" http://prntscr.com/cv2tnk

**Comment by WilliamEstrela** [comment]
After login my password http://prntscr.com/cv2tz7

**Comment by games647** [comment]
Send me the log file not images and your username.

**Comment by WilliamEstrela** [comment]
[latest.txt](https://github.com/games647/FastLogin/files/532022/latest.txt)

**Comment by games647** [comment]
What's the key in your bungee-whitelist file?

**Comment by WilliamEstrela** [comment]
Bungge log
[proxy.txt](https://github.com/games647/FastLogin/files/532026/proxy.txt)

**Comment by games647** [comment]
The whitelist file please.

**Comment by WilliamEstrela** [comment]
The file is empty "proxy-whitelist"

**Comment by games647** [comment]
Then do you really followed step 4 from the guide?

**Comment by WilliamEstrela** [comment]
Now I follow step 3, only restart the bungee?

**Comment by games647** [comment]
No, spigot.

**Comment by WilliamEstrela** [comment]
ok

**Comment by WilliamEstrela** [comment]
You should be working?

**Comment by games647** [comment]
Just follow the guide.

**Comment by WilliamEstrela** [comment]
Make a donation for you, god job!

**Comment by WilliamEstrela** [comment]
in replacement of "you should be working?". Sorry bad translation, I meant, great  work!
