### ISSUE TITLE
1.8.8-1.18.2 compatibility with ProtocolLib

### ISSUE THREAD

**Issue by games647** [games647/FastLogin#881]
Currently the compatibility with 1.8.8-1.18.2 is broken, because FastLogin (since 1.19) requires ProtocolLib 5.0 if no Minecraft proxies are involved. This version is only compatible with 1.19.

You can use `#1079` with ProtocolLib v4.8 and should be fine.

This only applies to you if:

- FastLogin **only on Bukkit**, so without any Minecraft proxies like BungeeCord or Velocity
- and
- Have Protocol**Lib** installed and **not** Protocol**Support**

**Comment by games647** [comment]
Related #880 
#878

**Comment by games647** [comment]
Copied from the CodeMC site:

>Normally you should always use the latest version, but currently due breaking changes in ProtocolLib, the latest version of FastLogin is incompatible with older ProtocolLib versions.

**Comment by games647** [comment]
`#1091` requires Java 17. Although Java is backwards compatible as you can even run Spigot 1.8.8 with Java 18. However some people need the older version. So you should be able to use `#1079`

**Comment by Smart123s** [comment]
ProtocolLib 5.0 was released (in April, lol) with support for 1.8-1.19.x.
I've tested autoregister & login (and it works properly) on a server with:
- FastLogin latest build (https://github.com/games647/FastLogin/commit/c106089a7275bce6a2bc17ee5355bceb16c5e220)
- Paper 1.8.8
- ProtocolLIb 5.0

**Comment by games647** [comment]
Thank you very much for testing. Then we could drop this recommendation. This makes the development and support much easier.
