### ISSUE TITLE
FastLogin won't work with 1.12.2

### ISSUE THREAD

**Issue by Wreeper** [games647/FastLogin#883]
### What happened?

When i write /premium it just shows "/premium [player]"
If i write /premium Wreeper it does the same

### What did you expect?

It should enable premium mode so i can login with premium account..

### Steps to reproduce

Honestly, I don't know. I just installed the plugin

### Plugin list

BlockedCmds, ColoredSigns, JoinMessageStaff, PlaceholderAPI, GroupManager, NametagEdit, MuteChat, Admin-Chat, PlayerReport, MOTD, WorldEdit, CustomList, ClearLag, Votifier, CustomJoin, Multiverse-Core, ProtocolLib, NoCheatPlus, Giveall, FeatherBoard, FastLogin, EffectLib, Whitelist, Alert, Vault, GAListener, LWC, HolographicDisplays, VoteParty, WorldGuard, SkinsRestorer, AuctionHouse, CratesPlus, ShopGUIPlus, LeakParkour, CombatLog, Essentials, AntiCheatReloaded, Jobs, BuycraftX, ajAntiXray, PreciousStones, Citizens, TradeSystem, EssentialsChat, TAB, EssentialsGeoIP, CommandNPC, BetterRTP, EssentialsSpawn, DeliveryMan, AuthMe, LiteBans

### Configuration file

https://paste.wreeper.top/Z31tH/raw/

### Plugin version

1.12-SNAPSHOT-6fe7eb2

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Where is the server log? If it just prints the message. It means it disabled itself on startup.
