### ISSUE TITLE
Menssage not change

### ISSUE THREAD

**Issue by WilliamEstrela** [games647/FastLogin#89]
![image](https://cloud.githubusercontent.com/assets/5386302/19420583/0a48569a-93cd-11e6-97c9-ca98c2b630b1.png)

**Comment by games647** [comment]
Is that the configuration from Spigot?

**Comment by Eufranio** [comment]
Where are you editing that message? It should be edited in each Spigot server, not Bungee server...

**Comment by WilliamEstrela** [comment]
Yes

**Comment by WilliamEstrela** [comment]
Was translating the config spigot, translate the bungee and it worked, thank you!
