### ISSUE TITLE
Premium player is stuck on encrypting when joining server

### ISSUE THREAD

**Issue by Nahciak** [games647/FastLogin#891]
### What happened?

When player is rejoining server after typing /premium command his loading screen stops on "Encrypting..."

### What did you expect?

To join the server and autolog premium player

### Steps to reproduce

I don't know I just uploaded FastLoginBukkit, AuthMe-5.6.0-SNAPSHOT and ProtocolLib 4.8.0 to my 1.18.2 Paper server and premium players cannot join

### Plugin list

ajLeaderboards, AntiCheatReloaded, AuthMe 5.6.0-SNAPSHOT-b2576, AutoPickup, BanHammer, BetterShulkerBoxes, BlueSlimeCore (SirBlobmanAPI, SirBlobmanCore, XSeries), BuycraftX, Citizens, ClearLag, CombatLogX, CustomCommands, CustomHeads*, DecentHolograms, DeluxeHub, DeluxeMentions, DeluxeMenus, DiscordSRV, EmojiChat*, Essentials, EssentialsChat, EssentialsDiscord, EssentialsSpawn, ExcellentCrates, ExecutableItems, FastAsyncWorldEdit (WorldEdit), FastLogin 1.12-SNAPSHOT-feb4639, GCore, GrimAC, HolographicDisplays, LuckPerms, MineResetLite, Multiverse-Core, MythicMobs, NametagEdit, NexEngine, PlaceholderAPI, PlayerKits, ProtocolLib 5.0.0-SNAPSHOT-b597, RacesPlugin*, SCore, ServerListPlus*, Shopkeepers, SkinsRestorer, SkQuery, Skript, Spicord, StreakRewards, TAB, TradeSystem, TrollingFreedom, Vault, ViaBackwards, ViaVersion, VoidGen, VotifierPlus, VotingPlugin, WorldEditSelectionVisualizer, WorldGuard, WorldGuardExtraFlags

### Configuration file

https://hastebin.com/buwuvavane.yaml

### Server log

https://hastebin.com/ekutosiroz.sql

### Plugin version

1.12-SNAPSHOT-feb4639

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
FastLogin isn't the only plugin having issues with ProtocolLib. Try to re-download it or use an older build of it.

**Comment by Nahciak** [comment]
I changed ProtocolLib to ProtocolSupport and its working but FastLogin isn't AutoLogging me even if I set it to true in the config file. When I'm joining server it says this:
[13:43:11 INFO]: [FastLogin] No on-going login session for player: CraftPlayer{name=Nahciak} with ID 5.133.14.195:57293.
[13:43:11 INFO]: [FastLogin] Setups using Minecraft proxies will start delayed when the command from the proxy is received

**Comment by games647** [comment]
I need the corresponding login id to check the login matching. Please post the part where the player logins too. 

Sorry for the delay btw: I was sick last week

**Comment by Nahciak** [comment]
[14:53:05 INFO]: Nahciak[/143.244.42.104:58158] logged in with entity id 123748 at ([end]118.43214055734285, 156.7498525318755, 238.5951655744151)
[14:53:05 INFO]: [+] Nahciak
[14:53:05 INFO]: [FastLogin] No on-going login session for player: CraftPlayer{name=Nahciak} with ID 143.244.42.104:58158.
[14:53:05 INFO]: [FastLogin] Setups using Minecraft proxies will start delayed when the command from the proxy is received
[14:53:07 INFO]: [DiscordSRV] Nahciak was sent a notice for having a degraded user experience due to LunarClient (You can use EnableIncompatibleClientAlert to disable the message if you'd like (Not recommended))
[14:53:15 INFO]: [AuthMe] Nahciak logged in 143.244.42.104

Btw I changed ProtocolSupport to ProtocolLib 4.8.0 because other plugins needed it but its not autologging too.

**Comment by games647** [comment]
There should log messages even before that. Please also include the startup log.

**Comment by Nahciak** [comment]
https://hastebin.com/veragosuta.yaml

**Comment by games647** [comment]
>NoSuchMethodError: 'com.comphenix.protocol.reflect.EquivalentConverter com.comphenix.protocol.wrappers.BukkitConverters.getWrappedPublicKeyDataConverter()'

FastLogin is currently compatible with ProtocolLib 5.0, because they made breaking changes. So  please use: https://ci.codemc.io/job/Games647/job/FastLogin/1091/
