### ISSUE TITLE
Suggestion about performing a blocking I/O operation on the main thread

### ISSUE THREAD

**Issue by FunkyNico** [games647/FastLogin#893]
Context:

I found this suggestion from another spigot plugin called [Lagmonitor ](https://github.com/games647/LagMonitor): Make stop the plugin from doing a blocking I/O operation on the main thread because this could affect the server performance, the thread pauses until it gets the response. Such operations should be performed asynchronous from the main thread. Besides gameplay performance it could also improve startup time.

Fastlogin Version: 1.12-SNAPSHOT-feb4639 / Server: Purpur-1762 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 39e30d6 on HEAD).

Log: https://logs.apexminecrafthosting.com/jhZtwBc

Thanks =D

**Comment by games647** [comment]
Funny that my own plugins detect my mistakes. In this case it was only a single load, but I fixed it.
