### ISSUE TITLE
Pufferfish 1.19.2 isn't supported

### ISSUE THREAD

**Issue by scope404** [games647/FastLogin#898]
### What happened?

the plugin isn't working with pufferfish 

### What did you expect?

it to work with pufferfish

### Server log

https://hastebin.com/iwodomabid.sql

### Plugin version

1.12-SNAPSHOT-ee6aeaf

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Please post the startup log
