### ISSUE TITLE
Premium/cracked message sent to everyone in Bungee 

### ISSUE THREAD

**Issue by Eufranio** [games647/FastLogin#90]
I have a bungee and a spigot server. If I use `/premium <user>` in the console of the spigot server, all other users in that Spigot server will see `Added to the premium list` message. 
Also, only the players receive that message. I think Bungee/Spigot console should show if the player has been added successfully, and dont send the message to the player.

**Comment by games647** [comment]
Fixed https://github.com/games647/FastLogin/commit/41abffdb080db8501dcd2f054f5cfe9dc0c53618
