### ISSUE TITLE
problems with AuthMe and online accounts

### ISSUE THREAD

**Issue by AkariDream** [games647/FastLogin#902]
### What happened?

use online accounts and online mode.
authme still let me type the password

### What did you expect?

skip AuthMe auth after entering with an online account
(not a matter of AutoRegister or /premium. these I have solved)

### Steps to reproduce

idk

### Plugin list

AdvancedBan, AuthMe, ChestCommands, CommandSync, ConsoleSpamFix, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsProtect, EssentialsSpawn, FastLogin, floodgate, ItemJoin, JoinCommands, PlaceholderAPI, PlayerPoints, ProtocolLib, SirBlobmanCore, TAB-Bridge, ViaBackwards, ViaRewind, ViaVersion, Vulcan, Yum. Grim Already Uninstall

### Configuration file

hastebin.com/uwuquwimev.yaml

### Server log

hastebin.com/oruconozut.sql

### Plugin version

FastLogin version 1.12-SNAPSHOT-ee6aeaf

### Platform

Spigot [git-Akarin-"e912498" (MC: 1.12.2)]

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
>Received proxy id:that doesn't exist in the proxy file

You didn't follow the setup guide for FastLogin bungee completely, because that entry is missing inside the allowed proxies file.

**Comment by AkariDream** [comment]
i didnt find any documentation on how to set it up

**Comment by games647** [comment]
https://github.com/games647/FastLogin#bungeecordwaterfall-or-velocity

**Comment by AkariDream** [comment]
not found _stats-id_ .
its "stats: something" in bungeecord cfg ?

**Comment by games647** [comment]
Yes

**Comment by AkariDream** [comment]
the problem is resolved. thx
i initially thought it was cfg in fastlogin. lol
