### ISSUE TITLE
nable to make private java.util.Collections$EmptyList() accessible

### ISSUE THREAD

**Issue by rysiuk** [games647/FastLogin#905]
### What happened?

The plug is not working. The chat shows that the account has been added to premium, but when I enter the server in the chat message / login password is displayed

### Plugin list

authme, protocllib, fastlogin, multiverscore, superiorskyblock, worldedit, worldguard

### Configuration file

https://hastebin.com/sadamiwewi.yaml

### Server log

[WARNING] [AuthMe] Could not save LimboPlayer for 'rysiukkk' [InaccessibleObjectException]: Unable to make private java.util.Collections$EmptyList() accessible: module java.base does not "opens java.util" to unnamed module @5274766b

### Plugin version

FastLogin version 1.12-SNAPSHOT-2e60f9b

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
That's error from AuthMe not by FastLogin.

**Comment by rysiuk** [comment]
so I have to do a different version of authme?

**Comment by rysiuk** [comment]
now he writes this to me https://hastebin.com/bacaluxeya.json

**Comment by games647** [comment]
Incompatible ProtocolLib version. Checkout this ticket #881 or https://ci.codemc.io/job/Games647/job/FastLogin/
