### ISSUE TITLE
Console error on Bungeecord when a bedrock user do login

### ISSUE THREAD

**Issue by comonier** [games647/FastLogin#907]
Should i have fastlogin.jar on bungeecord [proxy] and on lobby [backend],  right ?
An about the mysql database can be the same one for both servers ? (proxy + lobby?) Or does each have its own?
Is there an option to not use mysql database in proxy or backend?
Currently i am using a mysql database in bungeecord for fastlogin, however in the lobby it has the default setting of creating local database:

**Lobby**
```java
autoRegister: true
autoLogin: true
autoLoginFloodgate: true
autoRegisterFloodgate: true
# Database configuration
# Recommended is the use of MariaDB (a better version of MySQL)

# Single file SQLite database
driver: 'org.sqlite.JDBC'
# File location
database: '{pluginDir}/FastLogin.db'
```

### What happened?

I am trying enable to bedrock user auto login, but when they join on lobby it request to register account. 

Java player have auto login working...

So... i have geyser + floodgate + authmebung + fastlogin on proxy
And... i have floodgate-spigot + authme-spigot + fastlogin-spigot on lobby

error on link https://paste.ofcode.org/MvdiQbYdwfbt8GXSuxAQh6

### What did you expect?

Just a help to foud were i did mistake 
```java
autoRegister: true
respectIpLimit: true
secondAttemptCracked: false
switchMode: false
premiumUuid: true
nameChangeCheck: true
forwardSkin: true
premium-warning: true
ip-addresses: []
mojang-request-limit: 600
auto-register-unknown: false
autoLogin: true
autoLoginFloodgate: true
allowFloodgateNameConflict: false
autoRegisterFloodgate: true
floodgatePrefixWorkaround: true
```
bungeecord-fastlogin

### Plugin list

Plugins (32): AntiWorldFly, AuthMe, AutoRestart*, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, F3Name, FastLogin, floodgate, HackedCore*, HackedServer*, MineverseChat*, Multiverse-Core, MVdWPlaceholderAPI*, PermissionsEx*, PEXChat*, PlaceholderAPI, PlugMan, ProtocolLib, ServerSelectorX, SkinsRestorer, Skript, TAB, Themis, Vault, VentureChat, ViaBackwards, ViaVersion, VoidSpawn, WorldEdit, WorldGuard

### Plugin version

BungeeCord 1660

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by comonier** [comment]
Solution .....

i gues the problem was becuase i change prefix character and save it, so after i do a test with my bedrock account it ask to register again... BUT... on second time it does auto login

and i ask to a friend who NEVER HAVE JOINED on my server join, and he sad it auto register / and auto login ...

so....

i guess is it.

```java
[00:00:36 ERROR]: Parameters:
  net.minecraft.network.protocol.login.PacketLoginInStart@73da4179[
    a=*Killinin
    b=Optional.empty
    c=Optional[00000000-0000-0000-0009-01f3ae7c9d95]
  ]

[00:00:36 INFO]: UUID of player *Killinin is 00000000-0000-0000-0009-01f3ae7c9d95
[00:00:36 INFO]: [floodgate] Floodgate player logged in as *Killinin joined (UUID: 00000000-0000-0000-0009-01f3ae7c9d95)
[00:00:36 INFO]: *Killinin joined the game
[00:00:36 INFO]: *Killinin[/201.92.248.124:42022] logged in with entity id 16 at ([lobby]-0.5, 80.0, 0.5)
[00:00:36 INFO]: [FastLogin] Player info REGISTER command for *Killinin from proxy
[00:00:36 INFO]: [FastLogin] Delaying force login until join event fired?: false
[00:00:36 INFO]: [Essentials] Creating empty config: /root/lobby/plugins/Essentials/userdata/00000000-0000-0000-0009-01f3ae7c9d95.yml
[00:00:37 INFO]: [FastLogin] Register player *Killinin
[00:00:37 INFO]: [AuthMe] *Killinin registered 201.92.248.124
[00:00:37 INFO]: [AuthMe] *Killinin logged in 201.92.248.124
[00:01:29 INFO]: [floodgate] Floodgate player logged in as *Killinin disconnected
[00:01:29 INFO]: *Killinin lost connection: Disconnected
[00:01:29 INFO]: *Killinin left the game
```

**Comment by Polda18** [comment]
@comonier:
You should censor any kind of IP address that shows up in the log for
privacy reasons, even if it is your own IP address. You wouldn't believe
how much info can be extracted from a single IP address. If you enter the
IP address from the log here: https://www.whatismyip.com/ip-whois-lookup/ -
you will know that the person connecting from this IP address lives in
Brazil. Geolocation can be done in some cases from a single IP address,
which has been successfully done to dox users and players using leaked IP
addresses. Do not leak any kind of IP address to the public, always make
sure that you've censored the IP address of connecting players from the
server log. For example, I always replace any kind of IP address in the log
with localhost IP address: 127.0.0.1 - that's safe as this IP address
refers to the same computer.

pá 26. 8. 2022 v 5:11 odesílatel comonier ***@***.***> napsal:
