### ISSUE TITLE
couldn't look up profile properties

### ISSUE THREAD

**Issue by spartamc** [games647/FastLogin#916]
### What happened?

I do not know what has happened with the name of a user that whenever I restart the server comes out a crash with his name I do not know what can be due to that.

### What did you expect?

That did not give this error in console

### Steps to reproduce

It is that I do not know at what moment this error happened I do not know the player in question and I do not know why this happens

### Plugin list

AdvancedLogin*, ArmorStandTools, AuctionMaster, BloodMoon, BotSentry, BuycraftX, ChatSentry, Chunky, CMILib, CoreProtect, CrateReloaded, DeluxeMenus, eco, EcoSkills, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, EZColors, EZRanksPro, FastAsyncWorldEdit (WorldEdit), FastLogin, floodgate, Geyser-Spigot, HolographicDisplays, IllegalStack, Jobs, KixsAutoAnnouncerPremium, KixsChatGames, LiteBans, LuckPerms, MineableSpawners, MobFarmManager, Multiverse-Core, MyPet, Pl-Hide-Pro, PlaceholderAPI, ProtectionStones, ProtocolLib, PvPManager, RealScoreboard, RoyaleEconomy, ServerListPlus, SkinsRestorer, Skript, sleep-most, spark, TabList, TempFly, TradeSystem, Vault, ViaBackwards, ViaVersion, VotifierPlus, VotingPlugin, WorldGuard

### Configuration file

https://hastebin.com/ovabimibaz.yaml

### Server log

https://gist.github.com/spartamc/e40299f2b158d361c7e491801fc874d2

### Plugin version

1.12-SNAPSHOT-ed45fad

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by spartamc** [comment]
![crash](https://user-images.githubusercontent.com/94750050/190502136-9554204a-826b-43d1-ab04-a00503dd0e20.png)

**Comment by games647** [comment]
Why do think it's FastLogin caused? The error occurred, because the server is trying to set a skull item. The UUID further looks like a Floodgate UUID.. Maybe its an incompatibility between Floodgate and your server software.

**Comment by spartamc** [comment]
![image](https://user-images.githubusercontent.com/94750050/190601592-9a5d7314-fb55-44c4-9c09-1421397f7ec6.png)

I believe because this has never happened to me, apart from the database is that name. Why else what add-on could the error be treated for?

**Comment by games647** [comment]
As I said it could be from Floodgate, because of the UUID.

**Comment by spartamc** [comment]
Well thank you very much.
