### ISSUE TITLE
Premium players  sometimes get an offline uuid

### ISSUE THREAD

**Issue by Blackyvk** [games647/FastLogin#92]
Basically that....

for some reason some premium players get an offline uuid, i dont know how, and why... who knows if its when the server is starting and they try to join and the server hasnt finished loading yet but, i've had to delete some plugins data like VentureChat because when one player different uuid but same name in the data file they crash the server (venturechat crash)....

**Comment by games647** [comment]
You use Spigot right? Any errors besides the VentureChat one? What other plugins do you use?

**Comment by Blackyvk** [comment]
I think this is related this https://github.com/games647/FastLogin/issues/12  I just tried to login while my server was loading  and I got kicked because the whitelist has me with premium so it kicks my offline uuid.

**Comment by games647** [comment]
But are kicked every time right?

**Comment by Blackyvk** [comment]
I mean... i was doing a maintenance and I had the whitelist turned on which has me with my premium uuid, so I got kicked by the whitelist not by fastlogin because I was logging in while the server was loading... IF i turn off the whitelist and I try to login while the server is still loading I can get inside the server as no premium with offline uuid so I have to relog to get my premium uuid.

**Comment by games647** [comment]
>I try to login while the server is still loading I can get inside the server as no premium with offline uuid so I have to relog to get my premium uuid.

But then the plugin should kick you, because it didn't inject into the network manager yet.

**Comment by Blackyvk** [comment]
have a look to my log

http://pastebin.com/6ixDaWvJ

**Comment by games647** [comment]
Can't you just whitelist your premium UUID and wait until the server finished starting up?

**Comment by Eufranio** [comment]
You can enable late-bind in your spigot.yml, then people will be able to join only after all the server loading...
