### ISSUE TITLE
SQLite NoClassDefFound Velocity

### ISSUE THREAD

**Issue by JumperBoost** [games647/FastLogin#929]
### What happened?

FastLogin unable to access SQLite classes at starting due to presumably non-implementation in Velocity.

I have already fixed this problem a few months ago by adding SQLite JDBC lib from xenial in maven pom but it doesn't include SQLiteDataSource.class, so i had to add the class manually _(the only problem is that the file size becomes heavy)_. I don't know why this class doesn't compile because when we compile directly jdbc, he includes SQLiteDataSource.class (look images below). 
_This issue is the same as #912 due to missing lib but i create another one with my details._

FastLoginVelocity build with sqlite included (no SQLiteDataSource class here):
![FastLoginVelocity with sqlite](https://user-images.githubusercontent.com/38703849/192880900-5439cb75-c471-45e2-b893-b73c16f47cc2.jpg)

SQLite JDBC compiled by source (here, SQLiteDataSource is present):
![SQLite compilation](https://user-images.githubusercontent.com/38703849/192880902-dc95eda8-ba39-4c5b-bd08-c02bd337392e.jpg)

Velocity jar libs (here, no sqlite lib is included):
![Velocity libs](https://user-images.githubusercontent.com/38703849/192880903-56146dc6-ce55-47de-8a17-80b8fa907bb2.jpg)

### What did you expect?

Fix the problem.

### Steps to reproduce

Download the latest version of FastLogin & Velocity and run the server.

### Plugin list

FastLogin, floodgate, Geyser, LuckPerms, SkinsRestorer

### Server log

Log with latest build:
https://pastebin.com/m6QbujDF

Log with modified build:
https://pastebin.com/6LSxTzJu

### Plugin version

1.12-SNAPSHOT-2989d9a

### Platform

Velocity

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
For large servers, it's recommended to use MySQL/MariaDB. In your case it could be that the `maven-shade-plugin` removed, because it thought it's not used. 

Recently FastLogin also added a direct dependency on SQLite. So you could also tune it [here](https://github.com/games647/FastLogin/blame/2989d9a62d3dc7a1b9464541719c7e6ca2540b41/core/pom.xml#L191) by changing the scope.
