### ISSUE TITLE
Are these settings ok?(last questions)

### ISSUE THREAD

**Issue by Wearwolfy** [games647/FastLogin#93]
1. Would these settings cause any problems for UUID players (http://pastebin.com/Zk7v8i9T), just to make sure before release

2. Recently i started getting this error (http://pastebin.com/rbSFZdjH), this is only when I( premium player) joined when a cracked player join, no errors came up, and the wierd thing as well is that it only showed the error on the hub/lobby server, I fixed this but going into the mysql db and deleting my Row( name/uuid), restarted the server and it was fixed, I report this as an issue, since i don't want to remove every premium player from the db manually to fix this problem

**Comment by games647** [comment]
>Would these settings cause any problems for UUID players (http://pastebin.com/Zk7v8i9T), just to make sure before release

Your premium users will receive a premium UUIDs and cracked players not. This also means if a cracked player activates premium authentication later on the uuid will change.

>Recently i started getting this error (http://pastebin.com/rbSFZdjH), 

Not a FastLogin error. It's a AuthMe one.
