### ISSUE TITLE
autoregister not working on velocity

### ISSUE THREAD

**Issue by frogglen** [games647/FastLogin#930]
### What happened?

I'm trying to set up autoregister with authme but it doesn't work, autologin works fine after using /premium command

I already have the latest velocity snapshot installed, authme velocity, fastlogin bukkit, fastlogin velocity and authme reloaded in 1.19.2

### What did you expect?

when logging into my auth server with my premium account, it should automatically register with a random strong password and then send me to the desired server in the authme config

### Plugin list

AuthMe, AuthMeVelocity, Chatty, FastLogin, PlaceholderAPI, ProtocolLib, SkinsRestorer, spark, UTitleAuth, Vault, WorldEdit, WorldGuard

### Configuration file

https://hastebin.com/vafewohova.yaml

### Server log

[17:51:26 INFO]: [FastLogin] No on-going login session for player: CraftPlayer{name=Frog42} with ID 185.:38516. 
[17:51:26 INFO]: [FastLogin] Setups using Minecraft proxies will start delayed when the command from the proxy is received

### Plugin version

Build #1162 fastlogin

### Platform

Velocity

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Please post the +/- messages of the player login process. There are relevant data missing to fix it.

**Comment by frogglen** [comment]
I'm sorry, I was trying to enter with my premium account that already had my data in the mysql database, I tried to enter with another premium account that was not in the DB and the autoregister worked
