### ISSUE TITLE
Fastlogin / Floodgate not working toogether on velocity server

### ISSUE THREAD

**Issue by scope404** [games647/FastLogin#935]
### What happened?

It keeps thinking i'm logging in as Java user even thought I have the prefix _ in front and keeps saying my floodgate config is wrong even thought it works fine without using fastlogin
also works fine if it isn't an server network with a proxy 

### What did you expect?

bedrock players to be able to join

### Steps to reproduce

add Fastlogin & Gayser/Floodgate and and log in with an username that an java user is using (floodgate adds an prefix before so...)

### Plugin list

FastLogin , Geyser-Spigot , Floodgate

### Server log

https://hastebin.com/ijinefedoz

### Plugin version

Newest

### Platform

Velocity

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by Smart123s** [comment]
FastLogin Velocity doesn't support Floodgate yet. https://github.com/games647/FastLogin/issues/729#issuecomment-1050530340
