### ISSUE TITLE
IllegalAccessError com.comphenix.protocol.injector.netty.Injector

### ISSUE THREAD

**Issue by piesio98** [games647/FastLogin#94]
Error:
http://pastebin.com/JxYpQm1v

Config:
http://pastebin.com/MH2gndzr

Authme v3.4
Fastlogin v1.9
ProtocolLib v3.7.0

**Comment by games647** [comment]
Which Minecraft version?

**Comment by piesio98** [comment]
1.7-1.8

**Comment by games647** [comment]
Another plugin is modifying the network manager. This conflicts with FastLogin

**Comment by piesio98** [comment]
List of plugins
http://pastebin.com/Y0sL8dGW

Now... there is no error on start, but when i join i'm not logged in automaticly. After type /premium, plugin added me to the premium list, after that i'v tried to rejoin but i cant connect (loggining in...) and plugin gave i this.
http://pastebin.com/BDJv6JKh
It's the same ;/ What plugin causes those conflicts.
