### ISSUE TITLE
Error occurred on thread pool

### ISSUE THREAD

**Issue by mkaldk** [games647/FastLogin#944]
### What happened?

When logging in from a premium account, the endless inscription "Encryption..." and an error appears in the console

### Steps to reproduce

Sign in with a premium account

### Plugin list

AuthMe, FastLogin, ProtocolLib

### Configuration file

https://mcpaste.io/4c6a01a0b03da7ee

### Server log

When a player joins - https://mcpaste.io/ebfc825c22bd6a55
General log - (names and ip changed to "(player name) (ip)") - https://mcpaste.io/eee338e09d4ca7ad

### Plugin version

1.12-SNAPSHOT-2989d9a

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
How do you solved it?
