### ISSUE TITLE
[18:27:32 INFO]: [FastLogin] No on-going login session for player: CraftPlayer{name=Lynrayy} with ID 127.0.0.1:7081. [18:27:32 INFO]: [FastLogin] Setups using Minecraft proxies will start delayed when the command from the proxy is received

### ISSUE THREAD

**Issue by lynrayy** [games647/FastLogin#946]
### What happened?

Installed fastlogin bukkit skip filtering and got this
FastLogin is installed on HUB server and BUNGEE server
AuthMe installed on all servers too
HUB server authentificates player automatically (1.12.2), but playing server says:

[18:27:32 INFO]: [FastLogin] No on-going login session for player: CraftPlayer{name=Lynrayy} with ID 127.0.0.1:7081.
[18:27:32 INFO]: [FastLogin] Setups using Minecraft proxies will start delayed when the command from the proxy is received

### Plugin version

1.12-SNAPSHOT-5af4317

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by lynrayy** [comment]
server is 1.19.2

**Comment by games647** [comment]
The spigot server doesn't have bungee support enabled.

**Comment by lynrayy** [comment]
No it have 
![image](https://user-images.githubusercontent.com/59417884/204146218-e66153ae-d67d-4c19-a87a-000652bc17f1.png)

**Comment by lynrayy** [comment]
HUB and GAME_server have same fastlogin configs, same proxy whitelists and same authme versions+config

**Comment by games647** [comment]
Please post the bungee log too

**Comment by lynrayy** [comment]
Bungee log
https://gist.github.com/lynrayy/53c1a9bfeca8036bc822847f0a36483e

Hub server log
https://gist.github.com/lynrayy/9eefb9c76075169b893b7ee88864df69

Game server log
https://gist.github.com/lynrayy/693a2621e870f9bde70039a6b16d489c

**Comment by games647** [comment]
Did you used the premium command? FastLogin  by default is opt-in.

**Comment by lynrayy** [comment]
Just tried, nothing happens

`[19:46:38 INFO]: Lynrayy issued server command: /premium
[19:46:49 INFO]: Lynrayy lost connection: Disconnected
[19:46:49 INFO]: Lynrayy left the game
[19:47:00 INFO]: UUID of player Lynrayy is ffa8cd52-4adf-400c-b831-cc9f60485982
[19:47:00 INFO]: Lynrayy joined the game
[19:47:00 INFO]: Lynrayy[/127.0.0.1:11534] logged in with entity id 185 at ([world]-40.43919541031197, 65.0, -207.45493351439856)
[19:47:01 INFO]: [FastLogin] No on-going login session for player: CraftPlayer{name=Lynrayy} with ID 127.0.0.1:11534.
[19:47:01 INFO]: [FastLogin] Setups using Minecraft proxies will start delayed when the command from the proxy is received
[19:47:02 INFO]: [AuthMe] Lynrayy logged in 127.0.0.1`

![image](https://user-images.githubusercontent.com/59417884/204148753-58271011-0163-491a-afce-ce30b7cbf7dc.png)

**Comment by games647** [comment]
The game have to invoked from bungee or in-game by the player

**Comment by lynrayy** [comment]
What?

**Comment by lynrayy** [comment]
/premium just says
![image](https://user-images.githubusercontent.com/59417884/204149142-9a2a591c-8f1d-420a-8dd1-3d920ea58054.png)

and nothing happens
No autologin, just nothing

**Comment by games647** [comment]
This means the bungee module isn't responding. In this case I see that you are using the outdated version there.

**Comment by lynrayy** [comment]
But latest fastlogin not working on bungee 
![image](https://user-images.githubusercontent.com/59417884/204150368-e4ecd04d-5249-4ba7-8129-6897a4cec9b6.png)

**Comment by lynrayy** [comment]
Look, it works on 1.12.2 server connected to the same Bungee
![image](https://user-images.githubusercontent.com/59417884/204151388-cba8be6b-7811-405e-9462-fbac6534aaf0.png)

**Comment by lynrayy** [comment]
Same bungee, different server (1.19.2)
![image](https://user-images.githubusercontent.com/59417884/204151420-d8debb49-c7c2-494a-a20f-7b9852a81e6a.png)

**Comment by games647** [comment]
> But latest fastlogin not working on bungee ![image](https://user-images.githubusercontent.com/59417884/204150368-e4ecd04d-5249-4ba7-8129-6897a4cec9b6.png)

You need to download the bungee version from the site. You have the Bukkit version installed on bungee.



> Latest from github not working on bungee
> 
> Latest from spigot https://www.spigotmc.org/resources/fastlogin.14153/ is described above this message. This is not 'OuTdAtEd', it is latest on spigotmc

Spigot version is the latest fixed version, but that is outdated. As you can also see based on the version number.

**Comment by games647** [comment]
> Look, it works on 1.12.2 server connected to the same Bungee ![image](https://user-images.githubusercontent.com/59417884/204151388-cba8be6b-7811-405e-9462-fbac6534aaf0.png)

The communication format changed. Therefore newer versions cannot communicate with older versions.

**Comment by lynrayy** [comment]
> You need to download the bungee version from the site. You have the Bukkit version installed on bungee.
I can't find it anywhere

**Comment by lynrayy** [comment]
I can't find it anywhere

**Comment by games647** [comment]
Quote from the resource page:
>Click on the left side on the build to download it or click status to get always the latest.
>https://ci.codemc.org/job/Games647/job/FastLogin/changes

**Comment by lynrayy** [comment]
Thanks it works
