### ISSUE TITLE
SQLite not available in Velocity

### ISSUE THREAD

**Issue by klaksik** [games647/FastLogin#950]
update finally the velosity how much time has passed

**Comment by klaksik** [comment]
![image](https://user-images.githubusercontent.com/89664351/206463275-bb29ab60-1fef-4911-a9d9-5a0150e75ec6.png)

**Comment by games647** [comment]
Velocity doesn't include the driver for SQLite. You have to use MySQL. This is mentioned in the configuration file.

**Comment by klaksik** [comment]
![image](https://user-images.githubusercontent.com/89664351/206561269-539ecedb-0ea4-4a98-a8a1-a0f7c1a8951d.png)
![image](https://user-images.githubusercontent.com/89664351/206561312-8312725c-f283-4d22-9395-bc86bd372ce9.png)

**Comment by games647** [comment]
> ![image](https://user-images.githubusercontent.com/89664351/206561269-539ecedb-0ea4-4a98-a8a1-a0f7c1a8951d.png) ![image](https://user-images.githubusercontent.com/89664351/206561312-8312725c-f283-4d22-9395-bc86bd372ce9.png)

Read two lines below from the configuration file. Use `mariadb` for Velocity. MySQL and MariaDB server can be exchanged, because they have same history. However, the driver to communicate to it has to available in the server.

**Comment by klaksik** [comment]
sank
