### ISSUE TITLE
[Failed to connect to bedrock]

### ISSUE THREAD

**Issue by Arthuuurr** [games647/FastLogin#952]
### What happened?

Cannot access server from Minecraft Bedrock due to error "Could not check whether Bedrock Player GiselRayo's name conflicts a premium Java player's name."

### What did you expect?

That I could connect like the last days

### Plugin version

Latest version of Bungeecord

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by Arthuuurr** [comment]
![image](https://user-images.githubusercontent.com/90864573/207730847-319d58f0-2d98-4c2f-a810-19f8093de2ec.png)
![image](https://user-images.githubusercontent.com/90864573/207730955-237c580c-6db1-4dd2-a1c0-3c9ba20860cc.png)

This is the error

**Comment by Aloki** [comment]
You can (temporarily) disable this check by setting `allowFloodgateNameConflict` to _true_ in config.yml.

**Comment by Arthuuurr** [comment]
Fixed, thanks!
