### ISSUE TITLE
FastLogin Error occurred on thread pool

### ISSUE THREAD

**Issue by LcyDev** [games647/FastLogin#955]
### What happened?

Plugin can't handle premium users properly and kicks them
Also spamming the console

### Configuration file

https://pastebin.com/ThuGt0iQ

### Server log

https://pastebin.com/02L1dvcS

### Plugin version

FastLoginBukkit-b1180

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Which ProtocolLib version do you use?

**Comment by LcyDev** [comment]
ProtocolLib-5.0.0-b605
