### ISSUE TITLE
tab heads

### ISSUE THREAD

**Issue by klaksik** [games647/FastLogin#956]
Why can't you send packs of tab heads to all players? and those who have a license display them, or it doesn’t work that way?

**Comment by games647** [comment]
The skin is included in the tablist packet, but the client ignores it. If it isn't an onlinemode connection. That's why it isn't possible.

**Comment by klaksik** [comment]
so why if there is no fast login heads are not displayed

**Comment by games647** [comment]
If the client is not login with an onlinemode connection, there are no heads. It's vanilla behavior.

**Comment by klaksik** [comment]
Is there a plugin that does just that?

**Comment by klaksik** [comment]
I understand, but I have a question about the operation of the plugin, should I recreate the ticket?
