### ISSUE TITLE
bangecord not responding

### ISSUE THREAD

**Issue by klaksik** [games647/FastLogin#957]
### What happened?

the plugin reads the mysql database but with the premium command it sends a request to the bungeecord and it ignores it

### Server log

https://pastebin.com/LyejTXj2 

https://pastebin.com/ySTHvmkZ

### Plugin version

1.12-SNAPSHOT-2989d9a

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Outdated plugin version on Bungee.
