### ISSUE TITLE
Can't download build 1079

### ISSUE THREAD

**Issue by epicdex** [games647/FastLogin#958]
Hi, I was just minding my own business, when one time FastLogin stopped working. I did a full reinstall, and that didn't work too. I downloaded the latest build, then I realised it's only for 1.19. ProtocolLib is for sure works fine.
Later I was searching for the build #1079 but it's not on codemc or anywhere else. (I have a 1.17 papermc server)
Where can I download it? The link that redirects me to the #1079 is saying 404 error.

Thanks in advance.

**Comment by games647** [comment]
I created a release here on GitHub.

https://github.com/games647/FastLogin/releases/tag/1.11

**Comment by epicdex** [comment]
Thank you!
