### ISSUE TITLE
Plugin crashing on player join.

### ISSUE THREAD

**Issue by Cut3Olix** [games647/FastLogin#961]
### What happened?

When player joins plugin gives error and not working auto-login

### Steps to reproduce

Premium player need to login, when typed before /premium

### Plugin list

AdvancedBan, AutoMessage, CommandWhitelist, DecentHolograms, FastAsyncWorldEdit (WorldEdit), FastLogin, LPC, LuckPerms, MultiHell, NametagEdit, PixelMOTD*, PlaceholderAPI, PlayerKits, PlugMan, ProtocolLib, SternalBoard, UserLogin, Vault, WorldGuard

### Configuration file

https://pastebin.com/S79DYfyb

### Server log

https://pastebin.com/1bXKyn47

### Plugin version

v 1.11-a9e4c90

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Outdated plugin version.

**Comment by Cut3Olix** [comment]
Thanks, working form jenkins <3
