### ISSUE TITLE
Auto login under 1.19.3 dosen't work

### ISSUE THREAD

**Issue by zoliidev** [games647/FastLogin#966]
### What happened?

At server start the plugin throws the following warning: [12:31:32 WARN]: [FastLogin] Cannot access proxy field

When a player joins: [12:34:49 ERROR]: [FastLogin] Unhandled exception occurred in onAsyncPacket() for FastLogin

### What did you expect?

Auto login for premium players does not work. 

### Steps to reproduce

Use Purpur 1.19.3, Protocollib 5
Start the server
Join to the server

### Plugin list

AuthMe, FastLogin, Hg-Clan, Hg-Core, LuckPerms, ProtocolLib, SkinsRestorer, spark, Vault, WorldEdit, WorldGuard, WorldGuardEvents

### Configuration file

https://gist.github.com/zoliidev/bb028de1ff9c19015a935960d3448ba6

### Server log

https://gist.github.com/zoliidev/9a9f7011e084bb534a6299dfbebf90d0

### Plugin version

[12:45:03 INFO]: FastLogin version 1.11-a9e4c90

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Outdated plugin version. 1.11 is not supported for 1.19.3. If you click the check box for latest, please use the latest build.

**Comment by zoliidev** [comment]
I just found the codemc link. Now its working
