### ISSUE TITLE
Server is not fully started yet problem

### ISSUE THREAD

**Issue by pawelkuwa** [games647/FastLogin#977]
### What happened?

After install FastLogin plugin i getting this notice after trying to join server: ```Server is not fully started yet problem```

### What did you expect?

Works fine

### Steps to reproduce

Install latest fastlogin version, protocollib 5.0.0 build and online-mode to false

### Plugin list

FastLogin, PlugManX, ProtocolLib, SkinsRestorer

### Configuration file

https://hastebin.com/erovumison.yaml

### Server log

https://hastebin.com/subosuvubi.csharp

### Plugin version

v1.10-git484855724b794de1fe057cf7360245362658b432*

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
1.10 is very outdated and not the latest build. Downloading a development will likely already fix it.

**Comment by pawelkuwa** [comment]
so i changed to https://github.com/games647/FastLogin/releases/tag/1.11
and still doesn't work

**Comment by games647** [comment]
This is still not a dev build. It even mentions in the description 1.11 is for versions below 1.19
