### ISSUE TITLE
 is not assignable to 'java/security/GeneralSecurityException'

### ISSUE THREAD

**Issue by JekoTC** [games647/FastLogin#984]
### What happened?

help

### What did you expect?

Help fixed

### Plugin list

AuthMeBungee,FastLoginBungee,floodgate-bungee,Geyser-BungeeCord,GeyserSkinManager-BungeeCord,ProtocolChanger,ProtocolLib,RedirectPlus-2.12.0,RedisBungee-0.6.3,ServerStatus,ShieldMotd,SkinsRestorer

### Server log

https://mclo.gs/Ata6svx

### Plugin version

#1192

### Platform

BungeeCord

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones

**Comment by games647** [comment]
Broken Java installation. Please reinstall it.
